-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "cat-everlike-mocha"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { fg = "#e69875" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.documentation", { fg = "#6d6649", italic = true })
hi(0, "@comment.error", { bg = "#e06062", fg = "#1f2428" })
hi(0, "@comment.hint", { bg = "#59a6c3", fg = "#1f2428" })
hi(0, "@comment.note", { bg = "#59a6c3", fg = "#1f2428" })
hi(0, "@comment.todo", { bg = "#ff9185", fg = "#1f2428" })
hi(0, "@comment.warning", { bg = "#d3ad63", fg = "#1f2428" })
hi(0, "@comment.warning.gitcommit", { fg = "#d3ad63" })
hi(0, "@conditional", { fg = "#cb7ec8", italic = true })
hi(0, "@constant.builtin", { fg = "#e69875" })
hi(0, "@constant.java", { fg = "#6db57f" })
hi(0, "@constant.macro", { fg = "#cb7ec8" })
hi(0, "@constructor", { fg = "#60aaa0" })
hi(0, "@constructor.lua", { fg = "#ff9185" })
hi(0, "@constructor.tsx", { fg = "#e0d3d4" })
hi(0, "@constructor.typescript", { fg = "#e0d3d4" })
hi(0, "@define", { link = "Define" })
hi(0, "@diff.delta", { fg = "#59a6c3" })
hi(0, "@diff.minus", { fg = "#e06062" })
hi(0, "@diff.plus", { fg = "#b0cc76" })
hi(0, "@error", { fg = "#e06062" })
hi(0, "@exception", { fg = "#cb7ec8" })
hi(0, "@field", { fg = "#e0d3d4" })
hi(0, "@float", { link = "Float" })
hi(0, "@function.builtin", { fg = "#e69875" })
hi(0, "@function.builtin.bash", { fg = "#e06062", italic = true })
hi(0, "@function.call", { fg = "#59a6c3" })
hi(0, "@function.macro", { fg = "#6db57f" })
hi(0, "@function.method", { fg = "#59a6c3" })
hi(0, "@function.method.call", { fg = "#59a6c3" })
hi(0, "@function.method.call.php", { fg = "#59a6c3" })
hi(0, "@function.method.php", { fg = "#59a6c3" })
hi(0, "@include", { fg = "#cb7ec8" })
hi(0, "@keyword.conditional", { fg = "#cb7ec8", italic = true })
hi(0, "@keyword.conditional.ternary", { fg = "#7fbbb3" })
hi(0, "@keyword.coroutine", { fg = "#cb7ec8" })
hi(0, "@keyword.debug", { fg = "#cb7ec8" })
hi(0, "@keyword.directive", { fg = "#d699b6" })
hi(0, "@keyword.directive.define", { link = "Define" })
hi(0, "@keyword.exception", { fg = "#cb7ec8" })
hi(0, "@keyword.export", { fg = "#7fbbb3" })
hi(0, "@keyword.function", { fg = "#cb7ec8" })
hi(0, "@keyword.import", { fg = "#cb7ec8" })
hi(0, "@keyword.modifier", { fg = "#cb7ec8" })
hi(0, "@keyword.operator", { fg = "#7fbbb3" })
hi(0, "@keyword.repeat", { fg = "#cb7ec8" })
hi(0, "@keyword.return", { fg = "#cb7ec8" })
hi(0, "@keyword.storage", { fg = "#cb7ec8" })
hi(0, "@keyword.type", { fg = "#cb7ec8" })
hi(0, "@label.json", { fg = "#59a6c3" })
hi(0, "@lsp.type.boolean", { link = "@boolean" })
hi(0, "@lsp.type.builtinType", { fg = "#d3ad63" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.escapeSequence", { fg = "#d699b6" })
hi(0, "@lsp.type.formatSpecifier", { fg = "#d699b6" })
hi(0, "@lsp.type.interface", { fg = "#ff9185" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.namespace", { fg = "#e0d3d4", italic = true })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { fg = "#e67e80" })
hi(0, "@lsp.type.property", { fg = "#e0d3d4" })
hi(0, "@lsp.type.selfKeyword", { fg = "#e06062" })
hi(0, "@lsp.type.typeAlias", { fg = "#d3ad63" })
hi(0, "@lsp.type.unresolvedReference", { fg = "#e06062" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.class.defaultLibrary", { fg = "#d3ad63" })
hi(0, "@lsp.typemod.enum.defaultLibrary", { fg = "#d3ad63" })
hi(0, "@lsp.typemod.enumMember.defaultLibrary", { fg = "#e69875" })
hi(0, "@lsp.typemod.function.defaultLibrary", { fg = "#e69875" })
hi(0, "@lsp.typemod.keyword.async", { fg = "#cb7ec8" })
hi(0, "@lsp.typemod.macro.defaultLibrary", { fg = "#e69875" })
hi(0, "@lsp.typemod.method.defaultLibrary", { fg = "#e69875" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.type.defaultLibrary", { fg = "#d3ad63" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { fg = "#e06062" })
hi(0, "@lsp.typemod.variable.injected", { fg = "#e8e1bf" })
hi(0, "@markup", { fg = "#e8e1bf" })
hi(0, "@markup.environment", { fg = "#d699b6" })
hi(0, "@markup.environment.name", { fg = "#59a6c3" })
hi(0, "@markup.heading", { bold = true, fg = "#59a6c3" })
hi(0, "@markup.heading.1.markdown", { fg = "#e06062" })
hi(0, "@markup.heading.2.markdown", { fg = "#e69875" })
hi(0, "@markup.heading.3.markdown", { fg = "#d3ad63" })
hi(0, "@markup.heading.4.markdown", { fg = "#b0cc76" })
hi(0, "@markup.heading.5.markdown", { fg = "#60aaa0" })
hi(0, "@markup.heading.6.markdown", { fg = "#e0d3d4" })
hi(0, "@markup.italic", { fg = "#e67e80", italic = true })
hi(0, "@markup.link", { bold = true, fg = "#e0d3d4" })
hi(0, "@markup.link.label", { fg = "#60aaa0" })
hi(0, "@markup.link.url", { fg = "#fed1cb", italic = true, underline = true })
hi(0, "@markup.list", { fg = "#d699b6" })
hi(0, "@markup.list.checked", { fg = "#b0cc76" })
hi(0, "@markup.list.unchecked", { fg = "#859289" })
hi(0, "@markup.math", { fg = "#59a6c3" })
hi(0, "@markup.quote", { bold = true, fg = "#e67e80" })
hi(0, "@markup.raw", { fg = "#6db57f" })
hi(0, "@markup.strikethrough", { fg = "#e8e1bf", strikethrough = true })
hi(0, "@markup.strong", { bold = true, fg = "#e67e80" })
hi(0, "@markup.underline", { link = "Underlined" })
hi(0, "@method", { fg = "#59a6c3" })
hi(0, "@method.call", { fg = "#59a6c3" })
hi(0, "@method.call.php", { fg = "#59a6c3" })
hi(0, "@method.php", { fg = "#59a6c3" })
hi(0, "@module", { fg = "#e0d3d4", italic = true })
hi(0, "@namespace", { fg = "#e0d3d4", italic = true })
hi(0, "@number.css", { fg = "#e69875" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@parameter", { fg = "#e67e80" })
hi(0, "@preproc", { fg = "#d699b6" })
hi(0, "@property", { fg = "#e0d3d4" })
hi(0, "@property.class.css", { fg = "#d3ad63" })
hi(0, "@property.cpp", { fg = "#e8e1bf" })
hi(0, "@property.css", { fg = "#e0d3d4" })
hi(0, "@property.id.css", { fg = "#59a6c3" })
hi(0, "@property.toml", { fg = "#59a6c3" })
hi(0, "@property.typescript", { fg = "#e0d3d4" })
hi(0, "@punctuation.bracket", { fg = "#9da9a0" })
hi(0, "@punctuation.delimiter", { fg = "#9da9a0" })
hi(0, "@punctuation.special", { fg = "#d699b6" })
hi(0, "@repeat", { fg = "#cb7ec8" })
hi(0, "@storageclass", { fg = "#cb7ec8" })
hi(0, "@string.documentation", { fg = "#6db57f" })
hi(0, "@string.escape", { fg = "#d699b6" })
hi(0, "@string.plain.css", { fg = "#e69875" })
hi(0, "@string.regex", { fg = "#e69875" })
hi(0, "@string.regexp", { fg = "#e69875" })
hi(0, "@string.special", { fg = "#d699b6" })
hi(0, "@string.special.path", { fg = "#d699b6" })
hi(0, "@string.special.path.gitignore", { fg = "#e8e1bf" })
hi(0, "@string.special.symbol", { fg = "#ff9185" })
hi(0, "@string.special.symbol.ruby", { fg = "#ff9185" })
hi(0, "@string.special.url", { fg = "#fed1cb", italic = true, underline = true })
hi(0, "@symbol", { fg = "#ff9185" })
hi(0, "@symbol.ruby", { fg = "#ff9185" })
hi(0, "@tag", { fg = "#cb7ec8" })
hi(0, "@tag.attribute", { fg = "#6db57f", italic = true })
hi(0, "@tag.attribute.tsx", { fg = "#6db57f", italic = true })
hi(0, "@tag.delimiter", { fg = "#7fbbb3" })
hi(0, "@text", { fg = "#e8e1bf" })
hi(0, "@text.danger", { bg = "#e06062", fg = "#1f2428" })
hi(0, "@text.diff.add", { fg = "#b0cc76" })
hi(0, "@text.diff.delete", { fg = "#e06062" })
hi(0, "@text.emphasis", { fg = "#e67e80", italic = true })
hi(0, "@text.environment", { fg = "#d699b6" })
hi(0, "@text.environment.name", { fg = "#59a6c3" })
hi(0, "@text.literal", { fg = "#6db57f" })
hi(0, "@text.math", { fg = "#59a6c3" })
hi(0, "@text.note", { bg = "#59a6c3", fg = "#1f2428" })
hi(0, "@text.reference", { bold = true, fg = "#e0d3d4" })
hi(0, "@text.strike", { fg = "#e8e1bf", strikethrough = true })
hi(0, "@text.strong", { bold = true, fg = "#e67e80" })
hi(0, "@text.title", { bold = true, fg = "#59a6c3" })
hi(0, "@text.title.1.markdown", { fg = "#e06062" })
hi(0, "@text.title.2.markdown", { fg = "#e69875" })
hi(0, "@text.title.3.markdown", { fg = "#d3ad63" })
hi(0, "@text.title.4.markdown", { fg = "#b0cc76" })
hi(0, "@text.title.5.markdown", { fg = "#60aaa0" })
hi(0, "@text.title.6.markdown", { fg = "#e0d3d4" })
hi(0, "@text.todo", { bg = "#ff9185", fg = "#1f2428" })
hi(0, "@text.todo.checked", { fg = "#b0cc76" })
hi(0, "@text.todo.unchecked", { fg = "#859289" })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.warning", { bg = "#d3ad63", fg = "#1f2428" })
hi(0, "@type.builtin", { fg = "#d3ad63" })
hi(0, "@type.builtin.c", { fg = "#d3ad63" })
hi(0, "@type.builtin.cpp", { fg = "#d3ad63" })
hi(0, "@type.css", { fg = "#e0d3d4" })
hi(0, "@type.definition", { fg = "#d3ad63" })
hi(0, "@type.qualifier", { fg = "#cb7ec8" })
hi(0, "@type.tag.css", { fg = "#cb7ec8" })
hi(0, "@variable", { fg = "#e8e1bf" })
hi(0, "@variable.builtin", { fg = "#e06062" })
hi(0, "@variable.member", { fg = "#e0d3d4" })
hi(0, "@variable.parameter", { fg = "#e67e80" })
hi(0, "AlphaButtons", { fg = "#e0d3d4" })
hi(0, "AlphaFooter", { fg = "#d3ad63", italic = true })
hi(0, "AlphaHeader", { fg = "#59a6c3" })
hi(0, "AlphaHeaderLabel", { fg = "#e69875" })
hi(0, "AlphaShortcut", { fg = "#b0cc76" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#e69875" })
hi(0, "Character", { fg = "#6db57f" })
hi(0, "CmpItemAbbr", { fg = "#9da9a0" })
hi(0, "CmpItemAbbrDefault", { fg = "#9da9a0" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#6d6649", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#6d6649" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#e8e1bf" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#9da9a0" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#e8e1bf" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#9da9a0" })
hi(0, "CmpItemKind", { fg = "#59a6c3" })
hi(0, "CmpItemKindClass", { fg = "#d3ad63" })
hi(0, "CmpItemKindClassDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindColor", { fg = "#e06062" })
hi(0, "CmpItemKindColorDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindConstant", { fg = "#e69875" })
hi(0, "CmpItemKindConstantDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindConstructor", { fg = "#59a6c3" })
hi(0, "CmpItemKindConstructorDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindCopilot", { fg = "#6db57f" })
hi(0, "CmpItemKindDefault", { fg = "#d699b6" })
hi(0, "CmpItemKindEnum", { fg = "#b0cc76" })
hi(0, "CmpItemKindEnumDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindEnumMember", { fg = "#e06062" })
hi(0, "CmpItemKindEnumMemberDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindEvent", { fg = "#59a6c3" })
hi(0, "CmpItemKindEventDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindField", { fg = "#b0cc76" })
hi(0, "CmpItemKindFieldDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindFile", { fg = "#59a6c3" })
hi(0, "CmpItemKindFileDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindFolder", { fg = "#59a6c3" })
hi(0, "CmpItemKindFolderDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindFunction", { fg = "#59a6c3" })
hi(0, "CmpItemKindFunctionDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindInterface", { fg = "#d3ad63" })
hi(0, "CmpItemKindInterfaceDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindKeyword", { fg = "#e06062" })
hi(0, "CmpItemKindKeywordDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindMethod", { fg = "#59a6c3" })
hi(0, "CmpItemKindMethodDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindModule", { fg = "#59a6c3" })
hi(0, "CmpItemKindModuleDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindOperator", { fg = "#59a6c3" })
hi(0, "CmpItemKindOperatorDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindProperty", { fg = "#b0cc76" })
hi(0, "CmpItemKindPropertyDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindReference", { fg = "#e06062" })
hi(0, "CmpItemKindReferenceDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindSnippet", { fg = "#cb7ec8" })
hi(0, "CmpItemKindSnippetDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindStruct", { fg = "#59a6c3" })
hi(0, "CmpItemKindStructDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindText", { fg = "#6db57f" })
hi(0, "CmpItemKindTextDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindTypeParameter", { fg = "#59a6c3" })
hi(0, "CmpItemKindTypeParameterDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindUnit", { fg = "#b0cc76" })
hi(0, "CmpItemKindUnitDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindValue", { fg = "#e69875" })
hi(0, "CmpItemKindValueDefault", { fg = "#59a6c3" })
hi(0, "CmpItemKindVariable", { fg = "#ff9185" })
hi(0, "CmpItemKindVariableDefault", { fg = "#59a6c3" })
hi(0, "CmpItemMenu", { fg = "#e8e1bf" })
hi(0, "CmpItemMenuDefault", { fg = "#9da9a0" })
hi(0, "ColorColumn", { bg = "#374145" })
hi(0, "Comment", { fg = "#6d6649", italic = true })
hi(0, "Conceal", { fg = "#859289" })
hi(0, "Conditional", { fg = "#cb7ec8", italic = true })
hi(0, "Constant", { fg = "#e69875" })
hi(0, "CurSearch", { bg = "#e06062", fg = "#161b1d" })
hi(0, "Cursor", { bg = "#e8e1bf", fg = "#1f2428" })
hi(0, "CursorColumn", { bg = "#161b1d" })
hi(0, "CursorIM", { bg = "#e8e1bf", fg = "#1f2428" })
hi(0, "CursorLine", { bg = "#2e373b" })
hi(0, "CursorLineNr", { fg = "#e0d3d4" })
hi(0, "DapBreakpoint", { fg = "#e06062" })
hi(0, "DapBreakpointCondition", { fg = "#d3ad63" })
hi(0, "DapBreakpointRejected", { fg = "#cb7ec8" })
hi(0, "DapLogPoint", { fg = "#7fbbb3" })
hi(0, "DapStopped", { fg = "#e67e80" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#b0cc76" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#585c4a" })
hi(0, "DapUIBreakpointsInfo", { fg = "#b0cc76" })
hi(0, "DapUIBreakpointsPath", { fg = "#7fbbb3" })
hi(0, "DapUIDecoration", { fg = "#7fbbb3" })
hi(0, "DapUIFloatBorder", { fg = "#59a6c3" })
hi(0, "DapUILineNumber", { fg = "#7fbbb3" })
hi(0, "DapUIModifiedValue", { fg = "#e69875" })
hi(0, "DapUIPlayPause", { fg = "#b0cc76" })
hi(0, "DapUIRestart", { fg = "#b0cc76" })
hi(0, "DapUIScope", { fg = "#7fbbb3" })
hi(0, "DapUISource", { fg = "#e0d3d4" })
hi(0, "DapUIStepBack", { fg = "#59a6c3" })
hi(0, "DapUIStepInto", { fg = "#59a6c3" })
hi(0, "DapUIStepOut", { fg = "#59a6c3" })
hi(0, "DapUIStepOver", { fg = "#59a6c3" })
hi(0, "DapUIStop", { fg = "#e06062" })
hi(0, "DapUIStoppedThread", { fg = "#7fbbb3" })
hi(0, "DapUIThread", { fg = "#b0cc76" })
hi(0, "DapUIType", { fg = "#cb7ec8" })
hi(0, "DapUIUnavailable", { fg = "#414b50" })
hi(0, "DapUIValue", { fg = "#7fbbb3" })
hi(0, "DapUIVariable", { fg = "#e8e1bf" })
hi(0, "DapUIWatchesEmpty", { fg = "#e67e80" })
hi(0, "DapUIWatchesError", { fg = "#e67e80" })
hi(0, "DapUIWatchesValue", { fg = "#b0cc76" })
hi(0, "DapUIWinSelect", { fg = "#e69875" })
hi(0, "DashboardCenter", { fg = "#b0cc76" })
hi(0, "DashboardDesc", { fg = "#59a6c3" })
hi(0, "DashboardFiles", { fg = "#e0d3d4" })
hi(0, "DashboardFooter", { fg = "#d3ad63", italic = true })
hi(0, "DashboardHeader", { fg = "#59a6c3" })
hi(0, "DashboardIcon", { bold = true, fg = "#d699b6" })
hi(0, "DashboardKey", { fg = "#e69875" })
hi(0, "DashboardMruTitle", { fg = "#7fbbb3" })
hi(0, "DashboardProjectTitle", { fg = "#7fbbb3" })
hi(0, "DashboardShortcut", { fg = "#d699b6" })
hi(0, "Delimiter", { fg = "#9da9a0" })
hi(0, "DiagnosticError", { fg = "#e06062", italic = true })
hi(0, "DiagnosticFloatingError", { fg = "#e06062" })
hi(0, "DiagnosticFloatingHint", { fg = "#6db57f" })
hi(0, "DiagnosticFloatingInfo", { fg = "#7fbbb3" })
hi(0, "DiagnosticFloatingOk", { fg = "#b0cc76" })
hi(0, "DiagnosticFloatingWarn", { fg = "#d3ad63" })
hi(0, "DiagnosticHint", { fg = "#6db57f", italic = true })
hi(0, "DiagnosticInfo", { fg = "#7fbbb3", italic = true })
hi(0, "DiagnosticOk", { fg = "#b0cc76", italic = true })
hi(0, "DiagnosticSignError", { fg = "#e06062" })
hi(0, "DiagnosticSignHint", { fg = "#6db57f" })
hi(0, "DiagnosticSignInfo", { fg = "#7fbbb3" })
hi(0, "DiagnosticSignOk", { fg = "#b0cc76" })
hi(0, "DiagnosticSignWarn", { fg = "#d3ad63" })
hi(0, "DiagnosticUnderlineError", { sp = "#e06062", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#6db57f", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#7fbbb3", underline = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#b0cc76", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#d3ad63", underline = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#312a2e", fg = "#e06062", italic = true })
hi(0, "DiagnosticVirtualTextHint", { bg = "#263230", fg = "#6db57f", italic = true })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#283235", fg = "#7fbbb3", italic = true })
hi(0, "DiagnosticVirtualTextOk", { bg = "#263230", fg = "#b0cc76", italic = true })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#30312e", fg = "#d3ad63", italic = true })
hi(0, "DiagnosticWarn", { fg = "#d3ad63", italic = true })
hi(0, "DiffAdd", { bg = "#394236" })
hi(0, "DiffChange", { bg = "#232d33" })
hi(0, "DiffDelete", { bg = "#422f32" })
hi(0, "DiffText", { bg = "#304b57" })
hi(0, "Directory", { fg = "#59a6c3" })
hi(0, "DropBarIconUISeparator", { fg = "#859289" })
hi(0, "DropBarKindArray", { fg = "#e8e1bf" })
hi(0, "DropBarKindBoolean", { fg = "#e8e1bf" })
hi(0, "DropBarKindBreakStatement", { fg = "#e8e1bf" })
hi(0, "DropBarKindCall", { fg = "#e8e1bf" })
hi(0, "DropBarKindCaseStatement", { fg = "#e8e1bf" })
hi(0, "DropBarKindClass", { fg = "#e8e1bf" })
hi(0, "DropBarKindConstant", { fg = "#e8e1bf" })
hi(0, "DropBarKindConstructor", { fg = "#e8e1bf" })
hi(0, "DropBarKindContinueStatement", { fg = "#e8e1bf" })
hi(0, "DropBarKindDeclaration", { fg = "#e8e1bf" })
hi(0, "DropBarKindDelete", { fg = "#e8e1bf" })
hi(0, "DropBarKindDoStatement", { fg = "#e8e1bf" })
hi(0, "DropBarKindElseStatement", { fg = "#e8e1bf" })
hi(0, "DropBarKindEnum", { fg = "#e8e1bf" })
hi(0, "DropBarKindEnumMember", { fg = "#e8e1bf" })
hi(0, "DropBarKindEvent", { fg = "#e8e1bf" })
hi(0, "DropBarKindField", { fg = "#e8e1bf" })
hi(0, "DropBarKindFile", { fg = "#e8e1bf" })
hi(0, "DropBarKindFolder", { fg = "#e8e1bf" })
hi(0, "DropBarKindForStatement", { fg = "#e8e1bf" })
hi(0, "DropBarKindFunction", { fg = "#e8e1bf" })
hi(0, "DropBarKindIdentifier", { fg = "#e8e1bf" })
hi(0, "DropBarKindIfStatement", { fg = "#e8e1bf" })
hi(0, "DropBarKindInterface", { fg = "#e8e1bf" })
hi(0, "DropBarKindKeyword", { fg = "#e8e1bf" })
hi(0, "DropBarKindList", { fg = "#e8e1bf" })
hi(0, "DropBarKindMacro", { fg = "#e8e1bf" })
hi(0, "DropBarKindMarkdownH1", { fg = "#e8e1bf" })
hi(0, "DropBarKindMarkdownH2", { fg = "#e8e1bf" })
hi(0, "DropBarKindMarkdownH3", { fg = "#e8e1bf" })
hi(0, "DropBarKindMarkdownH4", { fg = "#e8e1bf" })
hi(0, "DropBarKindMarkdownH5", { fg = "#e8e1bf" })
hi(0, "DropBarKindMarkdownH6", { fg = "#e8e1bf" })
hi(0, "DropBarKindMethod", { fg = "#e8e1bf" })
hi(0, "DropBarKindModule", { fg = "#e8e1bf" })
hi(0, "DropBarKindNamespace", { fg = "#e8e1bf" })
hi(0, "DropBarKindNull", { fg = "#e8e1bf" })
hi(0, "DropBarKindNumber", { fg = "#e8e1bf" })
hi(0, "DropBarKindObject", { fg = "#e8e1bf" })
hi(0, "DropBarKindOperator", { fg = "#e8e1bf" })
hi(0, "DropBarKindPackage", { fg = "#e8e1bf" })
hi(0, "DropBarKindProperty", { fg = "#e8e1bf" })
hi(0, "DropBarKindReference", { fg = "#e8e1bf" })
hi(0, "DropBarKindRepeat", { fg = "#e8e1bf" })
hi(0, "DropBarKindScope", { fg = "#e8e1bf" })
hi(0, "DropBarKindSpecifier", { fg = "#e8e1bf" })
hi(0, "DropBarKindStatement", { fg = "#e8e1bf" })
hi(0, "DropBarKindString", { fg = "#e8e1bf" })
hi(0, "DropBarKindStruct", { fg = "#e8e1bf" })
hi(0, "DropBarKindSwitchStatement", { fg = "#e8e1bf" })
hi(0, "DropBarKindType", { fg = "#e8e1bf" })
hi(0, "DropBarKindTypeParameter", { fg = "#e8e1bf" })
hi(0, "DropBarKindUnit", { fg = "#e8e1bf" })
hi(0, "DropBarKindValue", { fg = "#e8e1bf" })
hi(0, "DropBarKindVariable", { fg = "#e8e1bf" })
hi(0, "DropBarKindWhileStatement", { fg = "#e8e1bf" })
hi(0, "DropBarMenuHoverEntry", { bg = "#414b50", bold = true })
hi(0, "DropBarMenuHoverIcon", { reverse = true })
hi(0, "DropBarMenuHoverSymbol", { bold = true })
hi(0, "EndOfBuffer", { fg = "#1f2428" })
hi(0, "Error", { fg = "#e06062" })
hi(0, "ErrorMsg", { bold = true, fg = "#e06062", italic = true })
hi(0, "Exception", { fg = "#cb7ec8" })
hi(0, "FlashBackdrop", { fg = "#6d6649" })
hi(0, "FlashCurrent", { bg = "#1f2428", fg = "#e69875" })
hi(0, "FlashLabel", { bg = "#1f2428", bold = true, fg = "#b0cc76" })
hi(0, "FlashMatch", { bg = "#1f2428", fg = "#e0d3d4" })
hi(0, "FlashPrompt", { bg = "#161b1d", fg = "#e8e1bf" })
hi(0, "FloatBorder", { fg = "#59a6c3" })
hi(0, "FloatTitle", { fg = "#d3c6aa" })
hi(0, "FoldColumn", { fg = "#6d6649" })
hi(0, "Folded", { bg = "#414b50", fg = "#59a6c3" })
hi(0, "Function", { fg = "#59a6c3" })
hi(0, "GitSignsAdd", { fg = "#b0cc76" })
hi(0, "GitSignsAddPreview", { bg = "#394236" })
hi(0, "GitSignsChange", { fg = "#d3ad63" })
hi(0, "GitSignsCurrentLineBlame", { fg = "#414b50" })
hi(0, "GitSignsDelete", { fg = "#e06062" })
hi(0, "GitSignsDeletePreview", { bg = "#422f32" })
hi(0, "GlyphPalette1", { fg = "#e06062" })
hi(0, "GlyphPalette2", { fg = "#6db57f" })
hi(0, "GlyphPalette3", { fg = "#d3ad63" })
hi(0, "GlyphPalette4", { fg = "#59a6c3" })
hi(0, "GlyphPalette6", { fg = "#6db57f" })
hi(0, "GlyphPalette7", { fg = "#e8e1bf" })
hi(0, "GlyphPalette9", { fg = "#e06062" })
hi(0, "IblIndent", { fg = "#374145" })
hi(0, "IblScope", { fg = "#e8e1bf" })
hi(0, "Identifier", { fg = "#ff9185" })
hi(0, "IlluminatedWordRead", { bg = "#373f44" })
hi(0, "IlluminatedWordText", { bg = "#373f44" })
hi(0, "IlluminatedWordWrite", { bg = "#373f44" })
hi(0, "IncSearch", { bg = "#75aca5", fg = "#161b1d" })
hi(0, "Include", { fg = "#cb7ec8" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#cb7ec8" })
hi(0, "Label", { fg = "#60aaa0" })
hi(0, "LineNr", { fg = "#414b50" })
hi(0, "LspCodeLens", { fg = "#6d6649" })
hi(0, "LspDiagnosticsDefaultError", { fg = "#e06062" })
hi(0, "LspDiagnosticsDefaultHint", { fg = "#6db57f" })
hi(0, "LspDiagnosticsDefaultInformation", { fg = "#7fbbb3" })
hi(0, "LspDiagnosticsDefaultWarning", { fg = "#d3ad63" })
hi(0, "LspDiagnosticsError", { fg = "#e06062" })
hi(0, "LspDiagnosticsHint", { fg = "#6db57f" })
hi(0, "LspDiagnosticsInformation", { fg = "#7fbbb3" })
hi(0, "LspDiagnosticsUnderlineError", { sp = "#e06062", underline = true })
hi(0, "LspDiagnosticsUnderlineHint", { sp = "#6db57f", underline = true })
hi(0, "LspDiagnosticsUnderlineInformation", { sp = "#7fbbb3", underline = true })
hi(0, "LspDiagnosticsUnderlineWarning", { sp = "#d3ad63", underline = true })
hi(0, "LspDiagnosticsVirtualTextError", { fg = "#e06062", italic = true })
hi(0, "LspDiagnosticsVirtualTextHint", { fg = "#6db57f", italic = true })
hi(0, "LspDiagnosticsVirtualTextInformation", { fg = "#7fbbb3", italic = true })
hi(0, "LspDiagnosticsVirtualTextWarning", { fg = "#d3ad63", italic = true })
hi(0, "LspDiagnosticsWarning", { fg = "#d3ad63" })
hi(0, "LspInfoBorder", { fg = "#59a6c3" })
hi(0, "LspInlayHint", { bg = "#2e373b", fg = "#6d6649" })
hi(0, "LspReferenceRead", { bg = "#414b50" })
hi(0, "LspReferenceText", { bg = "#414b50" })
hi(0, "LspReferenceWrite", { bg = "#414b50" })
hi(0, "LspSignatureActiveParameter", { fg = "#e69875" })
hi(0, "Macro", { fg = "#cb7ec8" })
hi(0, "MatchParen", { bg = "#414b50", bold = true, fg = "#e69875" })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { bg = "#161b1d", fg = "#e8e1bf" })
hi(0, "MiniClueBorder", { fg = "#59a6c3" })
hi(0, "MiniClueDescGroup", { fg = "#d3ad63" })
hi(0, "MiniClueDescSingle", { bg = "#161b1d", fg = "#e8e1bf" })
hi(0, "MiniClueNextKey", { fg = "#6db57f" })
hi(0, "MiniClueNextKeyWithPostkeys", { fg = "#e06062" })
hi(0, "MiniClueSeparator", { fg = "#7fbbb3" })
hi(0, "MiniClueTitle", { fg = "#d3c6aa" })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniDepsChangeAdded", { fg = "#b0cc76" })
hi(0, "MiniDepsChangeRemoved", { fg = "#e06062" })
hi(0, "MiniDepsHint", { fg = "#6db57f", italic = true })
hi(0, "MiniDepsInfo", { fg = "#7fbbb3", italic = true })
hi(0, "MiniDepsMsgBreaking", { fg = "#d3ad63", italic = true })
hi(0, "MiniDepsPlaceholder", { fg = "#6d6649", italic = true })
hi(0, "MiniDepsTitle", { bold = true, fg = "#59a6c3" })
hi(0, "MiniDepsTitleError", { bg = "#e06062", fg = "#1f2428" })
hi(0, "MiniDepsTitleSame", { bg = "#304b57" })
hi(0, "MiniDepsTitleUpdate", { bg = "#b0cc76", fg = "#1f2428" })
hi(0, "MiniDiffOverAdd", { bg = "#394236" })
hi(0, "MiniDiffOverChange", { bg = "#304b57" })
hi(0, "MiniDiffOverContext", { bg = "#232d33" })
hi(0, "MiniDiffOverDelete", { bg = "#422f32" })
hi(0, "MiniDiffSignAdd", { fg = "#b0cc76" })
hi(0, "MiniDiffSignAdd_stl", { bg = "#161b1d", fg = "#b0cc76" })
hi(0, "MiniDiffSignChange", { fg = "#d3ad63" })
hi(0, "MiniDiffSignChange_stl", { bg = "#161b1d", fg = "#d3ad63" })
hi(0, "MiniDiffSignDelete", { fg = "#e06062" })
hi(0, "MiniDiffSignDelete_stl", { bg = "#161b1d", fg = "#e06062" })
hi(0, "MiniFilesBorder", { fg = "#59a6c3" })
hi(0, "MiniFilesBorderModified", { fg = "#d3ad63" })
hi(0, "MiniFilesCursorLine", { bg = "#2e373b" })
hi(0, "MiniFilesDirectory", { fg = "#59a6c3" })
hi(0, "MiniFilesFile", { fg = "#e8e1bf" })
hi(0, "MiniFilesNormal", { bg = "#161b1d", fg = "#e8e1bf" })
hi(0, "MiniFilesTitle", { fg = "#d3c6aa" })
hi(0, "MiniFilesTitleFocused", { bold = true, fg = "#d3c6aa" })
hi(0, "MiniHipatternsFixme", { bg = "#e06062", bold = true, fg = "#1f2428" })
hi(0, "MiniHipatternsHack", { bg = "#d3ad63", bold = true, fg = "#1f2428" })
hi(0, "MiniHipatternsNote", { bg = "#7fbbb3", bold = true, fg = "#1f2428" })
hi(0, "MiniHipatternsTodo", { bg = "#6db57f", bold = true, fg = "#1f2428" })
hi(0, "MiniIconsAzure", { fg = "#60aaa0" })
hi(0, "MiniIconsBlue", { fg = "#59a6c3" })
hi(0, "MiniIconsCyan", { fg = "#6db57f" })
hi(0, "MiniIconsGreen", { fg = "#b0cc76" })
hi(0, "MiniIconsGrey", { fg = "#e8e1bf" })
hi(0, "MiniIconsOrange", { fg = "#e69875" })
hi(0, "MiniIconsPurple", { fg = "#cb7ec8" })
hi(0, "MiniIconsRed", { fg = "#e06062" })
hi(0, "MiniIconsYellow", { fg = "#d3ad63" })
hi(0, "MiniIndentscopePrefix", { nocombine = true })
hi(0, "MiniIndentscopeSymbol", { fg = "#e8e1bf" })
hi(0, "MiniJump", { bg = "#d699b6", fg = "#9da9a0" })
hi(0, "MiniJump2dDim", { fg = "#6d6649" })
hi(0, "MiniJump2dSpot", { bg = "#1f2428", bold = true, fg = "#e69875", underline = true })
hi(0, "MiniJump2dSpotAhead", { bg = "#171c1f", fg = "#6db57f" })
hi(0, "MiniJump2dSpotUnique", { bg = "#1f2428", bold = true, fg = "#7fbbb3" })
hi(0, "MiniMapNormal", { bg = "#161b1d", fg = "#e8e1bf" })
hi(0, "MiniMapSymbolCount", { fg = "#d699b6" })
hi(0, "MiniMapSymbolLine", { bold = true, fg = "#59a6c3" })
hi(0, "MiniMapSymbolView", { fg = "#9da9a0" })
hi(0, "MiniNotifyBorder", { fg = "#59a6c3" })
hi(0, "MiniNotifyNormal", { bg = "#161b1d", fg = "#e8e1bf" })
hi(0, "MiniNotifyTitle", { fg = "#d3c6aa" })
hi(0, "MiniOperatorsExchangeFrom", { bg = "#75aca5", fg = "#161b1d" })
hi(0, "MiniPickBorderText", { fg = "#cb7ec8" })
hi(0, "MiniPickCursor", { blend = 100, nocombine = true })
hi(0, "MiniStarterFooter", { fg = "#d3ad63", italic = true })
hi(0, "MiniStarterHeader", { fg = "#59a6c3" })
hi(0, "MiniStarterInactive", { fg = "#585c4a", italic = true })
hi(0, "MiniStarterItem", { fg = "#e8e1bf" })
hi(0, "MiniStarterItemBullet", { fg = "#59a6c3" })
hi(0, "MiniStarterItemPrefix", { fg = "#d699b6" })
hi(0, "MiniStarterQuery", { fg = "#b0cc76" })
hi(0, "MiniStarterSection", { fg = "#ff9185" })
hi(0, "MiniStatuslineDevinfo", { bg = "#414b50", fg = "#e0d7c3" })
hi(0, "MiniStatuslineFileinfo", { bg = "#414b50", fg = "#e0d7c3" })
hi(0, "MiniStatuslineFilename", { bg = "#161b1d", fg = "#e8e1bf" })
hi(0, "MiniStatuslineInactive", { bg = "#161b1d", fg = "#59a6c3" })
hi(0, "MiniStatuslineModeCommand", { bg = "#e69875", bold = true, fg = "#1f2428" })
hi(0, "MiniStatuslineModeInsert", { bg = "#b0cc76", bold = true, fg = "#1f2428" })
hi(0, "MiniStatuslineModeNormal", { bg = "#59a6c3", bold = true, fg = "#161b1d" })
hi(0, "MiniStatuslineModeOther", { bg = "#6db57f", bold = true, fg = "#1f2428" })
hi(0, "MiniStatuslineModeReplace", { bg = "#e06062", bold = true, fg = "#1f2428" })
hi(0, "MiniStatuslineModeVisual", { bg = "#cb7ec8", bold = true, fg = "#1f2428" })
hi(0, "MiniSurround", { bg = "#d699b6", fg = "#414b50" })
hi(0, "MiniTablineCurrent", { bg = "#1f2428", bold = true, fg = "#e8e1bf", italic = true, sp = "#e06062", underline = true })
hi(0, "MiniTablineFill", { bg = "#1f2428" })
hi(0, "MiniTablineHidden", { bg = "#161b1d", fg = "#e8e1bf" })
hi(0, "MiniTablineModifiedCurrent", { bold = true, fg = "#e06062", italic = true })
hi(0, "MiniTablineModifiedHidden", { fg = "#e06062" })
hi(0, "MiniTablineModifiedVisible", { fg = "#e06062" })
hi(0, "MiniTablineTabpagesection", { bg = "#1f2428", fg = "#414b50" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#e06062" })
hi(0, "MiniTestPass", { bold = true, fg = "#b0cc76" })
hi(0, "MiniTrailspace", { bg = "#e06062" })
hi(0, "ModeMsg", { bold = true, fg = "#e8e1bf" })
hi(0, "MoreMsg", { fg = "#59a6c3" })
hi(0, "MsgSeparator", {})
hi(0, "NeoTreeDimText", { fg = "#859289" })
hi(0, "NeoTreeDirectoryIcon", { fg = "#59a6c3" })
hi(0, "NeoTreeDirectoryName", { fg = "#59a6c3" })
hi(0, "NeoTreeExpander", { fg = "#6d6649" })
hi(0, "NeoTreeFileNameOpened", { fg = "#d699b6" })
hi(0, "NeoTreeFilterTerm", { bold = true, fg = "#b0cc76" })
hi(0, "NeoTreeFloatBorder", { fg = "#59a6c3" })
hi(0, "NeoTreeFloatTitle", { fg = "#d3c6aa" })
hi(0, "NeoTreeGitAdded", { fg = "#b0cc76" })
hi(0, "NeoTreeGitConflict", { fg = "#e06062" })
hi(0, "NeoTreeGitDeleted", { fg = "#e06062" })
hi(0, "NeoTreeGitIgnored", { fg = "#6d6649" })
hi(0, "NeoTreeGitModified", { fg = "#d3ad63" })
hi(0, "NeoTreeGitStaged", { fg = "#b0cc76" })
hi(0, "NeoTreeGitUnstaged", { fg = "#e06062" })
hi(0, "NeoTreeGitUntracked", { fg = "#cb7ec8" })
hi(0, "NeoTreeIndentMarker", { fg = "#6d6649" })
hi(0, "NeoTreeModified", { fg = "#e69875" })
hi(0, "NeoTreeNormal", { bg = "#161b1d", fg = "#e8e1bf" })
hi(0, "NeoTreeNormalNC", { bg = "#161b1d", fg = "#e8e1bf" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#59a6c3" })
hi(0, "NeoTreeStatusLineNC", { bg = "#161b1d", fg = "#161b1d" })
hi(0, "NeoTreeSymbolicLinkTarget", { fg = "#d699b6" })
hi(0, "NeoTreeTabActive", { bg = "#161b1d", bold = true, fg = "#e0d3d4" })
hi(0, "NeoTreeTabInactive", { bg = "#1f2428", fg = "#6d6649" })
hi(0, "NeoTreeTabSeparatorActive", { bg = "#161b1d", fg = "#161b1d" })
hi(0, "NeoTreeTabSeparatorInactive", { bg = "#1f2428", fg = "#1f2428" })
hi(0, "NeoTreeTitleBar", { bg = "#59a6c3", fg = "#161b1d" })
hi(0, "NeoTreeVertSplit", { bg = "#1f2428", fg = "#1f2428" })
hi(0, "NeoTreeWinSeparator", { bg = "#1f2428", fg = "#1f2428" })
hi(0, "NeogitBranch", { bold = true, fg = "#e69875" })
hi(0, "NeogitChangeAdded", { bold = true, fg = "#b0cc76" })
hi(0, "NeogitChangeBothModified", { bold = true, fg = "#d3ad63" })
hi(0, "NeogitChangeCopied", { bold = true, fg = "#d699b6" })
hi(0, "NeogitChangeDeleted", { bold = true, fg = "#e06062" })
hi(0, "NeogitChangeModified", { bold = true, fg = "#59a6c3" })
hi(0, "NeogitChangeNewFile", { bold = true, fg = "#b0cc76" })
hi(0, "NeogitChangeRenamed", { bold = true, fg = "#cb7ec8" })
hi(0, "NeogitChangeUpdated", { bold = true, fg = "#e69875" })
hi(0, "NeogitCommitViewHeader", { bg = "#304b57", fg = "#76b2c2" })
hi(0, "NeogitDiffAdd", { bg = "#2d342f", fg = "#93aa66" })
hi(0, "NeogitDiffAddHighlight", { bg = "#515e43", fg = "#b8cf81" })
hi(0, "NeogitDiffContext", { bg = "#1f2428" })
hi(0, "NeogitDiffContextHighlight", { bg = "#374145" })
hi(0, "NeogitDiffDelete", { bg = "#312a2e", fg = "#b95456" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#62393c", fg = "#e17370" })
hi(0, "NeogitDiffHeader", { bg = "#1f2428", bold = true, fg = "#59a6c3" })
hi(0, "NeogitDiffHeaderHighlight", { bg = "#1f2428", bold = true, fg = "#e69875" })
hi(0, "NeogitFilePath", { fg = "#59a6c3", italic = true })
hi(0, "NeogitGraphBlue", { fg = "#59a6c3" })
hi(0, "NeogitGraphBoldBlue", { bold = true, fg = "#59a6c3" })
hi(0, "NeogitGraphBoldCyan", { bold = true, fg = "#59a6c3" })
hi(0, "NeogitGraphBoldGray", { bold = true, fg = "#e0d7c3" })
hi(0, "NeogitGraphBoldGreen", { bold = true, fg = "#b0cc76" })
hi(0, "NeogitGraphBoldPurple", { bold = true, fg = "#e0d3d4" })
hi(0, "NeogitGraphBoldRed", { bold = true, fg = "#e06062" })
hi(0, "NeogitGraphBoldWhite", { bold = true })
hi(0, "NeogitGraphBoldYellow", { bold = true, fg = "#d3ad63" })
hi(0, "NeogitGraphCyan", { fg = "#59a6c3" })
hi(0, "NeogitGraphGray", { fg = "#e0d7c3" })
hi(0, "NeogitGraphGreen", { fg = "#b0cc76" })
hi(0, "NeogitGraphOrange", { fg = "#e69875" })
hi(0, "NeogitGraphPurple", { fg = "#e0d3d4" })
hi(0, "NeogitGraphRed", { fg = "#e06062" })
hi(0, "NeogitGraphWhite", { fg = "#1f2428" })
hi(0, "NeogitGraphYellow", { fg = "#d3ad63" })
hi(0, "NeogitHunkHeader", { bg = "#253037", fg = "#3c6576" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#2b4049", fg = "#59a6c3" })
hi(0, "NeogitNotificationError", { fg = "#e06062" })
hi(0, "NeogitNotificationInfo", { fg = "#59a6c3" })
hi(0, "NeogitNotificationWarning", { fg = "#d3ad63" })
hi(0, "NeogitObjectId", { fg = "#6d6649", italic = true })
hi(0, "NeogitPopupActionKey", { fg = "#e0d3d4" })
hi(0, "NeogitPopupBold", { bold = true })
hi(0, "NeogitPopupConfigKey", { fg = "#e0d3d4" })
hi(0, "NeogitPopupOptionKey", { fg = "#e0d3d4" })
hi(0, "NeogitPopupSwitchKey", { fg = "#e0d3d4" })
hi(0, "NeogitRebaseDone", { fg = "#6d6649", italic = true })
hi(0, "NeogitRebasing", { bold = true, fg = "#cb7ec8" })
hi(0, "NeogitRecentcommits", { bold = true, fg = "#cb7ec8" })
hi(0, "NeogitRemote", { bold = true, fg = "#b0cc76" })
hi(0, "NeogitSectionHeader", { bold = true, fg = "#cb7ec8" })
hi(0, "NeogitStagedchanges", { bold = true, fg = "#cb7ec8" })
hi(0, "NeogitStash", { fg = "#6d6649", italic = true })
hi(0, "NeogitStashes", { bold = true, fg = "#cb7ec8" })
hi(0, "NeogitTagDistance", { fg = "#59a6c3" })
hi(0, "NeogitTagName", { fg = "#d3ad63" })
hi(0, "NeogitUnmergedInto", { fg = "#59a6c3" })
hi(0, "NeogitUnmergedchanges", { bold = true, fg = "#cb7ec8" })
hi(0, "NeogitUnpulledFrom", { fg = "#59a6c3" })
hi(0, "NeogitUnpulledchanges", { bold = true, fg = "#cb7ec8" })
hi(0, "NeogitUnpushedTo", { bold = true, fg = "#e0d3d4" })
hi(0, "NeogitUnstagedchanges", { bold = true, fg = "#cb7ec8" })
hi(0, "NeogitUntrackedfiles", { bold = true, fg = "#cb7ec8" })
hi(0, "NeogitWinSeparator", { fg = "#14181a" })
hi(0, "NonText", { fg = "#6d6649" })
hi(0, "Normal", { bg = "#1f2428", fg = "#e8e1bf" })
hi(0, "NormalFloat", { bg = "#161b1d", fg = "#e8e1bf" })
hi(0, "NormalNC", { bg = "#1f2428", fg = "#e8e1bf" })
hi(0, "NormalSB", { bg = "#14181a", fg = "#e8e1bf" })
hi(0, "NotifyDEBUGBorder", { fg = "#8b8b8b" })
hi(0, "NotifyDEBUGIcon", { fg = "#8b8b8b" })
hi(0, "NotifyDEBUGTitle", { fg = "#8b8b8b" })
hi(0, "NotifyERRORBorder", { fg = "#8a1f1f" })
hi(0, "NotifyERRORIcon", { fg = "#f70067" })
hi(0, "NotifyERRORTitle", { fg = "#f70067" })
hi(0, "NotifyINFOBorder", { fg = "#4f6752" })
hi(0, "NotifyINFOIcon", { fg = "#a9ff68" })
hi(0, "NotifyINFOTitle", { fg = "#a9ff68" })
hi(0, "NotifyTRACEBorder", { fg = "#4f3552" })
hi(0, "NotifyTRACEIcon", { fg = "#d484ff" })
hi(0, "NotifyTRACETitle", { fg = "#d484ff" })
hi(0, "NotifyWARNBorder", { fg = "#79491d" })
hi(0, "NotifyWARNIcon", { fg = "#f79000" })
hi(0, "NotifyWARNTitle", { fg = "#f79000" })
hi(0, "Number", { fg = "#e69875" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#59a6c3" })
hi(0, "NvimTreeFolderIcon", { fg = "#59a6c3" })
hi(0, "NvimTreeFolderName", { fg = "#59a6c3" })
hi(0, "NvimTreeGitDeleted", { fg = "#e06062" })
hi(0, "NvimTreeGitDirty", { fg = "#d3ad63" })
hi(0, "NvimTreeGitNew", { fg = "#59a6c3" })
hi(0, "NvimTreeImageFile", { fg = "#e8e1bf" })
hi(0, "NvimTreeIndentMarker", { fg = "#6d6649" })
hi(0, "NvimTreeNormal", { bg = "#161b1d", fg = "#e8e1bf" })
hi(0, "NvimTreeOpenedFile", { fg = "#d699b6" })
hi(0, "NvimTreeOpenedFolderName", { fg = "#59a6c3" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#e0d3d4" })
hi(0, "NvimTreeSpecialFile", { fg = "#ff9185" })
hi(0, "NvimTreeStatuslineNc", { bg = "#161b1d", fg = "#161b1d" })
hi(0, "NvimTreeSymlink", { fg = "#d699b6" })
hi(0, "NvimTreeWinSeparator", { bg = "#1f2428", fg = "#1f2428" })
hi(0, "Operator", { fg = "#7fbbb3" })
hi(0, "Pmenu", { bg = "#30393c", fg = "#9da9a0" })
hi(0, "PmenuSbar", { bg = "#414b50" })
hi(0, "PmenuSel", { bg = "#414b50", bold = true })
hi(0, "PmenuThumb", { bg = "#6d6649" })
hi(0, "PreProc", { fg = "#d699b6" })
hi(0, "Question", { fg = "#59a6c3" })
hi(0, "QuickFixLine", { bg = "#414b50", bold = true })
hi(0, "RainbowDelimiterBlue", { fg = "#59a6c3" })
hi(0, "RainbowDelimiterCyan", { fg = "#6db57f" })
hi(0, "RainbowDelimiterGreen", { fg = "#b0cc76" })
hi(0, "RainbowDelimiterOrange", { fg = "#e69875" })
hi(0, "RainbowDelimiterRed", { fg = "#e06062" })
hi(0, "RainbowDelimiterViolet", { fg = "#cb7ec8" })
hi(0, "RainbowDelimiterYellow", { fg = "#d3ad63" })
hi(0, "RenderMarkdownBullet", { fg = "#7fbbb3" })
hi(0, "RenderMarkdownCode", { bg = "#374145" })
hi(0, "RenderMarkdownCodeInline", { bg = "#414b50" })
hi(0, "RenderMarkdownError", { fg = "#e06062" })
hi(0, "RenderMarkdownH1", { fg = "#e06062" })
hi(0, "RenderMarkdownH1Bg", { bg = "#593639" })
hi(0, "RenderMarkdownH2", { fg = "#e69875" })
hi(0, "RenderMarkdownH2Bg", { bg = "#5b473f" })
hi(0, "RenderMarkdownH3", { fg = "#d3ad63" })
hi(0, "RenderMarkdownH3Bg", { bg = "#554d3a" })
hi(0, "RenderMarkdownH4", { fg = "#b0cc76" })
hi(0, "RenderMarkdownH4Bg", { bg = "#4b563f" })
hi(0, "RenderMarkdownH5", { fg = "#60aaa0" })
hi(0, "RenderMarkdownH5Bg", { bg = "#334c4c" })
hi(0, "RenderMarkdownH6", { fg = "#e0d3d4" })
hi(0, "RenderMarkdownH6Bg", { bg = "#59595c" })
hi(0, "RenderMarkdownHint", { fg = "#6db57f" })
hi(0, "RenderMarkdownInfo", { fg = "#7fbbb3" })
hi(0, "RenderMarkdownSuccess", { fg = "#b0cc76" })
hi(0, "RenderMarkdownTableHead", { fg = "#59a6c3" })
hi(0, "RenderMarkdownTableRow", { fg = "#e0d3d4" })
hi(0, "RenderMarkdownWarn", { fg = "#d3ad63" })
hi(0, "Repeat", { fg = "#cb7ec8" })
hi(0, "Search", { bg = "#3c5152", fg = "#e8e1bf" })
hi(0, "SignColumn", { fg = "#414b50" })
hi(0, "SignColumnSB", { bg = "#14181a", fg = "#414b50" })
hi(0, "Special", { fg = "#d699b6" })
hi(0, "SpecialKey", { fg = "#6d6649" })
hi(0, "SpellBad", { sp = "#e06062", undercurl = true })
hi(0, "SpellCap", { sp = "#d3ad63", undercurl = true })
hi(0, "SpellLocal", { sp = "#59a6c3", undercurl = true })
hi(0, "SpellRare", { sp = "#b0cc76", undercurl = true })
hi(0, "Statement", { fg = "#cb7ec8" })
hi(0, "StatusLine", { bg = "#161b1d", fg = "#e8e1bf" })
hi(0, "StatusLineNC", { bg = "#161b1d", fg = "#414b50" })
hi(0, "StorageClass", { fg = "#d3ad63" })
hi(0, "String", { fg = "#b0cc76" })
hi(0, "Structure", { fg = "#d3ad63" })
hi(0, "Substitute", { bg = "#414b50", fg = "#d699b6" })
hi(0, "TabLine", { bg = "#161b1d", fg = "#6d6649" })
hi(0, "TabLineFill", { bg = "#161b1d" })
hi(0, "TabLineSel", { bg = "#1f2428", fg = "#b0cc76" })
hi(0, "Tag", { bold = true, fg = "#e0d3d4" })
hi(0, "TelescopeBorder", { fg = "#59a6c3" })
hi(0, "TelescopeMatching", { fg = "#59a6c3" })
hi(0, "TelescopeSelection", { bg = "#374145", bold = true, fg = "#e8e1bf" })
hi(0, "TelescopeSelectionCaret", { fg = "#ff9185" })
hi(0, "TermCursor", { bg = "#fed1cb", fg = "#1f2428" })
hi(0, "TermCursorNC", { bg = "#9da9a0", fg = "#1f2428" })
hi(0, "Title", { bold = true, fg = "#59a6c3" })
hi(0, "Todo", { bg = "#ff9185", bold = true, fg = "#1f2428" })
hi(0, "TreesitterContextBottom", { sp = "#374145", underline = true })
hi(0, "TreesitterContextLineNumber", { bg = "#161b1d", fg = "#414b50" })
hi(0, "Type", { fg = "#d3ad63" })
hi(0, "UfoFoldedEllipsis", { bg = "#59a6c3", fg = "#14181a" })
hi(0, "UfoFoldedFg", { fg = "#e0d3d4" })
hi(0, "VertSplit", { fg = "#14181a" })
hi(0, "Visual", { bg = "#414b50", bold = true })
hi(0, "VisualNOS", { bg = "#414b50", bold = true })
hi(0, "WarningMsg", { fg = "#d3ad63" })
hi(0, "Whitespace", { fg = "#414b50" })
hi(0, "WildMenu", { bg = "#6d6649" })
hi(0, "WinBar", { fg = "#fed1cb" })
hi(0, "WinBarNC", { fg = "#fed1cb" })
hi(0, "WinSeparator", { fg = "#14181a" })
hi(0, "csvCol0", { fg = "#e06062" })
hi(0, "csvCol1", { fg = "#e69875" })
hi(0, "csvCol2", { fg = "#d3ad63" })
hi(0, "csvCol3", { fg = "#b0cc76" })
hi(0, "csvCol4", { fg = "#7fbbb3" })
hi(0, "csvCol5", { fg = "#59a6c3" })
hi(0, "csvCol6", { fg = "#e0d3d4" })
hi(0, "csvCol7", { fg = "#cb7ec8" })
hi(0, "csvCol8", { fg = "#d699b6" })
hi(0, "debugBreakpoint", { bg = "#1f2428", fg = "#6d6649" })
hi(0, "debugPC", { bg = "#14181a" })
hi(0, "diffAdded", { fg = "#b0cc76" })
hi(0, "diffChanged", { fg = "#59a6c3" })
hi(0, "diffFile", { fg = "#59a6c3" })
hi(0, "diffIndexLine", { fg = "#6db57f" })
hi(0, "diffLine", { fg = "#6d6649" })
hi(0, "diffNewFile", { fg = "#e69875" })
hi(0, "diffOldFile", { fg = "#d3ad63" })
hi(0, "diffRemoved", { fg = "#e06062" })
hi(0, "gitcommitSummary", { fg = "#fed1cb", italic = true })
hi(0, "healthError", { fg = "#e06062" })
hi(0, "healthSuccess", { fg = "#6db57f" })
hi(0, "healthWarning", { fg = "#d3ad63" })
hi(0, "htmlH1", { bold = true, fg = "#d699b6" })
hi(0, "htmlH2", { bold = true, fg = "#59a6c3" })
hi(0, "illuminatedCurWord", { bg = "#414b50" })
hi(0, "illuminatedWord", { bg = "#414b50" })
hi(0, "lCursor", { bg = "#e8e1bf", fg = "#1f2428" })
hi(0, "markdownCode", { fg = "#ff9185" })
hi(0, "markdownCodeBlock", { fg = "#ff9185" })
hi(0, "markdownH1", { fg = "#e06062" })
hi(0, "markdownH2", { fg = "#e69875" })
hi(0, "markdownH3", { fg = "#d3ad63" })
hi(0, "markdownH4", { fg = "#b0cc76" })
hi(0, "markdownH5", { fg = "#60aaa0" })
hi(0, "markdownH6", { fg = "#e0d3d4" })
hi(0, "markdownHeadingDelimiter", { bold = true, fg = "#e69875" })
hi(0, "markdownLinkText", { fg = "#59a6c3", underline = true })
hi(0, "mkdCodeDelimiter", { bg = "#1f2428", fg = "#e8e1bf" })
hi(0, "mkdCodeEnd", { bold = true, fg = "#ff9185" })
hi(0, "mkdCodeStart", { bold = true, fg = "#ff9185" })
hi(0, "qfFileName", { fg = "#59a6c3" })
hi(0, "qfLineNr", { fg = "#d3ad63" })
hi(0, "rainbow1", { fg = "#e06062" })
hi(0, "rainbow2", { fg = "#e69875" })
hi(0, "rainbow3", { fg = "#d3ad63" })
hi(0, "rainbow4", { fg = "#b0cc76" })
hi(0, "rainbow5", { fg = "#60aaa0" })
hi(0, "rainbow6", { fg = "#e0d3d4" })
hi(0, "zshKSHFunction", { fg = "#59a6c3" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#26233a"
g.terminal_color_1 = "#eb6f92"
g.terminal_color_2 = "#31748f"
g.terminal_color_3 = "#f6c177"
g.terminal_color_4 = "#9ccfd8"
g.terminal_color_5 = "#c4a7e7"
g.terminal_color_6 = "#ebbcba"
g.terminal_color_7 = "#e0def4"
g.terminal_color_8 = "#908caa"
g.terminal_color_9 = "#eb6f92"
g.terminal_color_10 = "#31748f"
g.terminal_color_11 = "#f6c177"
g.terminal_color_12 = "#9ccfd8"
g.terminal_color_13 = "#c4a7e7"
g.terminal_color_14 = "#ebbcba"
g.terminal_color_15 = "#e0def4"
