-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "catppuccin-macchiato"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "Constant" })
hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.documentation", { link = "Comment" })
hi(0, "@comment.error", { bg = "#ed8796", fg = "#24273a" })
hi(0, "@comment.hint", { bg = "#8aadf4", fg = "#24273a" })
hi(0, "@comment.note", { bg = "#8aadf4", fg = "#24273a" })
hi(0, "@comment.todo", { bg = "#f0c6c6", fg = "#24273a" })
hi(0, "@comment.warning", { bg = "#eed49f", fg = "#24273a" })
hi(0, "@comment.warning.gitcommit", { fg = "#eed49f" })
hi(0, "@conditional", { link = "Conditional" })
hi(0, "@constant.builtin", { fg = "#f5a97f" })
hi(0, "@constant.java", { fg = "#8bd5ca" })
hi(0, "@constant.macro", { link = "Macro" })
hi(0, "@constructor", { fg = "#7dc4e4" })
hi(0, "@constructor.lua", { fg = "#f0c6c6" })
hi(0, "@constructor.tsx", { fg = "#b7bdf8" })
hi(0, "@constructor.typescript", { fg = "#b7bdf8" })
hi(0, "@define", { link = "Define" })
hi(0, "@diff.delta", { link = "diffChanged" })
hi(0, "@diff.minus", { link = "diffRemoved" })
hi(0, "@diff.plus", { link = "diffAdded" })
hi(0, "@error", { link = "Error" })
hi(0, "@exception", { link = "Exception" })
hi(0, "@field", { fg = "#b7bdf8" })
hi(0, "@float", { link = "Float" })
hi(0, "@function.builtin", { fg = "#f5a97f" })
hi(0, "@function.builtin.bash", { fg = "#ed8796", italic = true })
hi(0, "@function.call", { link = "Function" })
hi(0, "@function.macro", { fg = "#8bd5ca" })
hi(0, "@function.method", { link = "Function" })
hi(0, "@function.method.call", { link = "Function" })
hi(0, "@function.method.call.php", { link = "Function" })
hi(0, "@function.method.php", { link = "Function" })
hi(0, "@include", { link = "Include" })
hi(0, "@keyword.conditional", { link = "Conditional" })
hi(0, "@keyword.conditional.ternary", { link = "Operator" })
hi(0, "@keyword.coroutine", { link = "Keyword" })
hi(0, "@keyword.debug", { link = "Exception" })
hi(0, "@keyword.directive", { link = "PreProc" })
hi(0, "@keyword.directive.define", { link = "Define" })
hi(0, "@keyword.exception", { link = "Exception" })
hi(0, "@keyword.export", { fg = "#91d7e3" })
hi(0, "@keyword.function", { fg = "#c6a0f6" })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.modifier", { link = "Keyword" })
hi(0, "@keyword.operator", { link = "Operator" })
hi(0, "@keyword.repeat", { link = "Repeat" })
hi(0, "@keyword.return", { fg = "#c6a0f6" })
hi(0, "@keyword.storage", { link = "Keyword" })
hi(0, "@keyword.type", { link = "Keyword" })
hi(0, "@label.json", { fg = "#8aadf4" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.boolean", { link = "@boolean" })
hi(0, "@lsp.type.builtinType", { link = "@type.builtin" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.formatSpecifier", { link = "@punctuation.special" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { fg = "#f0c6c6" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeAlias", { link = "@type.definition" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.unresolvedReference", { link = "@error" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
hi(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.type.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@markup", { fg = "#cad3f5" })
hi(0, "@markup.environment", { fg = "#f5bde6" })
hi(0, "@markup.environment.name", { fg = "#8aadf4" })
hi(0, "@markup.heading", { bold = true, fg = "#8aadf4" })
hi(0, "@markup.heading.1.markdown", { link = "rainbow1" })
hi(0, "@markup.heading.2.markdown", { link = "rainbow2" })
hi(0, "@markup.heading.3.markdown", { link = "rainbow3" })
hi(0, "@markup.heading.4.markdown", { link = "rainbow4" })
hi(0, "@markup.heading.5.markdown", { link = "rainbow5" })
hi(0, "@markup.heading.6.markdown", { link = "rainbow6" })
hi(0, "@markup.italic", { fg = "#ee99a0", italic = true })
hi(0, "@markup.link", { link = "Tag" })
hi(0, "@markup.link.label", { link = "Label" })
hi(0, "@markup.link.url", { fg = "#f4dbd6", italic = true, underline = true })
hi(0, "@markup.list", { link = "Special" })
hi(0, "@markup.list.checked", { fg = "#a6da95" })
hi(0, "@markup.list.unchecked", { fg = "#8087a2" })
hi(0, "@markup.math", { fg = "#8aadf4" })
hi(0, "@markup.quote", { bold = true, fg = "#ee99a0" })
hi(0, "@markup.raw", { fg = "#8bd5ca" })
hi(0, "@markup.strikethrough", { fg = "#cad3f5", strikethrough = true })
hi(0, "@markup.strong", { bold = true, fg = "#ee99a0" })
hi(0, "@markup.underline", { link = "Underlined" })
hi(0, "@method", { link = "Function" })
hi(0, "@method.call", { link = "Function" })
hi(0, "@method.call.php", { link = "Function" })
hi(0, "@method.php", { link = "Function" })
hi(0, "@module", { fg = "#b7bdf8", italic = true })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@namespace", { fg = "#b7bdf8", italic = true })
hi(0, "@number.css", { fg = "#f5a97f" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@parameter", { fg = "#ee99a0" })
hi(0, "@preproc", { link = "PreProc" })
hi(0, "@property", { fg = "#b7bdf8" })
hi(0, "@property.class.css", { fg = "#eed49f" })
hi(0, "@property.cpp", { fg = "#cad3f5" })
hi(0, "@property.css", { fg = "#b7bdf8" })
hi(0, "@property.id.css", { fg = "#8aadf4" })
hi(0, "@property.toml", { fg = "#8aadf4" })
hi(0, "@property.typescript", { fg = "#b7bdf8" })
hi(0, "@punctuation.bracket", { fg = "#939ab7" })
hi(0, "@punctuation.delimiter", { link = "Delimiter" })
hi(0, "@punctuation.special", { link = "Special" })
hi(0, "@repeat", { link = "Repeat" })
hi(0, "@storageclass", { link = "Keyword" })
hi(0, "@string.documentation", { fg = "#8bd5ca" })
hi(0, "@string.escape", { fg = "#f5bde6" })
hi(0, "@string.plain.css", { fg = "#f5a97f" })
hi(0, "@string.regex", { fg = "#f5a97f" })
hi(0, "@string.regexp", { fg = "#f5a97f" })
hi(0, "@string.special", { link = "Special" })
hi(0, "@string.special.path", { link = "Special" })
hi(0, "@string.special.symbol", { fg = "#f0c6c6" })
hi(0, "@string.special.symbol.ruby", { fg = "#f0c6c6" })
hi(0, "@string.special.url", { fg = "#f4dbd6", italic = true, underline = true })
hi(0, "@symbol", { fg = "#f0c6c6" })
hi(0, "@symbol.ruby", { fg = "#f0c6c6" })
hi(0, "@tag", { fg = "#c6a0f6" })
hi(0, "@tag.attribute", { fg = "#8bd5ca", italic = true })
hi(0, "@tag.attribute.tsx", { fg = "#8bd5ca", italic = true })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@tag.delimiter", { fg = "#91d7e3" })
hi(0, "@text", { fg = "#cad3f5" })
hi(0, "@text.danger", { bg = "#ed8796", fg = "#24273a" })
hi(0, "@text.diff.add", { link = "diffAdded" })
hi(0, "@text.diff.delete", { link = "diffRemoved" })
hi(0, "@text.emphasis", { fg = "#ee99a0", italic = true })
hi(0, "@text.environment", { fg = "#f5bde6" })
hi(0, "@text.environment.name", { fg = "#8aadf4" })
hi(0, "@text.literal", { fg = "#8bd5ca" })
hi(0, "@text.math", { fg = "#8aadf4" })
hi(0, "@text.note", { bg = "#8aadf4", fg = "#24273a" })
hi(0, "@text.reference", { link = "Tag" })
hi(0, "@text.strike", { fg = "#cad3f5", strikethrough = true })
hi(0, "@text.strong", { bold = true, fg = "#ee99a0" })
hi(0, "@text.title", { bold = true, fg = "#8aadf4" })
hi(0, "@text.title.1.markdown", { link = "rainbow1" })
hi(0, "@text.title.2.markdown", { link = "rainbow2" })
hi(0, "@text.title.3.markdown", { link = "rainbow3" })
hi(0, "@text.title.4.markdown", { link = "rainbow4" })
hi(0, "@text.title.5.markdown", { link = "rainbow5" })
hi(0, "@text.title.6.markdown", { link = "rainbow6" })
hi(0, "@text.todo", { bg = "#f0c6c6", fg = "#24273a" })
hi(0, "@text.todo.checked", { fg = "#a6da95" })
hi(0, "@text.todo.unchecked", { fg = "#8087a2" })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.warning", { bg = "#eed49f", fg = "#24273a" })
hi(0, "@type.builtin", { fg = "#eed49f" })
hi(0, "@type.builtin.c", { fg = "#eed49f" })
hi(0, "@type.builtin.cpp", { fg = "#eed49f" })
hi(0, "@type.css", { fg = "#b7bdf8" })
hi(0, "@type.definition", { link = "Type" })
hi(0, "@type.qualifier", { link = "Keyword" })
hi(0, "@type.tag.css", { fg = "#c6a0f6" })
hi(0, "@variable", { fg = "#cad3f5" })
hi(0, "@variable.builtin", { fg = "#ed8796" })
hi(0, "@variable.member", { fg = "#b7bdf8" })
hi(0, "@variable.parameter", { fg = "#ee99a0" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "AlphaButtons", { fg = "#b7bdf8" })
hi(0, "AlphaFooter", { fg = "#eed49f", italic = true })
hi(0, "AlphaHeader", { fg = "#8aadf4" })
hi(0, "AlphaHeaderLabel", { fg = "#f5a97f" })
hi(0, "AlphaShortcut", { fg = "#a6da95" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#f5a97f" })
hi(0, "Character", { fg = "#8bd5ca" })
hi(0, "CmpItemAbbr", { fg = "#939ab7" })
hi(0, "CmpItemAbbrDefault", { fg = "#939ab7" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#6e738d", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#6e738d" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#cad3f5" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#939ab7" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#cad3f5" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#939ab7" })
hi(0, "CmpItemKind", { fg = "#8aadf4" })
hi(0, "CmpItemKindClass", { fg = "#eed49f" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { fg = "#ed8796" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { fg = "#f5a97f" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { fg = "#8aadf4" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCopilot", { fg = "#8bd5ca" })
hi(0, "CmpItemKindDefault", { fg = "#f5bde6" })
hi(0, "CmpItemKindEnum", { fg = "#a6da95" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { fg = "#ed8796" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { fg = "#8aadf4" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { fg = "#a6da95" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { fg = "#8aadf4" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { fg = "#8aadf4" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { fg = "#8aadf4" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { fg = "#eed49f" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { fg = "#ed8796" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { fg = "#8aadf4" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { fg = "#8aadf4" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { fg = "#8aadf4" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { fg = "#a6da95" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { fg = "#ed8796" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { fg = "#c6a0f6" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { fg = "#8aadf4" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { fg = "#8bd5ca" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { fg = "#8aadf4" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { fg = "#a6da95" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { fg = "#f5a97f" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { fg = "#f0c6c6" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#cad3f5" })
hi(0, "CmpItemMenuDefault", { fg = "#939ab7" })
hi(0, "ColorColumn", { bg = "#363a4f" })
hi(0, "Comment", { fg = "#6e738d", italic = true })
hi(0, "Conceal", { fg = "#8087a2" })
hi(0, "Conditional", { fg = "#c6a0f6", italic = true })
hi(0, "Constant", { fg = "#f5a97f" })
hi(0, "CurSearch", { bg = "#ed8796", fg = "#1e2030" })
hi(0, "Cursor", { bg = "#cad3f5", fg = "#24273a" })
hi(0, "CursorColumn", { bg = "#1e2030" })
hi(0, "CursorIM", { bg = "#cad3f5", fg = "#24273a" })
hi(0, "CursorLine", { bg = "#303347" })
hi(0, "CursorLineNr", { fg = "#b7bdf8" })
hi(0, "DapBreakpoint", { fg = "#ed8796" })
hi(0, "DapBreakpointCondition", { fg = "#eed49f" })
hi(0, "DapBreakpointRejected", { fg = "#c6a0f6" })
hi(0, "DapLogPoint", { fg = "#91d7e3" })
hi(0, "DapStopped", { fg = "#ee99a0" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#a6da95" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#5b6078" })
hi(0, "DapUIBreakpointsInfo", { fg = "#a6da95" })
hi(0, "DapUIBreakpointsPath", { fg = "#91d7e3" })
hi(0, "DapUIDecoration", { fg = "#91d7e3" })
hi(0, "DapUIFloatBorder", { fg = "#91d7e3" })
hi(0, "DapUILineNumber", { fg = "#91d7e3" })
hi(0, "DapUIModifiedValue", { fg = "#f5a97f" })
hi(0, "DapUIPlayPause", { fg = "#a6da95" })
hi(0, "DapUIRestart", { fg = "#a6da95" })
hi(0, "DapUIScope", { fg = "#91d7e3" })
hi(0, "DapUISource", { fg = "#b7bdf8" })
hi(0, "DapUIStepBack", { fg = "#8aadf4" })
hi(0, "DapUIStepInto", { fg = "#8aadf4" })
hi(0, "DapUIStepOut", { fg = "#8aadf4" })
hi(0, "DapUIStepOver", { fg = "#8aadf4" })
hi(0, "DapUIStop", { fg = "#ed8796" })
hi(0, "DapUIStoppedThread", { fg = "#91d7e3" })
hi(0, "DapUIThread", { fg = "#a6da95" })
hi(0, "DapUIType", { fg = "#c6a0f6" })
hi(0, "DapUIUnavailable", { fg = "#494d64" })
hi(0, "DapUIValue", { fg = "#91d7e3" })
hi(0, "DapUIVariable", { fg = "#cad3f5" })
hi(0, "DapUIWatchesEmpty", { fg = "#ee99a0" })
hi(0, "DapUIWatchesError", { fg = "#ee99a0" })
hi(0, "DapUIWatchesValue", { fg = "#a6da95" })
hi(0, "DapUIWinSelect", { fg = "#f5a97f" })
hi(0, "DashboardCenter", { fg = "#a6da95" })
hi(0, "DashboardDesc", { fg = "#8aadf4" })
hi(0, "DashboardFiles", { fg = "#b7bdf8" })
hi(0, "DashboardFooter", { fg = "#eed49f", italic = true })
hi(0, "DashboardHeader", { fg = "#8aadf4" })
hi(0, "DashboardIcon", { bold = true, fg = "#f5bde6" })
hi(0, "DashboardKey", { fg = "#f5a97f" })
hi(0, "DashboardMruTitle", { fg = "#91d7e3" })
hi(0, "DashboardProjectTitle", { fg = "#91d7e3" })
hi(0, "DashboardShortCut", { fg = "#f5bde6" })
hi(0, "Delimiter", { fg = "#939ab7" })
hi(0, "DiagnosticError", { fg = "#ed8796", italic = true })
hi(0, "DiagnosticFloatingError", { fg = "#ed8796" })
hi(0, "DiagnosticFloatingHint", { fg = "#8bd5ca" })
hi(0, "DiagnosticFloatingInfo", { fg = "#91d7e3" })
hi(0, "DiagnosticFloatingOk", { fg = "#a6da95" })
hi(0, "DiagnosticFloatingWarn", { fg = "#eed49f" })
hi(0, "DiagnosticHint", { fg = "#8bd5ca", italic = true })
hi(0, "DiagnosticInfo", { fg = "#91d7e3", italic = true })
hi(0, "DiagnosticOk", { fg = "#a6da95", italic = true })
hi(0, "DiagnosticSignError", { fg = "#ed8796" })
hi(0, "DiagnosticSignHint", { fg = "#8bd5ca" })
hi(0, "DiagnosticSignInfo", { fg = "#91d7e3" })
hi(0, "DiagnosticSignOk", { fg = "#a6da95" })
hi(0, "DiagnosticSignWarn", { fg = "#eed49f" })
hi(0, "DiagnosticUnderlineError", { sp = "#ed8796", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#8bd5ca", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#91d7e3", underline = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#a6da95", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#eed49f", underline = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#373043", fg = "#ed8796", italic = true })
hi(0, "DiagnosticVirtualTextHint", { bg = "#2e3848", fg = "#8bd5ca", italic = true })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#2e384a", fg = "#91d7e3", italic = true })
hi(0, "DiagnosticVirtualTextOk", { bg = "#2e3848", fg = "#a6da95", italic = true })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#373744", fg = "#eed49f", italic = true })
hi(0, "DiagnosticWarn", { fg = "#eed49f", italic = true })
hi(0, "DiffAdd", { bg = "#3b474a" })
hi(0, "DiffChange", { bg = "#2b3047" })
hi(0, "DiffDelete", { bg = "#48384b" })
hi(0, "DiffText", { bg = "#434f72" })
hi(0, "Directory", { fg = "#8aadf4" })
hi(0, "DropBarIconUISeparator", { fg = "#8087a2" })
hi(0, "DropBarKindArray", { fg = "#cad3f5" })
hi(0, "DropBarKindBoolean", { fg = "#cad3f5" })
hi(0, "DropBarKindBreakStatement", { fg = "#cad3f5" })
hi(0, "DropBarKindCall", { fg = "#cad3f5" })
hi(0, "DropBarKindCaseStatement", { fg = "#cad3f5" })
hi(0, "DropBarKindClass", { fg = "#cad3f5" })
hi(0, "DropBarKindConstant", { fg = "#cad3f5" })
hi(0, "DropBarKindConstructor", { fg = "#cad3f5" })
hi(0, "DropBarKindContinueStatement", { fg = "#cad3f5" })
hi(0, "DropBarKindDeclaration", { fg = "#cad3f5" })
hi(0, "DropBarKindDelete", { fg = "#cad3f5" })
hi(0, "DropBarKindDoStatement", { fg = "#cad3f5" })
hi(0, "DropBarKindElseStatement", { fg = "#cad3f5" })
hi(0, "DropBarKindEnum", { fg = "#cad3f5" })
hi(0, "DropBarKindEnumMember", { fg = "#cad3f5" })
hi(0, "DropBarKindEvent", { fg = "#cad3f5" })
hi(0, "DropBarKindField", { fg = "#cad3f5" })
hi(0, "DropBarKindFile", { fg = "#cad3f5" })
hi(0, "DropBarKindFolder", { fg = "#cad3f5" })
hi(0, "DropBarKindForStatement", { fg = "#cad3f5" })
hi(0, "DropBarKindFunction", { fg = "#cad3f5" })
hi(0, "DropBarKindIdentifier", { fg = "#cad3f5" })
hi(0, "DropBarKindIfStatement", { fg = "#cad3f5" })
hi(0, "DropBarKindInterface", { fg = "#cad3f5" })
hi(0, "DropBarKindKeyword", { fg = "#cad3f5" })
hi(0, "DropBarKindList", { fg = "#cad3f5" })
hi(0, "DropBarKindMacro", { fg = "#cad3f5" })
hi(0, "DropBarKindMarkdownH1", { fg = "#cad3f5" })
hi(0, "DropBarKindMarkdownH2", { fg = "#cad3f5" })
hi(0, "DropBarKindMarkdownH3", { fg = "#cad3f5" })
hi(0, "DropBarKindMarkdownH4", { fg = "#cad3f5" })
hi(0, "DropBarKindMarkdownH5", { fg = "#cad3f5" })
hi(0, "DropBarKindMarkdownH6", { fg = "#cad3f5" })
hi(0, "DropBarKindMethod", { fg = "#cad3f5" })
hi(0, "DropBarKindModule", { fg = "#cad3f5" })
hi(0, "DropBarKindNamespace", { fg = "#cad3f5" })
hi(0, "DropBarKindNull", { fg = "#cad3f5" })
hi(0, "DropBarKindNumber", { fg = "#cad3f5" })
hi(0, "DropBarKindObject", { fg = "#cad3f5" })
hi(0, "DropBarKindOperator", { fg = "#cad3f5" })
hi(0, "DropBarKindPackage", { fg = "#cad3f5" })
hi(0, "DropBarKindProperty", { fg = "#cad3f5" })
hi(0, "DropBarKindReference", { fg = "#cad3f5" })
hi(0, "DropBarKindRepeat", { fg = "#cad3f5" })
hi(0, "DropBarKindScope", { fg = "#cad3f5" })
hi(0, "DropBarKindSpecifier", { fg = "#cad3f5" })
hi(0, "DropBarKindStatement", { fg = "#cad3f5" })
hi(0, "DropBarKindString", { fg = "#cad3f5" })
hi(0, "DropBarKindStruct", { fg = "#cad3f5" })
hi(0, "DropBarKindSwitchStatement", { fg = "#cad3f5" })
hi(0, "DropBarKindType", { fg = "#cad3f5" })
hi(0, "DropBarKindTypeParameter", { fg = "#cad3f5" })
hi(0, "DropBarKindUnit", { fg = "#cad3f5" })
hi(0, "DropBarKindValue", { fg = "#cad3f5" })
hi(0, "DropBarKindVariable", { fg = "#cad3f5" })
hi(0, "DropBarKindWhileStatement", { fg = "#cad3f5" })
hi(0, "DropBarMenuHoverEntry", { link = "Visual" })
hi(0, "DropBarMenuHoverIcon", { reverse = true })
hi(0, "DropBarMenuHoverSymbol", { bold = true })
hi(0, "EndOfBuffer", { fg = "#24273a" })
hi(0, "Error", { fg = "#ed8796" })
hi(0, "ErrorMsg", { bold = true, fg = "#ed8796", italic = true })
hi(0, "Exception", { fg = "#c6a0f6" })
hi(0, "FlashBackdrop", { fg = "#6e738d" })
hi(0, "FlashCurrent", { bg = "#24273a", fg = "#f5a97f" })
hi(0, "FlashLabel", { bg = "#24273a", bold = true, fg = "#a6da95" })
hi(0, "FlashMatch", { bg = "#24273a", fg = "#b7bdf8" })
hi(0, "FlashPrompt", { link = "NormalFloat" })
hi(0, "FloatBorder", { bg = "#1e2030", fg = "#8aadf4" })
hi(0, "FloatTitle", { fg = "#a5adcb" })
hi(0, "FoldColumn", { fg = "#6e738d" })
hi(0, "Folded", { bg = "#494d64", fg = "#8aadf4" })
hi(0, "Function", { fg = "#8aadf4" })
hi(0, "GitSignsAdd", { fg = "#a6da95" })
hi(0, "GitSignsAddPreview", { link = "DiffAdd" })
hi(0, "GitSignsChange", { fg = "#eed49f" })
hi(0, "GitSignsCurrentLineBlame", { fg = "#494d64" })
hi(0, "GitSignsDelete", { fg = "#ed8796" })
hi(0, "GitSignsDeletePreview", { link = "DiffDelete" })
hi(0, "GlyphPalette1", { fg = "#ed8796" })
hi(0, "GlyphPalette2", { fg = "#8bd5ca" })
hi(0, "GlyphPalette3", { fg = "#eed49f" })
hi(0, "GlyphPalette4", { fg = "#8aadf4" })
hi(0, "GlyphPalette6", { fg = "#8bd5ca" })
hi(0, "GlyphPalette7", { fg = "#cad3f5" })
hi(0, "GlyphPalette9", { fg = "#ed8796" })
hi(0, "IblIndent", { fg = "#363a4f" })
hi(0, "IblScope", { fg = "#cad3f5" })
hi(0, "Identifier", { fg = "#f0c6c6" })
hi(0, "IlluminatedWordRead", { bg = "#3e4257" })
hi(0, "IlluminatedWordText", { bg = "#3e4257" })
hi(0, "IlluminatedWordWrite", { bg = "#3e4257" })
hi(0, "IncSearch", { bg = "#86c5d2", fg = "#1e2030" })
hi(0, "Include", { fg = "#c6a0f6" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#c6a0f6" })
hi(0, "Label", { fg = "#7dc4e4" })
hi(0, "LineNr", { fg = "#494d64" })
hi(0, "LspCodeLens", { fg = "#6e738d" })
hi(0, "LspDiagnosticsDefaultError", { fg = "#ed8796" })
hi(0, "LspDiagnosticsDefaultHint", { fg = "#8bd5ca" })
hi(0, "LspDiagnosticsDefaultInformation", { fg = "#91d7e3" })
hi(0, "LspDiagnosticsDefaultWarning", { fg = "#eed49f" })
hi(0, "LspDiagnosticsError", { fg = "#ed8796" })
hi(0, "LspDiagnosticsHint", { fg = "#8bd5ca" })
hi(0, "LspDiagnosticsInformation", { fg = "#91d7e3" })
hi(0, "LspDiagnosticsUnderlineError", { sp = "#ed8796", underline = true })
hi(0, "LspDiagnosticsUnderlineHint", { sp = "#8bd5ca", underline = true })
hi(0, "LspDiagnosticsUnderlineInformation", { sp = "#91d7e3", underline = true })
hi(0, "LspDiagnosticsUnderlineWarning", { sp = "#eed49f", underline = true })
hi(0, "LspDiagnosticsVirtualTextError", { fg = "#ed8796", italic = true })
hi(0, "LspDiagnosticsVirtualTextHint", { fg = "#8bd5ca", italic = true })
hi(0, "LspDiagnosticsVirtualTextInformation", { fg = "#91d7e3", italic = true })
hi(0, "LspDiagnosticsVirtualTextWarning", { fg = "#eed49f", italic = true })
hi(0, "LspDiagnosticsWarning", { fg = "#eed49f" })
hi(0, "LspInfoBorder", { link = "FloatBorder" })
hi(0, "LspInlayHint", { bg = "#303347", fg = "#6e738d" })
hi(0, "LspReferenceRead", { bg = "#494d64" })
hi(0, "LspReferenceText", { bg = "#494d64" })
hi(0, "LspReferenceWrite", { bg = "#494d64" })
hi(0, "LspSignatureActiveParameter", { fg = "#f5a97f" })
hi(0, "Macro", { fg = "#c6a0f6" })
hi(0, "MatchParen", { bg = "#494d64", bold = true, fg = "#f5a97f" })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "FloatBorder" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { link = "FloatTitle" })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniDepsChangeAdded", { link = "diffAdded" })
hi(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
hi(0, "MiniDepsHint", { link = "DiagnosticHint" })
hi(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
hi(0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
hi(0, "MiniDepsPlaceholder", { link = "Comment" })
hi(0, "MiniDepsTitle", { link = "Title" })
hi(0, "MiniDepsTitleError", { bg = "#ed8796", fg = "#24273a" })
hi(0, "MiniDepsTitleSame", { link = "DiffText" })
hi(0, "MiniDepsTitleUpdate", { bg = "#a6da95", fg = "#24273a" })
hi(0, "MiniDiffOverAdd", { link = "DiffAdd" })
hi(0, "MiniDiffOverChange", { link = "DiffText" })
hi(0, "MiniDiffOverContext", { link = "DiffChange" })
hi(0, "MiniDiffOverDelete", { link = "DiffDelete" })
hi(0, "MiniDiffSignAdd", { fg = "#a6da95" })
hi(0, "MiniDiffSignAdd_stl", { fg = "#a6da95" })
hi(0, "MiniDiffSignChange", { fg = "#eed49f" })
hi(0, "MiniDiffSignChange_stl", { fg = "#eed49f" })
hi(0, "MiniDiffSignDelete", { fg = "#ed8796" })
hi(0, "MiniDiffSignDelete_stl", { fg = "#ed8796" })
hi(0, "MiniFilesBorder", { link = "FloatBorder" })
hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniFilesCursorLine", { link = "CursorLine" })
hi(0, "MiniFilesDirectory", { link = "Directory" })
hi(0, "MiniFilesFile", { fg = "#cad3f5" })
hi(0, "MiniFilesNormal", { link = "NormalFloat" })
hi(0, "MiniFilesTitle", { link = "FloatTitle" })
hi(0, "MiniFilesTitleFocused", { bold = true, fg = "#a5adcb" })
hi(0, "MiniHipatternsFixme", { bg = "#ed8796", bold = true, fg = "#24273a" })
hi(0, "MiniHipatternsHack", { bg = "#eed49f", bold = true, fg = "#24273a" })
hi(0, "MiniHipatternsNote", { bg = "#91d7e3", bold = true, fg = "#24273a" })
hi(0, "MiniHipatternsTodo", { bg = "#8bd5ca", bold = true, fg = "#24273a" })
hi(0, "MiniIconsAzure", { fg = "#7dc4e4" })
hi(0, "MiniIconsBlue", { fg = "#8aadf4" })
hi(0, "MiniIconsCyan", { fg = "#8bd5ca" })
hi(0, "MiniIconsGreen", { fg = "#a6da95" })
hi(0, "MiniIconsGrey", { fg = "#cad3f5" })
hi(0, "MiniIconsOrange", { fg = "#f5a97f" })
hi(0, "MiniIconsPurple", { fg = "#c6a0f6" })
hi(0, "MiniIconsRed", { fg = "#ed8796" })
hi(0, "MiniIconsYellow", { fg = "#eed49f" })
hi(0, "MiniIndentscopePrefix", { nocombine = true })
hi(0, "MiniIndentscopeSymbol", { fg = "#c6a0f6" })
hi(0, "MiniJump", { bg = "#f5bde6", fg = "#939ab7" })
hi(0, "MiniJump2dDim", { fg = "#6e738d" })
hi(0, "MiniJump2dSpot", { bg = "#24273a", bold = true, fg = "#f5a97f", underline = true })
hi(0, "MiniJump2dSpotAhead", { bg = "#1f2132", fg = "#8bd5ca" })
hi(0, "MiniJump2dSpotUnique", { bg = "#24273a", bold = true, fg = "#91d7e3" })
hi(0, "MiniMapNormal", { link = "NormalFloat" })
hi(0, "MiniMapSymbolCount", { link = "Special" })
hi(0, "MiniMapSymbolLine", { link = "Title" })
hi(0, "MiniMapSymbolView", { link = "Delimiter" })
hi(0, "MiniNotifyBorder", { link = "FloatBorder" })
hi(0, "MiniNotifyNormal", { link = "NormalFloat" })
hi(0, "MiniNotifyTitle", { link = "FloatTitle" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniPickBorder", { link = "FloatBorder" })
hi(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniPickBorderText", { fg = "#c6a0f6" })
hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickIconDirectory", { link = "Directory" })
hi(0, "MiniPickIconFile", { link = "MiniPickNormal" })
hi(0, "MiniPickMatchCurrent", { link = "CursorLine" })
hi(0, "MiniPickMatchMarked", { link = "Visual" })
hi(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickNormal", { link = "NormalFloat" })
hi(0, "MiniPickPreviewLine", { link = "CursorLine" })
hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
hi(0, "MiniPickPrompt", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniStarterFooter", { fg = "#eed49f", italic = true })
hi(0, "MiniStarterHeader", { fg = "#8aadf4" })
hi(0, "MiniStarterInactive", { fg = "#5b6078", italic = true })
hi(0, "MiniStarterItem", { fg = "#cad3f5" })
hi(0, "MiniStarterItemBullet", { fg = "#8aadf4" })
hi(0, "MiniStarterItemPrefix", { fg = "#f5bde6" })
hi(0, "MiniStarterQuery", { fg = "#a6da95" })
hi(0, "MiniStarterSection", { fg = "#f0c6c6" })
hi(0, "MiniStatuslineDevinfo", { bg = "#494d64", fg = "#b8c0e0" })
hi(0, "MiniStatuslineFileinfo", { bg = "#494d64", fg = "#b8c0e0" })
hi(0, "MiniStatuslineFilename", { bg = "#1e2030", fg = "#cad3f5" })
hi(0, "MiniStatuslineInactive", { bg = "#1e2030", fg = "#8aadf4" })
hi(0, "MiniStatuslineModeCommand", { bg = "#f5a97f", bold = true, fg = "#24273a" })
hi(0, "MiniStatuslineModeInsert", { bg = "#a6da95", bold = true, fg = "#24273a" })
hi(0, "MiniStatuslineModeNormal", { bg = "#8aadf4", bold = true, fg = "#1e2030" })
hi(0, "MiniStatuslineModeOther", { bg = "#8bd5ca", bold = true, fg = "#24273a" })
hi(0, "MiniStatuslineModeReplace", { bg = "#ed8796", bold = true, fg = "#24273a" })
hi(0, "MiniStatuslineModeVisual", { bg = "#c6a0f6", bold = true, fg = "#24273a" })
hi(0, "MiniSurround", { bg = "#f5bde6", fg = "#494d64" })
hi(0, "MiniTablineCurrent", { bg = "#24273a", bold = true, fg = "#cad3f5", italic = true, sp = "#ed8796", underline = true })
hi(0, "MiniTablineFill", { bg = "#24273a" })
hi(0, "MiniTablineHidden", { bg = "#1e2030", fg = "#cad3f5" })
hi(0, "MiniTablineModifiedCurrent", { bold = true, fg = "#ed8796", italic = true })
hi(0, "MiniTablineModifiedHidden", { fg = "#ed8796" })
hi(0, "MiniTablineModifiedVisible", { fg = "#ed8796" })
hi(0, "MiniTablineTabpagesection", { bg = "#24273a", fg = "#494d64" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#ed8796" })
hi(0, "MiniTestPass", { bold = true, fg = "#a6da95" })
hi(0, "MiniTrailspace", { bg = "#ed8796" })
hi(0, "ModeMsg", { bold = true, fg = "#cad3f5" })
hi(0, "MoreMsg", { fg = "#8aadf4" })
hi(0, "MsgSeparator", {})
hi(0, "NeoTreeDimText", { fg = "#8087a2" })
hi(0, "NeoTreeDirectoryIcon", { fg = "#8aadf4" })
hi(0, "NeoTreeDirectoryName", { fg = "#8aadf4" })
hi(0, "NeoTreeExpander", { fg = "#6e738d" })
hi(0, "NeoTreeFileNameOpened", { fg = "#f5bde6" })
hi(0, "NeoTreeFilterTerm", { bold = true, fg = "#a6da95" })
hi(0, "NeoTreeFloatBorder", { link = "FloatBorder" })
hi(0, "NeoTreeFloatTitle", { link = "FloatTitle" })
hi(0, "NeoTreeGitAdded", { fg = "#a6da95" })
hi(0, "NeoTreeGitConflict", { fg = "#ed8796" })
hi(0, "NeoTreeGitDeleted", { fg = "#ed8796" })
hi(0, "NeoTreeGitIgnored", { fg = "#6e738d" })
hi(0, "NeoTreeGitModified", { fg = "#eed49f" })
hi(0, "NeoTreeGitStaged", { fg = "#a6da95" })
hi(0, "NeoTreeGitUnstaged", { fg = "#ed8796" })
hi(0, "NeoTreeGitUntracked", { fg = "#c6a0f6" })
hi(0, "NeoTreeIndentMarker", { fg = "#6e738d" })
hi(0, "NeoTreeModified", { fg = "#f5a97f" })
hi(0, "NeoTreeNormal", { bg = "#1e2030", fg = "#cad3f5" })
hi(0, "NeoTreeNormalNC", { bg = "#1e2030", fg = "#cad3f5" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#8aadf4" })
hi(0, "NeoTreeStatusLineNC", { bg = "#1e2030", fg = "#1e2030" })
hi(0, "NeoTreeSymbolicLinkTarget", { fg = "#f5bde6" })
hi(0, "NeoTreeTabActive", { bg = "#1e2030", bold = true, fg = "#b7bdf8" })
hi(0, "NeoTreeTabInactive", { bg = "#24273a", fg = "#6e738d" })
hi(0, "NeoTreeTabSeparatorActive", { bg = "#1e2030", fg = "#1e2030" })
hi(0, "NeoTreeTabSeparatorInactive", { bg = "#24273a", fg = "#24273a" })
hi(0, "NeoTreeTitleBar", { bg = "#8aadf4", fg = "#1e2030" })
hi(0, "NeoTreeVertSplit", { bg = "#24273a", fg = "#24273a" })
hi(0, "NeoTreeWinSeparator", { bg = "#24273a", fg = "#24273a" })
hi(0, "NeogitBranch", { bold = true, fg = "#f5a97f" })
hi(0, "NeogitChangeAdded", { bold = true, fg = "#a6da95" })
hi(0, "NeogitChangeBothModified", { bold = true, fg = "#eed49f" })
hi(0, "NeogitChangeCopied", { bold = true, fg = "#f5bde6" })
hi(0, "NeogitChangeDeleted", { bold = true, fg = "#ed8796" })
hi(0, "NeogitChangeModified", { bold = true, fg = "#8aadf4" })
hi(0, "NeogitChangeNewFile", { bold = true, fg = "#a6da95" })
hi(0, "NeogitChangeRenamed", { bold = true, fg = "#c6a0f6" })
hi(0, "NeogitChangeUpdated", { bold = true, fg = "#f5a97f" })
hi(0, "NeogitCommitViewHeader", { bg = "#434f72", fg = "#97b5f4" })
hi(0, "NeogitDiffAdd", { bg = "#303843", fg = "#8cb683" })
hi(0, "NeogitDiffAddHighlight", { bg = "#516559", fg = "#abd9a3" })
hi(0, "NeogitDiffContext", { bg = "#24273a" })
hi(0, "NeogitDiffContextHighlight", { bg = "#363a4f" })
hi(0, "NeogitDiffDelete", { bg = "#373043", fg = "#c57484" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#69485a", fg = "#e892a4" })
hi(0, "NeogitDiffHeader", { bg = "#24273a", bold = true, fg = "#8aadf4" })
hi(0, "NeogitDiffHeaderHighlight", { bg = "#24273a", bold = true, fg = "#f5a97f" })
hi(0, "NeogitFilePath", { fg = "#8aadf4", italic = true })
hi(0, "NeogitGraphBlue", { fg = "#8aadf4" })
hi(0, "NeogitGraphBoldBlue", { bold = true, fg = "#8aadf4" })
hi(0, "NeogitGraphBoldCyan", { bold = true, fg = "#8aadf4" })
hi(0, "NeogitGraphBoldGray", { bold = true, fg = "#b8c0e0" })
hi(0, "NeogitGraphBoldGreen", { bold = true, fg = "#a6da95" })
hi(0, "NeogitGraphBoldPurple", { bold = true, fg = "#b7bdf8" })
hi(0, "NeogitGraphBoldRed", { bold = true, fg = "#ed8796" })
hi(0, "NeogitGraphBoldWhite", { bold = true })
hi(0, "NeogitGraphBoldYellow", { bold = true, fg = "#eed49f" })
hi(0, "NeogitGraphCyan", { fg = "#8aadf4" })
hi(0, "NeogitGraphGray", { fg = "#b8c0e0" })
hi(0, "NeogitGraphGreen", { fg = "#a6da95" })
hi(0, "NeogitGraphOrange", { fg = "#f5a97f" })
hi(0, "NeogitGraphPurple", { fg = "#b7bdf8" })
hi(0, "NeogitGraphRed", { fg = "#ed8796" })
hi(0, "NeogitGraphWhite", { fg = "#24273a" })
hi(0, "NeogitGraphYellow", { fg = "#eed49f" })
hi(0, "NeogitHunkHeader", { bg = "#2e344c", fg = "#576a97" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#3a4462", fg = "#8aadf4" })
hi(0, "NeogitNotificationError", { fg = "#ed8796" })
hi(0, "NeogitNotificationInfo", { fg = "#8aadf4" })
hi(0, "NeogitNotificationWarning", { fg = "#eed49f" })
hi(0, "NeogitObjectId", { link = "Comment" })
hi(0, "NeogitPopupActionKey", { fg = "#b7bdf8" })
hi(0, "NeogitPopupBold", { bold = true })
hi(0, "NeogitPopupConfigKey", { fg = "#b7bdf8" })
hi(0, "NeogitPopupOptionKey", { fg = "#b7bdf8" })
hi(0, "NeogitPopupSwitchKey", { fg = "#b7bdf8" })
hi(0, "NeogitRebaseDone", { link = "Comment" })
hi(0, "NeogitRebasing", { bold = true, fg = "#c6a0f6" })
hi(0, "NeogitRecentcommits", { bold = true, fg = "#c6a0f6" })
hi(0, "NeogitRemote", { bold = true, fg = "#a6da95" })
hi(0, "NeogitSectionHeader", { bold = true, fg = "#c6a0f6" })
hi(0, "NeogitStagedchanges", { bold = true, fg = "#c6a0f6" })
hi(0, "NeogitStash", { link = "Comment" })
hi(0, "NeogitStashes", { bold = true, fg = "#c6a0f6" })
hi(0, "NeogitTagDistance", { fg = "#8aadf4" })
hi(0, "NeogitTagName", { fg = "#eed49f" })
hi(0, "NeogitUnmergedInto", { link = "Function" })
hi(0, "NeogitUnmergedchanges", { bold = true, fg = "#c6a0f6" })
hi(0, "NeogitUnpulledFrom", { link = "Function" })
hi(0, "NeogitUnpulledchanges", { bold = true, fg = "#c6a0f6" })
hi(0, "NeogitUnpushedTo", { bold = true, fg = "#b7bdf8" })
hi(0, "NeogitUnstagedchanges", { bold = true, fg = "#c6a0f6" })
hi(0, "NeogitUntrackedfiles", { bold = true, fg = "#c6a0f6" })
hi(0, "NeogitWinSeparator", { link = "WinSeparator" })
hi(0, "NonText", { fg = "#6e738d" })
hi(0, "Normal", { bg = "#24273a", fg = "#cad3f5" })
hi(0, "NormalFloat", { bg = "#1e2030", fg = "#cad3f5" })
hi(0, "NormalNC", { bg = "#24273a", fg = "#cad3f5" })
hi(0, "NormalSB", { bg = "#181926", fg = "#cad3f5" })
hi(0, "Number", { fg = "#f5a97f" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#8aadf4" })
hi(0, "NvimTreeFolderIcon", { fg = "#8aadf4" })
hi(0, "NvimTreeFolderName", { fg = "#8aadf4" })
hi(0, "NvimTreeGitDeleted", { fg = "#ed8796" })
hi(0, "NvimTreeGitDirty", { fg = "#eed49f" })
hi(0, "NvimTreeGitNew", { fg = "#8aadf4" })
hi(0, "NvimTreeImageFile", { fg = "#cad3f5" })
hi(0, "NvimTreeIndentMarker", { fg = "#6e738d" })
hi(0, "NvimTreeNormal", { bg = "#1e2030", fg = "#cad3f5" })
hi(0, "NvimTreeOpenedFile", { fg = "#f5bde6" })
hi(0, "NvimTreeOpenedFolderName", { fg = "#8aadf4" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#b7bdf8" })
hi(0, "NvimTreeSpecialFile", { fg = "#f0c6c6" })
hi(0, "NvimTreeStatuslineNc", { bg = "#1e2030", fg = "#1e2030" })
hi(0, "NvimTreeSymlink", { fg = "#f5bde6" })
hi(0, "NvimTreeWinSeparator", { bg = "#24273a", fg = "#24273a" })
hi(0, "Operator", { fg = "#91d7e3" })
hi(0, "Pmenu", { bg = "#303347", fg = "#939ab7" })
hi(0, "PmenuSbar", { bg = "#494d64" })
hi(0, "PmenuSel", { bg = "#494d64", bold = true })
hi(0, "PmenuThumb", { bg = "#6e738d" })
hi(0, "PreProc", { fg = "#f5bde6" })
hi(0, "Question", { fg = "#8aadf4" })
hi(0, "QuickFixLine", { bg = "#494d64", bold = true })
hi(0, "RainbowDelimiterBlue", { fg = "#8aadf4" })
hi(0, "RainbowDelimiterCyan", { fg = "#8bd5ca" })
hi(0, "RainbowDelimiterGreen", { fg = "#a6da95" })
hi(0, "RainbowDelimiterOrange", { fg = "#f5a97f" })
hi(0, "RainbowDelimiterRed", { fg = "#ed8796" })
hi(0, "RainbowDelimiterViolet", { fg = "#c6a0f6" })
hi(0, "RainbowDelimiterYellow", { fg = "#eed49f" })
hi(0, "Repeat", { fg = "#c6a0f6" })
hi(0, "Search", { bg = "#455c6d", fg = "#cad3f5" })
hi(0, "SignColumn", { fg = "#494d64" })
hi(0, "SignColumnSB", { bg = "#181926", fg = "#494d64" })
hi(0, "Special", { fg = "#f5bde6" })
hi(0, "SpecialKey", { link = "NonText" })
hi(0, "SpellBad", { sp = "#ed8796", undercurl = true })
hi(0, "SpellCap", { sp = "#eed49f", undercurl = true })
hi(0, "SpellLocal", { sp = "#8aadf4", undercurl = true })
hi(0, "SpellRare", { sp = "#a6da95", undercurl = true })
hi(0, "Statement", { fg = "#c6a0f6" })
hi(0, "StatusLine", { bg = "#1e2030", fg = "#cad3f5" })
hi(0, "StatusLineNC", { bg = "#1e2030", fg = "#494d64" })
hi(0, "StorageClass", { fg = "#eed49f" })
hi(0, "String", { fg = "#a6da95" })
hi(0, "Structure", { fg = "#eed49f" })
hi(0, "Substitute", { bg = "#494d64", fg = "#f5bde6" })
hi(0, "TabLine", { bg = "#1e2030", fg = "#494d64" })
hi(0, "TabLineFill", {})
hi(0, "TabLineSel", { bg = "#494d64", fg = "#a6da95" })
hi(0, "Tag", { bold = true, fg = "#b7bdf8" })
hi(0, "TelescopeBorder", { link = "FloatBorder" })
hi(0, "TelescopeMatching", { fg = "#8aadf4" })
hi(0, "TelescopePreviewBorder", { bg = "#181926", fg = "#181926" })
hi(0, "TelescopePreviewNormal", { bg = "#181926" })
hi(0, "TelescopePreviewTitle", { bg = "#181926", fg = "#181926" })
hi(0, "TelescopePromptBorder", { bg = "#363a4f", fg = "#363a4f" })
hi(0, "TelescopePromptCounter", { bold = true, fg = "#c6a0f6" })
hi(0, "TelescopePromptNormal", { bg = "#363a4f" })
hi(0, "TelescopePromptPrefix", { bg = "#363a4f" })
hi(0, "TelescopePromptTitle", { bg = "#363a4f", fg = "#363a4f" })
hi(0, "TelescopeResultsBorder", { bg = "#1e2030", fg = "#1e2030" })
hi(0, "TelescopeResultsNormal", { bg = "#1e2030" })
hi(0, "TelescopeResultsTitle", { bg = "#1e2030", fg = "#1e2030" })
hi(0, "TelescopeSelection", { bg = "#363a4f", bold = true, fg = "#cad3f5" })
hi(0, "TelescopeSelectionCaret", { fg = "#f0c6c6" })
hi(0, "Title", { bold = true, fg = "#8aadf4" })
hi(0, "Todo", { bg = "#f0c6c6", bold = true, fg = "#24273a" })
hi(0, "TreesitterContextBottom", { sp = "#363a4f", underline = true })
hi(0, "TreesitterContextLineNumber", { bg = "#1e2030", fg = "#494d64" })
hi(0, "Type", { fg = "#eed49f" })
hi(0, "UfoFoldedEllipsis", { bg = "#8aadf4", fg = "#181926" })
hi(0, "UfoFoldedFg", { fg = "#b7bdf8" })
hi(0, "VertSplit", { fg = "#181926" })
hi(0, "Visual", { bg = "#494d64", bold = true })
hi(0, "VisualNOS", { bg = "#494d64", bold = true })
hi(0, "WarningMsg", { fg = "#eed49f" })
hi(0, "Whitespace", { fg = "#494d64" })
hi(0, "WildMenu", { bg = "#6e738d" })
hi(0, "WinBar", { fg = "#f4dbd6" })
hi(0, "WinBarNC", { link = "WinBar" })
hi(0, "WinSeparator", { fg = "#181926" })
hi(0, "csvCol0", { fg = "#ed8796" })
hi(0, "csvCol1", { fg = "#f5a97f" })
hi(0, "csvCol2", { fg = "#eed49f" })
hi(0, "csvCol3", { fg = "#a6da95" })
hi(0, "csvCol4", { fg = "#91d7e3" })
hi(0, "csvCol5", { fg = "#8aadf4" })
hi(0, "csvCol6", { fg = "#b7bdf8" })
hi(0, "csvCol7", { fg = "#c6a0f6" })
hi(0, "csvCol8", { fg = "#f5bde6" })
hi(0, "debugBreakpoint", { bg = "#24273a", fg = "#6e738d" })
hi(0, "debugPC", { bg = "#181926" })
hi(0, "diffAdded", { fg = "#a6da95" })
hi(0, "diffChanged", { fg = "#8aadf4" })
hi(0, "diffFile", { fg = "#8aadf4" })
hi(0, "diffIndexLine", { fg = "#8bd5ca" })
hi(0, "diffLine", { fg = "#6e738d" })
hi(0, "diffNewFile", { fg = "#f5a97f" })
hi(0, "diffOldFile", { fg = "#eed49f" })
hi(0, "diffRemoved", { fg = "#ed8796" })
hi(0, "gitcommitSummary", { fg = "#f4dbd6", italic = true })
hi(0, "healthError", { fg = "#ed8796" })
hi(0, "healthSuccess", { fg = "#8bd5ca" })
hi(0, "healthWarning", { fg = "#eed49f" })
hi(0, "htmlH1", { bold = true, fg = "#f5bde6" })
hi(0, "htmlH2", { bold = true, fg = "#8aadf4" })
hi(0, "illuminatedCurWord", { bg = "#494d64" })
hi(0, "illuminatedWord", { bg = "#494d64" })
hi(0, "lCursor", { bg = "#cad3f5", fg = "#24273a" })
hi(0, "markdownCode", { fg = "#f0c6c6" })
hi(0, "markdownCodeBlock", { fg = "#f0c6c6" })
hi(0, "markdownH1", { link = "rainbow1" })
hi(0, "markdownH2", { link = "rainbow2" })
hi(0, "markdownH3", { link = "rainbow3" })
hi(0, "markdownH4", { link = "rainbow4" })
hi(0, "markdownH5", { link = "rainbow5" })
hi(0, "markdownH6", { link = "rainbow6" })
hi(0, "markdownHeadingDelimiter", { bold = true, fg = "#f5a97f" })
hi(0, "markdownLinkText", { fg = "#8aadf4", underline = true })
hi(0, "mkdCodeDelimiter", { bg = "#24273a", fg = "#cad3f5" })
hi(0, "mkdCodeEnd", { bold = true, fg = "#f0c6c6" })
hi(0, "mkdCodeStart", { bold = true, fg = "#f0c6c6" })
hi(0, "qfFileName", { fg = "#8aadf4" })
hi(0, "qfLineNr", { fg = "#eed49f" })
hi(0, "rainbow1", { fg = "#ed8796" })
hi(0, "rainbow2", { fg = "#f5a97f" })
hi(0, "rainbow3", { fg = "#eed49f" })
hi(0, "rainbow4", { fg = "#a6da95" })
hi(0, "rainbow5", { fg = "#7dc4e4" })
hi(0, "rainbow6", { fg = "#b7bdf8" })
hi(0, "zshKSHFunction", { link = "Function" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#15161e"
g.terminal_color_1 = "#f7768e"
g.terminal_color_2 = "#9ece6a"
g.terminal_color_3 = "#e0af68"
g.terminal_color_4 = "#7aa2f7"
g.terminal_color_5 = "#bb9af7"
g.terminal_color_6 = "#7dcfff"
g.terminal_color_7 = "#a9b1d6"
g.terminal_color_8 = "#414868"
g.terminal_color_9 = "#dca0c2"
g.terminal_color_10 = "#afccb0"
g.terminal_color_11 = "#d0bdaf"
g.terminal_color_12 = "#9db6f6"
g.terminal_color_14 = "#9fcdfa"
g.terminal_color_15 = "#c0caf5"
