-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "catppuccin-mocha"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "Constant" })
hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.documentation", { link = "Comment" })
hi(0, "@comment.error", { bg = "#f38ba8", fg = "#1e1e2e" })
hi(0, "@comment.hint", { bg = "#89b4fa", fg = "#1e1e2e" })
hi(0, "@comment.note", { bg = "#89b4fa", fg = "#1e1e2e" })
hi(0, "@comment.todo", { bg = "#f2cdcd", fg = "#1e1e2e" })
hi(0, "@comment.warning", { bg = "#f9e2af", fg = "#1e1e2e" })
hi(0, "@comment.warning.gitcommit", { fg = "#f9e2af" })
hi(0, "@conditional", { link = "Conditional" })
hi(0, "@constant.builtin", { fg = "#fab387" })
hi(0, "@constant.java", { fg = "#94e2d5" })
hi(0, "@constant.macro", { link = "Macro" })
hi(0, "@constructor", { fg = "#74c7ec" })
hi(0, "@constructor.lua", { fg = "#f2cdcd" })
hi(0, "@constructor.tsx", { fg = "#b4befe" })
hi(0, "@constructor.typescript", { fg = "#b4befe" })
hi(0, "@define", { link = "Define" })
hi(0, "@diff.delta", { link = "diffChanged" })
hi(0, "@diff.minus", { link = "diffRemoved" })
hi(0, "@diff.plus", { link = "diffAdded" })
hi(0, "@error", { link = "Error" })
hi(0, "@exception", { link = "Exception" })
hi(0, "@field", { fg = "#b4befe" })
hi(0, "@float", { link = "Float" })
hi(0, "@function.builtin", { fg = "#fab387" })
hi(0, "@function.builtin.bash", { fg = "#f38ba8", italic = true })
hi(0, "@function.call", { link = "Function" })
hi(0, "@function.macro", { fg = "#94e2d5" })
hi(0, "@function.method", { link = "Function" })
hi(0, "@function.method.call", { link = "Function" })
hi(0, "@function.method.call.php", { link = "Function" })
hi(0, "@function.method.php", { link = "Function" })
hi(0, "@include", { link = "Include" })
hi(0, "@keyword.conditional", { link = "Conditional" })
hi(0, "@keyword.conditional.ternary", { link = "Operator" })
hi(0, "@keyword.coroutine", { link = "Keyword" })
hi(0, "@keyword.debug", { link = "Exception" })
hi(0, "@keyword.directive", { link = "PreProc" })
hi(0, "@keyword.directive.define", { link = "Define" })
hi(0, "@keyword.exception", { link = "Exception" })
hi(0, "@keyword.export", { fg = "#89dceb" })
hi(0, "@keyword.function", { fg = "#cba6f7" })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.modifier", { link = "Keyword" })
hi(0, "@keyword.operator", { link = "Operator" })
hi(0, "@keyword.repeat", { link = "Repeat" })
hi(0, "@keyword.return", { fg = "#cba6f7" })
hi(0, "@keyword.storage", { link = "Keyword" })
hi(0, "@keyword.type", { link = "Keyword" })
hi(0, "@label.json", { fg = "#89b4fa" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", { link = "@variable" })
hi(0, "@markup", { fg = "#cdd6f4" })
hi(0, "@markup.environment", { fg = "#f5c2e7" })
hi(0, "@markup.environment.name", { fg = "#89b4fa" })
hi(0, "@markup.heading", { bold = true, fg = "#89b4fa" })
hi(0, "@markup.heading.1.markdown", { link = "rainbow1" })
hi(0, "@markup.heading.2.markdown", { link = "rainbow2" })
hi(0, "@markup.heading.3.markdown", { link = "rainbow3" })
hi(0, "@markup.heading.4.markdown", { link = "rainbow4" })
hi(0, "@markup.heading.5.markdown", { link = "rainbow5" })
hi(0, "@markup.heading.6.markdown", { link = "rainbow6" })
hi(0, "@markup.italic", { fg = "#eba0ac", italic = true })
hi(0, "@markup.link", { link = "Tag" })
hi(0, "@markup.link.label", { link = "Label" })
hi(0, "@markup.link.url", { fg = "#f5e0dc", italic = true, underline = true })
hi(0, "@markup.list", { link = "Special" })
hi(0, "@markup.list.checked", { fg = "#a6e3a1" })
hi(0, "@markup.list.unchecked", { fg = "#7f849c" })
hi(0, "@markup.math", { fg = "#89b4fa" })
hi(0, "@markup.quote", { bold = true, fg = "#eba0ac" })
hi(0, "@markup.raw", { fg = "#94e2d5" })
hi(0, "@markup.strikethrough", { fg = "#cdd6f4", strikethrough = true })
hi(0, "@markup.strong", { bold = true, fg = "#eba0ac" })
hi(0, "@markup.underline", { link = "Underlined" })
hi(0, "@method", { link = "Function" })
hi(0, "@method.call", { link = "Function" })
hi(0, "@method.call.php", { link = "Function" })
hi(0, "@method.php", { link = "Function" })
hi(0, "@module", { fg = "#b4befe", italic = true })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@namespace", { fg = "#b4befe", italic = true })
hi(0, "@number.css", { fg = "#fab387" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@parameter", { fg = "#eba0ac" })
hi(0, "@preproc", { link = "PreProc" })
hi(0, "@property", { fg = "#b4befe" })
hi(0, "@property.class.css", { fg = "#f9e2af" })
hi(0, "@property.cpp", { fg = "#cdd6f4" })
hi(0, "@property.css", { fg = "#b4befe" })
hi(0, "@property.id.css", { fg = "#89b4fa" })
hi(0, "@property.toml", { fg = "#89b4fa" })
hi(0, "@property.typescript", { fg = "#b4befe" })
hi(0, "@punctuation.bracket", { fg = "#9399b2" })
hi(0, "@punctuation.delimiter", { link = "Delimiter" })
hi(0, "@punctuation.special", { link = "Special" })
hi(0, "@repeat", { link = "Repeat" })
hi(0, "@storageclass", { link = "Keyword" })
hi(0, "@string.documentation", { fg = "#94e2d5" })
hi(0, "@string.escape", { fg = "#f5c2e7" })
hi(0, "@string.plain.css", { fg = "#fab387" })
hi(0, "@string.regex", { fg = "#fab387" })
hi(0, "@string.regexp", { fg = "#fab387" })
hi(0, "@string.special", { link = "Special" })
hi(0, "@string.special.path", { link = "Special" })
hi(0, "@string.special.symbol", { fg = "#f2cdcd" })
hi(0, "@string.special.symbol.ruby", { fg = "#f2cdcd" })
hi(0, "@string.special.url", { fg = "#f5e0dc", italic = true, underline = true })
hi(0, "@symbol", { fg = "#f2cdcd" })
hi(0, "@symbol.ruby", { fg = "#f2cdcd" })
hi(0, "@tag", { fg = "#cba6f7" })
hi(0, "@tag.attribute", { fg = "#94e2d5", italic = true })
hi(0, "@tag.attribute.tsx", { fg = "#94e2d5", italic = true })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@tag.delimiter", { fg = "#89dceb" })
hi(0, "@text", { fg = "#cdd6f4" })
hi(0, "@text.danger", { bg = "#f38ba8", fg = "#1e1e2e" })
hi(0, "@text.diff.add", { link = "diffAdded" })
hi(0, "@text.diff.delete", { link = "diffRemoved" })
hi(0, "@text.emphasis", { fg = "#eba0ac", italic = true })
hi(0, "@text.environment", { fg = "#f5c2e7" })
hi(0, "@text.environment.name", { fg = "#89b4fa" })
hi(0, "@text.literal", { fg = "#94e2d5" })
hi(0, "@text.math", { fg = "#89b4fa" })
hi(0, "@text.note", { bg = "#89b4fa", fg = "#1e1e2e" })
hi(0, "@text.reference", { link = "Tag" })
hi(0, "@text.strike", { fg = "#cdd6f4", strikethrough = true })
hi(0, "@text.strong", { bold = true, fg = "#eba0ac" })
hi(0, "@text.title", { bold = true, fg = "#89b4fa" })
hi(0, "@text.title.1.markdown", { link = "rainbow1" })
hi(0, "@text.title.2.markdown", { link = "rainbow2" })
hi(0, "@text.title.3.markdown", { link = "rainbow3" })
hi(0, "@text.title.4.markdown", { link = "rainbow4" })
hi(0, "@text.title.5.markdown", { link = "rainbow5" })
hi(0, "@text.title.6.markdown", { link = "rainbow6" })
hi(0, "@text.todo", { bg = "#f2cdcd", fg = "#1e1e2e" })
hi(0, "@text.todo.checked", { fg = "#a6e3a1" })
hi(0, "@text.todo.unchecked", { fg = "#7f849c" })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.warning", { bg = "#f9e2af", fg = "#1e1e2e" })
hi(0, "@type.builtin", { fg = "#f9e2af" })
hi(0, "@type.builtin.c", { fg = "#f9e2af" })
hi(0, "@type.builtin.cpp", { fg = "#f9e2af" })
hi(0, "@type.css", { fg = "#b4befe" })
hi(0, "@type.definition", { link = "Type" })
hi(0, "@type.qualifier", { link = "Keyword" })
hi(0, "@type.tag.css", { fg = "#cba6f7" })
hi(0, "@variable", { fg = "#cdd6f4" })
hi(0, "@variable.builtin", { fg = "#f38ba8" })
hi(0, "@variable.member", { fg = "#b4befe" })
hi(0, "@variable.parameter", { fg = "#eba0ac" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#fab387" })
hi(0, "Character", { fg = "#94e2d5" })
hi(0, "CmpItemAbbr", { fg = "#9399b2" })
hi(0, "CmpItemAbbrDefault", { fg = "#9399b2" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#6c7086", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#6c7086" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#cdd6f4" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#9399b2" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#cdd6f4" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#9399b2" })
hi(0, "CmpItemKind", { fg = "#89b4fa" })
hi(0, "CmpItemKindClass", { fg = "#f9e2af" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { fg = "#f38ba8" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { fg = "#fab387" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { fg = "#89b4fa" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCopilot", { fg = "#94e2d5" })
hi(0, "CmpItemKindDefault", { fg = "#f5c2e7" })
hi(0, "CmpItemKindEnum", { fg = "#a6e3a1" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { fg = "#f38ba8" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { fg = "#89b4fa" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { fg = "#a6e3a1" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { fg = "#89b4fa" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { fg = "#89b4fa" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { fg = "#89b4fa" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { fg = "#f9e2af" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { fg = "#f38ba8" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { fg = "#89b4fa" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { fg = "#89b4fa" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { fg = "#89b4fa" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { fg = "#a6e3a1" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { fg = "#f38ba8" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { fg = "#cba6f7" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { fg = "#89b4fa" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { fg = "#94e2d5" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { fg = "#89b4fa" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { fg = "#a6e3a1" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { fg = "#fab387" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { fg = "#f2cdcd" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#cdd6f4" })
hi(0, "CmpItemMenuDefault", { fg = "#9399b2" })
hi(0, "ColorColumn", { bg = "#313244" })
hi(0, "Comment", { fg = "#6c7086", italic = true })
hi(0, "Conceal", { fg = "#7f849c" })
hi(0, "Conditional", { fg = "#cba6f7", italic = true })
hi(0, "Constant", { fg = "#fab387" })
hi(0, "CurSearch", { bg = "#f38ba8", fg = "#181825" })
hi(0, "Cursor", { bg = "#cdd6f4", fg = "#1e1e2e" })
hi(0, "CursorColumn", { bg = "#181825" })
hi(0, "CursorIM", { bg = "#cdd6f4", fg = "#1e1e2e" })
hi(0, "CursorLine", { bg = "#2a2b3c" })
hi(0, "CursorLineNr", { fg = "#b4befe" })
hi(0, "Delimiter", { fg = "#9399b2" })
hi(0, "DiagnosticError", { fg = "#f38ba8", italic = true })
hi(0, "DiagnosticFloatingError", { fg = "#f38ba8" })
hi(0, "DiagnosticFloatingHint", { fg = "#94e2d5" })
hi(0, "DiagnosticFloatingInfo", { fg = "#89dceb" })
hi(0, "DiagnosticFloatingOk", { fg = "#a6e3a1" })
hi(0, "DiagnosticFloatingWarn", { fg = "#f9e2af" })
hi(0, "DiagnosticHint", { fg = "#94e2d5", italic = true })
hi(0, "DiagnosticInfo", { fg = "#89dceb", italic = true })
hi(0, "DiagnosticOk", { fg = "#a6e3a1", italic = true })
hi(0, "DiagnosticSignError", { fg = "#f38ba8" })
hi(0, "DiagnosticSignHint", { fg = "#94e2d5" })
hi(0, "DiagnosticSignInfo", { fg = "#89dceb" })
hi(0, "DiagnosticSignOk", { fg = "#a6e3a1" })
hi(0, "DiagnosticSignWarn", { fg = "#f9e2af" })
hi(0, "DiagnosticUnderlineError", { sp = "#f38ba8", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#94e2d5", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#89dceb", underline = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#a6e3a1", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#f9e2af", underline = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#32283a", fg = "#f38ba8", italic = true })
hi(0, "DiagnosticVirtualTextHint", { bg = "#29313e", fg = "#94e2d5", italic = true })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#283040", fg = "#89dceb", italic = true })
hi(0, "DiagnosticVirtualTextOk", { bg = "#29313e", fg = "#a6e3a1", italic = true })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#33313a", fg = "#f9e2af", italic = true })
hi(0, "DiagnosticWarn", { fg = "#f9e2af", italic = true })
hi(0, "DiffAdd", { bg = "#364143" })
hi(0, "DiffChange", { bg = "#25293c" })
hi(0, "DiffDelete", { bg = "#443244" })
hi(0, "DiffText", { bg = "#3e4b6b" })
hi(0, "Directory", { fg = "#89b4fa" })
hi(0, "EndOfBuffer", { fg = "#1e1e2e" })
hi(0, "Error", { fg = "#f38ba8" })
hi(0, "ErrorMsg", { bold = true, fg = "#f38ba8", italic = true })
hi(0, "Exception", { fg = "#cba6f7" })
hi(0, "FloatBorder", { fg = "#89b4fa" })
hi(0, "FloatTitle", { fg = "#a6adc8" })
hi(0, "FoldColumn", { fg = "#6c7086" })
hi(0, "Folded", { bg = "#45475a", fg = "#89b4fa" })
hi(0, "Function", { fg = "#89b4fa" })
hi(0, "GlyphPalette1", { fg = "#f38ba8" })
hi(0, "GlyphPalette2", { fg = "#94e2d5" })
hi(0, "GlyphPalette3", { fg = "#f9e2af" })
hi(0, "GlyphPalette4", { fg = "#89b4fa" })
hi(0, "GlyphPalette6", { fg = "#94e2d5" })
hi(0, "GlyphPalette7", { fg = "#cdd6f4" })
hi(0, "GlyphPalette9", { fg = "#f38ba8" })
hi(0, "HarpoonBorder", { fg = "#89b4fa" })
hi(0, "HarpoonWindow", { bg = "#1e1e2e", fg = "#cdd6f4" })
hi(0, "Identifier", { fg = "#f2cdcd" })
hi(0, "IncSearch", { bg = "#7ec9d8", fg = "#181825" })
hi(0, "Include", { fg = "#cba6f7" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#cba6f7" })
hi(0, "Label", { fg = "#74c7ec" })
hi(0, "LineNr", { fg = "#45475a" })
hi(0, "LspCodeLens", { fg = "#6c7086" })
hi(0, "LspDiagnosticsDefaultError", { fg = "#f38ba8" })
hi(0, "LspDiagnosticsDefaultHint", { fg = "#94e2d5" })
hi(0, "LspDiagnosticsDefaultInformation", { fg = "#89dceb" })
hi(0, "LspDiagnosticsDefaultWarning", { fg = "#f9e2af" })
hi(0, "LspDiagnosticsError", { fg = "#f38ba8" })
hi(0, "LspDiagnosticsHint", { fg = "#94e2d5" })
hi(0, "LspDiagnosticsInformation", { fg = "#89dceb" })
hi(0, "LspDiagnosticsUnderlineError", { sp = "#f38ba8", underline = true })
hi(0, "LspDiagnosticsUnderlineHint", { sp = "#94e2d5", underline = true })
hi(0, "LspDiagnosticsUnderlineInformation", { sp = "#89dceb", underline = true })
hi(0, "LspDiagnosticsUnderlineWarning", { sp = "#f9e2af", underline = true })
hi(0, "LspDiagnosticsVirtualTextError", { fg = "#f38ba8", italic = true })
hi(0, "LspDiagnosticsVirtualTextHint", { fg = "#94e2d5", italic = true })
hi(0, "LspDiagnosticsVirtualTextInformation", { fg = "#89dceb", italic = true })
hi(0, "LspDiagnosticsVirtualTextWarning", { fg = "#f9e2af", italic = true })
hi(0, "LspDiagnosticsWarning", { fg = "#f9e2af" })
hi(0, "LspInfoBorder", { link = "FloatBorder" })
hi(0, "LspInlayHint", { bg = "#2a2b3c", fg = "#6c7086" })
hi(0, "LspReferenceRead", { bg = "#45475a" })
hi(0, "LspReferenceText", { bg = "#45475a" })
hi(0, "LspReferenceWrite", { bg = "#45475a" })
hi(0, "LspSignatureActiveParameter", { fg = "#fab387" })
hi(0, "Macro", { fg = "#cba6f7" })
hi(0, "MatchParen", { bg = "#45475a", bold = true, fg = "#fab387" })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniDiffSignAdd_stl", { fg = "#b3f6c0" })
hi(0, "MiniDiffSignChange_stl", { fg = "#8cf8f7" })
hi(0, "MiniDiffSignDelete_stl", { fg = "#ffc0b9" })
hi(0, "MiniIndentscopePrefix", { nocombine = true })
hi(0, "MiniIndentscopeSymbol", { fg = "#cba6f7" })
hi(0, "MiniJump", { bg = "#f5c2e7", fg = "#9399b2" })
hi(0, "MiniJump2dSpot", { bg = "#1e1e2e", bold = true, fg = "#fab387", underline = true })
hi(0, "MiniStarterFooter", { fg = "#f9e2af", italic = true })
hi(0, "MiniStarterHeader", { fg = "#89b4fa" })
hi(0, "MiniStarterInactive", { fg = "#585b70", italic = true })
hi(0, "MiniStarterItem", { fg = "#cdd6f4" })
hi(0, "MiniStarterItemBullet", { fg = "#89b4fa" })
hi(0, "MiniStarterItemPrefix", { fg = "#f5c2e7" })
hi(0, "MiniStarterQuery", { fg = "#a6e3a1" })
hi(0, "MiniStarterSection", { fg = "#f2cdcd" })
hi(0, "MiniStatuslineDevinfo", { bg = "#45475a", fg = "#bac2de" })
hi(0, "MiniStatuslineFileinfo", { bg = "#45475a", fg = "#bac2de" })
hi(0, "MiniStatuslineFilename", { bg = "#181825", fg = "#cdd6f4" })
hi(0, "MiniStatuslineInactive", { bg = "#181825", fg = "#89b4fa" })
hi(0, "MiniStatuslineModeCommand", { bg = "#fab387", bold = true, fg = "#1e1e2e" })
hi(0, "MiniStatuslineModeInsert", { bg = "#a6e3a1", bold = true, fg = "#1e1e2e" })
hi(0, "MiniStatuslineModeNormal", { bg = "#89b4fa", bold = true, fg = "#181825" })
hi(0, "MiniStatuslineModeOther", { bg = "#94e2d5", bold = true, fg = "#1e1e2e" })
hi(0, "MiniStatuslineModeReplace", { bg = "#f38ba8", bold = true, fg = "#1e1e2e" })
hi(0, "MiniStatuslineModeVisual", { bg = "#cba6f7", bold = true, fg = "#1e1e2e" })
hi(0, "MiniSurround", { bg = "#f5c2e7", fg = "#45475a" })
hi(0, "MiniTablineCurrent", { bg = "#1e1e2e", bold = true, fg = "#cdd6f4", italic = true, sp = "#f38ba8", underline = true })
hi(0, "MiniTablineFill", { bg = "#1e1e2e" })
hi(0, "MiniTablineHidden", { bg = "#181825", fg = "#cdd6f4" })
hi(0, "MiniTablineModifiedCurrent", { bold = true, fg = "#f38ba8", italic = true })
hi(0, "MiniTablineModifiedHidden", { fg = "#f38ba8" })
hi(0, "MiniTablineModifiedVisible", { fg = "#f38ba8" })
hi(0, "MiniTablineTabpagesection", { bg = "#1e1e2e", fg = "#45475a" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#f38ba8" })
hi(0, "MiniTestPass", { bold = true, fg = "#a6e3a1" })
hi(0, "MiniTrailspace", { bg = "#f38ba8" })
hi(0, "ModeMsg", { bold = true, fg = "#cdd6f4" })
hi(0, "MoreMsg", { fg = "#89b4fa" })
hi(0, "MsgSeparator", {})
hi(0, "NonText", { fg = "#6c7086" })
hi(0, "Normal", { bg = "#1e1e2e", fg = "#cdd6f4" })
hi(0, "NormalFloat", { bg = "#181825", fg = "#cdd6f4" })
hi(0, "NormalNC", { bg = "#1e1e2e", fg = "#cdd6f4" })
hi(0, "NormalSB", { bg = "#11111b", fg = "#cdd6f4" })
hi(0, "Number", { fg = "#fab387" })
hi(0, "Operator", { fg = "#89dceb" })
hi(0, "Pmenu", { bg = "#2b2b3c", fg = "#9399b2" })
hi(0, "PmenuSbar", { bg = "#45475a" })
hi(0, "PmenuSel", { bg = "#45475a", bold = true })
hi(0, "PmenuThumb", { bg = "#6c7086" })
hi(0, "PreProc", { fg = "#f5c2e7" })
hi(0, "Question", { fg = "#89b4fa" })
hi(0, "QuickFixLine", { bg = "#45475a", bold = true })
hi(0, "Repeat", { fg = "#cba6f7" })
hi(0, "Search", { bg = "#3e5767", fg = "#cdd6f4" })
hi(0, "SignColumn", { fg = "#45475a" })
hi(0, "SignColumnSB", { bg = "#11111b", fg = "#45475a" })
hi(0, "Special", { fg = "#f5c2e7" })
hi(0, "SpecialKey", { link = "NonText" })
hi(0, "SpellBad", { sp = "#f38ba8", undercurl = true })
hi(0, "SpellCap", { sp = "#f9e2af", undercurl = true })
hi(0, "SpellLocal", { sp = "#89b4fa", undercurl = true })
hi(0, "SpellRare", { sp = "#a6e3a1", undercurl = true })
hi(0, "Statement", { fg = "#cba6f7" })
hi(0, "StatusLine", { bg = "#181825", fg = "#cdd6f4" })
hi(0, "StatusLineNC", { bg = "#181825", fg = "#45475a" })
hi(0, "StorageClass", { fg = "#f9e2af" })
hi(0, "String", { fg = "#a6e3a1" })
hi(0, "Structure", { fg = "#f9e2af" })
hi(0, "Substitute", { bg = "#45475a", fg = "#f5c2e7" })
hi(0, "TabLine", { bg = "#181825", fg = "#45475a" })
hi(0, "TabLineFill", {})
hi(0, "TabLineSel", { bg = "#45475a", fg = "#a6e3a1" })
hi(0, "Tag", { bold = true, fg = "#b4befe" })
hi(0, "TelescopeBorder", { link = "FloatBorder" })
hi(0, "TelescopeMatching", { fg = "#89b4fa" })
hi(0, "TelescopePreviewBorder", { bg = "#11111b", fg = "#11111b" })
hi(0, "TelescopePreviewNormal", { bg = "#11111b" })
hi(0, "TelescopePreviewTitle", { bg = "#11111b", fg = "#11111b" })
hi(0, "TelescopePromptBorder", { bg = "#313244", fg = "#313244" })
hi(0, "TelescopePromptCounter", { bold = true, fg = "#cba6f7" })
hi(0, "TelescopePromptNormal", { bg = "#313244" })
hi(0, "TelescopePromptPrefix", { bg = "#313244" })
hi(0, "TelescopePromptTitle", { bg = "#313244", fg = "#313244" })
hi(0, "TelescopeResultsBorder", { bg = "#181825", fg = "#181825" })
hi(0, "TelescopeResultsNormal", { bg = "#181825" })
hi(0, "TelescopeResultsTitle", { bg = "#181825", fg = "#181825" })
hi(0, "TelescopeSelection", { bg = "#313244", bold = true, fg = "#cdd6f4" })
hi(0, "TelescopeSelectionCaret", { fg = "#f2cdcd" })
hi(0, "Title", { bold = true, fg = "#89b4fa" })
hi(0, "Todo", { bg = "#f2cdcd", bold = true, fg = "#1e1e2e" })
hi(0, "Type", { fg = "#f9e2af" })
hi(0, "VertSplit", { fg = "#11111b" })
hi(0, "Visual", { bg = "#45475a", bold = true })
hi(0, "VisualNOS", { bg = "#45475a", bold = true })
hi(0, "WarningMsg", { fg = "#f9e2af" })
hi(0, "Whitespace", { fg = "#45475a" })
hi(0, "WildMenu", { bg = "#6c7086" })
hi(0, "WinBar", { fg = "#f5e0dc" })
hi(0, "WinBarNC", { link = "WinBar" })
hi(0, "WinSeparator", { fg = "#11111b" })
hi(0, "csvCol0", { fg = "#f38ba8" })
hi(0, "csvCol1", { fg = "#fab387" })
hi(0, "csvCol2", { fg = "#f9e2af" })
hi(0, "csvCol3", { fg = "#a6e3a1" })
hi(0, "csvCol4", { fg = "#89dceb" })
hi(0, "csvCol5", { fg = "#89b4fa" })
hi(0, "csvCol6", { fg = "#b4befe" })
hi(0, "csvCol7", { fg = "#cba6f7" })
hi(0, "csvCol8", { fg = "#f5c2e7" })
hi(0, "debugBreakpoint", { bg = "#1e1e2e", fg = "#6c7086" })
hi(0, "debugPC", { bg = "#11111b" })
hi(0, "diffAdded", { fg = "#a6e3a1" })
hi(0, "diffChanged", { fg = "#89b4fa" })
hi(0, "diffFile", { fg = "#89b4fa" })
hi(0, "diffIndexLine", { fg = "#94e2d5" })
hi(0, "diffLine", { fg = "#6c7086" })
hi(0, "diffNewFile", { fg = "#fab387" })
hi(0, "diffOldFile", { fg = "#f9e2af" })
hi(0, "diffRemoved", { fg = "#f38ba8" })
hi(0, "gitcommitSummary", { fg = "#f5e0dc", italic = true })
hi(0, "healthError", { fg = "#f38ba8" })
hi(0, "healthSuccess", { fg = "#94e2d5" })
hi(0, "healthWarning", { fg = "#f9e2af" })
hi(0, "htmlH1", { bold = true, fg = "#f5c2e7" })
hi(0, "htmlH2", { bold = true, fg = "#89b4fa" })
hi(0, "illuminatedCurWord", { bg = "#45475a" })
hi(0, "illuminatedWord", { bg = "#45475a" })
hi(0, "lCursor", { bg = "#cdd6f4", fg = "#1e1e2e" })
hi(0, "mkdCodeDelimiter", { bg = "#1e1e2e", fg = "#cdd6f4" })
hi(0, "mkdCodeEnd", { bold = true, fg = "#f2cdcd" })
hi(0, "mkdCodeStart", { bold = true, fg = "#f2cdcd" })
hi(0, "qfFileName", { fg = "#89b4fa" })
hi(0, "qfLineNr", { fg = "#f9e2af" })
hi(0, "rainbow1", { fg = "#f38ba8" })
hi(0, "rainbow2", { fg = "#fab387" })
hi(0, "rainbow3", { fg = "#f9e2af" })
hi(0, "rainbow4", { fg = "#a6e3a1" })
hi(0, "rainbow5", { fg = "#74c7ec" })
hi(0, "rainbow6", { fg = "#b4befe" })
hi(0, "stl_fill", { fg = "#cdd6f4" })
hi(0, "zshKSHFunction", { link = "Function" })

-- No terminal colors defined
