-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "ef-autumn"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.documentation", { link = "@comment" })
hi(0, "@comment.error", { link = "@text.danger" })
hi(0, "@comment.note", { link = "@text.note" })
hi(0, "@comment.todo", { link = "@text.todo" })
hi(0, "@comment.warning", { link = "@text.warning" })
hi(0, "@conditional", { link = "Conditional" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@constant.macro", { link = "Macro" })
hi(0, "@debug", { link = "Debug" })
hi(0, "@define", { link = "Define" })
hi(0, "@diff.delta", { link = "diffChanged" })
hi(0, "@diff.minus", { link = "diffRemoved" })
hi(0, "@diff.plus", { link = "diffAdded" })
hi(0, "@exception", { link = "Exception" })
hi(0, "@field", { link = "Identifier" })
hi(0, "@float", { link = "Float" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@function.call", { link = "Function" })
hi(0, "@function.macro", { link = "Macro" })
hi(0, "@function.method", { link = "@method" })
hi(0, "@function.method.call", { link = "@method.call" })
hi(0, "@include", { link = "Include" })
hi(0, "@keyword.conditional", { link = "@keyword" })
hi(0, "@keyword.conditional.ternary", { link = "Keyword" })
hi(0, "@keyword.coroutine", { link = "@keyword" })
hi(0, "@keyword.debug", { bold = true, fg = "#2c957d" })
hi(0, "@keyword.directive", { bold = true, fg = "#97ace0" })
hi(0, "@keyword.directive.define", { link = "@keyword.directive" })
hi(0, "@keyword.exception", { link = "@keyword" })
hi(0, "@keyword.function", { link = "@keyword" })
hi(0, "@keyword.import", { bold = true, fg = "#97ace0" })
hi(0, "@keyword.operator", { link = "@keyword" })
hi(0, "@keyword.repeat", { link = "@keyword" })
hi(0, "@keyword.return", { bold = true, fg = "#bc5918" })
hi(0, "@keyword.storage", { bold = true, fg = "#9ab2b3" })
hi(0, "@lsp.mod.deprecated", { fg = "#d6370f" })
hi(0, "@lsp.type.class", { link = "@structure" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@function" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@macro" })
hi(0, "@lsp.type.method", { link = "@method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@structure" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", { link = "@variable" })
hi(0, "@macro", { link = "Macro" })
hi(0, "@markup.environment", { link = "@module" })
hi(0, "@markup.heading", { link = "@text.title" })
hi(0, "@markup.italic", { link = "@text.emphasis" })
hi(0, "@markup.link", { link = "@text.reference" })
hi(0, "@markup.link.label", { link = "@markup.link" })
hi(0, "@markup.link.url", { fg = "#9ab2b3", underline = true })
hi(0, "@markup.list", { link = "@punctuation.special" })
hi(0, "@markup.list.checked", { link = "DiagnosticOk" })
hi(0, "@markup.list.unchecked", { link = "DiagnosticWarn" })
hi(0, "@markup.math", { link = "@string.special" })
hi(0, "@markup.quote", { link = "@string.special" })
hi(0, "@markup.raw", { link = "@text.literal" })
hi(0, "@markup.raw.block", { link = "@markup.raw" })
hi(0, "@markup.strikethrough", { link = "@text.strike" })
hi(0, "@markup.strong", { link = "@text.strong" })
hi(0, "@markup.underline", { link = "@text.underline" })
hi(0, "@method", { link = "Function" })
hi(0, "@method.call", { link = "Function" })
hi(0, "@module", { link = "@namespace" })
hi(0, "@module.builtin", { link = "@variable.builtin" })
hi(0, "@namespace", { link = "Identifier" })
hi(0, "@none", { link = "Normal" })
hi(0, "@number.float", { link = "@float" })
hi(0, "@parameter", { fg = "#97ace0" })
hi(0, "@preproc", { link = "PreProc" })
hi(0, "@punctuation.bracket", { link = "@punctuation" })
hi(0, "@punctuation.delimiter", { link = "@punctuation" })
hi(0, "@punctuation.special", { link = "Special" })
hi(0, "@repeat", { link = "Repeat" })
hi(0, "@storageclass", { link = "StorageClass" })
hi(0, "@string.documentation", { link = "@string" })
hi(0, "@string.escape", { link = "SpecialChar" })
hi(0, "@string.regexp", { link = "SpecialChar" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.path", { link = "Directory" })
hi(0, "@string.special.symbol", { link = "@constant" })
hi(0, "@string.special.url", { link = "@markup.link.url" })
hi(0, "@string.special.vimdoc", { link = "@constant" })
hi(0, "@structure", { link = "Structure" })
hi(0, "@symbol", { link = "Keyword" })
hi(0, "@tag.attribute", { link = "@tag" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@tag.delimiter", { link = "@punctuation" })
hi(0, "@text.danger", { link = "ErrorMsg" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.literal", { link = "Special" })
hi(0, "@text.note", { link = "MoreMsg" })
hi(0, "@text.reference", { link = "Identifier" })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { link = "Title" })
hi(0, "@text.todo", { link = "Todo" })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.uri", { link = "Underlined" })
hi(0, "@text.warning", { link = "WarningMsg" })
hi(0, "@type.builtin", { link = "Special" })
hi(0, "@type.definition", { link = "Typedef" })
hi(0, "@type.qualifier", { link = "StorageClass" })
hi(0, "@variable", { fg = "#9ab2b3" })
hi(0, "@variable.builtin", { link = "Special" })
hi(0, "@variable.member", { link = "@field" })
hi(0, "@variable.parameter", { link = "@parameter" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "Added", { fg = "#5f9327" })
hi(0, "Beacon", { bg = "#d0e9ea" })
hi(0, "BlinkCmpLabelMatch", { fg = "#2f9726" })
hi(0, "Bold", { bold = true })
hi(0, "BqfPreviewFloat", { link = "NormalFloat" })
hi(0, "BqfPreviewTitle", { link = "FloatTitle" })
hi(0, "BqfSign", { fg = "#2c957d" })
hi(0, "BufferCurrent", { bg = "#000100", bold = true, fg = "#bf9ed1" })
hi(0, "BufferCurrentIcon", { bg = "#000100" })
hi(0, "BufferCurrentIndex", { link = "BufferCurrentIcon" })
hi(0, "BufferCurrentMod", { bg = "#181e1a", bold = true, fg = "#bf9ed1" })
hi(0, "BufferCurrentSign", { link = "BufferCurrent" })
hi(0, "BufferCurrentTarget", { bg = "#343a36", bold = true, fg = "#bf9ed1" })
hi(0, "BufferInactive", { bg = "#000000", fg = "#9ab2b3" })
hi(0, "BufferInactiveIcon", { bg = "#000000" })
hi(0, "BufferInactiveIndex", { link = "BufferInactiveIcon" })
hi(0, "BufferInactiveMod", { bg = "#181e1a", fg = "#9ab2b3" })
hi(0, "BufferInactiveSign", { link = "BufferInactive" })
hi(0, "BufferInactiveTarget", { bg = "#343a36", fg = "#9ab2b3" })
hi(0, "BufferLineBuffer", { fg = "#5f7576" })
hi(0, "BufferLineBufferSelected", { bold = true, fg = "#9ab2b3" })
hi(0, "BufferLineBufferVisible", { fg = "#9ab2b3" })
hi(0, "BufferLineCloseButton", { link = "BufferLineBackground" })
hi(0, "BufferLineCloseButtonSelected", { link = "BufferLineBufferSelected" })
hi(0, "BufferLineCloseButtonVisible", { link = "BufferLineBufferVisible" })
hi(0, "BufferLineFill", { link = "Normal" })
hi(0, "BufferLineTab", { bg = "#5f9327", fg = "#000100" })
hi(0, "BufferLineTabSelected", { bg = "#5f9327", bold = true, fg = "#000100" })
hi(0, "BufferOffset", { link = "Normal" })
hi(0, "BufferTabpageFill", { link = "Normal" })
hi(0, "BufferTabpages", { bg = "#5f9327", bold = true, fg = "#000100" })
hi(0, "BufferVisible", { bg = "#000100", bold = true, fg = "#9ab2b3" })
hi(0, "BufferVisibleIcon", { bg = "#000100" })
hi(0, "BufferVisibleIndex", { link = "BufferVisibleIcon" })
hi(0, "BufferVisibleMod", { bg = "#181e1a", bold = true, fg = "#9ab2b3" })
hi(0, "BufferVisibleSign", { link = "BufferVisible" })
hi(0, "BufferVisibleTarget", { bg = "#343a36", bold = true, fg = "#9ab2b3" })
hi(0, "Changed", { fg = "#2c957d" })
hi(0, "CmpItemAbbr", { fg = "#9ab2b3" })
hi(0, "CmpItemAbbrDeprecated", { link = "Comment" })
hi(0, "CmpItemAbbrMatch", { bold = true })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true })
hi(0, "CmpItemKind", { fg = "#9ab2b3" })
hi(0, "CmpItemKindClass", { link = "Type" })
hi(0, "CmpItemKindColor", { link = "Special" })
hi(0, "CmpItemKindConstant", { link = "Constant" })
hi(0, "CmpItemKindConstructor", { link = "Type" })
hi(0, "CmpItemKindEnum", { link = "Structure" })
hi(0, "CmpItemKindEnumMember", { link = "Structure" })
hi(0, "CmpItemKindEvent", { link = "Exception" })
hi(0, "CmpItemKindField", { link = "Structure" })
hi(0, "CmpItemKindFile", { link = "Tag" })
hi(0, "CmpItemKindFolder", { link = "Directory" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindInterface", { link = "Structure" })
hi(0, "CmpItemKindKeyword", { link = "Keyword" })
hi(0, "CmpItemKindMethod", { link = "Function" })
hi(0, "CmpItemKindModule", { link = "Structure" })
hi(0, "CmpItemKindOperator", { link = "Operator" })
hi(0, "CmpItemKindProperty", { link = "Structure" })
hi(0, "CmpItemKindReference", { link = "Tag" })
hi(0, "CmpItemKindSnippet", { link = "Special" })
hi(0, "CmpItemKindStruct", { link = "Structure" })
hi(0, "CmpItemKindText", { link = "Normal" })
hi(0, "CmpItemKindTypeParameter", { link = "Type" })
hi(0, "CmpItemKindUnit", { link = "Special" })
hi(0, "CmpItemKindValue", { link = "Identifier" })
hi(0, "CmpItemKindVariable", { link = "Delimiter" })
hi(0, "CmpItemMenu", { fg = "#9ab2b3" })
hi(0, "CocCodeLens", { link = "LspCodeLens" })
hi(0, "CocDisabled", { link = "Comment" })
hi(0, "CocFadeOut", { link = "Comment" })
hi(0, "CocMarkdownLink", { fg = "#97ace0" })
hi(0, "CocMenuSel", { bg = "#343a36" })
hi(0, "CocNotificationProgress", { link = "CocMarkdownLink" })
hi(0, "CocPumVirtualText", { link = "CocMarkdownLink" })
hi(0, "CocSearch", { fg = "#97ace0" })
hi(0, "CocSelectedText", { fg = "#bc5918" })
hi(0, "ColorColumn", { bg = "#343a36" })
hi(0, "Comment", { fg = "#5f7576" })
hi(0, "CompileModeCheckResult", { bold = true, fg = "#7c3200" })
hi(0, "CompileModeCheckTarget", { fg = "#7c3200" })
hi(0, "CompileModeCommandOutput", { fg = "#1f4baa" })
hi(0, "CompileModeDirectoryMessage", { fg = "#1f4baa" })
hi(0, "CompileModeError", { fg = "#cb0000" })
hi(0, "CompileModeErrorLocus", { link = "Visual" })
hi(0, "CompileModeInfo", { fg = "#349f30" })
hi(0, "CompileModeMessage", { underline = true })
hi(0, "CompileModeMessageCol", { fg = "#007676" })
hi(0, "CompileModeMessageRow", { fg = "#a600a6" })
hi(0, "CompileModeOutputFile", { fg = "#824fb2" })
hi(0, "CompileModeWarning", { fg = "#747400" })
hi(0, "Conceal", { fg = "#70b2cb" })
hi(0, "Constant", { fg = "#b355d4" })
hi(0, "CurSearch", { bg = "#bc5918", fg = "#000100" })
hi(0, "Cursor", { bg = "#e2397b" })
hi(0, "CursorColumn", { bg = "#181e1a" })
hi(0, "CursorLine", { bg = "#181e1a" })
hi(0, "CursorLineFold", { fg = "#343a36" })
hi(0, "CursorLineNr", { bold = true, fg = "#bf9ed1" })
hi(0, "CursorLineSign", { fg = "#343a36" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#5f9327" })
hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
hi(0, "DapUIBreakpointsInfo", { link = "DiagnosticInfo" })
hi(0, "DapUIBreakpointsPath", { link = "Directory" })
hi(0, "DapUIDecoration", { link = "Title" })
hi(0, "DapUIFloatBorder", { link = "SpecialChar" })
hi(0, "DapUILineNumber", { link = "Title" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#bc5918" })
hi(0, "DapUIScope", { link = "Title" })
hi(0, "DapUISource", { link = "Directory" })
hi(0, "DapUIStoppedThread", { link = "Title" })
hi(0, "DapUIThread", { link = "String" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIWatchesEmpty", { link = "ErrorMsg" })
hi(0, "DapUIWatchesError", { link = "DiagnosticError" })
hi(0, "DapUIWatchesValue", { link = "String" })
hi(0, "DashboardCenter", { link = "Delimiter" })
hi(0, "DashboardFooter", { link = "Comment" })
hi(0, "DashboardHeader", { link = "Title" })
hi(0, "DashboardShortCut", { link = "WarningMsg" })
hi(0, "Definitions", { fg = "#5f9327" })
hi(0, "DefinitionsIcon", { fg = "#70b2cb" })
hi(0, "Delimiter", { fg = "#bc5918" })
hi(0, "DiagnosticDeprecated", { sp = "#d6370f", strikethrough = true })
hi(0, "DiagnosticError", { fg = "#d6370f" })
hi(0, "DiagnosticFloatingError", { bg = "#000000", fg = "#d6370f" })
hi(0, "DiagnosticFloatingHint", { bg = "#000000", fg = "#2c957d" })
hi(0, "DiagnosticFloatingInfo", { bg = "#000000", fg = "#97ace0" })
hi(0, "DiagnosticFloatingOk", { bg = "#000000", fg = "#5f9327" })
hi(0, "DiagnosticFloatingWarn", { bg = "#000000", fg = "#bc5918" })
hi(0, "DiagnosticHint", { fg = "#2c957d" })
hi(0, "DiagnosticInfo", { fg = "#97ace0" })
hi(0, "DiagnosticOk", { fg = "#5f9327" })
hi(0, "DiagnosticUnderlineError", { sp = "#d6370f", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#2c957d", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#97ace0", underline = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#5f9327", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#bc5918", underline = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#2a0c19", fg = "#d6370f" })
hi(0, "DiagnosticVirtualTextHint", { bg = "#121d39", fg = "#97ace0" })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#0a1a00", fg = "#5f9327" })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#291e00", fg = "#bc5918" })
hi(0, "DiagnosticWarn", { fg = "#bc5918" })
hi(0, "DiffAdd", { bg = "#0a1a00" })
hi(0, "DiffChange", { bg = "#002923" })
hi(0, "DiffDelete", { bg = "#2a0c19" })
hi(0, "DiffText", { bg = "#291e00" })
hi(0, "Directory", { fg = "#70b2cb" })
hi(0, "EndOfBuffer", { fg = "#343a36" })
hi(0, "Error", { bg = "#2a0c19" })
hi(0, "ErrorMsg", { fg = "#d6370f" })
hi(0, "ExeMod", { fg = "#6567e7" })
hi(0, "FinderParam", { fg = "#bc5918" })
hi(0, "FinderSpinner", { fg = "#5f9327" })
hi(0, "FinderSpinnerBorder", { fg = "#bf9ed1" })
hi(0, "FinderSpinnerTitle", { link = "Title" })
hi(0, "FinderVirtText", { fg = "#bc5918" })
hi(0, "Float", { link = "Constant" })
hi(0, "FloatBorder", { bg = "#000000", fg = "#bf9ed1" })
hi(0, "FloatShadow", { bg = "#4f5257", blend = 80, ctermbg = 0 })
hi(0, "FloatShadowThrough", { bg = "#4f5257", blend = 100, ctermbg = 0 })
hi(0, "FloatTitle", { bg = "#000000", bold = true, fg = "#bf9ed1" })
hi(0, "FoldColumn", { fg = "#343a36" })
hi(0, "Folded", { bg = "#000000", fg = "#5f7576" })
hi(0, "Function", { fg = "#70b2cb" })
hi(0, "GitSignsAdd", { fg = "#5f9327" })
hi(0, "GitSignsAddInline", { link = "GitSignsAdd" })
hi(0, "GitSignsAddLn", { link = "GitSignsAdd" })
hi(0, "GitSignsChange", { fg = "#bc5918" })
hi(0, "GitSignsChangeInline", { link = "GitSignsChange" })
hi(0, "GitSignsChangeLn", { link = "GitSignsChange" })
hi(0, "GitSignsDelete", { fg = "#d6370f" })
hi(0, "GitSignsDeleteInline", { link = "GitSignsDelete" })
hi(0, "GitSignsDeleteLn", { link = "GitSignsDelete" })
hi(0, "GitSignsUntracked", { fg = "#70b2cb" })
hi(0, "GitSignsUntrackedInline", { link = "GitSignsUntracked" })
hi(0, "GitSignsUntrackedLn", { link = "GitSignsUntracked" })
hi(0, "HopNextKey", { bold = true, fg = "#5f9327", nocombine = true })
hi(0, "HopNextKey1", { bold = true, fg = "#bc5918", nocombine = true })
hi(0, "HopNextKey2", { bold = true, fg = "#7d9495", nocombine = true })
hi(0, "HopPreview", { bold = true, fg = "#bc5918", nocombine = true })
hi(0, "HopUnmatched", { fg = "#343a36" })
hi(0, "HydraAmaranth", { fg = "#b355d4" })
hi(0, "HydraBlue", { fg = "#70b2cb" })
hi(0, "HydraHint", { link = "NormalFloat" })
hi(0, "HydraPink", { fg = "#bc5918" })
hi(0, "HydraRed", { fg = "#d6370f" })
hi(0, "HydraTeal", { fg = "#2c957d" })
hi(0, "Identifier", { fg = "#bc5918" })
hi(0, "Ignore", {})
hi(0, "IncSearch", { bg = "#bc5918", fg = "#000100" })
hi(0, "IndentBlanklineChar", { fg = "#343a36", nocombine = true })
hi(0, "IndentBlanklineContextChar", { fg = "#bf9ed1", nocombine = true })
hi(0, "IndentBlanklineContextStart", { nocombine = true, sp = "#bf9ed1", underline = true })
hi(0, "IndentBlanklineIndent1", { fg = "#97ace0", nocombine = true })
hi(0, "IndentBlanklineIndent2", { fg = "#2c957d", nocombine = true })
hi(0, "IndentBlanklineIndent3", { fg = "#bc5918", nocombine = true })
hi(0, "IndentBlanklineIndent4", { fg = "#d6370f", nocombine = true })
hi(0, "IndentBlanklineIndent5", { fg = "#70b2cb", nocombine = true })
hi(0, "IndentBlanklineIndent6", { fg = "#5f9327", nocombine = true })
hi(0, "IndentBlanklineIndent7", { fg = "#bc5918", nocombine = true })
hi(0, "IndentBlanklineIndent8", { fg = "#b355d4", nocombine = true })
hi(0, "Italic", { italic = true })
hi(0, "LSOutlinePreviewBorder", { fg = "#bf9ed1" })
hi(0, "LazyButton", { bg = "#181e1a" })
hi(0, "LazyButtonActive", { bg = "#343a36" })
hi(0, "LazyDimmed", { link = "Comment" })
hi(0, "LazyH1", { bg = "#343a36", bold = true, fg = "#bf9ed1" })
hi(0, "LeapBackdrop", { link = "Comment" })
hi(0, "LeapLabel", { bold = true, fg = "#bc5918", nocombine = true })
hi(0, "LeapLabelSelected", { bold = true, fg = "#2c957d", nocombine = true })
hi(0, "LeapMatch", { bold = true, fg = "#5f9327", nocombine = true, underline = true })
hi(0, "LineNr", { fg = "#343a36" })
hi(0, "LspCodeLens", { link = "Comment" })
hi(0, "LspCodeLensSeparator", { link = "Comment" })
hi(0, "LspReferenceText", { bg = "#343a36" })
hi(0, "LspSagaAutoPreview", { fg = "#97ace0" })
hi(0, "LspSagaBorderTitle", { link = "FloatTitle" })
hi(0, "LspSagaCodeActionBorder", { fg = "#bf9ed1" })
hi(0, "LspSagaCodeActionContent", { fg = "#9ab2b3" })
hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#70b2cb" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#bf9ed1" })
hi(0, "LspSagaDiagnosticBorder", { fg = "#bf9ed1" })
hi(0, "LspSagaDiagnosticHeader", { link = "Title" })
hi(0, "LspSagaDiagnosticSource", { fg = "#bc5918" })
hi(0, "LspSagaFinderSelection", { fg = "#2c957d" })
hi(0, "LspSagaHoverBorder", { fg = "#bf9ed1" })
hi(0, "LspSagaLspFinderBorder", { fg = "#bf9ed1" })
hi(0, "LspSagaRenameBorder", { fg = "#bf9ed1" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#bf9ed1" })
hi(0, "LspSignatureActiveParameter", { link = "LspReferenceText" })
hi(0, "MasonError", { fg = "#d6370f" })
hi(0, "MasonHeader", { bg = "#70b2cb", bold = true, fg = "#000100" })
hi(0, "MasonHeaderSecondary", { bg = "#97ace0", bold = true, fg = "#000100" })
hi(0, "MasonHeading", { link = "Bold" })
hi(0, "MasonHighlight", { fg = "#bf9ed1" })
hi(0, "MasonHighlightBlock", { bg = "#bf9ed1", fg = "#000100" })
hi(0, "MasonHighlightBlockBold", { link = "MasonHeaderSecondary" })
hi(0, "MasonHighlightBlockBoldSecondary", { link = "MasonHeader" })
hi(0, "MasonHighlightBlockSecondary", { bg = "#70b2cb", fg = "#000100" })
hi(0, "MasonHighlightSecondary", { fg = "#70b2cb" })
hi(0, "MasonLink", { link = "MasonHighlight" })
hi(0, "MasonMuted", { link = "Comment" })
hi(0, "MasonMutedBlock", { bg = "#343a36", fg = "#000100" })
hi(0, "MasonMutedBlockBold", { bg = "#343a36", bold = true, fg = "#000100" })
hi(0, "MatchParen", { bg = "#343a36", bold = true })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniCompletionActiveParameter", { bg = "#343a36" })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniDepsChangeAdded", { link = "diffAdded" })
hi(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
hi(0, "MiniDiffSignAdd", { link = "diffAdded" })
hi(0, "MiniDiffSignChange", { link = "diffChanged" })
hi(0, "MiniDiffSignDelete", { link = "diffRemoved" })
hi(0, "MiniFilesBorder", { link = "Normal" })
hi(0, "MiniFilesCursorLine", { bg = "#200b28" })
hi(0, "MiniFilesFile", { fg = "#9ab2b3" })
hi(0, "MiniFilesNormal", { link = "Normal" })
hi(0, "MiniFilesTitleFocused", { bg = "#000000", bold = true, fg = "#9ab2b3" })
hi(0, "MiniHipatternsFixme", { bg = "#d6370f", bold = true, fg = "#000100" })
hi(0, "MiniHipatternsFixmeBody", { fg = "#d6370f" })
hi(0, "MiniHipatternsFixmeColon", { bg = "#d6370f", bold = true, fg = "#000100" })
hi(0, "MiniHipatternsHack", { bg = "#bc5918", bold = true, fg = "#000100" })
hi(0, "MiniHipatternsHackBody", { fg = "#bc5918" })
hi(0, "MiniHipatternsHackColon", { bg = "#bc5918", bold = true, fg = "#000100" })
hi(0, "MiniHipatternsNote", { bg = "#2c957d", bold = true, fg = "#000100" })
hi(0, "MiniHipatternsNoteBody", { fg = "#2c957d" })
hi(0, "MiniHipatternsNoteColon", { bg = "#2c957d", bold = true, fg = "#000100" })
hi(0, "MiniHipatternsTodo", { bg = "#97ace0", bold = true, fg = "#000100" })
hi(0, "MiniHipatternsTodoBody", { fg = "#97ace0" })
hi(0, "MiniHipatternsTodoColon", { bg = "#97ace0", bold = true, fg = "#000100" })
hi(0, "MiniHipatterns_000000_fg", { fg = "#ffffff" })
hi(0, "MiniHipatterns_182a40_fg", { fg = "#b8cfec" })
hi(0, "MiniHipatterns_192330_fg", { fg = "#c9d6e8" })
hi(0, "MiniHipatterns_1c2f44_fg", { fg = "#b2cae5" })
hi(0, "MiniHipatterns_1d344f_fg", { fg = "#a8c4e6" })
hi(0, "MiniHipatterns_233f5e_fg", { fg = "#98b8dd" })
hi(0, "MiniHipatterns_24476f_fg", { fg = "#88afdd" })
hi(0, "MiniHipatterns_2e537d_fg", { fg = "#7aa2d1" })
hi(0, "MiniHipatterns_32343b_fg", { fg = "#bdbfc8" })
hi(0, "MiniHipatterns_393b44_fg", { fg = "#b4b6c2" })
hi(0, "MiniHipatterns_475072_fg", { fg = "#919cc2" })
hi(0, "MiniHipatterns_485e7d_fg", { fg = "#7c94b5" })
hi(0, "MiniHipatterns_4ab8ba_fg", { fg = "#006f71" })
hi(0, "MiniHipatterns_4d688e_fg", { fg = "#6d89b1" })
hi(0, "MiniHipatterns_4e75aa_fg", { fg = "#557cb2" })
hi(0, "MiniHipatterns_526175_fg", { fg = "#8090a6" })
hi(0, "MiniHipatterns_5483c1_fg", { fg = "#406eaa" })
hi(0, "MiniHipatterns_58cd8b_fg", { fg = "#006d3d" })
hi(0, "MiniHipatterns_597668_fg", { fg = "#6a8879" })
hi(0, "MiniHipatterns_59f0ff_fg", { fg = "#006870" })
hi(0, "MiniHipatterns_5a99b0_fg", { fg = "#28697e" })
hi(0, "MiniHipatterns_618774_fg", { fg = "#557b68" })
hi(0, "MiniHipatterns_629f81_fg", { fg = "#306d51" })
hi(0, "MiniHipatterns_63cdcf_fg", { fg = "#006466" })
hi(0, "MiniHipatterns_689c83_fg", { fg = "#396c55" })
hi(0, "MiniHipatterns_6ca7bd_fg", { fg = "#1d5b6f" })
hi(0, "MiniHipatterns_70a288_fg", { fg = "#35664e" })
hi(0, "MiniHipatterns_719cd6_fg", { fg = "#2e568b" })
hi(0, "MiniHipatterns_74b2c9_fg", { fg = "#0a5166" })
hi(0, "MiniHipatterns_7f848e_fg", { fg = "#666a74" })
hi(0, "MiniHipatterns_806589_fg", { fg = "#8d7297" })
hi(0, "MiniHipatterns_81b29a_fg", { fg = "#275642" })
hi(0, "MiniHipatterns_835dc1_fg", { fg = "#8660c4" })
hi(0, "MiniHipatterns_84cee4_fg", { fg = "#004c5c" })
hi(0, "MiniHipatterns_8e6f98_fg", { fg = "#83658d" })
hi(0, "MiniHipatterns_904a6a_fg", { fg = "#b96f90" })
hi(0, "MiniHipatterns_9d79d6_fg", { fg = "#6d49a1" })
hi(0, "MiniHipatterns_9f75ac_fg", { fg = "#7d558a" })
hi(0, "MiniHipatterns_a36f3e_fg", { fg = "#986534" })
hi(0, "MiniHipatterns_a4c1c2_fg", { fg = "#243e3f" })
hi(0, "MiniHipatterns_a58155_fg", { fg = "#815f33" })
hi(0, "MiniHipatterns_ac5169_fg", { fg = "#b55971" })
hi(0, "MiniHipatterns_ad425c_fg", { fg = "#c65971" })
hi(0, "MiniHipatterns_b6bcc2_fg", { fg = "#34393d" })
hi(0, "MiniHipatterns_b8a1e3_fg", { fg = "#4b356e" })
hi(0, "MiniHipatterns_b95d76_fg", { fg = "#a84e67" })
hi(0, "MiniHipatterns_ba793e_fg", { fg = "#915310" })
hi(0, "MiniHipatterns_bdbdc0_fg", { fg = "#363638" })
hi(0, "MiniHipatterns_bebebe_fg", { fg = "#353535" })
hi(0, "MiniHipatterns_c07a6d_fg", { fg = "#8c4b3f" })
hi(0, "MiniHipatterns_c15dbc_fg", { fg = "#973593" })
hi(0, "MiniHipatterns_c76882_fg", { fg = "#9b415c" })
hi(0, "MiniHipatterns_c7a957_fg", { fg = "#6b5300" })
hi(0, "MiniHipatterns_c94f6d_fg", { fg = "#b63e5d" })
hi(0, "MiniHipatterns_c9709e_fg", { fg = "#8e3b69" })
hi(0, "MiniHipatterns_ca884a_fg", { fg = "#844a00" })
hi(0, "MiniHipatterns_cdd1d5_fg", { fg = "#232629" })
hi(0, "MiniHipatterns_ced6db_fg", { fg = "#1d2327" })
hi(0, "MiniHipatterns_cfd6dd_fg", { fg = "#1d2328" })
hi(0, "MiniHipatterns_d6616b_fg", { fg = "#a63544" })
hi(0, "MiniHipatterns_d67ad2_fg", { fg = "#7a2278" })
hi(0, "MiniHipatterns_d685af_fg", { fg = "#783058" })
hi(0, "MiniHipatterns_d76558_fg", { fg = "#a5372e" })
hi(0, "MiniHipatterns_dbc074_fg", { fg = "#5b4700" })
hi(0, "MiniHipatterns_dbcece_fg", { fg = "#2c2222" })
hi(0, "MiniHipatterns_dbdbdb_fg", { fg = "#1d1d1d" })
hi(0, "MiniHipatterns_de8db7_fg", { fg = "#6f2951" })
hi(0, "MiniHipatterns_df97db_fg", { fg = "#5f1f5e" })
hi(0, "MiniHipatterns_dfdfe0_fg", { fg = "#19191a" })
hi(0, "MiniHipatterns_e28940_fg", { fg = "#8d4901" })
hi(0, "MiniHipatterns_e3786c_fg", { fg = "#902d26" })
hi(0, "MiniHipatterns_e7d2be_fg", { fg = "#2d1e0e" })
hi(0, "MiniHipatterns_e8857a_fg", { fg = "#822923" })
hi(0, "MiniHipatterns_eaeaea_fg", { fg = "#0f0f0f" })
hi(0, "MiniHipatterns_f2f2f2_fg", { fg = "#070707" })
hi(0, "MiniHipatterns_f4a261_fg", { fg = "#773e00" })
hi(0, "MiniHipatterns_f6a878_fg", { fg = "#6a3100" })
hi(0, "MiniHipatterns_ffe37e_fg", { fg = "#5b4a00" })
hi(0, "MiniIconsAzure", { fg = "#70b2cb" })
hi(0, "MiniIconsBlue", { fg = "#97ace0" })
hi(0, "MiniIconsCyan", { fg = "#2c957d" })
hi(0, "MiniIconsGreen", { fg = "#5f9327" })
hi(0, "MiniIconsGrey", { fg = "#b4cdce" })
hi(0, "MiniIconsOrange", { fg = "#bc5918" })
hi(0, "MiniIconsPurple", { fg = "#b355d4" })
hi(0, "MiniIconsRed", { fg = "#d6370f" })
hi(0, "MiniIconsYellow", { fg = "#bc5918" })
hi(0, "MiniIndentscopeSymbol", { fg = "#bf9ed1" })
hi(0, "MiniIndentscopeSymbolOff", { fg = "#d6370f" })
hi(0, "MiniJump", { sp = "#bf9ed1", undercurl = true })
hi(0, "MiniJump2dDim", { fg = "#343a36" })
hi(0, "MiniJump2dSpot", { bold = true, fg = "#b355d4", underline = true })
hi(0, "MiniJump2dSpotAhead", { fg = "#bc5918" })
hi(0, "MiniJump2dSpotUnique", { bold = true, fg = "#d6370f", underline = true })
hi(0, "MiniMapNormal", { bg = "#000000", fg = "#5f7576" })
hi(0, "MiniMapSymbolCount", { fg = "#5f7576" })
hi(0, "MiniMapSymbolLine", { fg = "#bf9ed1" })
hi(0, "MiniMapSymbolView", { fg = "#bf9ed1" })
hi(0, "MiniPickCursor", { blend = 100, nocombine = true })
hi(0, "MiniPickExplorerDate", { fg = "#3582d4" })
hi(0, "MiniPickExplorerDirectory", { fg = "#9ab2b3" })
hi(0, "MiniPickExplorerSize", { fg = "#3582d4" })
hi(0, "MiniPickMatchCurrent", { link = "CursorLine" })
hi(0, "MiniSnippetsCurrent", { sp = "#bc5918", underdouble = true })
hi(0, "MiniSnippetsCurrentReplace", { sp = "#d6370f", underdouble = true })
hi(0, "MiniSnippetsFinal", { sp = "#5f9327", underdouble = true })
hi(0, "MiniSnippetsUnvisited", { sp = "#2c957d", underdouble = true })
hi(0, "MiniSnippetsVisited", { sp = "#97ace0", underdouble = true })
hi(0, "MiniStarterFooter", { link = "Comment" })
hi(0, "MiniStarterHeader", { bold = true, fg = "#bf9ed1" })
hi(0, "MiniStarterItem", {})
hi(0, "MiniStarterItemBullet", { fg = "#5f7576" })
hi(0, "MiniStarterItemPrefix", { bold = true, fg = "#bc5918" })
hi(0, "MiniStarterQuery", { bold = true, fg = "#5f9327" })
hi(0, "MiniStarterSection", { fg = "#b355d4" })
hi(0, "MiniStatuslineDevinfo", { bg = "#181e1a", fg = "#7d9495" })
hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
hi(0, "MiniStatuslineFilename", { bg = "#00512c", fg = "#7d9495" })
hi(0, "MiniStatuslineInactive", { link = "StatusLineNC" })
hi(0, "MiniStatuslineModeCommand", { bg = "#bc5918", bold = true, fg = "#000100" })
hi(0, "MiniStatuslineModeInsert", { bg = "#70b2cb", bold = true, fg = "#000100" })
hi(0, "MiniStatuslineModeNormal", { bg = "#9ab2b3", bold = true, fg = "#000100" })
hi(0, "MiniStatuslineModeOther", { bg = "#2c957d", bold = true, fg = "#000100" })
hi(0, "MiniStatuslineModeReplace", { bg = "#d6370f", bold = true, fg = "#000100" })
hi(0, "MiniStatuslineModeVisual", { bg = "#5f9327", bold = true, fg = "#000100" })
hi(0, "MiniTablineCurrent", { bg = "#000100", fg = "#d0e9ea", underline = true })
hi(0, "MiniTablineFill", { link = "MiniTablineHidden" })
hi(0, "MiniTablineHidden", { bg = "#000100", fg = "#181e1a" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#bf9ed1", bold = true, fg = "#000100" })
hi(0, "MiniTablineModifiedHidden", { bg = "#7d9495", fg = "#000000" })
hi(0, "MiniTablineModifiedVisible", { bg = "#7d9495", bold = true, fg = "#000000" })
hi(0, "MiniTablineTabpagesection", { bg = "#5f9327", bold = true, fg = "#000100" })
hi(0, "MiniTablineVisible", { bg = "#000100", fg = "#181e1a" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#d6370f" })
hi(0, "MiniTestPass", { bold = true, fg = "#5f9327" })
hi(0, "MiniTrailspace", { bg = "#2a0c19" })
hi(0, "ModeMsg", { fg = "#5f9327" })
hi(0, "MoreMsg", { fg = "#70b2cb" })
hi(0, "MsgArea", { link = "Normal" })
hi(0, "MsgSeparator", { bg = "#343a36", fg = "#5f7576" })
hi(0, "NeoTreeDimText", { fg = "#343a36" })
hi(0, "NeoTreeDotfile", { fg = "#7d9495" })
hi(0, "NeoTreeFadeText1", { link = "NeoTreeDimText" })
hi(0, "NeoTreeFadeText2", { fg = "#343a36" })
hi(0, "NeoTreeGitAdded", { fg = "#5f9327" })
hi(0, "NeoTreeGitConflict", { bold = true, fg = "#bc5918" })
hi(0, "NeoTreeGitDeleted", { fg = "#d6370f" })
hi(0, "NeoTreeGitModified", { fg = "#bc5918" })
hi(0, "NeoTreeGitUnstaged", { fg = "#b355d4" })
hi(0, "NeoTreeGitUntracked", { fg = "#2c957d" })
hi(0, "NeoTreeMessage", { bg = "#181e1a", fg = "#9ab2b3" })
hi(0, "NeoTreeModified", { fg = "#b4cdce" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#bf9ed1" })
hi(0, "NeoTreeTabInactive", { fg = "#5f7576" })
hi(0, "NeoTreeTabSeparatorActive", { bg = "#343a36", fg = "#5f7576" })
hi(0, "NeoTreeTabSeparatorInactive", { bg = "#181e1a", fg = "#181e1a" })
hi(0, "NeogitCommitViewHeader", { link = "Special" })
hi(0, "NeogitDiffAdd", { link = "DiffAdd" })
hi(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
hi(0, "NeogitDiffDelete", { link = "DiffDelete" })
hi(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
hi(0, "NeogitFold", { link = "FoldColumn" })
hi(0, "NeogitHunkHeader", { fg = "#bf9ed1" })
hi(0, "NeogitHunkHeaderHighlight", { bold = true, fg = "#bf9ed1" })
hi(0, "NeogitNotificationError", { link = "DiagnosticError" })
hi(0, "NeogitNotificationInfo", { link = "DiagnosticInfo" })
hi(0, "NeogitNotificationWarning", { link = "DiagnosticWarn" })
hi(0, "NoiceCmdlinePopupBorder", { fg = "#70b2cb" })
hi(0, "NoiceConfirmBorder", { fg = "#bc5918" })
hi(0, "NonText", { fg = "#343a36" })
hi(0, "Normal", { bg = "#000100", fg = "#9ab2b3" })
hi(0, "NormalBG", { bg = "#000100" })
hi(0, "NormalFloat", { bg = "#000000", fg = "#9ab2b3" })
hi(0, "NormalNC", { link = "Normal" })
hi(0, "NotifyDEBUGBorder", { fg = "#5f9327" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyERRORBorder", { fg = "#d6370f" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
hi(0, "NotifyINFOBorder", { fg = "#97ace0" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
hi(0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
hi(0, "NotifyTRACEBorder", { fg = "#2c957d" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
hi(0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
hi(0, "NotifyWARNBorder", { fg = "#bc5918" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
hi(0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
hi(0, "NvimInternalError", { bg = "#cb0000", ctermbg = 9, ctermfg = 9, fg = "#cb0000" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#5f9327" })
hi(0, "NvimTreeFolderIcon", { fg = "#5f7576" })
hi(0, "NvimTreeGitDeleted", { fg = "#d6370f" })
hi(0, "NvimTreeGitDirty", { fg = "#bc5918" })
hi(0, "NvimTreeGitMerge", { fg = "#bc5918" })
hi(0, "NvimTreeGitNew", { fg = "#2c957d" })
hi(0, "NvimTreeGitRenamed", { fg = "#b355d4" })
hi(0, "NvimTreeGitStaged", { fg = "#5f9327" })
hi(0, "NvimTreeImageFile", { fg = "#bc5918" })
hi(0, "NvimTreeIndentMarker", { link = "NvimTreeFolderIcon" })
hi(0, "NvimTreeOpenedFile", { link = "NvimTreeExecFile" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#bf9ed1" })
hi(0, "NvimTreeSpecialFile", { fg = "#bf9ed1", underline = true })
hi(0, "NvimTreeSymlink", { bold = true, fg = "#97ace0" })
hi(0, "NvimTreeWindowPicker", { bg = "#343a36", bold = true, fg = "#9ab2b3" })
hi(0, "Operator", { fg = "#9ab2b3" })
hi(0, "OutlineDetail", { fg = "#343a36" })
hi(0, "OutlineFoldPrefix", { fg = "#bc5918" })
hi(0, "OutlineIndentEvn", { fg = "#5f7576" })
hi(0, "OutlineIndentOdd", { fg = "#9ab2b3" })
hi(0, "Pmenu", { bg = "#020503", fg = "#9ab2b3" })
hi(0, "PmenuMatch", { bg = "#181e1a", bold = true, fg = "#9ab2b3" })
hi(0, "PmenuMatchSel", { blend = 0, bold = true, reverse = true })
hi(0, "PmenuSel", { bg = "#001926" })
hi(0, "PmenuThumb", { bg = "#343a36" })
hi(0, "PounceAccept", { bg = "#bc5918", bold = true, fg = "#000100", nocombine = true })
hi(0, "PounceAcceptBest", { bg = "#5f9327", bold = true, fg = "#000100", nocombine = true })
hi(0, "PounceGap", { bg = "#343a36", bold = true, fg = "#000100", nocombine = true })
hi(0, "PounceMatch", { bg = "#9ab2b3", bold = true, fg = "#000100", nocombine = true })
hi(0, "PreProc", { fg = "#97ace0" })
hi(0, "Question", { fg = "#70b2cb" })
hi(0, "QuickFixLine", { bold = true })
hi(0, "RainbowDelimiterBlue", { fg = "#70b2cb" })
hi(0, "RainbowDelimiterCyan", { fg = "#2c957d" })
hi(0, "RainbowDelimiterGreen", { fg = "#5f9327" })
hi(0, "RainbowDelimiterOrange", { fg = "#bc5918" })
hi(0, "RainbowDelimiterRed", { fg = "#d6370f" })
hi(0, "RainbowDelimiterViolet", { fg = "#b355d4" })
hi(0, "RainbowDelimiterYellow", { fg = "#bc5918" })
hi(0, "ReadBit", { fg = "#2c957d" })
hi(0, "RedrawDebugClear", { bg = "#4e3c00", ctermbg = 3, ctermfg = 15 })
hi(0, "RedrawDebugComposed", { bg = "#003a16", ctermbg = 2, ctermfg = 15 })
hi(0, "RedrawDebugRecompose", { bg = "#421311", ctermbg = 1, ctermfg = 15 })
hi(0, "References", { fg = "#5f9327" })
hi(0, "ReferencesIcon", { fg = "#70b2cb" })
hi(0, "Removed", { fg = "#d6370f" })
hi(0, "Search", { bg = "#bf9ed1", fg = "#000100" })
hi(0, "SepBit", { fg = "#777294" })
hi(0, "SignColumn", { fg = "#343a36" })
hi(0, "Sneak", { bg = "#bc5918", fg = "#000100" })
hi(0, "SneakLabel", { bg = "#bc5918", bold = true, fg = "#000100" })
hi(0, "SneakScope", { bg = "#d0e9ea", fg = "#000100" })
hi(0, "SnippetTabstop", { bg = "#291e00" })
hi(0, "Special", { fg = "#2c957d" })
hi(0, "SpecialKey", { fg = "#343a36" })
hi(0, "SpellBad", { sp = "#d6370f", undercurl = true })
hi(0, "SpellCap", { sp = "#2c957d", undercurl = true })
hi(0, "SpellLocal", { sp = "#bc5918", undercurl = true })
hi(0, "SpellRare", { sp = "#97ace0", undercurl = true })
hi(0, "Statement", { bold = true, fg = "#9ab2b3" })
hi(0, "StatusLine", { bg = "#00512c", fg = "#bbccbf" })
hi(0, "StatusLineNC", { bg = "#000000", fg = "#7d9495" })
hi(0, "String", { fg = "#5f9327" })
hi(0, "Substitute", { bg = "#97ace0", fg = "#000100" })
hi(0, "TabLine", { bg = "#000000", fg = "#7d9495" })
hi(0, "TabLineSel", { bg = "#000000", fg = "#bf9ed1" })
hi(0, "TargetFileName", { fg = "#9ab2b3" })
hi(0, "TelescopeBorder", { fg = "#bf9ed1" })
hi(0, "TelescopeMatching", { bold = true })
hi(0, "TelescopeMultiSelection", { bg = "#343a36" })
hi(0, "TelescopeSelection", { bg = "#181e1a" })
hi(0, "TermCursor", { link = "Cursor" })
hi(0, "TermCursorNC", { reverse = true })
hi(0, "Title", { fg = "#bf9ed1" })
hi(0, "Todo", { bg = "#00512c", bold = true, fg = "#bf9ed1" })
hi(0, "TroubleCount", { bold = true, fg = "#bf9ed1" })
hi(0, "TroubleFoldIcon", { bold = true, fg = "#bf9ed1" })
hi(0, "TroubleIndent", { fg = "#343a36" })
hi(0, "TroubleLocation", { fg = "#7d9495" })
hi(0, "TroubleSignError", { link = "DiagnosticError" })
hi(0, "TroubleSignHint", { link = "DiagnosticHint" })
hi(0, "TroubleSignInformation", { link = "DiagnosticInfo" })
hi(0, "TroubleSignOther", { link = "DiagnosticInfo" })
hi(0, "TroubleSignWarning", { link = "DiagnosticWarn" })
hi(0, "TroubleText", { fg = "#9ab2b3" })
hi(0, "TroubleTextError", { link = "TroubleText" })
hi(0, "TroubleTextHint", { link = "TroubleText" })
hi(0, "TroubleTextInformation", { link = "TroubleText" })
hi(0, "TroubleTextWarning", { link = "TroubleText" })
hi(0, "Type", { fg = "#9ab2b3" })
hi(0, "VertSplit", { fg = "#bf9ed1" })
hi(0, "Visual", { bg = "#343a36" })
hi(0, "VisualNOS", { bg = "#181e1a" })
hi(0, "WarningMsg", { fg = "#bc5918" })
hi(0, "WhichKey", { fg = "#2c957d" })
hi(0, "WhichKeyBorder", { link = "FloatBorder" })
hi(0, "WhichKeyDesc", { fg = "#9ab2b3" })
hi(0, "WhichKeyFloat", { bg = "#000000", fg = "#9ab2b3" })
hi(0, "WhichKeyGroup", { fg = "#d6370f" })
hi(0, "WhichKeySeparator", { fg = "#5f9327" })
hi(0, "WhichKeyValue", { link = "Comment" })
hi(0, "Whitespace", { fg = "#343a36" })
hi(0, "WinBar", { link = "StatusLine" })
hi(0, "WinBarNC", { link = "StatusLineNC" })
hi(0, "WinSeparator", { fg = "#bf9ed1" })
hi(0, "WriteBit", { fg = "#c31a99" })
hi(0, "diffAdded", { fg = "#5f9327" })
hi(0, "diffChanged", { fg = "#2c957d" })
hi(0, "diffFile", { fg = "#bc5918" })
hi(0, "diffLine", { fg = "#97ace0" })
hi(0, "diffRemoved", { fg = "#d6370f" })
hi(0, "gitcommitBranch", { bold = true, fg = "#bc5918" })
hi(0, "gitcommitComment", { link = "Comment" })
hi(0, "gitcommitDiscarded", { link = "Comment" })
hi(0, "gitcommitDiscardedFile", { bold = true, fg = "#bc5918" })
hi(0, "gitcommitDiscardedType", { fg = "#70b2cb" })
hi(0, "gitcommitHeader", { link = "Title" })
hi(0, "gitcommitOverflow", { fg = "#bc5918" })
hi(0, "gitcommitSelected", { link = "Comment" })
hi(0, "gitcommitSelectedFile", { bold = true, fg = "#5f9327" })
hi(0, "gitcommitSelectedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitSummary", { fg = "#5f9327" })
hi(0, "gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
hi(0, "gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitUntracked", { link = "Comment" })
hi(0, "gitcommitUntrackedFile", { fg = "#2c957d" })
hi(0, "lCursor", { link = "Cursor" })
hi(0, "statusadded", { bg = "#00512c", fg = "#5f9327" })
hi(0, "statuschanged", { bg = "#00512c", fg = "#2c957d" })
hi(0, "statusmodeCO", { bg = "#d6370f", fg = "#000100" })
hi(0, "statusmodeNO", { bg = "#9ab2b3", fg = "#000100" })
hi(0, "statusmodeRO", { bg = "#2c957d", fg = "#000100" })
hi(0, "statusremoved", { bg = "#00512c", fg = "#d6370f" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#000100"
g.terminal_color_1 = "#d6370f"
g.terminal_color_2 = "#5f9327"
g.terminal_color_3 = "#bc5918"
g.terminal_color_4 = "#70b2cb"
g.terminal_color_5 = "#b355d4"
g.terminal_color_6 = "#2c957d"
g.terminal_color_7 = "#9ab2b3"
g.terminal_color_8 = "#000100"
g.terminal_color_9 = "#d6370f"
g.terminal_color_10 = "#5f9327"
g.terminal_color_11 = "#bc5918"
g.terminal_color_12 = "#70b2cb"
g.terminal_color_13 = "#b355d4"
g.terminal_color_14 = "#2c957d"
g.terminal_color_15 = "#9ab2b3"
