-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "github_light"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@annotation", { ctermfg = 25, fg = "#044289" })
hi(0, "@attribute", { ctermfg = 136, fg = "#b08800" })
hi(0, "@character", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "@comment", { ctermfg = 250, fg = "#bcbec0" })
hi(0, "@comment.danger", { bg = "#de2c2e", ctermbg = 160, ctermfg = 255, fg = "#edeff1" })
hi(0, "@comment.note", { bg = "#0d7fdd", ctermbg = 32, ctermfg = 231, fg = "#ffffff" })
hi(0, "@comment.todo", { bg = "#24292e", ctermbg = 235, ctermfg = 251, fg = "#c7c9cb" })
hi(0, "@comment.warning", { bg = "#b93a86", ctermbg = 162, ctermfg = 255, fg = "#edeff1" })
hi(0, "@constant", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "@constant.builtin", { ctermfg = 162, fg = "#b93a86" })
hi(0, "@constant.macro", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "@constructor", { ctermfg = 35, fg = "#28a745" })
hi(0, "@definition", { sp = "#c7c9cb", underline = true })
hi(0, "@diff.delta", { ctermfg = 248, fg = "#a6a8aa" })
hi(0, "@diff.minus", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "@diff.plus", { ctermfg = 23, fg = "#18654b" })
hi(0, "@error", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "@event", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "@function", { ctermfg = 26, fg = "#005cc5" })
hi(0, "@function.builtin", { ctermfg = 26, fg = "#005cc5" })
hi(0, "@function.call", { ctermfg = 26, fg = "#005cc5" })
hi(0, "@function.macro", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "@function.method", { ctermfg = 26, fg = "#005cc5" })
hi(0, "@function.method.call", { ctermfg = 26, fg = "#005cc5" })
hi(0, "@keyword", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "@keyword.conditional", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "@keyword.conditional.ternary", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "@keyword.directive", { ctermfg = 136, fg = "#b08800" })
hi(0, "@keyword.directive.define", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "@keyword.exception", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "@keyword.function", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.operator", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "@keyword.repeat", { ctermfg = 136, fg = "#b08800" })
hi(0, "@keyword.return", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "@keyword.storage", { ctermfg = 136, fg = "#b08800" })
hi(0, "@lsp.mod.deprecated", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "@lsp.type.class", { link = "Structure" })
hi(0, "@lsp.type.decorator", { link = "Function" })
hi(0, "@lsp.type.enum", { link = "Type" })
hi(0, "@lsp.type.enumMember", { link = "Constant" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "Structure" })
hi(0, "@lsp.type.macro", { link = "@macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.struct", { link = "Structure" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParamater", { link = "Typedef" })
hi(0, "@lsp.type.variable", { link = "@variable" })
hi(0, "@markup.heading", { ctermfg = 26, fg = "#005cc5" })
hi(0, "@markup.heading.1.markdown", { link = "markdownH1" })
hi(0, "@markup.heading.1.marker.markdown", { link = "markdownH1Delimiter" })
hi(0, "@markup.heading.2.markdown", { link = "markdownH2" })
hi(0, "@markup.heading.2.marker.markdown", { link = "markdownH2Delimiter" })
hi(0, "@markup.heading.3.markdown", { link = "markdownH3" })
hi(0, "@markup.heading.3.marker.markdown", { link = "markdownH3Delimiter" })
hi(0, "@markup.heading.4.markdown", { link = "markdownH4" })
hi(0, "@markup.heading.4.marker.markdown", { link = "markdownH4Delimiter" })
hi(0, "@markup.heading.5.markdown", { link = "markdownH5" })
hi(0, "@markup.heading.5.marker.markdown", { link = "markdownH5Delimiter" })
hi(0, "@markup.heading.6.markdown", { link = "markdownH6" })
hi(0, "@markup.heading.6.marker.markdown", { link = "markdownH6Delimiter" })
hi(0, "@markup.link", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "@markup.link.label", { ctermfg = 99, fg = "#8263eb" })
hi(0, "@markup.link.url", { ctermfg = 162, fg = "#b93a86", underline = true })
hi(0, "@markup.list", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "@markup.quote", {})
hi(0, "@markup.raw", { ctermfg = 162, fg = "#b93a86" })
hi(0, "@modifier", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "@module", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "@number", { ctermfg = 162, fg = "#b93a86" })
hi(0, "@number.float", { ctermfg = 162, fg = "#b93a86" })
hi(0, "@operator", { ctermfg = 166, fg = "#d15704" })
hi(0, "@property", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "@punctuation.bracket", { ctermfg = 32, fg = "#0d7fdd" })
hi(0, "@punctuation.delimiter", { ctermfg = 25, fg = "#044289" })
hi(0, "@reference", { ctermfg = 237, fg = "#383d42" })
hi(0, "@regexp", { ctermfg = 25, fg = "#044289" })
hi(0, "@scope", { bold = true })
hi(0, "@string", { ctermfg = 54, fg = "#4c2889" })
hi(0, "@string.escape", { ctermfg = 99, fg = "#8263eb" })
hi(0, "@string.regex", { ctermfg = 99, fg = "#8263eb" })
hi(0, "@string.special.vimdoc", { link = "SpecialChar" })
hi(0, "@symbol", { ctermfg = 54, fg = "#4c2889" })
hi(0, "@tag", { ctermfg = 136, fg = "#b08800" })
hi(0, "@tag.attribute", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "@tag.delimiter", { ctermfg = 25, fg = "#044289" })
hi(0, "@text", { ctermfg = 237, fg = "#383d42" })
hi(0, "@text.emphasis", { ctermfg = 162, fg = "#b93a86" })
hi(0, "@text.strike", { ctermfg = 25, fg = "#044289", strikethrough = true })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@type.builtin", { ctermfg = 136, fg = "#b08800" })
hi(0, "@variable", { ctermfg = 237, fg = "#383d42" })
hi(0, "@variable.builtin", { ctermfg = 162, fg = "#b93a86" })
hi(0, "@variable.member", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "@variable.member.key", { ctermfg = 235, fg = "#24292e" })
hi(0, "@variable.parameter", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "@variable.parameter.vimdoc", { ctermfg = 162, fg = "#b93a86" })
hi(0, "Added", { ctermfg = 23, fg = "#18654b" })
hi(0, "Beacon", { bg = "#24292e", ctermbg = 235 })
hi(0, "BlimkCmpKindClass", { ctermfg = 31, fg = "#22839b" })
hi(0, "BlimkCmpKindCodeium", { ctermfg = 35, fg = "#28a745" })
hi(0, "BlimkCmpKindColor", { ctermfg = 235, fg = "#24292e" })
hi(0, "BlimkCmpKindConstant", { ctermfg = 162, fg = "#b93a86" })
hi(0, "BlimkCmpKindConstructor", { ctermfg = 32, fg = "#0d7fdd" })
hi(0, "BlimkCmpKindCopilot", { ctermfg = 23, fg = "#18654b" })
hi(0, "BlimkCmpKindEnum", { ctermfg = 32, fg = "#0d7fdd" })
hi(0, "BlimkCmpKindEnumMember", { ctermfg = 99, fg = "#8263eb" })
hi(0, "BlimkCmpKindEvent", { ctermfg = 178, fg = "#dbab09" })
hi(0, "BlimkCmpKindField", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "BlimkCmpKindFile", { ctermfg = 235, fg = "#24292e" })
hi(0, "BlimkCmpKindFolder", { ctermfg = 235, fg = "#24292e" })
hi(0, "BlimkCmpKindFunction", { ctermfg = 26, fg = "#005cc5" })
hi(0, "BlimkCmpKindIdentifier", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "BlimkCmpKindInterface", { ctermfg = 23, fg = "#18654b" })
hi(0, "BlimkCmpKindKeyword", { ctermfg = 235, fg = "#24292e" })
hi(0, "BlimkCmpKindMethod", { ctermfg = 26, fg = "#005cc5" })
hi(0, "BlimkCmpKindModule", { ctermfg = 136, fg = "#b08800" })
hi(0, "BlimkCmpKindOperator", { ctermfg = 237, fg = "#383d42" })
hi(0, "BlimkCmpKindProperty", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "BlimkCmpKindReference", { ctermfg = 237, fg = "#383d42" })
hi(0, "BlimkCmpKindSnippet", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "BlimkCmpKindStruct", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "BlimkCmpKindStructure", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "BlimkCmpKindSuperMaven", { ctermfg = 178, fg = "#dbab09" })
hi(0, "BlimkCmpKindTabNine", { ctermfg = 169, fg = "#ea4aaa" })
hi(0, "BlimkCmpKindText", { ctermfg = 54, fg = "#4c2889" })
hi(0, "BlimkCmpKindType", { ctermfg = 136, fg = "#b08800" })
hi(0, "BlimkCmpKindTypeParameter", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "BlimkCmpKindUnit", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "BlimkCmpKindValue", { ctermfg = 31, fg = "#0598bc" })
hi(0, "BlimkCmpKindVariable", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "BlinkCmpDoc", { link = "CmpDoc" })
hi(0, "BlinkCmpDocBorder", { link = "CmpDocBorder" })
hi(0, "BlinkCmpMenu", { link = "CmpPmenu" })
hi(0, "BlinkCmpMenuBorder", { link = "CmpBorder" })
hi(0, "BlinkCmpSignatureHelp", { link = "CmpDoc" })
hi(0, "BlinkCmpSignatureHelpBorder", { link = "CmpDocBorder" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { ctermfg = 162, fg = "#b93a86" })
hi(0, "BqfPreviewFloat", { link = "NormalFloat" })
hi(0, "BqfPreviewTitle", { bg = "#edeff1", ctermbg = 255, ctermfg = 26, fg = "#005cc5" })
hi(0, "BqfSign", { bg = "#edeff1", ctermbg = 255, ctermfg = 99, fg = "#8263eb" })
hi(0, "BufferCurrent", { bg = "#e1e3e5", bold = true, ctermbg = 254, ctermfg = 237, fg = "#383d42" })
hi(0, "BufferCurrentIcon", { bg = "#e1e3e5", ctermbg = 254 })
hi(0, "BufferCurrentIndex", { link = "BufferCurrentIcon" })
hi(0, "BufferCurrentMod", { bg = "#e1e3e5", bold = true, ctermbg = 254, ctermfg = 55, fg = "#5a32a3" })
hi(0, "BufferCurrentSign", { link = "BufferCurrent" })
hi(0, "BufferCurrentTarget", { bg = "#e1e3e5", bold = true, ctermbg = 254, ctermfg = 160, fg = "#de2c2e" })
hi(0, "BufferInactive", { bg = "#edeff1", ctermbg = 255, ctermfg = 251, fg = "#c7c9cb" })
hi(0, "BufferInactiveIcon", { bg = "#edeff1", ctermbg = 255 })
hi(0, "BufferInactiveIndex", { link = "BufferInactiveIcon" })
hi(0, "BufferInactiveMod", { bg = "#edeff1", ctermbg = 255, ctermfg = 55, fg = "#5a32a3" })
hi(0, "BufferInactiveSign", { link = "BufferInactive" })
hi(0, "BufferInactiveTarget", { bg = "#edeff1", bold = true, ctermbg = 255, ctermfg = 160, fg = "#de2c2e" })
hi(0, "BufferLineBuffer", { ctermfg = 251, fg = "#c7c9cb" })
hi(0, "BufferLineBufferSelected", { bold = true, ctermfg = 237, fg = "#383d42" })
hi(0, "BufferLineBufferVisible", { ctermfg = 237, fg = "#383d42" })
hi(0, "BufferLineCloseButton", { link = "BufferLineBackground" })
hi(0, "BufferLineCloseButtonSelected", { link = "BufferLineBufferSelected" })
hi(0, "BufferLineCloseButtonVisible", { link = "BufferLineBufferVisible" })
hi(0, "BufferLineFill", { link = "Normal" })
hi(0, "BufferLineTab", { bg = "#b08800", ctermbg = 136, ctermfg = 231, fg = "#ffffff" })
hi(0, "BufferLineTabSelected", { bg = "#b08800", bold = true, ctermbg = 136, ctermfg = 231, fg = "#ffffff" })
hi(0, "BufferOffset", { link = "Normal" })
hi(0, "BufferTabpageFill", { link = "Normal" })
hi(0, "BufferTabpages", { bg = "#b08800", bold = true, ctermbg = 136, ctermfg = 255, fg = "#edeff1" })
hi(0, "BufferVisible", { bg = "#edeff1", bold = true, ctermbg = 255, ctermfg = 237, fg = "#383d42" })
hi(0, "BufferVisibleIcon", { bg = "#edeff1", ctermbg = 255 })
hi(0, "BufferVisibleIndex", { link = "BufferVisibleIcon" })
hi(0, "BufferVisibleMod", { bg = "#edeff1", bold = true, ctermbg = 255, ctermfg = 55, fg = "#5a32a3" })
hi(0, "BufferVisibleSign", { link = "BufferVisible" })
hi(0, "BufferVisibleTarget", { bg = "#edeff1", bold = true, ctermbg = 255, ctermfg = 160, fg = "#de2c2e" })
hi(0, "Changed", { ctermfg = 178, fg = "#dbab09" })
hi(0, "Character", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "CmpBorder", { ctermfg = 250, fg = "#bcbec0" })
hi(0, "CmpDoc", { bg = "#ffffff", ctermbg = 231 })
hi(0, "CmpDocBorder", { ctermfg = 250, fg = "#bcbec0" })
hi(0, "CmpItemAbbr", { ctermfg = 235, fg = "#24292e" })
hi(0, "CmpItemAbbrDeprecated", { ctermfg = 253, fg = "#d7d9db" })
hi(0, "CmpItemAbbrMatch", { bold = true, ctermfg = 32, fg = "#0d7fdd" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, ctermfg = 136, fg = "#b08800" })
hi(0, "CmpItemKind", { bg = "#edeff1", ctermbg = 255, ctermfg = 25, fg = "#044289" })
hi(0, "CmpItemKindClass", { ctermfg = 31, fg = "#22839b" })
hi(0, "CmpItemKindCodeium", { ctermfg = 35, fg = "#28a745" })
hi(0, "CmpItemKindColor", { ctermfg = 235, fg = "#24292e" })
hi(0, "CmpItemKindConstant", { ctermfg = 162, fg = "#b93a86" })
hi(0, "CmpItemKindConstructor", { ctermfg = 32, fg = "#0d7fdd" })
hi(0, "CmpItemKindCopilot", { ctermfg = 23, fg = "#18654b" })
hi(0, "CmpItemKindEnum", { ctermfg = 32, fg = "#0d7fdd" })
hi(0, "CmpItemKindEnumMember", { ctermfg = 99, fg = "#8263eb" })
hi(0, "CmpItemKindEvent", { ctermfg = 178, fg = "#dbab09" })
hi(0, "CmpItemKindField", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "CmpItemKindFile", { ctermfg = 235, fg = "#24292e" })
hi(0, "CmpItemKindFolder", { ctermfg = 235, fg = "#24292e" })
hi(0, "CmpItemKindFunction", { ctermfg = 26, fg = "#005cc5" })
hi(0, "CmpItemKindIdentifier", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "CmpItemKindInterface", { ctermfg = 23, fg = "#18654b" })
hi(0, "CmpItemKindKeyword", { ctermfg = 235, fg = "#24292e" })
hi(0, "CmpItemKindMethod", { ctermfg = 26, fg = "#005cc5" })
hi(0, "CmpItemKindModule", { ctermfg = 136, fg = "#b08800" })
hi(0, "CmpItemKindOperator", { ctermfg = 237, fg = "#383d42" })
hi(0, "CmpItemKindProperty", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "CmpItemKindReference", { ctermfg = 237, fg = "#383d42" })
hi(0, "CmpItemKindSnippet", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "CmpItemKindStruct", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "CmpItemKindStructure", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "CmpItemKindSuperMaven", { ctermfg = 178, fg = "#dbab09" })
hi(0, "CmpItemKindTabNine", { ctermfg = 169, fg = "#ea4aaa" })
hi(0, "CmpItemKindText", { ctermfg = 54, fg = "#4c2889" })
hi(0, "CmpItemKindType", { ctermfg = 136, fg = "#b08800" })
hi(0, "CmpItemKindTypeParameter", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "CmpItemKindUnit", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "CmpItemKindValue", { ctermfg = 31, fg = "#0598bc" })
hi(0, "CmpItemKindVariable", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "CmpItemMenu", { bg = "#edeff1", ctermbg = 255, ctermfg = 237, fg = "#383d42" })
hi(0, "CmpPmenu", { bg = "#ffffff", ctermbg = 231 })
hi(0, "CmpSel", { bg = "#8263eb", ctermbg = 99, ctermfg = 231, fg = "#ffffff" })
hi(0, "CocCodeLens", { link = "LspCodeLens" })
hi(0, "CocDisabled", { link = "Comment" })
hi(0, "CocFadeOut", { link = "Comment" })
hi(0, "CocMarkdownLink", { ctermfg = 25, fg = "#044289" })
hi(0, "CocMenuSel", { bg = "#e1e3e5", ctermbg = 254 })
hi(0, "CocNotificationProgress", { link = "CocMarkdownLink" })
hi(0, "CocPumVirtualText", { link = "CocMarkdownLink" })
hi(0, "CocSearch", { ctermfg = 136, fg = "#b08800" })
hi(0, "CocSelectedText", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "ColorColumn", { bg = "#edeff1", ctermbg = 255 })
hi(0, "Comment", { ctermfg = 248, fg = "#a6a8aa" })
hi(0, "Conceal", {})
hi(0, "Conditional", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "Constant", { ctermfg = 235, fg = "#24292e" })
hi(0, "CurSearch", { bg = "#b93a86", ctermbg = 162, ctermfg = 255, fg = "#edeff1" })
hi(0, "Cursor", { bg = "#383d42", ctermbg = 237, ctermfg = 231, fg = "#ffffff" })
hi(0, "CursorColumn", { bg = "#edeff1", ctermbg = 255 })
hi(0, "CursorIM", { bg = "#383d42", ctermbg = 237, ctermfg = 231, fg = "#ffffff" })
hi(0, "CursorLine", { bg = "#edeff1", ctermbg = 255 })
hi(0, "CursorLineFold", { bg = "#edeff1", ctermbg = 255, ctermfg = 99, fg = "#8263eb" })
hi(0, "CursorLineNr", { ctermfg = 235, fg = "#24292e" })
hi(0, "CursorLineSign", { bg = "#edeff1", ctermbg = 255, ctermfg = 253, fg = "#d7d9db" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, ctermfg = 54, fg = "#4c2889" })
hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
hi(0, "DapUIBreakpointsInfo", { link = "DiagnosticInfo" })
hi(0, "DapUIBreakpointsPath", { link = "Directory" })
hi(0, "DapUIDecoration", { link = "Title" })
hi(0, "DapUIFloatBorder", { link = "SpecialChar" })
hi(0, "DapUILineNumber", { link = "Title" })
hi(0, "DapUIModifiedValue", { bold = true, ctermfg = 160, fg = "#de2c2e" })
hi(0, "DapUIScope", { link = "Title" })
hi(0, "DapUISource", { link = "Directory" })
hi(0, "DapUIStoppedThread", { link = "Title" })
hi(0, "DapUIThread", { link = "String" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIWatchesEmpty", { link = "ErrorMsg" })
hi(0, "DapUIWatchesError", { link = "DiagnosticError" })
hi(0, "DapUIWatchesValue", { link = "String" })
hi(0, "DashboardCenter", { link = "Delimiter" })
hi(0, "DashboardFooter", { link = "Title" })
hi(0, "DashboardHeader", { link = "Title" })
hi(0, "DashboardShortCut", { link = "WarningMsg" })
hi(0, "Debug", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "Define", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "Definitions", { ctermfg = 54, fg = "#4c2889" })
hi(0, "DefinitionsIcon", { ctermfg = 26, fg = "#005cc5" })
hi(0, "Delimiter", { ctermfg = 25, fg = "#044289" })
hi(0, "DiagnosticError", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "DiagnosticFloatingError", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "DiagnosticFloatingHint", { ctermfg = 99, fg = "#8263eb" })
hi(0, "DiagnosticFloatingInfo", { ctermfg = 23, fg = "#18654b" })
hi(0, "DiagnosticFloatingOk", { ctermfg = 54, fg = "#4c2889" })
hi(0, "DiagnosticFloatingWarn", { ctermfg = 178, fg = "#dbab09" })
hi(0, "DiagnosticHint", { ctermfg = 99, fg = "#8263eb" })
hi(0, "DiagnosticInfo", { ctermfg = 23, fg = "#18654b" })
hi(0, "DiagnosticOk", { ctermfg = 54, fg = "#4c2889" })
hi(0, "DiagnosticSignError", { link = "DiagnosticFloatingError" })
hi(0, "DiagnosticSignHint", { link = "DiagnosticFloatingHint" })
hi(0, "DiagnosticSignInfo", { link = "DiagnosticFloatingInfo" })
hi(0, "DiagnosticSignOk", { link = "DiagnosticFloatingOk" })
hi(0, "DiagnosticSignWarn", { link = "DiagnosticFloatingWarn" })
hi(0, "DiagnosticUnderlineError", { ctermfg = 160, fg = "#de2c2e", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { ctermfg = 99, fg = "#8263eb", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { ctermfg = 23, fg = "#18654b", undercurl = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#4c2889", underline = true })
hi(0, "DiagnosticUnderlineWarn", { ctermfg = 178, fg = "#dbab09", undercurl = true })
hi(0, "DiagnosticWarn", { ctermfg = 178, fg = "#dbab09" })
hi(0, "DiffAdd", { bg = "#edeff1", ctermbg = 255, ctermfg = 54, fg = "#4c2889" })
hi(0, "DiffChange", { bg = "#edeff1", ctermbg = 255, ctermfg = 160, fg = "#de2c2e" })
hi(0, "DiffDelete", { bg = "#edeff1", ctermbg = 255, ctermfg = 55, fg = "#5a32a3" })
hi(0, "DiffText", { bg = "#edeff1", ctermbg = 255, ctermfg = 26, fg = "#005cc5" })
hi(0, "Directory", { ctermfg = 26, fg = "#005cc5" })
hi(0, "EndOfBuffer", { ctermfg = 253, fg = "#d7d9db" })
hi(0, "Error", { bg = "#5a32a3", ctermbg = 55, ctermfg = 231, fg = "#ffffff" })
hi(0, "ErrorMsg", { bg = "#ffffff", ctermbg = 231, ctermfg = 55, fg = "#5a32a3" })
hi(0, "Exception", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "FinderParam", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "FinderSpinner", { ctermfg = 54, fg = "#4c2889" })
hi(0, "FinderSpinnerBorder", { ctermfg = 25, fg = "#044289" })
hi(0, "FinderSpinnerTitle", { link = "Title" })
hi(0, "FinderVirtText", { ctermfg = 162, fg = "#b93a86" })
hi(0, "Float", { ctermfg = 162, fg = "#b93a86" })
hi(0, "FloatBorder", { ctermfg = 32, fg = "#0d7fdd" })
hi(0, "FloatTitle", { bg = "#c7c9cb", ctermbg = 251, ctermfg = 235, fg = "#24292e" })
hi(0, "FoldColumn", {})
hi(0, "Folded", { bg = "#edeff1", ctermbg = 255, ctermfg = 248, fg = "#a6a8aa" })
hi(0, "Function", { ctermfg = 26, fg = "#005cc5" })
hi(0, "GitSignsAdd", { bg = "#edeff1", ctermbg = 255, ctermfg = 54, fg = "#4c2889" })
hi(0, "GitSignsAddInline", { link = "GitSignsAdd" })
hi(0, "GitSignsAddLn", { link = "GitSignsAdd" })
hi(0, "GitSignsChange", { bg = "#edeff1", ctermbg = 255, ctermfg = 160, fg = "#de2c2e" })
hi(0, "GitSignsChangeInline", { link = "GitSignsChange" })
hi(0, "GitSignsChangeLn", { link = "GitSignsChange" })
hi(0, "GitSignsDelete", { bg = "#edeff1", ctermbg = 255, ctermfg = 55, fg = "#5a32a3" })
hi(0, "GitSignsDeleteInline", { link = "GitSignsDelete" })
hi(0, "GitSignsDeleteLn", { link = "GitSignsDelete" })
hi(0, "GitSignsUntracked", { bg = "#edeff1", ctermbg = 255, ctermfg = 26, fg = "#005cc5" })
hi(0, "GitSignsUntrackedInline", { link = "GitSignsUntracked" })
hi(0, "GitSignsUntrackedLn", { link = "GitSignsUntracked" })
hi(0, "HopNextKey", { bold = true, ctermfg = 160, fg = "#de2c2e", nocombine = true })
hi(0, "HopNextKey1", { bold = true, ctermfg = 55, fg = "#5a32a3", nocombine = true })
hi(0, "HopNextKey2", { bold = true, ctermfg = 251, fg = "#c7c9cb", nocombine = true })
hi(0, "HopPreview", { bold = true, ctermfg = 162, fg = "#b93a86", nocombine = true })
hi(0, "HopUnmatched", { link = "Comment" })
hi(0, "HydraAmaranth", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "HydraBlue", { ctermfg = 26, fg = "#005cc5" })
hi(0, "HydraHint", { link = "NormalFloat" })
hi(0, "HydraPink", { ctermfg = 162, fg = "#b93a86" })
hi(0, "HydraRed", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "HydraTeal", { ctermfg = 54, fg = "#4c2889" })
hi(0, "Identifier", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "Ignore", { ctermfg = 99, fg = "#8263eb" })
hi(0, "IncSearch", { bg = "#b93a86", ctermbg = 162, ctermfg = 255, fg = "#edeff1" })
hi(0, "Include", { ctermfg = 26, fg = "#005cc5" })
hi(0, "IndentBlanklineChar", { ctermfg = 254, fg = "#e1e3e5", nocombine = true })
hi(0, "IndentBlanklineContextChar", { ctermfg = 25, fg = "#044289", nocombine = true })
hi(0, "IndentBlanklineContextStart", { nocombine = true, sp = "#044289", underline = true })
hi(0, "IndentBlanklineIndent1", { ctermfg = 55, fg = "#5a32a3", nocombine = true })
hi(0, "IndentBlanklineIndent2", { ctermfg = 162, fg = "#b93a86", nocombine = true })
hi(0, "IndentBlanklineIndent3", { ctermfg = 136, fg = "#b08800", nocombine = true })
hi(0, "IndentBlanklineIndent4", { ctermfg = 54, fg = "#4c2889", nocombine = true })
hi(0, "IndentBlanklineIndent5", { ctermfg = 99, fg = "#8263eb", nocombine = true })
hi(0, "IndentBlanklineIndent6", { ctermfg = 26, fg = "#005cc5", nocombine = true })
hi(0, "IndentBlanklineIndent7", { ctermfg = 160, fg = "#de2c2e", nocombine = true })
hi(0, "IndentBlanklineIndent8", { ctermfg = 25, fg = "#044289", nocombine = true })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "LSOutlinePreviewBorder", { ctermfg = 25, fg = "#044289" })
hi(0, "Label", { ctermfg = 136, fg = "#b08800" })
hi(0, "LazyButton", { bg = "#edeff1", ctermbg = 255 })
hi(0, "LazyButtonActive", { bg = "#e1e3e5", ctermbg = 254 })
hi(0, "LazyDimmed", { link = "Comment" })
hi(0, "LazyH1", { bg = "#e1e3e5", bold = true, ctermbg = 254 })
hi(0, "LeapBackdrop", { link = "Comment" })
hi(0, "LeapLabel", { bold = true, ctermfg = 55, fg = "#5a32a3", nocombine = true })
hi(0, "LeapLabelSelected", { bold = true, ctermfg = 162, fg = "#b93a86", nocombine = true })
hi(0, "LeapMatch", { bold = true, ctermfg = 160, fg = "#de2c2e", nocombine = true, underline = true })
hi(0, "LightspeedCursor", { link = "Cursor" })
hi(0, "LightspeedGreyWash", { link = "Comment" })
hi(0, "LightspeedLabel", { bold = true, ctermfg = 160, fg = "#de2c2e", underline = true })
hi(0, "LightspeedLabelDistant", { bold = true, ctermfg = 26, fg = "#005cc5", underline = true })
hi(0, "LightspeedMaskedChar", { ctermfg = 251, fg = "#c7c9cb" })
hi(0, "LightspeedOneCharMatch", { link = "LightspeedShortcut" })
hi(0, "LightspeedPendingOpArea", { link = "IncSearch" })
hi(0, "LightspeedShortcut", { bold = true, ctermfg = 235, fg = "#24292e" })
hi(0, "LightspeedUniqueChar", { link = "LightspeedUnlabeledMatch" })
hi(0, "LightspeedUnlabeledMatch", { bold = true, ctermfg = 237, fg = "#383d42" })
hi(0, "LineNr", { ctermfg = 251, fg = "#c7c9cb" })
hi(0, "LineNrAbove", { ctermfg = 251, fg = "#c7c9cb" })
hi(0, "LineNrBelow", { ctermfg = 251, fg = "#c7c9cb" })
hi(0, "LspCodeLens", { link = "Comment" })
hi(0, "LspCodeLensSeparator", { link = "Comment" })
hi(0, "LspReferenceText", { bg = "#e1e3e5", ctermbg = 254 })
hi(0, "LspSagaAutoPreview", { ctermfg = 25, fg = "#044289" })
hi(0, "LspSagaBorderTitle", { link = "Title" })
hi(0, "LspSagaCodeActionBorder", { ctermfg = 25, fg = "#044289" })
hi(0, "LspSagaCodeActionContent", { ctermfg = 237, fg = "#383d42" })
hi(0, "LspSagaCodeActionTitle", { bold = true, ctermfg = 26, fg = "#005cc5" })
hi(0, "LspSagaDefPreviewBorder", { ctermfg = 25, fg = "#044289" })
hi(0, "LspSagaDiagnosticBorder", { ctermfg = 25, fg = "#044289" })
hi(0, "LspSagaDiagnosticHeader", { link = "Title" })
hi(0, "LspSagaDiagnosticSource", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "LspSagaFinderSelection", { ctermfg = 136, fg = "#b08800" })
hi(0, "LspSagaHoverBorder", { ctermfg = 25, fg = "#044289" })
hi(0, "LspSagaLspFinderBorder", { ctermfg = 25, fg = "#044289" })
hi(0, "LspSagaRenameBorder", { ctermfg = 25, fg = "#044289" })
hi(0, "LspSagaSignatureHelpBorder", { ctermfg = 25, fg = "#044289" })
hi(0, "LspSignatureActiveParameter", { link = "LspReferenceText" })
hi(0, "Macro", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "MasonError", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "MasonHeader", { bg = "#005cc5", bold = true, ctermbg = 26, ctermfg = 231, fg = "#ffffff" })
hi(0, "MasonHeaderSecondary", { bg = "#044289", bold = true, ctermbg = 25, ctermfg = 231, fg = "#ffffff" })
hi(0, "MasonHeading", { link = "Bold" })
hi(0, "MasonHighlight", { ctermfg = 25, fg = "#044289" })
hi(0, "MasonHighlightBlock", { bg = "#044289", ctermbg = 25, ctermfg = 231, fg = "#ffffff" })
hi(0, "MasonHighlightBlockBold", { link = "MasonHeaderSecondary" })
hi(0, "MasonHighlightBlockBoldSecondary", { link = "MasonHeader" })
hi(0, "MasonHighlightBlockSecondary", { bg = "#005cc5", ctermbg = 26, ctermfg = 231, fg = "#ffffff" })
hi(0, "MasonHighlightSecondary", { ctermfg = 26, fg = "#005cc5" })
hi(0, "MasonLink", { link = "MasonHighlight" })
hi(0, "MasonMuted", { link = "Comment" })
hi(0, "MasonMutedBlock", { bg = "#d7d9db", ctermbg = 253, ctermfg = 231, fg = "#ffffff" })
hi(0, "MasonMutedBlockBold", { bg = "#d7d9db", bold = true, ctermbg = 253, ctermfg = 231, fg = "#ffffff" })
hi(0, "MatchParen", { link = "MatchWord" })
hi(0, "MatchWord", { bg = "#c7c9cb", ctermbg = 251, ctermfg = 235, fg = "#24292e" })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "NormalFloat" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { bg = "#edeff1", bold = true, ctermbg = 255, ctermfg = 26, fg = "#005cc5" })
hi(0, "MiniCompletionActiveParameter", { bg = "#e1e3e5", ctermbg = 254 })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniDepsChangeAdded", { link = "diffAdded" })
hi(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
hi(0, "MiniDepsHint", { link = "DiagnosticHint" })
hi(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
hi(0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
hi(0, "MiniDepsPlaceholder", { link = "Comment" })
hi(0, "MiniDepsTitle", { link = "Title" })
hi(0, "MiniDepsTitleError", { link = "DiffDelete" })
hi(0, "MiniDepsTitleSame", { link = "DiffText" })
hi(0, "MiniDepsTitleUpdate", { link = "DiffAdd" })
hi(0, "MiniDiffSignAdd", { ctermfg = 54, fg = "#4c2889" })
hi(0, "MiniDiffSignChange", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "MiniDiffSignDelete", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "MiniFilesBorder", { link = "NormalFloat" })
hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniFilesCursorLine", { bg = "#e1e3e5", ctermbg = 254 })
hi(0, "MiniFilesDirectory", { link = "Directory" })
hi(0, "MiniFilesFile", { ctermfg = 237, fg = "#383d42" })
hi(0, "MiniFilesNormal", { link = "NormalFloat" })
hi(0, "MiniFilesTitle", { bg = "#edeff1", ctermbg = 255, ctermfg = 26, fg = "#005cc5" })
hi(0, "MiniFilesTitleFocused", { bg = "#edeff1", bold = true, ctermbg = 255, ctermfg = 26, fg = "#005cc5" })
hi(0, "MiniHipatternsFixme", { bg = "#5a32a3", bold = true, ctermbg = 55, ctermfg = 231, fg = "#ffffff" })
hi(0, "MiniHipatternsHack", { bg = "#de2c2e", bold = true, ctermbg = 160, ctermfg = 231, fg = "#ffffff" })
hi(0, "MiniHipatternsNote", { bg = "#005cc5", bold = true, ctermbg = 26, ctermfg = 231, fg = "#ffffff" })
hi(0, "MiniHipatternsTodo", { bg = "#8263eb", bold = true, ctermbg = 99, ctermfg = 231, fg = "#ffffff" })
hi(0, "MiniIconsAzure", { ctermfg = 26, fg = "#0366d6" })
hi(0, "MiniIconsBlue", { ctermfg = 32, fg = "#0d7fdd" })
hi(0, "MiniIconsCyan", { ctermfg = 31, fg = "#0598bc" })
hi(0, "MiniIconsGreen", { ctermfg = 23, fg = "#18654b" })
hi(0, "MiniIconsGrey", { ctermfg = 251, fg = "#c7c9cb" })
hi(0, "MiniIconsOrange", { ctermfg = 166, fg = "#d15704" })
hi(0, "MiniIconsPurple", { ctermfg = 99, fg = "#8263eb" })
hi(0, "MiniIconsRed", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "MiniIconsYellow", { ctermfg = 178, fg = "#dbab09" })
hi(0, "MiniIndentscopeSymbol", { ctermfg = 25, fg = "#044289" })
hi(0, "MiniIndentscopeSymbolOff", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "MiniJump", { link = "SpellRare" })
hi(0, "MiniJump2dDim", { link = "Comment" })
hi(0, "MiniJump2dSpot", { bg = "#edeff1", bold = true, ctermbg = 255, ctermfg = 235, fg = "#24292e", nocombine = true })
hi(0, "MiniJump2dSpotAhead", { bg = "#ffffff", ctermbg = 231, ctermfg = 236, fg = "#2e3338", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { link = "MiniJump2dSpot" })
hi(0, "MiniMapNormal", { bg = "#edeff1", ctermbg = 255, ctermfg = 237, fg = "#383d42" })
hi(0, "MiniMapSymbolCount", { ctermfg = 99, fg = "#8263eb" })
hi(0, "MiniMapSymbolLine", { ctermfg = 26, fg = "#005cc5" })
hi(0, "MiniMapSymbolView", { ctermfg = 25, fg = "#044289" })
hi(0, "MiniNotifyBorder", { link = "NormalFloat" })
hi(0, "MiniNotifyNormal", { link = "NormalFloat" })
hi(0, "MiniNotifyTitle", { link = "FloatTitle" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniPickBorder", { bg = "#f3f5f7", ctermbg = 255, ctermfg = 255, fg = "#f3f5f7" })
hi(0, "MiniPickBorderBusy", { bg = "#f3f5f7", ctermbg = 255, ctermfg = 178, fg = "#dbab09" })
hi(0, "MiniPickBorderText", { bg = "#de2c2e", ctermbg = 160, ctermfg = 231, fg = "#ffffff" })
hi(0, "MiniPickCursor", { blend = 100, nocombine = true })
hi(0, "MiniPickHeader", { bg = "#de2c2e", ctermbg = 160, ctermfg = 231, fg = "#ffffff" })
hi(0, "MiniPickIconDirectory", { link = "Directory" })
hi(0, "MiniPickIconFile", { ctermfg = 237, fg = "#383d42" })
hi(0, "MiniPickMatchCurrent", { bg = "#e1e3e5", ctermbg = 254 })
hi(0, "MiniPickMatchMarked", { bg = "#d7d9db", ctermbg = 253 })
hi(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickNormal", { bg = "#f3f5f7", ctermbg = 255 })
hi(0, "MiniPickPreviewLine", { bg = "#e1e3e5", ctermbg = 254 })
hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
hi(0, "MiniPickPrompt", { bg = "#edeff1", ctermbg = 255, ctermfg = 235, fg = "#24292e" })
hi(0, "MiniStarterFooter", { ctermfg = 26, fg = "#005cc5" })
hi(0, "MiniStarterHeader", { ctermfg = 26, fg = "#005cc5" })
hi(0, "MiniStarterInactive", { link = "Comment" })
hi(0, "MiniStarterItem", { ctermfg = 237, fg = "#383d42" })
hi(0, "MiniStarterItemBullet", { ctermfg = 25, fg = "#044289" })
hi(0, "MiniStarterItemPrefix", { bold = true, ctermfg = 55, fg = "#5a32a3" })
hi(0, "MiniStarterQuery", { bold = true, ctermfg = 54, fg = "#4c2889" })
hi(0, "MiniStarterSection", { ctermfg = 25, fg = "#044289" })
hi(0, "MiniStatuslineDevinfo", { bg = "#e1e3e5", ctermbg = 254, ctermfg = 251, fg = "#c7c9cb" })
hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
hi(0, "MiniStatuslineFilename", { bg = "#edeff1", ctermbg = 255, ctermfg = 253, fg = "#d7d9db" })
hi(0, "MiniStatuslineInactive", { link = "StatusLineNC" })
hi(0, "MiniStatuslineModeCommand", { bg = "#5a32a3", bold = true, ctermbg = 55, ctermfg = 231, fg = "#ffffff" })
hi(0, "MiniStatuslineModeInsert", { bg = "#005cc5", bold = true, ctermbg = 26, ctermfg = 231, fg = "#ffffff" })
hi(0, "MiniStatuslineModeNormal", { bg = "#383d42", bold = true, ctermbg = 237, ctermfg = 231, fg = "#ffffff" })
hi(0, "MiniStatuslineModeOther", { bg = "#d7d9db", bold = true, ctermbg = 253, ctermfg = 231, fg = "#ffffff" })
hi(0, "MiniStatuslineModeReplace", { bg = "#de2c2e", bold = true, ctermbg = 160, ctermfg = 231, fg = "#ffffff" })
hi(0, "MiniStatuslineModeVisual", { bg = "#4c2889", bold = true, ctermbg = 54, ctermfg = 231, fg = "#ffffff" })
hi(0, "MiniSurround", { link = "IncSearch" })
hi(0, "MiniTablineCurrent", { bg = "#e1e3e5", bold = true, ctermbg = 254, ctermfg = 237, fg = "#383d42" })
hi(0, "MiniTablineHidden", { bg = "#edeff1", ctermbg = 255, ctermfg = 251, fg = "#c7c9cb" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#383d42", bold = true, ctermbg = 237, ctermfg = 254, fg = "#e1e3e5" })
hi(0, "MiniTablineModifiedHidden", { bg = "#c7c9cb", ctermbg = 251, ctermfg = 255, fg = "#edeff1" })
hi(0, "MiniTablineModifiedVisible", { bg = "#c7c9cb", bold = true, ctermbg = 251, ctermfg = 254, fg = "#e1e3e5" })
hi(0, "MiniTablineTabpagesection", { bg = "#b08800", bold = true, ctermbg = 136, ctermfg = 255, fg = "#edeff1" })
hi(0, "MiniTablineVisible", { bg = "#edeff1", bold = true, ctermbg = 255, ctermfg = 237, fg = "#383d42" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, ctermfg = 55, fg = "#5a32a3" })
hi(0, "MiniTestPass", { bold = true, ctermfg = 54, fg = "#4c2889" })
hi(0, "MiniTrailspace", { link = "Error" })
hi(0, "ModeMsg", { ctermfg = 54, fg = "#4c2889" })
hi(0, "MoreMsg", { ctermfg = 54, fg = "#4c2889" })
hi(0, "MsgArea", { bg = "#ffffff", ctermbg = 231, ctermfg = 237, fg = "#383d42" })
hi(0, "MsgSeparator", { bg = "#e1e3e5", ctermbg = 254, ctermfg = 251, fg = "#c7c9cb" })
hi(0, "NeoTreeDimText", { ctermfg = 253, fg = "#d7d9db" })
hi(0, "NeoTreeDotfile", { ctermfg = 251, fg = "#c7c9cb" })
hi(0, "NeoTreeFadeText1", { link = "NeoTreeDimText" })
hi(0, "NeoTreeFadeText2", { ctermfg = 254, fg = "#e1e3e5" })
hi(0, "NeoTreeGitAdded", { ctermfg = 54, fg = "#4c2889" })
hi(0, "NeoTreeGitConflict", { bold = true, ctermfg = 55, fg = "#5a32a3" })
hi(0, "NeoTreeGitDeleted", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "NeoTreeGitModified", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "NeoTreeGitUnstaged", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "NeoTreeGitUntracked", { ctermfg = 136, fg = "#b08800" })
hi(0, "NeoTreeMessage", { bg = "#edeff1", ctermbg = 255, ctermfg = 237, fg = "#383d42" })
hi(0, "NeoTreeModified", { ctermfg = 235, fg = "#24292e" })
hi(0, "NeoTreeRootName", { bold = true, ctermfg = 26, fg = "#005cc5" })
hi(0, "NeoTreeTabInactive", { ctermfg = 251, fg = "#c7c9cb" })
hi(0, "NeoTreeTabSeparatorActive", { bg = "#e1e3e5", ctermbg = 254, ctermfg = 253, fg = "#d7d9db" })
hi(0, "NeoTreeTabSeparatorInactive", { bg = "#edeff1", ctermbg = 255, ctermfg = 255, fg = "#edeff1" })
hi(0, "NeogitCommitViewHeader", { link = "Special" })
hi(0, "NeogitDiffAdd", { link = "DiffAdd" })
hi(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
hi(0, "NeogitDiffDelete", { link = "DiffDelete" })
hi(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
hi(0, "NeogitFold", { link = "FoldColumn" })
hi(0, "NeogitHunkHeader", { ctermfg = 26, fg = "#005cc5" })
hi(0, "NeogitHunkHeaderHighlight", { bold = true, ctermfg = 26, fg = "#005cc5" })
hi(0, "NeogitNotificationError", { link = "DiagnosticError" })
hi(0, "NeogitNotificationInfo", { link = "DiagnosticInfo" })
hi(0, "NeogitNotificationWarning", { link = "DiagnosticWarn" })
hi(0, "NoiceCmdlinePopupBorder", { ctermfg = 26, fg = "#005cc5" })
hi(0, "NoiceConfirmBorder", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "NonText", { ctermfg = 253, fg = "#d7d9db" })
hi(0, "Normal", { bg = "#ffffff", ctermbg = 231, ctermfg = 237, fg = "#383d42" })
hi(0, "NormalFloat", { bg = "#f3f5f7", ctermbg = 255 })
hi(0, "NormalNC", { bg = "#ffffff", ctermbg = 231, ctermfg = 237, fg = "#383d42" })
hi(0, "NotifyDEBUGBorder", { ctermfg = 253, fg = "#d7d9db" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyERRORBorder", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
hi(0, "NotifyINFOBorder", { ctermfg = 99, fg = "#8263eb" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
hi(0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
hi(0, "NotifyTRACEBorder", { ctermfg = 26, fg = "#005cc5" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
hi(0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
hi(0, "NotifyWARNBorder", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
hi(0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
hi(0, "Number", { ctermfg = 162, fg = "#b93a86" })
hi(0, "NvimInternalError", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "NvimTreeExecFile", { bold = true, ctermfg = 54, fg = "#4c2889" })
hi(0, "NvimTreeFolderIcon", { ctermfg = 253, fg = "#d7d9db" })
hi(0, "NvimTreeGitDeleted", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "NvimTreeGitDirty", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "NvimTreeGitMerge", { ctermfg = 99, fg = "#8263eb" })
hi(0, "NvimTreeGitNew", { ctermfg = 136, fg = "#b08800" })
hi(0, "NvimTreeGitRenamed", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "NvimTreeGitStaged", { ctermfg = 54, fg = "#4c2889" })
hi(0, "NvimTreeImageFile", { bold = true, ctermfg = 160, fg = "#de2c2e" })
hi(0, "NvimTreeIndentMarker", { link = "NvimTreeFolderIcon" })
hi(0, "NvimTreeOpenedFile", { link = "NvimTreeExecFile" })
hi(0, "NvimTreeRootFolder", { link = "NvimTreeGitRenamed" })
hi(0, "NvimTreeSpecialFile", { bold = true, ctermfg = 26, fg = "#005cc5", underline = true })
hi(0, "NvimTreeSymlink", { bold = true, ctermfg = 25, fg = "#044289" })
hi(0, "NvimTreeWindowPicker", { bg = "#edeff1", bold = true, ctermbg = 255, ctermfg = 237, fg = "#383d42" })
hi(0, "Operator", { ctermfg = 237, fg = "#383d42" })
hi(0, "OutlineDetail", { ctermfg = 253, fg = "#d7d9db" })
hi(0, "OutlineFoldPrefix", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "OutlineIndentEvn", { ctermfg = 251, fg = "#c7c9cb" })
hi(0, "OutlineIndentOdd", { ctermfg = 237, fg = "#383d42" })
hi(0, "Pmenu", { bg = "#eaecee", ctermbg = 255 })
hi(0, "PmenuExtra", { bg = "#edeff1", ctermbg = 255, ctermfg = 237, fg = "#383d42" })
hi(0, "PmenuExtraSel", { bg = "#edeff1", ctermbg = 255, ctermfg = 237, fg = "#383d42", reverse = true })
hi(0, "PmenuKind", { bg = "#edeff1", ctermbg = 255, ctermfg = 237, fg = "#383d42" })
hi(0, "PmenuKindSel", { bg = "#edeff1", ctermbg = 255, ctermfg = 237, fg = "#383d42", reverse = true })
hi(0, "PmenuMatch", { bg = "#edeff1", bold = true, ctermbg = 255, ctermfg = 237, fg = "#383d42" })
hi(0, "PmenuMatchSel", { bg = "#edeff1", bold = true, ctermbg = 255, ctermfg = 237, fg = "#383d42", reverse = true })
hi(0, "PmenuSbar", { bg = "#eaecee", ctermbg = 255 })
hi(0, "PmenuSel", { bg = "#8263eb", ctermbg = 99, ctermfg = 231, fg = "#ffffff" })
hi(0, "PmenuThumb", { bg = "#c7c9cb", ctermbg = 251 })
hi(0, "PounceAccept", { bg = "#5a32a3", bold = true, ctermbg = 55, ctermfg = 231, fg = "#ffffff", nocombine = true })
hi(0, "PounceAcceptBest", { bg = "#4c2889", bold = true, ctermbg = 54, ctermfg = 231, fg = "#ffffff", nocombine = true })
hi(0, "PounceGap", { bg = "#d7d9db", bold = true, ctermbg = 253, ctermfg = 231, fg = "#ffffff", nocombine = true })
hi(0, "PounceMatch", { bg = "#383d42", bold = true, ctermbg = 237, ctermfg = 231, fg = "#ffffff", nocombine = true })
hi(0, "PreCondit", { ctermfg = 136, fg = "#b08800" })
hi(0, "PreProc", { ctermfg = 136, fg = "#b08800" })
hi(0, "Question", { ctermfg = 26, fg = "#005cc5" })
hi(0, "QuickFixLine", { bg = "#edeff1", ctermbg = 255 })
hi(0, "RainbowDelimiterBlue", { ctermfg = 26, fg = "#005cc5" })
hi(0, "RainbowDelimiterCyan", { ctermfg = 99, fg = "#8263eb" })
hi(0, "RainbowDelimiterGreen", { ctermfg = 54, fg = "#4c2889" })
hi(0, "RainbowDelimiterOrange", { ctermfg = 162, fg = "#b93a86" })
hi(0, "RainbowDelimiterRed", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "RainbowDelimiterViolet", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "RainbowDelimiterYellow", { ctermfg = 136, fg = "#b08800" })
hi(0, "References", { ctermfg = 54, fg = "#4c2889" })
hi(0, "ReferencesIcon", { ctermfg = 26, fg = "#005cc5" })
hi(0, "Removed", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "RenderMarkdownH1Bg", { bg = "#ded6ed", ctermbg = 189 })
hi(0, "RenderMarkdownH2Bg", { bg = "#cfe5f8", ctermbg = 254 })
hi(0, "RenderMarkdownH3Bg", { bg = "#d1e0db", ctermbg = 253 })
hi(0, "RenderMarkdownH4Bg", { bg = "#f8eece", ctermbg = 255 })
hi(0, "RenderMarkdownH5Bg", { bg = "#f8d5d5", ctermbg = 224 })
hi(0, "RenderMarkdownH6Bg", { bg = "#f6ddcd", ctermbg = 224 })
hi(0, "Repeat", { ctermfg = 136, fg = "#b08800" })
hi(0, "Search", { bg = "#b08800", ctermbg = 136, ctermfg = 255, fg = "#edeff1" })
hi(0, "SignColumn", { ctermfg = 253, fg = "#d7d9db" })
hi(0, "Sneak", { bg = "#de2c2e", ctermbg = 160, ctermfg = 231, fg = "#ffffff" })
hi(0, "SneakLabel", { bg = "#de2c2e", bold = true, ctermbg = 160, ctermfg = 231, fg = "#ffffff" })
hi(0, "SneakScope", { bg = "#24292e", ctermbg = 235, ctermfg = 231, fg = "#ffffff" })
hi(0, "Special", { ctermfg = 99, fg = "#8263eb" })
hi(0, "SpecialChar", { ctermfg = 25, fg = "#044289" })
hi(0, "SpecialComment", { ctermfg = 99, fg = "#8263eb" })
hi(0, "SpecialKey", { ctermfg = 253, fg = "#d7d9db" })
hi(0, "SpellBad", { sp = "#5a32a3", undercurl = true })
hi(0, "SpellCap", { sp = "#005cc5", undercurl = true })
hi(0, "SpellLocal", { sp = "#8263eb", undercurl = true })
hi(0, "SpellRare", { sp = "#de2c2e", undercurl = true })
hi(0, "Statement", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "StatusLine", { bg = "#edeff1", ctermbg = 255 })
hi(0, "StatusLineNC", { bg = "#edeff1", ctermbg = 255, ctermfg = 253, fg = "#d7d9db" })
hi(0, "StorageClass", { ctermfg = 136, fg = "#b08800" })
hi(0, "String", { ctermfg = 54, fg = "#4c2889" })
hi(0, "Structure", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "Substitute", { bg = "#b08800", ctermbg = 136, ctermfg = 255, fg = "#edeff1" })
hi(0, "TabLine", { bg = "#edeff1", ctermbg = 255, ctermfg = 253, fg = "#d7d9db" })
hi(0, "TabLineFill", { bg = "#edeff1", ctermbg = 255, ctermfg = 253, fg = "#d7d9db" })
hi(0, "TabLineSel", { bg = "#edeff1", ctermbg = 255, ctermfg = 54, fg = "#4c2889" })
hi(0, "Tag", { ctermfg = 35, fg = "#28a745" })
hi(0, "TargetFileName", { ctermfg = 237, fg = "#383d42" })
hi(0, "TelescopeBorder", { ctermfg = 25, fg = "#044289" })
hi(0, "TelescopeMatching", { ctermfg = 136, fg = "#b08800" })
hi(0, "TelescopeMultiSelection", { bg = "#edeff1", bold = true, ctermbg = 255 })
hi(0, "TelescopeSelection", { bg = "#edeff1", bold = true, ctermbg = 255 })
hi(0, "TermCursorNC", { reverse = true })
hi(0, "Title", { ctermfg = 26, fg = "#005cc5" })
hi(0, "Todo", { bg = "#edeff1", ctermbg = 255, ctermfg = 136, fg = "#b08800" })
hi(0, "TooLong", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "TroubleCount", { bold = true, ctermfg = 54, fg = "#4c2889" })
hi(0, "TroubleFoldIcon", { ctermfg = 237, fg = "#383d42" })
hi(0, "TroubleIndent", { ctermfg = 254, fg = "#e1e3e5" })
hi(0, "TroubleLocation", { ctermfg = 251, fg = "#c7c9cb" })
hi(0, "TroubleSignError", { link = "DiagnosticError" })
hi(0, "TroubleSignHint", { link = "DiagnosticHint" })
hi(0, "TroubleSignInformation", { link = "DiagnosticInfo" })
hi(0, "TroubleSignOther", { link = "DiagnosticInfo" })
hi(0, "TroubleSignWarning", { link = "DiagnosticWarn" })
hi(0, "TroubleText", { ctermfg = 237, fg = "#383d42" })
hi(0, "TroubleTextError", { link = "TroubleText" })
hi(0, "TroubleTextHint", { link = "TroubleText" })
hi(0, "TroubleTextInformation", { link = "TroubleText" })
hi(0, "TroubleTextWarning", { link = "TroubleText" })
hi(0, "Type", { ctermfg = 136, fg = "#b08800" })
hi(0, "Typedef", { ctermfg = 136, fg = "#b08800" })
hi(0, "VertSplit", { bg = "#e1e3e5", ctermbg = 254, ctermfg = 254, fg = "#e1e3e5" })
hi(0, "Visual", { bg = "#e1e3e5", ctermbg = 254 })
hi(0, "VisualNOS", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "WarningMsg", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "WhichKey", { ctermfg = 26, fg = "#005cc5" })
hi(0, "WhichKeyDesc", { ctermfg = 237, fg = "#383d42" })
hi(0, "WhichKeyFloat", { bg = "#edeff1", ctermbg = 255, ctermfg = 237, fg = "#383d42" })
hi(0, "WhichKeyGroup", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "WhichKeySeparator", { bg = "#edeff1", ctermbg = 255, ctermfg = 54, fg = "#4c2889" })
hi(0, "WhichKeyValue", { ctermfg = 253, fg = "#d7d9db" })
hi(0, "Whitespace", { ctermfg = 253, fg = "#d7d9db" })
hi(0, "WildMenu", { bg = "#b08800", ctermbg = 136, ctermfg = 55, fg = "#5a32a3" })
hi(0, "WinBar", {})
hi(0, "WinBarNC", {})
hi(0, "WinSeparator", { ctermfg = 255, fg = "#eaecee" })
hi(0, "diffAdded", { ctermfg = 54, fg = "#4c2889" })
hi(0, "diffChanged", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "diffFile", { ctermfg = 162, fg = "#b93a86" })
hi(0, "diffLine", { ctermfg = 99, fg = "#8263eb" })
hi(0, "diffRemoved", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "gitcommitBranch", { bold = true, ctermfg = 162, fg = "#b93a86" })
hi(0, "gitcommitComment", { link = "Comment" })
hi(0, "gitcommitDiscarded", { link = "Comment" })
hi(0, "gitcommitDiscardedFile", { bold = true, ctermfg = 55, fg = "#5a32a3" })
hi(0, "gitcommitDiscardedType", { ctermfg = 26, fg = "#005cc5" })
hi(0, "gitcommitHeader", { ctermfg = 160, fg = "#de2c2e" })
hi(0, "gitcommitOverflow", { ctermfg = 55, fg = "#5a32a3" })
hi(0, "gitcommitSelected", { link = "Comment" })
hi(0, "gitcommitSelectedFile", { bold = true, ctermfg = 54, fg = "#4c2889" })
hi(0, "gitcommitSelectedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitSummary", { ctermfg = 54, fg = "#4c2889" })
hi(0, "gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
hi(0, "gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitUntracked", { link = "Comment" })
hi(0, "gitcommitUntrackedFile", { ctermfg = 136, fg = "#b08800" })
hi(0, "healthSuccess", { bg = "#18654b", ctermbg = 23, ctermfg = 231, fg = "#ffffff" })
hi(0, "lCursor", { bg = "#383d42", ctermbg = 237, ctermfg = 231, fg = "#ffffff" })
hi(0, "markdownDelimiter", { ctermfg = 255, fg = "#eaecee" })
hi(0, "markdownH1", { bold = true, ctermfg = 55, fg = "#5a32a3" })
hi(0, "markdownH1Delimiter", { link = "markdownH1" })
hi(0, "markdownH2", { bold = true, ctermfg = 32, fg = "#0d7fdd" })
hi(0, "markdownH2Delimiter", { link = "markdownH2" })
hi(0, "markdownH3", { bold = true, ctermfg = 23, fg = "#18654b" })
hi(0, "markdownH3Delimiter", { link = "markdownH3" })
hi(0, "markdownH4", { bold = true, ctermfg = 178, fg = "#dbab09" })
hi(0, "markdownH4Delimiter", { link = "markdownH4" })
hi(0, "markdownH5", { bold = true, ctermfg = 160, fg = "#de2c2e" })
hi(0, "markdownH5Delimiter", { link = "markdownH5" })
hi(0, "markdownH6", { bold = true, ctermfg = 166, fg = "#d15704" })
hi(0, "markdownH6Delimiter", { link = "markdownH6" })
hi(0, "markdownLinkText", { link = "markdownUrl" })
hi(0, "markdownUrl", { ctermfg = 55, fg = "#5a32a3", sp = "#5a32a3", underline = true })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#ffffff"
g.terminal_color_1 = "#5a32a3"
g.terminal_color_2 = "#4c2889"
g.terminal_color_3 = "#b08800"
g.terminal_color_4 = "#005cc5"
g.terminal_color_5 = "#de2c2e"
g.terminal_color_6 = "#8263eb"
g.terminal_color_7 = "#383d42"
g.terminal_color_8 = "#d7d9db"
g.terminal_color_9 = "#5a32a3"
g.terminal_color_10 = "#4c2889"
g.terminal_color_11 = "#b08800"
g.terminal_color_12 = "#005cc5"
g.terminal_color_13 = "#de2c2e"
g.terminal_color_14 = "#8263eb"
g.terminal_color_15 = "#24292e"
