-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then
	vim.cmd("highlight clear")
end
vim.g.colors_name = "grei"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@constructor", { ctermfg = 159, fg = "#86deff" })
hi(0, "@function", { ctermfg = 204, fg = "#af9dff" })
hi(0, "@function.call", { ctermfg = 159, fg = "#86deff" })
hi(0, "@keyword.operator", { ctermfg = 122, fg = "#c0eeff" })
hi(0, "@markup", { link = "Title" })
hi(0, "@markup.emphasis", { italic = true })
hi(0, "@markup.link", { ctermfg = 141, fg = "#cbbfff" })
hi(0, "@markup.link.uri", { ctermfg = 159, fg = "#86deff" })
hi(0, "@markup.list.checked", { ctermfg = 252, fg = "#8985b1" })
hi(0, "@markup.list.unchecked", { bold = true, ctermfg = 121, fg = "#94e2ff" })
hi(0, "@markup.raw", { ctermfg = 122, fg = "#c0eeff" })
hi(0, "@module", { ctermfg = 141, fg = "#cbbfff" })
hi(0, "@punctuation.bracket", { ctermfg = 122, fg = "#c0eeff" })
hi(0, "@string.escape", { ctermfg = 122, fg = "#c0eeff" })
hi(0, "@string.special", { ctermfg = 135, fg = "#a993ff" })
hi(0, "@string.special.symbol", { ctermfg = 228, fg = "#bdf4e0" })
hi(0, "@symbol", { ctermfg = 228, fg = "#bdf4e0" })
hi(0, "@tag", { link = "Keyword" })
hi(0, "@tag.attribute", { link = "Constant" })
hi(0, "@tag.delimiter", { link = "Special" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.literal", { ctermfg = 122, fg = "#c0eeff" })
hi(0, "@text.reference", { ctermfg = 141, fg = "#cbbfff" })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.todo.checked", { ctermfg = 252, fg = "#8985b1" })
hi(0, "@text.todo.unchecked", { bold = true, ctermfg = 121, fg = "#94e2ff" })
hi(0, "@text.uri", { ctermfg = 159, fg = "#86deff" })
hi(0, "@variable", { fg = "#e0e0ed" })
hi(0, "@variable.builtin", { ctermfg = 122, fg = "#c0eeff" })
hi(0, "Added", { ctermfg = 10, fg = "#abf2d6" })
hi(0, "Boolean", { ctermfg = 215, fg = "#43deb0" })
hi(0, "Changed", { ctermfg = 14, fg = "#afeaff" })
hi(0, "CmpItemAbbrDefault", { fg = "#cfe1e9" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#8985b1" })
hi(0, "CmpItemAbbrMatch", { ctermfg = 141, fg = "#cbbfff" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#cfe1e9" })
hi(0, "CmpItemAbbrMatchFuzzy", { ctermfg = 228, fg = "#bdf4e0" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#cfe1e9" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { fg = "#c0eeff" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { link = "CmpItemKindDefault" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { link = "CmpItemKindFunction" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { link = "PreProc" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { link = "CmpItemKindDefault" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { link = "Constant" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { link = "CmpItemKindModule" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { link = "Comment" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { link = "Comment" })
hi(0, "CmpItemMenuDefault", { fg = "#cfe1e9" })
hi(0, "ColorColumn", { bg = "#282e3b", ctermbg = 233 })
hi(0, "Comment", { ctermfg = 252, fg = "#8985b1", italic = true })
hi(0, "Conceal", { ctermfg = 253, fg = "#cfe1e9" })
hi(0, "Constant", { ctermfg = 141, fg = "#cbbfff" })
hi(0, "CurSearch", { bg = "#f9e19e", ctermbg = 11, ctermfg = 0, fg = "#050713" })
hi(0, "Cursor", { bg = "#e3c2f8", ctermbg = 159, ctermfg = 236, fg = "#584f7f" })
hi(0, "CursorColumn", { bg = "#09121c", ctermbg = 232 })
hi(0, "CursorLine", { bg = "#09121c", ctermbg = 232 })
hi(0, "CursorLineNr", { bg = "#09121c", bold = true, ctermbg = 232, ctermfg = 159, fg = "#86deff" })
hi(0, "Delimiter", { fg = "#e0e0ed" })
hi(0, "DiagnosticDeprecated", { sp = "#ade1bc", strikethrough = true })
hi(0, "DiagnosticError", { bg = "#09121c", ctermbg = 232, ctermfg = 204, fg = "#af9dff" })
hi(0, "DiagnosticFloatingError", { link = "DiagnosticSignError" })
hi(0, "DiagnosticFloatingHint", { link = "DiagnosticSignHint" })
hi(0, "DiagnosticFloatingInfo", { link = "DiagnosticSignInfo" })
hi(0, "DiagnosticFloatingWarn", { link = "DiagnosticSignWarn" })
hi(0, "DiagnosticHint", { bg = "#09121c", ctermbg = 232, ctermfg = 141, fg = "#cbbfff" })
hi(0, "DiagnosticInfo", { bg = "#09121c", ctermbg = 232, ctermfg = 159, fg = "#86deff" })
hi(0, "DiagnosticOk", { ctermfg = 10, fg = "#abf2d6" })
hi(0, "DiagnosticSignError", { ctermfg = 204, fg = "#af9dff" })
hi(0, "DiagnosticSignHint", { ctermfg = 141, fg = "#cbbfff" })
hi(0, "DiagnosticSignInfo", { ctermfg = 159, fg = "#86deff" })
hi(0, "DiagnosticSignWarn", { ctermfg = 228, fg = "#bdf4e0" })
hi(0, "DiagnosticUnderlineError", { undercurl = true })
hi(0, "DiagnosticUnderlineHint", { undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { undercurl = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#ffd5cc", underline = true })
hi(0, "DiagnosticUnderlineWarn", { undercurl = true })
hi(0, "DiagnosticWarn", { bg = "#09121c", ctermbg = 232, ctermfg = 228, fg = "#bdf4e0" })
hi(0, "DiffAdd", { bg = "#322846", ctermbg = 119 })
hi(0, "DiffAdded", { ctermfg = 120, fg = "#95edcb" })
hi(0, "DiffChange", { bg = "#282e3b", ctermbg = 233 })
hi(0, "DiffDelete", { bg = "#083335", ctermbg = 203, ctermfg = 236, fg = "#422988" })
hi(0, "DiffFile", { bold = true, ctermfg = 145, fg = "#e4e4e4" })
hi(0, "DiffIndexLine", { bold = true, ctermfg = 145, fg = "#e4e4e4" })
hi(0, "DiffRemoved", { ctermfg = 204, fg = "#af9dff" })
hi(0, "DiffText", { bg = "#1a2942", ctermbg = 215 })
hi(0, "Directory", { ctermfg = 141, fg = "#cbbfff" })
hi(0, "Error", { bg = "#09121c", bold = true, ctermbg = 232, ctermfg = 203, fg = "#8a73e5" })
hi(0, "ErrorMsg", { ctermfg = 203, fg = "#8a73e5" })
hi(0, "Float", { ctermfg = 215, fg = "#43deb0" })
hi(0, "FloatBorder", { link = "WinSeparator" })
hi(0, "FloatShadow", { bg = "#525252", blend = 80, ctermbg = 0 })
hi(0, "FloatShadowThrough", { bg = "#525252", blend = 100, ctermbg = 0 })
hi(0, "FoldColumn", { ctermfg = 75, fg = "#8c67ff" })
hi(0, "Folded", { ctermfg = 75, fg = "#8c67ff" })
hi(0, "Function", { ctermfg = 204, fg = "#af9dff" })
hi(0, "FzfLuaPreviewTitle", { bg = "#9cd4fb", ctermbg = 141, ctermfg = 232, fg = "#13082e" })
hi(0, "FzfLuaScrollFloatEmpty", { bg = "#4d576b", ctermbg = 236 })
hi(0, "FzfLuaScrollFloatFull", { bg = "#97a0f5", ctermbg = 135 })
hi(0, "FzfLuaTitle", { bg = "#ffcdd2", ctermbg = 120, ctermfg = 232, fg = "#13082e" })
hi(0, "GitSignsAdd", { ctermfg = 120, fg = "#95edcb" })
hi(0, "GitSignsAddInline", { bg = "#ffcdd2", ctermbg = 120, ctermfg = 232, fg = "#13082e" })
hi(0, "GitSignsAddLn", { ctermfg = 119, fg = "#75e6be" })
hi(0, "GitSignsAddLnInline", { bg = "#ffcdd2", ctermbg = 120, ctermfg = 232, fg = "#13082e" })
hi(0, "GitSignsAddPreview", { bg = "#282e3b", ctermbg = 233, ctermfg = 120, fg = "#95edcb" })
hi(0, "GitSignsChange", { ctermfg = 228, fg = "#bdf4e0" })
hi(0, "GitSignsChangeDelete", { ctermfg = 215, fg = "#43deb0" })
hi(0, "GitSignsChangeInline", { bg = "#f7e9b7", ctermbg = 228, ctermfg = 232, fg = "#13082e" })
hi(0, "GitSignsChangeLn", { ctermfg = 228, fg = "#bdf4e0" })
hi(0, "GitSignsChangeLnInline", { bg = "#f7e9b7", ctermbg = 228, ctermfg = 232, fg = "#13082e" })
hi(0, "GitSignsChangeNr", { ctermfg = 215, fg = "#43deb0" })
hi(0, "GitSignsDelete", { ctermfg = 204, fg = "#af9dff" })
hi(0, "GitSignsDeleteInline", { bg = "#58c9b7", ctermbg = 204, ctermfg = 232, fg = "#13082e" })
hi(0, "GitSignsDeleteLnInline", { bg = "#58c9b7", ctermbg = 204, ctermfg = 232, fg = "#13082e" })
hi(0, "GitSignsDeletePreview", { bg = "#282e3b", ctermbg = 233, ctermfg = 204, fg = "#af9dff" })
hi(0, "GitSignsDeleteVirtLn", { bg = "#282e3b", ctermbg = 233, ctermfg = 204, fg = "#af9dff" })
hi(0, "GitSignsUntracked", { ctermfg = 159, fg = "#86deff" })
hi(0, "Identifier", { ctermfg = 141, fg = "#cbbfff" })
hi(0, "Ignore", { ctermfg = 233, fg = "#1d1c31" })
hi(0, "IncSearch", { bg = "#f7e9b7", ctermbg = 228, ctermfg = 233, fg = "#1d1c31" })
hi(0, "Keyword", { link = "@function" })
hi(0, "Label", { ctermfg = 135, fg = "#a993ff" })
hi(0, "LineNr", { ctermfg = 236, fg = "#584f7f" })
hi(0, "MatchParen", { bg = "#09121c", bold = true, ctermbg = 232, ctermfg = 141, fg = "#cbbfff", underline = true })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniDiffSignAdd_stl", { fg = "#abf2d6" })
hi(0, "MiniDiffSignChange_stl", { fg = "#afeaff" })
hi(0, "MiniDiffSignDelete", { link = "GitSignsDelete" })
hi(0, "MiniDiffSignDelete_stl", { fg = "#af9dff" })
hi(0, "MiniDiffSignsAdd", { link = "GitSignsAdd" })
hi(0, "MiniDiffSignsChange", { link = "GitSignsChange" })
hi(0, "MiniIndentscopeSymbol", { ctermfg = 145, fg = "#e4e4e4" })
hi(0, "ModeMsg", { bold = true, ctermfg = 252, fg = "#8985b1" })
hi(0, "MoreMsg", { link = "ModeMsg" })
hi(0, "NonText", { ctermfg = 236, fg = "#584f7f" })
-- hi(0, "Normal", { bg = "#172028", ctermbg = 233, ctermfg = 253, fg = "#cfe1e9" })
-- hi(0, "Normal", { bg = "#0f0f0f", ctermbg = 233, ctermfg = 253, fg = "#cfe1e9" })
hi(0, "Normal", { bg = "#1e1e2e", ctermbg = 233, ctermfg = 253, fg = "#cfe1e9" })
hi(0, "NormalFloat", { bg = "#080808" })
hi(0, "Number", { ctermfg = 215, fg = "#43deb0" })
hi(0, "NvimInternalError", { bg = "#00a44c", ctermbg = 9, ctermfg = 9, fg = "#8c67ff" })
hi(0, "NvimTreeFolderIcon", { ctermfg = 141, fg = "#cbbfff" })
hi(0, "NvimTreeFolderName", { ctermfg = 159, fg = "#86deff" })
hi(0, "NvimTreeRootFolder", { ctermfg = 120, fg = "#95edcb" })
hi(0, "Operator", { ctermfg = 121, fg = "#94e2ff" })
hi(0, "Pmenu", { bg = "#282e3b", ctermbg = 233, ctermfg = 253, fg = "#cfe1e9" })
hi(0, "PmenuSbar", { bg = "#09121c", ctermbg = 232, ctermfg = 253, fg = "#cfe1e9" })
hi(0, "PmenuSel", { bg = "#172028", ctermbg = 233, ctermfg = 141, fg = "#cbbfff" })
hi(0, "PmenuThumb", { bg = "#9099ce", ctermbg = 236, ctermfg = 253, fg = "#cfe1e9" })
hi(0, "PreProc", { ctermfg = 120, fg = "#95edcb" })
hi(0, "Question", { ctermfg = 120, fg = "#95edcb" })
hi(0, "QuickFixLine", { ctermfg = 14, fg = "#afeaff" })
hi(0, "RedrawDebugClear", { bg = "#685514", ctermbg = 11, ctermfg = 0 })
hi(0, "RedrawDebugComposed", { bg = "#722c22", ctermbg = 10, ctermfg = 0 })
hi(0, "RedrawDebugRecompose", { bg = "#00361b", ctermbg = 9, ctermfg = 0 })
hi(0, "Removed", { ctermfg = 9, fg = "#ccc1ff" })
hi(0, "Search", { bg = "#bccc8a", ctermbg = 215, ctermfg = 233, fg = "#1d1c31" })
hi(0, "SignColumn", { ctermfg = 120, fg = "#95edcb" })
hi(0, "Special", { ctermfg = 122, fg = "#c0eeff" })
hi(0, "SpecialKey", { ctermfg = 159, fg = "#86deff" })
hi(0, "SpellBad", { ctermfg = 203, fg = "#8a73e5", undercurl = true })
hi(0, "SpellCap", { ctermfg = 120, fg = "#95edcb", underline = true })
hi(0, "SpellLocal", { ctermfg = 119, fg = "#75e6be", underline = true })
hi(0, "SpellRare", { ctermfg = 204, fg = "#af9dff", underline = true })
hi(0, "Statement", { ctermfg = 120, fg = "#95edcb" })
hi(0, "StatusLine", { bg = "#9099ce", ctermbg = 236, ctermfg = 232, fg = "#13082e" })
hi(0, "StatusLineNC", { bg = "#09121c", ctermbg = 232, ctermfg = 252, fg = "#8985b1" })
hi(0, "String", { ctermfg = 228, fg = "#bdf4e0" })
hi(0, "TabLine", { bg = "#172028", ctermbg = 233, ctermfg = 252, fg = "#8985b1" })
hi(0, "TabLineFill", { bg = "#172028", ctermbg = 233, ctermfg = 252, fg = "#8985b1" })
hi(0, "TabLineSel", { bg = "#2c425b", bold = true, ctermbg = 236, ctermfg = 253, fg = "#cfe1e9" })
-- hi(0, "TelescopeBorder", { link = "LineNr" })
-- hi(0, "TelescopeMatching", { link = "String" })
-- hi(0, "TelescopeNormal", { ctermfg = 252, fg = "#8985b1" })
-- hi(0, "TelescopePreviewBorder", { bg = "#8b8b8b", ctermbg = 252, ctermfg = 252, fg = "#8985b1" })
-- hi(0, "TelescopePreviewNormal", { bg = "#8b8b8b", ctermbg = 252 })
-- hi(0, "TelescopePreviewTitle", { ctermfg = 252, fg = "#8985b1" })
-- hi(0, "TelescopePromptBorder", { bg = "#4d576b", ctermbg = 236, ctermfg = 236, fg = "#584f7f" })
-- hi(0, "TelescopePromptCounter", { bold = true, ctermfg = 120, fg = "#95edcb" })
-- hi(0, "TelescopePromptNormal", { bg = "#4d576b", ctermbg = 236 })
-- hi(0, "TelescopePromptPrefix", { bg = "#4d576b", ctermbg = 236 })
-- hi(0, "TelescopePromptTitle", { bg = "#4d576b", ctermbg = 236, ctermfg = 236, fg = "#584f7f" })
-- hi(0, "TelescopeResultsBorder", { bg = "#282e3b", ctermbg = 233, ctermfg = 233, fg = "#2e2a47" })
-- hi(0, "TelescopeResultsDiffAdd", { ctermfg = 120, fg = "#95edcb" })
-- hi(0, "TelescopeResultsDiffChange", { ctermfg = 228, fg = "#bdf4e0" })
-- hi(0, "TelescopeResultsDiffDelete", { ctermfg = 204, fg = "#af9dff" })
-- hi(0, "TelescopeResultsDiffUntracked", { link = "Title" })
-- hi(0, "TelescopeResultsNormal", { bg = "#282e3b", ctermbg = 233 })
-- hi(0, "TelescopeResultsTitle", { bg = "#282e3b", ctermbg = 233, ctermfg = 233, fg = "#2e2a47" })
-- hi(0, "TelescopeSelection", { bg = "#4d576b", ctermbg = 236 })
hi(0, "Terminal", { bg = "#09121c", ctermbg = 232, ctermfg = 253, fg = "#cfe1e9" })
hi(0, "Title", { ctermfg = 135, fg = "#a993ff" })
hi(0, "Todo", { bg = "#172028", bold = true, ctermbg = 233, ctermfg = 215, fg = "#43deb0" })
hi(0, "Type", { ctermfg = 141, fg = "#cbbfff" })
hi(0, "Underlined", { ctermfg = 121, fg = "#94e2ff", underline = true })
hi(0, "Visual", { bg = "#2c425b", ctermbg = 236 })
hi(0, "WarningMsg", { ctermfg = 228, fg = "#bdf4e0" })
hi(0, "WildMenu", { bg = "#ffd8f0", ctermbg = 122, ctermfg = 232, fg = "#13082e" })
hi(0, "WinBar", { bg = "#080808", bold = true, fg = "#9c99bf" })
hi(0, "WinBarNC", { bg = "#080808", fg = "#9c99bf" })
hi(0, "WinSeparator", { ctermfg = 236, fg = "#422988" })
hi(0, "diffFileId", { bold = true, ctermfg = 159, fg = "#86deff", reverse = true })
hi(0, "diffLine", { ctermfg = 141, fg = "#cbbfff" })
hi(0, "diffNewFile", { bold = true, ctermfg = 145, fg = "#e4e4e4" })
hi(0, "diffNoEOL", { ctermfg = 141, fg = "#cbbfff" })
hi(0, "diffOldFile", { bold = true, ctermfg = 145, fg = "#e4e4e4" })
hi(0, "diffSubname", { ctermfg = 145, fg = "#e4e4e4" })
hi(0, "elixirAtom", { ctermfg = 228, fg = "#bdf4e0" })
hi(0, "elixirVariable", { ctermfg = 141, fg = "#cbbfff" })
hi(0, "gitcommitBranch", { ctermfg = 141, fg = "#cbbfff" })
hi(0, "gitcommitComment", { ctermfg = 252, fg = "#8985b1" })
hi(0, "gitcommitDiscarded", { link = "gitcommitComment" })
hi(0, "gitcommitDiscardedArrow", { link = "gitcommitDiscardedFile" })
hi(0, "gitcommitDiscardedFile", { ctermfg = 204, fg = "#af9dff" })
hi(0, "gitcommitDiscardedType", { ctermfg = 204, fg = "#af9dff" })
hi(0, "gitcommitNoBranch", { link = "gitcommitBranch" })
hi(0, "gitcommitOverflow", { ctermfg = 204, fg = "#af9dff" })
hi(0, "gitcommitSelected", { link = "gitcommitComment" })
hi(0, "gitcommitSelectedArrow", { link = "gitcommitSelectedFile" })
hi(0, "gitcommitSelectedFile", { ctermfg = 120, fg = "#95edcb" })
hi(0, "gitcommitSelectedType", { ctermfg = 120, fg = "#95edcb" })
hi(0, "gitcommitSummary", { ctermfg = 145, fg = "#e4e4e4" })
hi(0, "gitcommitUnmerged", { ctermfg = 120, fg = "#95edcb" })
hi(0, "gitcommitUnmergedArrow", { link = "gitcommitUnmergedFile" })
hi(0, "gitcommitUnmergedFile", { ctermfg = 228, fg = "#bdf4e0" })
hi(0, "gitcommitUntracked", { link = "gitcommitComment" })
hi(0, "gitcommitUntrackedFile", { ctermfg = 122, fg = "#c0eeff" })
hi(0, "htmlBold", { bold = true })
hi(0, "htmlBoldItalic", { bold = true, italic = true })
hi(0, "htmlEndTag", { link = "htmlTag" })
hi(0, "htmlH1", { bold = true, ctermfg = 135, fg = "#a993ff" })
hi(0, "htmlH2", { bold = true, ctermfg = 135, fg = "#a993ff" })
hi(0, "htmlH3", { ctermfg = 159, fg = "#86deff", italic = true })
hi(0, "htmlH4", { ctermfg = 159, fg = "#86deff", italic = true })
hi(0, "htmlH5", { ctermfg = 121, fg = "#94e2ff" })
hi(0, "htmlH6", { ctermfg = 121, fg = "#94e2ff" })
hi(0, "htmlItalic", { italic = true })
hi(0, "htmlLink", { ctermfg = 159, fg = "#86deff", underline = true })
hi(0, "htmlTag", { link = "Special" })
hi(0, "htmlTagN", { link = "Keyword" })
hi(0, "htmlTagName", { link = "Keyword" })
hi(0, "jsAsyncKeyword", { link = "PreProc" })
hi(0, "jsClassDefinition", { link = "Type" })
hi(0, "jsClassKeyword", { ctermfg = 141, fg = "#cbbfff" })
hi(0, "jsConditional", { link = "PreProc" })
hi(0, "jsExtendsKeyword", { link = "PreProc" })
hi(0, "jsForAwait", { link = "PreProc" })
hi(0, "jsRepeat", { link = "PreProc" })
hi(0, "jsReturn", { link = "PreProc" })
hi(0, "jsxClosePunct", { link = "jsxOpenPunct" })
hi(0, "jsxOpenPunct", { ctermfg = 252, fg = "#8985b1" })
hi(0, "lCursor", { bg = "#e4dae4", fg = "#1d1c31" })
hi(0, "markdownBlockquote", { ctermfg = 252, fg = "#8985b1" })
hi(0, "markdownBold", { bold = true, ctermfg = 253, fg = "#cfe1e9" })
hi(0, "markdownBoldItalic", { bold = true, ctermfg = 253, fg = "#cfe1e9", italic = true })
hi(0, "markdownCode", { ctermfg = 120, fg = "#95edcb" })
hi(0, "markdownCodeDelimiter", { ctermfg = 252, fg = "#8985b1" })
hi(0, "markdownEscape", { ctermfg = 253, fg = "#cfe1e9" })
hi(0, "markdownH1", { bold = true, ctermfg = 135, fg = "#a993ff" })
hi(0, "markdownH2", { bold = true, ctermfg = 135, fg = "#a993ff" })
hi(0, "markdownH3", { bold = true, ctermfg = 135, fg = "#a993ff", italic = true })
hi(0, "markdownH4", { bold = true, ctermfg = 135, fg = "#a993ff", italic = true })
hi(0, "markdownH5", { ctermfg = 121, fg = "#94e2ff" })
hi(0, "markdownH6", { ctermfg = 121, fg = "#94e2ff" })
hi(0, "markdownHeadingDelimiter", { ctermfg = 253, fg = "#cfe1e9" })
hi(0, "markdownHeadingRule", { ctermfg = 253, fg = "#cfe1e9" })
hi(0, "markdownId", { ctermfg = 252, fg = "#8985b1" })
hi(0, "markdownIdDeclaration", { ctermfg = 252, fg = "#8985b1" })
hi(0, "markdownItalic", { ctermfg = 253, fg = "#cfe1e9", italic = true })
hi(0, "markdownLinkDelimiter", { ctermfg = 252, fg = "#8985b1" })
hi(0, "markdownLinkText", { ctermfg = 253, fg = "#cfe1e9" })
hi(0, "markdownLinkTextDelimiter", { ctermfg = 252, fg = "#8985b1" })
hi(0, "markdownListMarker", { ctermfg = 204, fg = "#af9dff" })
hi(0, "markdownOrderedListMarker", { ctermfg = 204, fg = "#af9dff" })
hi(0, "markdownRule", { ctermfg = 253, fg = "#cfe1e9" })
hi(0, "markdownUrl", { ctermfg = 135, fg = "#a993ff", underline = true })
hi(0, "markdownUrlDelimiter", { ctermfg = 252, fg = "#8985b1" })
hi(0, "markdownUrlTitle", { ctermfg = 253, fg = "#cfe1e9" })
hi(0, "markdownUrlTitleDelimiter", { ctermfg = 252, fg = "#8985b1" })
hi(0, "xmlEndTag", { link = "xmlTag" })
hi(0, "xmlTag", { link = "htmlTag" })
hi(0, "xmlTagName", { link = "htmlTagName" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#3f5a74"
g.terminal_color_1 = "#32cdb7"
g.terminal_color_2 = "#ffc8d0"
g.terminal_color_3 = "#f7e9b3"
g.terminal_color_4 = "#e5c1fc"
g.terminal_color_5 = "#95d4ff"
g.terminal_color_6 = "#ffd8f1"
g.terminal_color_7 = "#112032"
g.terminal_color_8 = "#3f5a74"
g.terminal_color_9 = "#00a080"
g.terminal_color_10 = "#ffb6c0"
g.terminal_color_11 = "#bacd84"
g.terminal_color_12 = "#969ffe"
g.terminal_color_13 = "#3e84ff"
g.terminal_color_14 = "#ffbfe7"
g.terminal_color_15 = "#7d8d9e"
