-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then
	vim.cmd("highlight clear")
end
vim.g.colors_name = "ice-cave"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { fg = "#b48ead" })
hi(0, "@attribute.builtin", {})
hi(0, "@boolean", { bold = true, fg = "#81a1c1" })
hi(0, "@character", { fg = "#a3be8c", italic = true })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment", { fg = "#616e88", italic = true })
hi(0, "@comment.danger", { bold = true, fg = "#ed333b" })
hi(0, "@comment.danger.comment", { bold = true, fg = "#ed333b" })
hi(0, "@comment.error", { bold = true, fg = "#ed333b" })
hi(0, "@comment.error.comment", { bold = true, fg = "#ed333b" })
hi(0, "@comment.note", { bold = true, fg = "#e2e7e8" })
hi(0, "@comment.note.comment", { bold = true, fg = "#e2e7e8" })
hi(0, "@comment.todo", { bold = true, fg = "#a2c4ff" })
hi(0, "@comment.todo.comment", { bold = true, fg = "#a2c4ff" })
hi(0, "@comment.warning", { bold = true, fg = "#e8a63b" })
hi(0, "@comment.warning.comment", { bold = true, fg = "#e8a63b" })
hi(0, "@conditional", { fg = "#81a1c1", italic = true })
hi(0, "@constant", { fg = "#ebcb8b" })
hi(0, "@constant.builtin", { fg = "#c3a4b3" })
hi(0, "@constant.macro", { bold = true, fg = "#8fbcbb" })
hi(0, "@constructor", { fg = "#81a1c1" })
hi(0, "@diff.delta", { link = "Changed" })
hi(0, "@diff.minus", { link = "Removed" })
hi(0, "@diff.plus", { link = "Added" })
hi(0, "@error", { fg = "#bf616a" })
hi(0, "@exception", { fg = "#b48ead" })
hi(0, "@field", { fg = "#d8dee9", italic = true })
hi(0, "@float", { fg = "#b48ead" })
hi(0, "@function", { fg = "#88c0d0", italic = true })
hi(0, "@function.builtin", { fg = "#88c0d0", italic = true })
hi(0, "@function.call", { bg = "#1e2124", fg = "#e2e7e8" })
hi(0, "@funtion.macro", { fg = "#8fbcbb" })
hi(0, "@include", { fg = "#81a1c1" })
hi(0, "@keyword", { fg = "#81a1c1", italic = true })
hi(0, "@keyword.function", { fg = "#88c0d0", italic = true })
hi(0, "@keyword.operator", { fg = "#88c0d0", italic = true })
hi(0, "@keyword.return", { fg = "#88c0d0", italic = true })
hi(0, "@label", { fg = "#b48ead" })
hi(0, "@lsp.mod.deprecated", {})
hi(0, "@lsp.type.class", {})
hi(0, "@lsp.type.comment", {})
hi(0, "@lsp.type.decorator", {})
hi(0, "@lsp.type.enum", {})
hi(0, "@lsp.type.enumMember", {})
hi(0, "@lsp.type.event", {})
hi(0, "@lsp.type.function", {})
hi(0, "@lsp.type.interface", {})
hi(0, "@lsp.type.keyword", {})
hi(0, "@lsp.type.macro", {})
hi(0, "@lsp.type.method", {})
hi(0, "@lsp.type.modifier", {})
hi(0, "@lsp.type.namespace", {})
hi(0, "@lsp.type.number", {})
hi(0, "@lsp.type.operator", {})
hi(0, "@lsp.type.parameter", {})
hi(0, "@lsp.type.property", {})
hi(0, "@lsp.type.regexp", {})
hi(0, "@lsp.type.string", {})
hi(0, "@lsp.type.struct", {})
hi(0, "@lsp.type.type", {})
hi(0, "@lsp.type.typeParameter", {})
hi(0, "@lsp.type.variable", {})
hi(0, "@markup.environment.latex", { bg = "#24292e" })
hi(0, "@markup.heading", { fg = "#a2c4ff" })
hi(0, "@markup.heading.1.latex", { fg = "#b3c3a4" })
hi(0, "@markup.heading.2.latex", { fg = "#b3c3a4" })
hi(0, "@markup.heading.3.latex", { fg = "#b3c3a4" })
hi(0, "@markup.heading.4.latex", { fg = "#b3c3a4" })
hi(0, "@markup.link", { link = "Underlined" })
hi(0, "@markup.link.label.markdown_inline", { fg = "#b3c3a4" })
hi(0, "@markup.link.latex", { fg = "#8391a7" })
hi(0, "@markup.link.markdown_inline", {})
hi(0, "@markup.link.url.markdown_inline", { fg = "#8391a7", underline = true })
hi(0, "@markup.quote.markdown", { fg = "#4c555c" })
hi(0, "@markup.raw.block", { bg = "#24292e" })
hi(0, "@markup.raw.delimiter.markdown", { fg = "#4c555c" })
hi(0, "@markup.raw.markdown_inline", { bg = "#24292e" })
hi(0, "@method", { fg = "#88c0d0", italic = true })
hi(0, "@method.call", { bg = "#1e2124", fg = "#e2e7e8" })
hi(0, "@module.builtin", {})
hi(0, "@module.latex", { fg = "#a2c4ff" })
hi(0, "@namespace", { fg = "#a2c4ff" })
hi(0, "@number", { fg = "#b48ead" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@operator", { fg = "#81a1c1" })
hi(0, "@parameter", { fg = "#5e81ac" })
hi(0, "@property", { fg = "#8391a7" })
hi(0, "@punctuation", {})
hi(0, "@punctuation.bracket", { fg = "#88c0d0" })
hi(0, "@punctuation.delimiter", { fg = "#88c0d0" })
hi(0, "@punctuation.special", { fg = "#88c0d0" })
hi(0, "@punctuation.special.latex", { fg = "#a2c4ff" })
hi(0, "@repeat", { fg = "#81a1c1", italic = true })
hi(0, "@string", { fg = "#a3be8c", italic = true })
hi(0, "@string.documentation", { fg = "#4c555c" })
hi(0, "@string.escape", { fg = "#4b8b51" })
hi(0, "@string.regex", { fg = "#4b8b51" })
hi(0, "@string.regexp", { fg = "#4b8b51" })
hi(0, "@string.special", { fg = "#4b8b51" })
hi(0, "@string.special.url", { link = "Underlined" })
hi(0, "@symbol", { fg = "#b48ead" })
hi(0, "@tag", { fg = "#d8dee9" })
hi(0, "@tag.builtin", {})
hi(0, "@tag.delimiter", { fg = "#b48ead" })
hi(0, "@text", { fg = "#d8dee9" })
hi(0, "@text.emphasis", { fg = "#5e81ac", italic = true })
hi(0, "@text.literal", { bg = "#1e2124", fg = "#e2e7e8" })
hi(0, "@text.math", { fg = "#8fbcbb" })
hi(0, "@text.reference", { fg = "#b3c3a4" })
hi(0, "@text.strike", { fg = "#d8dee9", strikethrough = true })
hi(0, "@text.strong", { bold = true, fg = "#5e81ac" })
hi(0, "@text.title", { bold = true, fg = "#5e81ac" })
hi(0, "@text.underline", { fg = "#d8dee9", underline = true })
hi(0, "@text.uri", { fg = "#8391a7", underline = true })
hi(0, "@type", { fg = "#81a1c1" })
hi(0, "@type.builtin", { fg = "#81a1c1" })
hi(0, "@variable", { bold = true, fg = "#d8dee9" })
hi(0, "@variable.builtin", { bold = true, fg = "#d8dee9" })
hi(0, "@variable.global", { bold = true, fg = "#d8dee9" })
hi(0, "@variable.parameter.builtin", {})
hi(0, "AerialArray", { fg = "#ebcb8b" })
hi(0, "AerialArrayIcon", { fg = "#ebcb8b" })
hi(0, "AerialBoolean", { bold = true, fg = "#81a1c1" })
hi(0, "AerialBooleanIcon", { bold = true, fg = "#81a1c1" })
hi(0, "AerialClass", { fg = "#81a1c1" })
hi(0, "AerialClassIcon", { fg = "#81a1c1" })
hi(0, "AerialConstant", { fg = "#ebcb8b" })
hi(0, "AerialConstantIcon", { fg = "#ebcb8b" })
hi(0, "AerialConstructor", { fg = "#81a1c1" })
hi(0, "AerialConstructorIcon", { fg = "#81a1c1" })
hi(0, "AerialEnum", { fg = "#81a1c1" })
hi(0, "AerialEnumIcon", { fg = "#81a1c1" })
hi(0, "AerialEnumMember", { fg = "#d8dee9" })
hi(0, "AerialEnumMemberIcon", { fg = "#d8dee9" })
hi(0, "AerialEvent", { fg = "#81a1c1" })
hi(0, "AerialEventIcon", { fg = "#81a1c1" })
hi(0, "AerialField", { fg = "#d8dee9" })
hi(0, "AerialFieldIcon", { fg = "#d8dee9" })
hi(0, "AerialFile", { fg = "#a3be8c" })
hi(0, "AerialFileIcon", { fg = "#a3be8c" })
hi(0, "AerialFunction", { fg = "#88c0d0" })
hi(0, "AerialFunctionIcon", { fg = "#88c0d0" })
hi(0, "AerialInterface", { fg = "#81a1c1" })
hi(0, "AerialInterfaceIcon", { fg = "#81a1c1" })
hi(0, "AerialKey", { fg = "#81a1c1" })
hi(0, "AerialKeyIcon", { fg = "#81a1c1" })
hi(0, "AerialLine", { bg = "#434c5e" })
hi(0, "AerialLineNC", { bg = "#434c5e" })
hi(0, "AerialMethod", { fg = "#8fbcbb" })
hi(0, "AerialMethodIcon", { fg = "#8fbcbb" })
hi(0, "AerialModule", { fg = "#d8dee9" })
hi(0, "AerialModuleIcon", { fg = "#d8dee9" })
hi(0, "AerialNamespace", { fg = "#d8dee9" })
hi(0, "AerialNamespaceIcon", { fg = "#d8dee9" })
hi(0, "AerialNull", { fg = "#81a1c1" })
hi(0, "AerialNullIcon", { fg = "#81a1c1" })
hi(0, "AerialNumber", { fg = "#b48ead" })
hi(0, "AerialNumberIcon", { fg = "#b48ead" })
hi(0, "AerialObject", { fg = "#81a1c1" })
hi(0, "AerialObjectIcon", { fg = "#81a1c1" })
hi(0, "AerialOperator", { fg = "#81a1c1" })
hi(0, "AerialOperatorIcon", { fg = "#81a1c1" })
hi(0, "AerialPackage", { fg = "#d8dee9" })
hi(0, "AerialPackageIcon", { fg = "#d8dee9" })
hi(0, "AerialProperty", { fg = "#5e81ac" })
hi(0, "AerialPropertyIcon", { fg = "#5e81ac" })
hi(0, "AerialString", { fg = "#a3be8c" })
hi(0, "AerialStringIcon", { fg = "#a3be8c" })
hi(0, "AerialStruct", { fg = "#81a1c1" })
hi(0, "AerialStructIcon", { fg = "#81a1c1" })
hi(0, "AerialTypeParameter", { fg = "#5e81ac" })
hi(0, "AerialTypeParameterIcon", { fg = "#5e81ac" })
hi(0, "AerialVariable", { bold = true, fg = "#d8dee9" })
hi(0, "AerialVariableIcon", { bold = true, fg = "#d8dee9" })
hi(0, "BufferCurrent", { bg = "#3b4252" })
hi(0, "BufferCurrentIcon", { bg = "#3b4252" })
hi(0, "BufferCurrentIndex", { bg = "#3b4252" })
hi(0, "BufferCurrentMod", { bg = "#3b4252", fg = "#b48ead" })
hi(0, "BufferCurrentSign", { bg = "#3b4252" })
hi(0, "BufferCurrentTarget", { bg = "#3b4252", fg = "#bf616a" })
hi(0, "BufferInactive", { bg = "#2e3440", fg = "#4c566a" })
hi(0, "BufferInactiveIcon", { bg = "#2e3440", fg = "#4c566a" })
hi(0, "BufferInactiveIndex", { bg = "#2e3440", fg = "#4c566a" })
hi(0, "BufferInactiveMod", { bg = "#2e3440", fg = "#b48ead" })
hi(0, "BufferInactiveSign", { bg = "#2e3440", fg = "#4c566a" })
hi(0, "BufferInactiveTarget", { bg = "#2e3440", fg = "#bf616a" })
hi(0, "BufferTabpageFill", { bg = "#2e3440" })
hi(0, "BufferVisible", { bg = "#434c5e" })
hi(0, "BufferVisibleIcon", { bg = "#434c5e" })
hi(0, "BufferVisibleIndex", { bg = "#434c5e" })
hi(0, "BufferVisibleMod", { bg = "#434c5e", fg = "#b48ead" })
hi(0, "BufferVisibleSign", { bg = "#434c5e" })
hi(0, "BufferVisibleTarget", { bg = "#434c5e", fg = "#bf616a" })
hi(0, "Character", { fg = "#b3c3a4" })
hi(0, "CmpItemAbbr", { fg = "#d8dee9" })
hi(0, "CmpItemAbbrDefault", { fg = "#777d85" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#4c555c" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#e5e9f0" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#777d85" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#e5e9f0" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#777d85" })
hi(0, "CmpItemKind", { fg = "#b48ead" })
hi(0, "CmpItemKindClassDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindColorDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindConstantDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindConstructorDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindEnumDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindEnumMemberDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindEventDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindFieldDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindFileDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindFolderDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindFunctionDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindInterfaceDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindKeywordDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindMethodDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindModuleDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindOperatorDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindPropertyDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindReferenceDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindSnippetDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindStructDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindTextDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindTypeParameterDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindUnitDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindValueDefault", { fg = "#b48ead" })
hi(0, "CmpItemKindVariableDefault", { fg = "#b48ead" })
hi(0, "CmpItemMenu", { fg = "#a3be8c" })
hi(0, "CmpItemMenuDefault", { fg = "#777d85" })
hi(0, "CodeBlock", { bg = "#3b4252" })
hi(0, "ColInLineDiagnostic", { fg = "#4c555c" })
hi(0, "ColorColumn", {})
hi(0, "CommandMode", { fg = "#d8dee9", reverse = true })
hi(0, "Comment", { fg = "#4c555c" })
hi(0, "Conceal", { bg = "#1e2124", fg = "#e2e7e8" })
hi(0, "Constant", { fg = "#c3a4b3" })
hi(0, "CopilotLabel", { fg = "#4c566a" })
hi(0, "CurSearch", { bg = "#e26d5c", fg = "#1e2124" })
hi(0, "Cursor", { bg = "#ed333b" })
hi(0, "CursorColumn", { bg = "#3b4252" })
hi(0, "CursorIM", { fg = "#e5e9f0", reverse = true })
hi(0, "CursorLine", { bg = "#24292e" })
hi(0, "CursorLineNr", { bg = "#1e2124", fg = "#e2e7e8" })
hi(0, "DapBreakpoint", { fg = "#a3be8c" })
hi(0, "DapStopped", { fg = "#b48ead" })
hi(0, "DapUIBreakpointsCurrentLine", { fg = "#88c0d0" })
hi(0, "DapUIBreakpointsInfo", { fg = "#88c0d0" })
hi(0, "DapUIBreakpointsLine", { fg = "#88c0d0" })
hi(0, "DapUIBreakpointsPath", { fg = "#88c0d0" })
hi(0, "DapUIDecoration", { fg = "#88c0d0" })
hi(0, "DapUIFloatBorder", { fg = "#88c0d0" })
hi(0, "DapUIFrameName", { fg = "#d8dee9" })
hi(0, "DapUILineNumber", { fg = "#88c0d0" })
hi(0, "DapUIModifiedValue", { fg = "#88c0d0" })
hi(0, "DapUIScope", { fg = "#88c0d0" })
hi(0, "DapUISource", { fg = "#81a1c1" })
hi(0, "DapUIStoppedThread", { fg = "#88c0d0" })
hi(0, "DapUIThread", { fg = "#88c0d0" })
hi(0, "DapUIType", { fg = "#81a1c1" })
hi(0, "DapUIValue", { fg = "#d8dee9" })
hi(0, "DapUIVariable", { fg = "#d8dee9" })
hi(0, "DapUIWatchesEmpty", { fg = "#bf616a" })
hi(0, "DapUIWatchesError", { fg = "#bf616a" })
hi(0, "DapUIWatchesValue", { fg = "#88c0d0" })
hi(0, "DashboardCenter", { fg = "#88c0d0" })
hi(0, "DashboardFooter", { fg = "#a3be8c", italic = true })
hi(0, "DashboardHeader", { fg = "#81a1c1" })
hi(0, "DashboardShortCut", { fg = "#8fbcbb" })
hi(0, "Debug", { fg = "#bf616a" })
hi(0, "DefinitionArrow", { fg = "#88c0d0" })
hi(0, "DefinitionBorder", { bg = "#2e3440", fg = "#d8dee9" })
hi(0, "DefinitionCount", { fg = "#5e81ac" })
hi(0, "DefinitionFile", { bg = "#2e3440", fg = "#d8dee9" })
hi(0, "DefinitionIcon", { fg = "#8fbcbb" })
hi(0, "DefinitionSearch", { bg = "#e2b05c", fg = "#1e2124" })
hi(0, "Definitions", { fg = "#b48ead" })
hi(0, "DefinitionsIcon", { fg = "#81a1c1" })
hi(0, "Delimiter", { bg = "#1e2124", fg = "#e2e7e8" })
hi(0, "DiagnosticError", { fg = "#ed333b" })
hi(0, "DiagnosticFloatingError", { fg = "#bf616a" })
hi(0, "DiagnosticFloatingHint", { fg = "#81a1c1" })
hi(0, "DiagnosticFloatingInfo", { fg = "#5e81ac" })
hi(0, "DiagnosticFloatingWarn", { fg = "#b48ead" })
hi(0, "DiagnosticHint", { fg = "#e2e7e8" })
hi(0, "DiagnosticInfo", { fg = "#a2c4ff" })
hi(0, "DiagnosticInformation", { fg = "#5e81ac" })
hi(0, "DiagnosticLineCol", { fg = "#d8dee9" })
hi(0, "DiagnosticMap", { fg = "#b48ead" })
hi(0, "DiagnosticOk", { fg = "#4b8b51" })
hi(0, "DiagnosticQuickFix", { fg = "#a3be8c" })
hi(0, "DiagnosticSignError", { bg = "#1e2124", fg = "#ed333b" })
hi(0, "DiagnosticSignHint", { bg = "#1e2124", fg = "#e2e7e8" })
hi(0, "DiagnosticSignInfo", { bg = "#1e2124", fg = "#a2c4ff" })
hi(0, "DiagnosticSignOk", { bg = "#1e2124", fg = "#4b8b51" })
hi(0, "DiagnosticSignWarn", { bg = "#1e2124", fg = "#e8a63b" })
hi(0, "DiagnosticTruncateLine", { fg = "#d8dee9" })
hi(0, "DiagnosticUnderlineError", { sp = "#c92b32", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#c0c4c5", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#89a6d8", undercurl = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#3f7644", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#c58d32", undercurl = true })
hi(0, "DiagnosticUnnecessary", { fg = "#4c555c", undercurl = true })
hi(0, "DiagnosticVirtualTextError", { fg = "#ed333b" })
hi(0, "DiagnosticVirtualTextHint", { fg = "#e2e7e8" })
hi(0, "DiagnosticVirtualTextInfo", { fg = "#a2c4ff" })
hi(0, "DiagnosticVirtualTextOk", { fg = "#4b8b51" })
hi(0, "DiagnosticVirtualTextWarn", { fg = "#e8a63b" })
hi(0, "DiagnosticWarn", { fg = "#e8a63b" })
hi(0, "DiagnosticWarning", { fg = "#b48ead" })
hi(0, "DiffAdd", { bg = "#162918", fg = "#e2e7e8" })
hi(0, "DiffChange", { bg = "#333f6a", fg = "#e2e7e8" })
hi(0, "DiffDelete", { bg = "#470f11", fg = "#e2e7e8" })
hi(0, "DiffText", { bg = "#566ab1", fg = "#e2e7e8" })
hi(0, "Directory", { fg = "#a2c4ff" })
hi(0, "Error", { fg = "#ed333b" })
hi(0, "ErrorMsg", { fg = "#ed333b" })
hi(0, "FernBranchText", { fg = "#616e88" })
hi(0, "FinderParam", { fg = "#b48ead" })
hi(0, "FinderPreviewSearch", { bg = "#e2b05c", fg = "#1e2124" })
hi(0, "FinderSpinner", { fg = "#88c0d0" })
hi(0, "FinderSpinnerBorder", { bg = "#2e3440", fg = "#d8dee9" })
hi(0, "FinderSpinnerTitle", { fg = "#a2c4ff" })
hi(0, "FloatBorder", { bg = "#1b1d20", fg = "#36393e" })
hi(0, "FloatTitle", { bg = "#1b1d20", fg = "#a2c4ff" })
hi(0, "FoldColumn", { fg = "#40484e" })
hi(0, "Folded", { fg = "#40484e" })
hi(0, "Function", { fg = "#a2c4ff" })
hi(0, "GitGutterAdd", { fg = "#a3be8c" })
hi(0, "GitGutterChange", { fg = "#ebcb8b" })
hi(0, "GitGutterDelete", { fg = "#bf616a" })
hi(0, "GitSignsAdd", { fg = "#a3be8c" })
hi(0, "GitSignsAddLn", { fg = "#a3be8c" })
hi(0, "GitSignsAddNr", { fg = "#a3be8c" })
hi(0, "GitSignsChange", { fg = "#ebcb8b" })
hi(0, "GitSignsChangeLn", { fg = "#ebcb8b" })
hi(0, "GitSignsChangeNr", { fg = "#ebcb8b" })
hi(0, "GitSignsCurrentLineBlame", { bold = true, fg = "#616e88" })
hi(0, "GitSignsDelete", { fg = "#bf616a" })
hi(0, "GitSignsDeleteLn", { fg = "#bf616a" })
hi(0, "GitSignsDeleteNr", { fg = "#bf616a" })
hi(0, "Headline1", { bg = "#3d3c44", fg = "#d08770" })
hi(0, "Headline2", { bg = "#3f4247", fg = "#ebcb8b" })
hi(0, "Headline3", { bg = "#394147", fg = "#a3be8c" })
hi(0, "Headline4", { bg = "#363e4c", fg = "#81a1c1" })
hi(0, "Headline5", { bg = "#3a3c4a", fg = "#b48ead" })
hi(0, "Headline6", { bg = "#3d434f", fg = "#d8dee9" })
hi(0, "HopNextKey", { bold = true, fg = "#d8dee9" })
hi(0, "HopNextKey1", { bold = true, fg = "#88c0d0" })
hi(0, "HopNextKey2", { fg = "#d8dee9" })
hi(0, "HopUnmatched", { fg = "#4c566a" })
hi(0, "Identifier", { bg = "#1e2124", fg = "#e2e7e8" })
hi(0, "Ignore", { fg = "#3b4252" })
hi(0, "IlluminatedWordRead", { bg = "#4c566a" })
hi(0, "IlluminatedWordText", { bg = "#4c566a" })
hi(0, "IlluminatedWordWrite", { bg = "#4c566a" })
hi(0, "Implements", { fg = "#b48ead" })
hi(0, "ImplementsCount", { fg = "#5e81ac" })
hi(0, "ImplementsIcon", { fg = "#81a1c1" })
hi(0, "IncSearch", { bg = "#e2b05c", fg = "#1e2124" })
hi(0, "IndentBlanklineChar", { fg = "#4c566a" })
hi(0, "IndentBlanklineContextChar", { fg = "#5e81ac" })
hi(0, "InsertMode", { fg = "#a3be8c", reverse = true })
hi(0, "Keyword", { fg = "#8391a7" })
hi(0, "LSOutlinePreviewBorder", { bg = "#2e3440", fg = "#d8dee9" })
hi(0, "Label", { link = "Conditional" })
hi(0, "LeapLabelPrimary", { bg = "#ebcb8b", fg = "#2e3440", nocombine = true })
hi(0, "LeapLabelSecondary", { bg = "#b48ead", fg = "#2e3440", nocombine = true })
hi(0, "LeapMatch", { fg = "#ebcb8b", nocombine = true, underline = true })
hi(0, "LightspeedGreyWash", { fg = "#616e88" })
hi(0, "LightspeedLabel", { bold = true, fg = "#88c0d0" })
hi(0, "LightspeedLabelDistant", { bold = true, fg = "#b48ead" })
hi(0, "LightspeedLabelDistantOverlapped", { bold = true, fg = "#b48ead", underline = true })
hi(0, "LightspeedLabelOverlapped", { bold = true, fg = "#88c0d0", underline = true })
hi(0, "LightspeedMaskedChar", { bg = "#434c5e", bold = true, fg = "#d8dee9" })
hi(0, "LightspeedOneCharMatch", { bold = true, fg = "#88c0d0", reverse = true })
hi(0, "LightspeedShortcut", { bold = true, fg = "#5e81ac" })
hi(0, "LightspeedShortcutOverlapped", { bold = true, fg = "#5e81ac", underline = true })
hi(0, "LightspeedUniqueChar", { bold = true, underline = true })
hi(0, "LightspeedUnlabeledMatch", { bg = "#3b4252", fg = "#d8dee9" })
hi(0, "LineNr", { fg = "#40484e" })
hi(0, "LspDiagnosticsDefaultError", { fg = "#bf616a" })
hi(0, "LspDiagnosticsDefaultHint", { fg = "#81a1c1" })
hi(0, "LspDiagnosticsDefaultInformation", { fg = "#5e81ac" })
hi(0, "LspDiagnosticsDefaultWarning", { fg = "#b48ead" })
hi(0, "LspDiagnosticsError", { fg = "#d08770" })
hi(0, "LspDiagnosticsFloatingError", { fg = "#bf616a" })
hi(0, "LspDiagnosticsFloatingHint", { fg = "#81a1c1" })
hi(0, "LspDiagnosticsFloatingInformation", { fg = "#5e81ac" })
hi(0, "LspDiagnosticsFloatingWarning", { fg = "#b48ead" })
hi(0, "LspDiagnosticsHint", { fg = "#81a1c1" })
hi(0, "LspDiagnosticsInformation", { fg = "#5e81ac" })
hi(0, "LspDiagnosticsSignError", { fg = "#bf616a" })
hi(0, "LspDiagnosticsSignHint", { fg = "#81a1c1" })
hi(0, "LspDiagnosticsSignInformation", { fg = "#5e81ac" })
hi(0, "LspDiagnosticsSignWarning", { fg = "#b48ead" })
hi(0, "LspDiagnosticsUnderlineError", { sp = "#bf616a", undercurl = true })
hi(0, "LspDiagnosticsUnderlineHint", { sp = "#5e81ac", undercurl = true })
hi(0, "LspDiagnosticsUnderlineInformation", { sp = "#5e81ac", undercurl = true })
hi(0, "LspDiagnosticsUnderlineWarning", { sp = "#b48ead", undercurl = true })
hi(0, "LspDiagnosticsVirtualTextError", { fg = "#bf616a" })
hi(0, "LspDiagnosticsVirtualTextHint", { fg = "#81a1c1" })
hi(0, "LspDiagnosticsVirtualTextInformation", { fg = "#5e81ac" })
hi(0, "LspDiagnosticsVirtualTextWarning", { fg = "#b48ead" })
hi(0, "LspDiagnosticsWarning", { fg = "#b48ead" })
hi(0, "LspFloatWinBorder", { bg = "#2e3440", fg = "#d8dee9" })
hi(0, "LspFloatWinNormal", { bg = "#2e3440", fg = "#d8dee9" })
hi(0, "LspReferenceRead", { bg = "#3b4252", fg = "#d8dee9" })
hi(0, "LspReferenceText", { bg = "#3b4252", fg = "#d8dee9" })
hi(0, "LspReferenceWrite", { bg = "#3b4252", fg = "#d8dee9" })
hi(0, "LspSagaAutoPreview", { fg = "#d8dee9" })
hi(0, "LspSagaBorderTitle", { fg = "#a2c4ff" })
hi(0, "LspSagaCodeActionBorder", { bg = "#2e3440", fg = "#d8dee9" })
hi(0, "LspSagaCodeActionContent", { fg = "#d8dee9" })
hi(0, "LspSagaCodeActionTitle", { fg = "#a2c4ff" })
hi(0, "LspSagaCodeActionTrunCateLine", { bg = "#2e3440", fg = "#d8dee9" })
hi(0, "LspSagaDefPreviewBorder", { bg = "#2e3440", fg = "#d8dee9" })
hi(0, "LspSagaDiagnosticBorder", { bg = "#2e3440", fg = "#d8dee9" })
hi(0, "LspSagaDiagnosticError", { fg = "#ed333b" })
hi(0, "LspSagaDiagnosticHeader", { fg = "#d8dee9" })
hi(0, "LspSagaDiagnosticHint", { fg = "#e2e7e8" })
hi(0, "LspSagaDiagnosticInfo", { fg = "#a2c4ff" })
hi(0, "LspSagaDiagnosticSource", { fg = "#4c555c" })
hi(0, "LspSagaDiagnosticTruncateLine", { bg = "#2e3440", fg = "#d8dee9" })
hi(0, "LspSagaDiagnosticWarn", { fg = "#e8a63b" })
hi(0, "LspSagaErrorTrunCateLine", { fg = "#ed333b" })
hi(0, "LspSagaFinderSelection", { bg = "#434c5e", fg = "#eceff4" })
hi(0, "LspSagaHintTrunCateLine", { fg = "#e2e7e8" })
hi(0, "LspSagaHoverBorder", { bg = "#2e3440", fg = "#d8dee9" })
hi(0, "LspSagaHoverTrunCateLine", { bg = "#2e3440", fg = "#d8dee9" })
hi(0, "LspSagaInfoTrunCateLine", { fg = "#a2c4ff" })
hi(0, "LspSagaLightBulb", { bg = "#1e2124", fg = "#e2e7e8" })
hi(0, "LspSagaLspFinderBorder", { bg = "#2e3440", fg = "#d8dee9" })
hi(0, "LspSagaRenameBorder", { bg = "#2e3440", fg = "#d8dee9" })
hi(0, "LspSagaRenameMatch", { bg = "#81a1c1", fg = "#eceff4" })
hi(0, "LspSagaShTrunCateLine", { bg = "#2e3440", fg = "#d8dee9" })
hi(0, "LspSagaSignatureHelpBorder", { bg = "#2e3440", fg = "#d8dee9" })
hi(0, "LspSagaWarnTrunCateLine", { fg = "#e8a63b" })
hi(0, "LspSignatureActiveParameter", { sp = "#d4dbdd", underline = true })
hi(0, "LspTroubleCount", { bg = "#5e81ac", fg = "#81a1c1" })
hi(0, "LspTroubleNormal", { bg = "#2e3440", fg = "#d8dee9" })
hi(0, "LspTroubleText", { fg = "#d8dee9" })
hi(0, "MatchParen", { bg = "#2b3237", fg = "#e2b05c" })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniCursorword", { bg = "#4c566a" })
hi(0, "MiniCursorwordCurrent", { bg = "#4c566a" })
hi(0, "MiniDiffSignAdd_stl", { fg = "#b3f6c0" })
hi(0, "MiniDiffSignChange_stl", { fg = "#8cf8f7" })
hi(0, "MiniDiffSignDelete_stl", { fg = "#ffc0b9" })
hi(0, "MiniHipatterns141617", { bg = "#141617", fg = "#ffffff" })
hi(0, "MiniHipatterns191b1c", { bg = "#191b1c", fg = "#ffffff" })
hi(0, "MiniHipatterns1d2021", { bg = "#1d2021", fg = "#ffffff" })
hi(0, "MiniHipatterns292929", { bg = "#292929", fg = "#ffffff" })
hi(0, "MiniHipatterns404040", { bg = "#404040", fg = "#ffffff" })
hi(0, "MiniHipatterns45707a", { bg = "#45707a", fg = "#ffffff" })
hi(0, "MiniHipatterns4c7a5d", { bg = "#4c7a5d", fg = "#ffffff" })
hi(0, "MiniHipatterns4d4d4d", { bg = "#4d4d4d", fg = "#ffffff" })
hi(0, "MiniHipatterns595959", { bg = "#595959", fg = "#ffffff" })
hi(0, "MiniHipatterns654735", { bg = "#654735", fg = "#ffffff" })
hi(0, "MiniHipatterns6c782e", { bg = "#6c782e", fg = "#ffffff" })
hi(0, "MiniHipatterns73503c", { bg = "#73503c", fg = "#ffffff" })
hi(0, "MiniHipatterns7daea3", { bg = "#7daea3", fg = "#000000" })
hi(0, "MiniHipatterns805942", { bg = "#805942", fg = "#ffffff" })
hi(0, "MiniHipatterns89b482", { bg = "#89b482", fg = "#000000" })
hi(0, "MiniHipatterns8c6249", { bg = "#8c6249", fg = "#ffffff" })
hi(0, "MiniHipatterns8c856d", { bg = "#8c856d", fg = "#000000" })
hi(0, "MiniHipatterns928374", { bg = "#928374", fg = "#000000" })
hi(0, "MiniHipatterns945e80", { bg = "#945e80", fg = "#ffffff" })
hi(0, "MiniHipatternsa69d81", { bg = "#a69d81", fg = "#000000" })
hi(0, "MiniHipatternsa89984", { bg = "#a89984", fg = "#000000" })
hi(0, "MiniHipatternsa9b665", { bg = "#a9b665", fg = "#000000" })
hi(0, "MiniHipatternsb47109", { bg = "#b47109", fg = "#000000" })
hi(0, "MiniHipatternsbdae93", { bg = "#bdae93", fg = "#000000" })
hi(0, "MiniHipatternsbfb695", { bg = "#bfb695", fg = "#000000" })
hi(0, "MiniHipatternsc14a4a", { bg = "#c14a4a", fg = "#000000" })
hi(0, "MiniHipatternsc35e0a", { bg = "#c35e0a", fg = "#000000" })
hi(0, "MiniHipatternsd1c7a3", { bg = "#d1c7a3", fg = "#000000" })
hi(0, "MiniHipatternsd3869b", { bg = "#d3869b", fg = "#000000" })
hi(0, "MiniHipatternsd5c4a1", { bg = "#d5c4a1", fg = "#000000" })
hi(0, "MiniHipatternsd8a657", { bg = "#d8a657", fg = "#000000" })
hi(0, "MiniHipatternse3dec3", { bg = "#e3dec3", fg = "#000000" })
hi(0, "MiniHipatternse78a4e", { bg = "#e78a4e", fg = "#000000" })
hi(0, "MiniHipatternse8e3c8", { bg = "#e8e3c8", fg = "#000000" })
hi(0, "MiniHipatternsea6962", { bg = "#ea6962", fg = "#000000" })
hi(0, "MiniHipatternsebdbb2", { bg = "#ebdbb2", fg = "#000000" })
hi(0, "MiniHipatternsf0ebce", { bg = "#f0ebce", fg = "#000000" })
hi(0, "MiniHipatternsf9f5d7", { bg = "#f9f5d7", fg = "#000000" })
hi(0, "MiniIndentscopePrefix", { nocombine = true })
hi(0, "MiniIndentscopeSymbol", { fg = "#5e81ac" })
hi(0, "MiniJump", { bg = "#d8dee9", fg = "#2e3440" })
hi(0, "MiniJump2dSpot", { bold = true, fg = "#d08770", nocombine = true })
hi(0, "MiniStarterCurrent", { nocombine = true })
hi(0, "MiniStarterFooter", { fg = "#a3be8c", italic = true })
hi(0, "MiniStarterHeader", { fg = "#81a1c1" })
hi(0, "MiniStarterInactive", { fg = "#4c555c" })
hi(0, "MiniStarterItem", { bg = "#1e2124", fg = "#e2e7e8" })
hi(0, "MiniStarterItemBullet", { fg = "#d8dee9" })
hi(0, "MiniStarterItemPrefix", { fg = "#b48ead" })
hi(0, "MiniStarterQuery", { fg = "#5e81ac" })
hi(0, "MiniStarterSection", { fg = "#d8dee9" })
hi(0, "MiniStatuslineDevinfo", { bg = "#434c5e", fg = "#d8dee9" })
hi(0, "MiniStatuslineFileinfo", { bg = "#434c5e", fg = "#d8dee9" })
hi(0, "MiniStatuslineFilename", { bg = "#3b4252", fg = "#d8dee9" })
hi(0, "MiniStatuslineInactive", { bg = "#2e3440", bold = true, fg = "#d8dee9" })
hi(0, "MiniStatuslineModeCommand", { bg = "#b48ead", bold = true, fg = "#2e3440" })
hi(0, "MiniStatuslineModeInsert", { bg = "#d8dee9", bold = true, fg = "#3b4252" })
hi(0, "MiniStatuslineModeNormal", { bg = "#81a1c1", bold = true, fg = "#3b4252" })
hi(0, "MiniStatuslineModeOther", { bg = "#ebcb8b", bold = true, fg = "#2e3440" })
hi(0, "MiniStatuslineModeReplace", { bg = "#bf616a", bold = true, fg = "#2e3440" })
hi(0, "MiniStatuslineModeVisual", { bg = "#8fbcbb", bold = true, fg = "#2e3440" })
hi(0, "MiniSurround", { bg = "#e2b05c", fg = "#1e2124" })
hi(0, "MiniTablineCurrent", { bg = "#3b4252" })
hi(0, "MiniTablineHidden", { bg = "#2e3440", fg = "#4c566a" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#3b4252", fg = "#b48ead" })
hi(0, "MiniTablineModifiedHidden", { bg = "#2e3440", fg = "#b48ead" })
hi(0, "MiniTablineModifiedVisible", { bg = "#434c5e", fg = "#b48ead" })
hi(0, "MiniTablineTabpagesection", { bg = "#eceff4", bold = true, fg = "#5e81ac", reverse = true })
hi(0, "MiniTablineVisible", { bg = "#434c5e" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#bf616a" })
hi(0, "MiniTestPass", { bold = true, fg = "#a3be8c" })
hi(0, "MiniTrailspace", { bg = "#bf616a" })
hi(0, "ModeMsg", { fg = "#c3a4b3" })
hi(0, "MoreMsg", { fg = "#c3a4b3" })
hi(0, "MsgSeparator", { fg = "#2e3440" })
hi(0, "NavicIconsArray", { fg = "#ebcb8b" })
hi(0, "NavicIconsBoolean", { bold = true, fg = "#81a1c1" })
hi(0, "NavicIconsClass", { fg = "#81a1c1" })
hi(0, "NavicIconsConstant", { fg = "#ebcb8b" })
hi(0, "NavicIconsConstructor", { fg = "#81a1c1" })
hi(0, "NavicIconsEnum", { fg = "#81a1c1" })
hi(0, "NavicIconsEnumMember", { fg = "#d8dee9" })
hi(0, "NavicIconsEvent", { fg = "#81a1c1" })
hi(0, "NavicIconsField", { fg = "#d8dee9", italic = true })
hi(0, "NavicIconsFile", { fg = "#a3be8c" })
hi(0, "NavicIconsFunction", { fg = "#88c0d0", italic = true })
hi(0, "NavicIconsInterface", { fg = "#81a1c1" })
hi(0, "NavicIconsKey", { fg = "#81a1c1" })
hi(0, "NavicIconsMethod", { fg = "#8fbcbb", italic = true })
hi(0, "NavicIconsModule", { fg = "#d8dee9", italic = true })
hi(0, "NavicIconsNamespace", { fg = "#d8dee9", italic = true })
hi(0, "NavicIconsNull", { fg = "#81a1c1" })
hi(0, "NavicIconsNumber", { fg = "#b48ead" })
hi(0, "NavicIconsObject", { fg = "#81a1c1" })
hi(0, "NavicIconsOperator", { fg = "#81a1c1" })
hi(0, "NavicIconsPackage", { fg = "#d8dee9", italic = true })
hi(0, "NavicIconsProperty", { fg = "#d8dee9", italic = true })
hi(0, "NavicIconsString", { fg = "#a3be8c", italic = true })
hi(0, "NavicIconsStruct", { fg = "#81a1c1" })
hi(0, "NavicIconsTypeParameter", { fg = "#5e81ac" })
hi(0, "NavicIconsVariable", { bold = true, fg = "#d8dee9" })
hi(0, "NavicSeparator", { fg = "#d8dee9" })
hi(0, "NavicText", { fg = "#d8dee9" })
hi(0, "NeogitBranch", { fg = "#5e81ac" })
hi(0, "NeogitDiffAddHighlight", { fg = "#a3be8c", reverse = true })
hi(0, "NeogitDiffContextHighlight", { bg = "#3b4252" })
hi(0, "NeogitDiffDeleteHighlight", { fg = "#bf616a", reverse = true })
hi(0, "NeogitHunkHeader", { fg = "#88c0d0" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#3b4252", fg = "#88c0d0" })
hi(0, "NeogitRemote", { fg = "#81a1c1" })
hi(0, "NonText", { fg = "#40484e" })
hi(0, "Normal", { bg = "#1e2124", fg = "#e2e7e8" })
hi(0, "NormalFloat", { bg = "#1b1d20", fg = "#d4dbdd" })
hi(0, "NormalMode", { fg = "#d8dee9", reverse = true })
hi(0, "NotifyDEBUGBorder", { fg = "#4c566a" })
hi(0, "NotifyDEBUGIcon", { fg = "#4c566a" })
hi(0, "NotifyDEBUGTitle", { fg = "#4c566a" })
hi(0, "NotifyERRORBorder", { fg = "#bf616a" })
hi(0, "NotifyERRORIcon", { fg = "#bf616a" })
hi(0, "NotifyERRORTitle", { fg = "#bf616a" })
hi(0, "NotifyINFOBorder", { fg = "#a3be8c" })
hi(0, "NotifyINFOIcon", { fg = "#a3be8c" })
hi(0, "NotifyINFOTitle", { fg = "#a3be8c" })
hi(0, "NotifyTRACEBorder", { fg = "#b48ead" })
hi(0, "NotifyTRACEIcon", { fg = "#b48ead" })
hi(0, "NotifyTRACETitle", { fg = "#b48ead" })
hi(0, "NotifyWARNBorder", { fg = "#ebcb8b" })
hi(0, "NotifyWARNIcon", { fg = "#ebcb8b" })
hi(0, "NotifyWARNTitle", { fg = "#ebcb8b" })
hi(0, "Number", { fg = "#e26d5c" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#d8dee9" })
hi(0, "NvimTreeExecFile", { fg = "#d8dee9" })
hi(0, "NvimTreeFolderIcon", { fg = "#81a1c1" })
hi(0, "NvimTreeFolderName", { fg = "#d8dee9" })
hi(0, "NvimTreeGitDeleted", { fg = "#bf616a" })
hi(0, "NvimTreeGitDirty", { fg = "#ebcb8b" })
hi(0, "NvimTreeGitIgnored", { fg = "#616e88" })
hi(0, "NvimTreeGitMerge", { fg = "#ebcb8b" })
hi(0, "NvimTreeGitNew", { fg = "#a3be8c" })
hi(0, "NvimTreeGitRenamed", { fg = "#ebcb8b" })
hi(0, "NvimTreeGitStaged", { fg = "#ebcb8b" })
hi(0, "NvimTreeImageFile", { fg = "#d8dee9" })
hi(0, "NvimTreeIndentMarker", { fg = "#81a1c1" })
hi(0, "NvimTreeMarkdownFile", { fg = "#d8dee9" })
hi(0, "NvimTreeNormal", { fg = "#d8dee9" })
hi(0, "NvimTreeOpenedFile", { fg = "#eceff4" })
hi(0, "NvimTreeOpenedFolderName", { fg = "#e5e9f0" })
hi(0, "NvimTreeRootFolder", { fg = "#b48ead" })
hi(0, "NvimTreeSpecialFile", { bold = true, fg = "#d8dee9" })
hi(0, "NvimTreeSymlink", { fg = "#e5e9f0" })
hi(0, "Operator", { fg = "#e2b05c" })
hi(0, "OutlineDetail", { fg = "#d8dee9" })
hi(0, "OutlineFoldPrefix", { fg = "#bf616a" })
hi(0, "OutlineIndentEvn", { fg = "#b48ead" })
hi(0, "OutlineIndentOdd", { fg = "#d08770" })
hi(0, "Pmenu", { bg = "#24292e", fg = "#777d85" })
hi(0, "PmenuSbar", { bg = "#1e2124", fg = "#e2e7e8" })
hi(0, "PmenuSel", { bg = "#e26d5c", fg = "#1e2124" })
hi(0, "PmenuThumb", { bg = "#2b3237" })
hi(0, "PreProc", {})
hi(0, "Question", { fg = "#b3c3a4" })
hi(0, "QuickFixLine", { bg = "#e2b05c", fg = "#1e2124" })
hi(0, "Quote", { fg = "#434c5e" })
hi(0, "RainbowDelimiterBlue", { fg = "#81a1c1" })
hi(0, "RainbowDelimiterCyan", { fg = "#88c0d0" })
hi(0, "RainbowDelimiterGreen", { fg = "#a3be8c" })
hi(0, "RainbowDelimiterOrange", { fg = "#d08770" })
hi(0, "RainbowDelimiterRed", { fg = "#bf616a" })
hi(0, "RainbowDelimiterViolet", { fg = "#b48ead" })
hi(0, "RainbowDelimiterYellow", { fg = "#ebcb8b" })
hi(0, "References", { fg = "#b48ead" })
hi(0, "ReferencesCount", { fg = "#5e81ac" })
hi(0, "ReferencesIcon", { fg = "#81a1c1" })
hi(0, "Repeat", { link = "Conditional" })
hi(0, "ReplacelMode", { fg = "#bf616a", reverse = true })
hi(0, "SagaShadow", { fg = "#000000" })
hi(0, "Search", { bg = "#e2b05c", fg = "#1e2124" })
hi(0, "SignColumn", { bg = "#1e2124", fg = "#e2e7e8" })
hi(0, "Sneak", { bg = "#d8dee9", fg = "#2e3440" })
hi(0, "SneakScope", { bg = "#3b4252" })
hi(0, "Special", {})
hi(0, "SpecialComment", { fg = "#e2b05c" })
hi(0, "SpecialKey", { fg = "#e2b05c" })
hi(0, "SpellBad", { fg = "#bf616a", italic = true, sp = "#ffc0b9", undercurl = true })
hi(0, "SpellCap", { fg = "#8fbcbb", italic = true, sp = "#fce094", undercurl = true })
hi(0, "SpellLocal", { fg = "#88c0d0", italic = true, sp = "#b3f6c0", undercurl = true })
hi(0, "SpellRare", { fg = "#81a1c1", italic = true, sp = "#8cf8f7", undercurl = true })
hi(0, "Statement", { fg = "#8391a7" })
hi(0, "StatusLine", { bg = "#24292e", fg = "#e2e7e8" })
hi(0, "StatusLineAccent", { bg = "#ebcb8b", fg = "#2e3440" })
hi(0, "StatusLineDull", { bg = "#3b4252", fg = "#4c566a" })
hi(0, "StatusLineNC", {})
hi(0, "StatusLineTerm", { bg = "#434c5e", fg = "#d8dee9" })
hi(0, "StatusLineTermNC", { bg = "#3b4252", fg = "#d8dee9" })
hi(0, "String", { fg = "#b3c3a4" })
hi(0, "Substitute", { bg = "#36393e", fg = "#ed333b" })
hi(0, "TSAnnotation", { fg = "#bf616a" })
hi(0, "TSAttribute", { fg = "#b48ead" })
hi(0, "TSBoolean", { bold = true, fg = "#81a1c1" })
hi(0, "TSCharacter", { fg = "#a3be8c", italic = true })
hi(0, "TSComment", { fg = "#616e88", italic = true })
hi(0, "TSConditional", { fg = "#81a1c1", italic = true })
hi(0, "TSConstBuiltin", { bold = true, fg = "#8fbcbb" })
hi(0, "TSConstMacro", { bold = true, fg = "#8fbcbb" })
hi(0, "TSConstant", { fg = "#ebcb8b" })
hi(0, "TSConstructor", { fg = "#81a1c1" })
hi(0, "TSEmphasis", { fg = "#5e81ac" })
hi(0, "TSError", { fg = "#bf616a" })
hi(0, "TSException", { fg = "#b48ead" })
hi(0, "TSField", { fg = "#d8dee9", italic = true })
hi(0, "TSFloat", { fg = "#b48ead" })
hi(0, "TSFuncBuiltin", { fg = "#88c0d0", italic = true })
hi(0, "TSFuncMacro", { fg = "#8fbcbb" })
hi(0, "TSFunction", { fg = "#88c0d0", italic = true })
hi(0, "TSInclude", { fg = "#81a1c1" })
hi(0, "TSKeyword", { fg = "#81a1c1", italic = true })
hi(0, "TSKeywordFunction", { fg = "#88c0d0", italic = true })
hi(0, "TSKeywordOperator", { fg = "#88c0d0", italic = true })
hi(0, "TSKeywordReturn", { fg = "#88c0d0", italic = true })
hi(0, "TSLabel", { fg = "#b48ead" })
hi(0, "TSLiteral", { fg = "#d8dee9" })
hi(0, "TSMethod", { fg = "#8fbcbb", italic = true })
hi(0, "TSNamespace", { fg = "#d8dee9", italic = true })
hi(0, "TSNumber", { fg = "#b48ead" })
hi(0, "TSOperator", { fg = "#81a1c1" })
hi(0, "TSParameter", { fg = "#5e81ac" })
hi(0, "TSParameterReference", { fg = "#5e81ac" })
hi(0, "TSProperty", { fg = "#5e81ac", italic = true })
hi(0, "TSPunctBracket", { fg = "#88c0d0" })
hi(0, "TSPunctDelimiter", { fg = "#88c0d0" })
hi(0, "TSPunctSpecial", { fg = "#88c0d0" })
hi(0, "TSRepeat", { fg = "#81a1c1", italic = true })
hi(0, "TSString", { fg = "#a3be8c", italic = true })
hi(0, "TSStringEscape", { fg = "#b48ead", italic = true })
hi(0, "TSStringRegex", { fg = "#8fbcbb", italic = true })
hi(0, "TSSymbol", { fg = "#b48ead" })
hi(0, "TSTag", { fg = "#d8dee9" })
hi(0, "TSTagDelimiter", { fg = "#b48ead" })
hi(0, "TSText", { fg = "#d8dee9" })
hi(0, "TSTextReference", { fg = "#b48ead" })
hi(0, "TSTitle", { bold = true, fg = "#5e81ac" })
hi(0, "TSType", { fg = "#81a1c1" })
hi(0, "TSTypeBuiltin", { fg = "#81a1c1" })
hi(0, "TSURI", { fg = "#a3be8c" })
hi(0, "TSUnderline", { fg = "#d8dee9", underline = true })
hi(0, "TSVariable", { bold = true, fg = "#d8dee9" })
hi(0, "TSVariableBuiltin", { bold = true, fg = "#d8dee9" })
hi(0, "TabLine", { bg = "#3b4252", fg = "#d8dee9" })
hi(0, "TabLineFill", {})
hi(0, "TabLineSel", { bg = "#81a1c1", fg = "#3b4252" })
hi(0, "Tag", {})
hi(0, "TargetFileName", { fg = "#d8dee9" })
hi(0, "TargetWord", { bold = true, fg = "#eceff4" })
hi(0, "TelescopeMatching", { bg = "#e2b05c", fg = "#1e2124" })
hi(0, "TelescopePreviewBorder", { fg = "#d8dee9" })
hi(0, "TelescopePromptBorder", { fg = "#d8dee9" })
hi(0, "TelescopeResultsBorder", { fg = "#d8dee9" })
hi(0, "TelescopeSelection", { bg = "#434c5e", fg = "#eceff4" })
hi(0, "TelescopeSelectionCaret", { fg = "#81a1c1" })
hi(0, "TermCursor", { bg = "#ed333b" })
hi(0, "Title", { fg = "#a2c4ff" })
hi(0, "Todo", { fg = "#e2b05c" })
hi(0, "ToolbarButton", { bold = true, fg = "#d8dee9" })
hi(0, "ToolbarLine", { bg = "#3b4252", fg = "#d8dee9" })
hi(0, "Type", { bg = "#1e2124", fg = "#e2e7e8" })
hi(0, "VertSplit", { fg = "#2e3440" })
hi(0, "Visual", { bg = "#2b3237", fg = "#e2e7e8" })
hi(0, "VisualMode", { fg = "#81a1c1", reverse = true })
hi(0, "VisualNOS", { bg = "#434c5e" })
hi(0, "WarningMsg", { fg = "#ed333b" })
hi(0, "Warnings", { fg = "#b48ead" })
hi(0, "WhichKey", { bold = true, fg = "#88c0d0" })
hi(0, "WhichKeyDesc", { fg = "#8fbcbb", italic = true })
hi(0, "WhichKeyFloat", { bg = "#3b4252" })
hi(0, "WhichKeyFloating", { bg = "#3b4252" })
hi(0, "WhichKeyGroup", { fg = "#e5e9f0" })
hi(0, "WhichKeySeperator", { fg = "#81a1c1" })
hi(0, "WhichKeyValue", { fg = "#8fbcbb" })
hi(0, "WildMenu", { bold = true, fg = "#d08770" })
hi(0, "WinBar", { bg = "#1e2124", fg = "#e2e7e8" })
hi(0, "WinBarNC", {})
hi(0, "WinSeparator", { fg = "#1b1d20" })
hi(0, "diffAdded", { bg = "#162918", fg = "#e2e7e8" })
hi(0, "diffChanged", { bg = "#333f6a", fg = "#e2e7e8" })
hi(0, "diffFile", { fg = "#8fbcbb" })
hi(0, "diffIndexLine", { fg = "#81a1c1" })
hi(0, "diffLine", { fg = "#4c566a" })
hi(0, "diffNewFile", { fg = "#d08770" })
hi(0, "diffRemoved", { bg = "#470f11", fg = "#e2e7e8" })
hi(0, "gitcommitArrow", { fg = "#8391a7" })
hi(0, "gitcommitBlank", { bg = "#162918", fg = "#e2e7e8" })
hi(0, "gitcommitBranch", { bg = "#162918", fg = "#e2e7e8" })
hi(0, "gitcommitDiscarded", { bg = "#162918", fg = "#e2e7e8" })
hi(0, "gitcommitDiscardedFile", { bg = "#162918", fg = "#e2e7e8" })
hi(0, "gitcommitDiscardedType", { bg = "#470f11", fg = "#e2e7e8" })
hi(0, "gitcommitSummary", { fg = "#a2c4ff" })
hi(0, "gitcommitType", { fg = "#c3a4b3" })
hi(0, "gitcommitUnmerged", { bg = "#162918", fg = "#e2e7e8" })
hi(0, "healthError", { fg = "#bf616a" })
hi(0, "healthSuccess", { fg = "#a3be8c" })
hi(0, "healthWarning", { fg = "#b48ead" })
hi(0, "helpCommand", { bg = "#1e2124", fg = "#e2e7e8" })
hi(0, "helpExample", { fg = "#b3c3a4" })
hi(0, "helpHyperTextEntry", { fg = "#a2c4ff" })
hi(0, "helpOption", { bg = "#1e2124", fg = "#e2e7e8" })
hi(0, "helpVim", { bg = "#1e2124", fg = "#e2e7e8" })
hi(0, "htmlH1", { bold = true, fg = "#88c0d0" })
hi(0, "htmlH2", { bold = true, fg = "#bf616a" })
hi(0, "htmlH3", { bold = true, fg = "#a3be8c" })
hi(0, "htmlH4", { bold = true, fg = "#b48ead" })
hi(0, "htmlH5", { bold = true, fg = "#81a1c1" })
hi(0, "htmlLink", { fg = "#a3be8c", underline = true })
hi(0, "illuminatedCurWord", { bg = "#4c566a" })
hi(0, "illuminatedWord", { bg = "#4c566a" })
hi(0, "lCursor", { bg = "#e2e7e8", fg = "#1e2124" })
hi(0, "markdownH1", { fg = "#a2c4ff" })
hi(0, "markdownH1Delimiter", { fg = "#a2c4ff" })
hi(0, "markdownH2", { fg = "#91b0e5" })
hi(0, "markdownH2Delimiter", { fg = "#91b0e5" })
hi(0, "markdownH3", { fg = "#819ccc" })
hi(0, "markdownH3Delimiter", { fg = "#819ccc" })
hi(0, "markdownH4", { fg = "#7189b2" })
hi(0, "markdownH4Delimiter", { fg = "#7189b2" })
hi(0, "markdownH5", { fg = "#617599" })
hi(0, "markdownH5Delimiter", { fg = "#617599" })
hi(0, "markdownH6", { fg = "#51627f" })
hi(0, "markdownH6Delimiter", { fg = "#51627f" })
hi(0, "markdownHeadingRule", { fg = "#40484e" })
hi(0, "markdownListMarker", { bg = "#1e2124", fg = "#e2e7e8" })
hi(0, "markdownRule", { fg = "#40484e" })
hi(0, "qfLineNr", { fg = "#d8dee9", reverse = true })
hi(0, "rainbowcol1", { fg = "#b48ead" })
hi(0, "rainbowcol2", { fg = "#ebcb8b" })
hi(0, "rainbowcol3", { fg = "#bf616a" })
hi(0, "rainbowcol4", { fg = "#8fbcbb" })
hi(0, "rainbowcol5", { fg = "#88c0d0" })
hi(0, "rainbowcol6", { fg = "#b48ead" })
hi(0, "rainbowcol7", { fg = "#ebcb8b" })
hi(0, "yamlBlockMappingKey", { fg = "#8fbcbb" })
hi(0, "yamlBool", { link = "Boolean" })
hi(0, "yamlDocumentStart", { fg = "#8391a7" })
hi(0, "yamlKey", { fg = "#8fbcbb" })
hi(0, "yamlTSField", { fg = "#8fbcbb" })
hi(0, "yamlTSPunctSpecial", { fg = "#8391a7" })
hi(0, "yamlTSString", { fg = "#d8dee9" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#3b4252"
g.terminal_color_1 = "#bf616a"
g.terminal_color_2 = "#a3be8c"
g.terminal_color_3 = "#ebcb8b"
g.terminal_color_4 = "#81a1c1"
g.terminal_color_5 = "#b48ead"
g.terminal_color_6 = "#88c0d0"
g.terminal_color_7 = "#e5e9f0"
g.terminal_color_8 = "#4c566a"
g.terminal_color_9 = "#bf616a"
g.terminal_color_10 = "#a3be8c"
g.terminal_color_11 = "#ebcb8b"
g.terminal_color_12 = "#81a1c1"
g.terminal_color_13 = "#b48ead"
g.terminal_color_14 = "#8fbcbb"
g.terminal_color_15 = "#eceff4"
