-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "kopicat"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { fg = "#ff9b5e" })
hi(0, "@attribute.builtin", { fg = "#f4b8e4" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.documentation", { fg = "#737994", italic = true })
hi(0, "@comment.error", { bg = "#ff657a", fg = "#202027" })
hi(0, "@comment.hint", { bg = "#5d81ab", fg = "#202027" })
hi(0, "@comment.note", { bg = "#5d81ab", fg = "#202027" })
hi(0, "@comment.todo", { bg = "#eebebe", fg = "#202027" })
hi(0, "@comment.warning", { bg = "#eccc81", fg = "#202027" })
hi(0, "@comment.warning.gitcommit", { fg = "#eccc81" })
hi(0, "@conditional", { fg = "#b18eab", italic = true })
hi(0, "@constant.builtin", { fg = "#ff9b5e" })
hi(0, "@constant.java", { fg = "#9cd1bb" })
hi(0, "@constant.macro", { fg = "#b18eab" })
hi(0, "@constructor", { fg = "#86aacc" })
hi(0, "@constructor.lua", { fg = "#eebebe" })
hi(0, "@constructor.tsx", { fg = "#66729c" })
hi(0, "@constructor.typescript", { fg = "#66729c" })
hi(0, "@define", { link = "Define" })
hi(0, "@diff.delta", { fg = "#5d81ab" })
hi(0, "@diff.minus", { fg = "#ff657a" })
hi(0, "@diff.plus", { fg = "#a8be81" })
hi(0, "@error", { fg = "#ff657a" })
hi(0, "@exception", { fg = "#b18eab" })
hi(0, "@field", { fg = "#66729c" })
hi(0, "@float", { link = "Float" })
hi(0, "@function.builtin", { fg = "#ff9b5e" })
hi(0, "@function.builtin.bash", { fg = "#ff657a", italic = true })
hi(0, "@function.call", { fg = "#5d81ab" })
hi(0, "@function.macro", { fg = "#9cd1bb" })
hi(0, "@function.method", { fg = "#5d81ab" })
hi(0, "@function.method.call", { fg = "#5d81ab" })
hi(0, "@function.method.call.php", { fg = "#5d81ab" })
hi(0, "@function.method.php", { fg = "#5d81ab" })
hi(0, "@include", { fg = "#b18eab" })
hi(0, "@keyword.conditional", { fg = "#b18eab", italic = true })
hi(0, "@keyword.conditional.ternary", { fg = "#a6c9e5" })
hi(0, "@keyword.coroutine", { fg = "#b18eab" })
hi(0, "@keyword.debug", { fg = "#b18eab" })
hi(0, "@keyword.directive", { fg = "#f4b8e4" })
hi(0, "@keyword.directive.define", { link = "Define" })
hi(0, "@keyword.exception", { fg = "#b18eab" })
hi(0, "@keyword.export", { fg = "#a6c9e5" })
hi(0, "@keyword.function", { fg = "#b18eab" })
hi(0, "@keyword.import", { fg = "#b18eab" })
hi(0, "@keyword.modifier", { fg = "#b18eab" })
hi(0, "@keyword.operator", { fg = "#a6c9e5" })
hi(0, "@keyword.repeat", { fg = "#b18eab" })
hi(0, "@keyword.return", { fg = "#b18eab" })
hi(0, "@keyword.storage", { fg = "#b18eab" })
hi(0, "@keyword.type", { fg = "#b18eab" })
hi(0, "@label.json", { fg = "#5d81ab" })
hi(0, "@lsp.type.boolean", { link = "@boolean" })
hi(0, "@lsp.type.builtinType", { fg = "#eccc81" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.escapeSequence", { fg = "#f4b8e4" })
hi(0, "@lsp.type.formatSpecifier", { fg = "#f4b8e4" })
hi(0, "@lsp.type.interface", { fg = "#eebebe" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.namespace", { fg = "#66729c", italic = true })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { fg = "#f29ba7" })
hi(0, "@lsp.type.property", { fg = "#66729c" })
hi(0, "@lsp.type.selfKeyword", { fg = "#ff657a" })
hi(0, "@lsp.type.typeAlias", { fg = "#eccc81" })
hi(0, "@lsp.type.unresolvedReference", { fg = "#ff657a" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.class.defaultLibrary", { fg = "#eccc81" })
hi(0, "@lsp.typemod.enum.defaultLibrary", { fg = "#eccc81" })
hi(0, "@lsp.typemod.enumMember.defaultLibrary", { fg = "#ff9b5e" })
hi(0, "@lsp.typemod.function.defaultLibrary", { fg = "#ff9b5e" })
hi(0, "@lsp.typemod.keyword.async", { fg = "#b18eab" })
hi(0, "@lsp.typemod.macro.defaultLibrary", { fg = "#ff9b5e" })
hi(0, "@lsp.typemod.method.defaultLibrary", { fg = "#ff9b5e" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.type.defaultLibrary", { fg = "#eccc81" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { fg = "#ff657a" })
hi(0, "@lsp.typemod.variable.injected", { fg = "#fcfcfa" })
hi(0, "@markup", { fg = "#fcfcfa" })
hi(0, "@markup.environment", { fg = "#f4b8e4" })
hi(0, "@markup.environment.name", { fg = "#5d81ab" })
hi(0, "@markup.heading", { bold = true, fg = "#5d81ab" })
hi(0, "@markup.heading.1.markdown", { fg = "#ff657a" })
hi(0, "@markup.heading.2.markdown", { fg = "#ff9b5e" })
hi(0, "@markup.heading.3.markdown", { fg = "#eccc81" })
hi(0, "@markup.heading.4.markdown", { fg = "#a8be81" })
hi(0, "@markup.heading.5.markdown", { fg = "#86aacc" })
hi(0, "@markup.heading.6.markdown", { fg = "#66729c" })
hi(0, "@markup.italic", { fg = "#f29ba7", italic = true })
hi(0, "@markup.link", { bold = true, fg = "#66729c" })
hi(0, "@markup.link.label", { fg = "#86aacc" })
hi(0, "@markup.link.url", { fg = "#f2d5cf", italic = true, underline = true })
hi(0, "@markup.list", { fg = "#f4b8e4" })
hi(0, "@markup.list.checked", { fg = "#a8be81" })
hi(0, "@markup.list.unchecked", { fg = "#838ba7" })
hi(0, "@markup.math", { fg = "#5d81ab" })
hi(0, "@markup.quote", { bold = true, fg = "#f29ba7" })
hi(0, "@markup.raw", { fg = "#9cd1bb" })
hi(0, "@markup.strikethrough", { fg = "#fcfcfa", strikethrough = true })
hi(0, "@markup.strong", { bold = true, fg = "#f29ba7" })
hi(0, "@markup.underline", { link = "Underlined" })
hi(0, "@method", { fg = "#5d81ab" })
hi(0, "@method.call", { fg = "#5d81ab" })
hi(0, "@method.call.php", { fg = "#5d81ab" })
hi(0, "@method.php", { fg = "#5d81ab" })
hi(0, "@module", { fg = "#66729c", italic = true })
hi(0, "@module.builtin", { fg = "#f4b8e4" })
hi(0, "@namespace", { fg = "#66729c", italic = true })
hi(0, "@number.css", { fg = "#ff9b5e" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@parameter", { fg = "#f29ba7" })
hi(0, "@preproc", { fg = "#f4b8e4" })
hi(0, "@property", { fg = "#66729c" })
hi(0, "@property.class.css", { fg = "#eccc81" })
hi(0, "@property.cpp", { fg = "#fcfcfa" })
hi(0, "@property.css", { fg = "#66729c" })
hi(0, "@property.id.css", { fg = "#5d81ab" })
hi(0, "@property.toml", { fg = "#5d81ab" })
hi(0, "@property.typescript", { fg = "#66729c" })
hi(0, "@punctuation.bracket", { fg = "#949cbb" })
hi(0, "@punctuation.delimiter", { fg = "#949cbb" })
hi(0, "@punctuation.special", { fg = "#f4b8e4" })
hi(0, "@repeat", { fg = "#b18eab" })
hi(0, "@storageclass", { fg = "#b18eab" })
hi(0, "@string.documentation", { fg = "#9cd1bb" })
hi(0, "@string.escape", { fg = "#f4b8e4" })
hi(0, "@string.plain.css", { fg = "#ff9b5e" })
hi(0, "@string.regex", { fg = "#ff9b5e" })
hi(0, "@string.regexp", { fg = "#ff9b5e" })
hi(0, "@string.special", { fg = "#f4b8e4" })
hi(0, "@string.special.path", { fg = "#f4b8e4" })
hi(0, "@string.special.symbol", { fg = "#eebebe" })
hi(0, "@string.special.symbol.ruby", { fg = "#eebebe" })
hi(0, "@string.special.url", { fg = "#f2d5cf", italic = true, underline = true })
hi(0, "@symbol", { fg = "#eebebe" })
hi(0, "@symbol.ruby", { fg = "#eebebe" })
hi(0, "@tag", { fg = "#b18eab" })
hi(0, "@tag.attribute", { fg = "#9cd1bb", italic = true })
hi(0, "@tag.attribute.tsx", { fg = "#9cd1bb", italic = true })
hi(0, "@tag.builtin", { fg = "#f4b8e4" })
hi(0, "@tag.delimiter", { fg = "#a6c9e5" })
hi(0, "@text", { fg = "#fcfcfa" })
hi(0, "@text.danger", { bg = "#ff657a", fg = "#202027" })
hi(0, "@text.diff.add", { fg = "#a8be81" })
hi(0, "@text.diff.delete", { fg = "#ff657a" })
hi(0, "@text.emphasis", { fg = "#f29ba7", italic = true })
hi(0, "@text.environment", { fg = "#f4b8e4" })
hi(0, "@text.environment.name", { fg = "#5d81ab" })
hi(0, "@text.literal", { fg = "#9cd1bb" })
hi(0, "@text.math", { fg = "#5d81ab" })
hi(0, "@text.note", { bg = "#5d81ab", fg = "#202027" })
hi(0, "@text.reference", { bold = true, fg = "#66729c" })
hi(0, "@text.strike", { fg = "#fcfcfa", strikethrough = true })
hi(0, "@text.strong", { bold = true, fg = "#f29ba7" })
hi(0, "@text.title", { bold = true, fg = "#5d81ab" })
hi(0, "@text.title.1.markdown", { fg = "#ff657a" })
hi(0, "@text.title.2.markdown", { fg = "#ff9b5e" })
hi(0, "@text.title.3.markdown", { fg = "#eccc81" })
hi(0, "@text.title.4.markdown", { fg = "#a8be81" })
hi(0, "@text.title.5.markdown", { fg = "#86aacc" })
hi(0, "@text.title.6.markdown", { fg = "#66729c" })
hi(0, "@text.todo", { bg = "#eebebe", fg = "#202027" })
hi(0, "@text.todo.checked", { fg = "#a8be81" })
hi(0, "@text.todo.unchecked", { fg = "#838ba7" })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.warning", { bg = "#eccc81", fg = "#202027" })
hi(0, "@type.builtin", { fg = "#eccc81" })
hi(0, "@type.builtin.c", { fg = "#eccc81" })
hi(0, "@type.builtin.cpp", { fg = "#eccc81" })
hi(0, "@type.css", { fg = "#66729c" })
hi(0, "@type.definition", { fg = "#eccc81" })
hi(0, "@type.qualifier", { fg = "#b18eab" })
hi(0, "@type.tag.css", { fg = "#b18eab" })
hi(0, "@variable", { fg = "#fcfcfa" })
hi(0, "@variable.builtin", { fg = "#ff657a" })
hi(0, "@variable.member", { fg = "#66729c" })
hi(0, "@variable.parameter", { fg = "#f29ba7" })
hi(0, "@variable.parameter.builtin", { fg = "#f4b8e4" })
hi(0, "AlphaButtons", { fg = "#66729c" })
hi(0, "AlphaFooter", { fg = "#eccc81", italic = true })
hi(0, "AlphaHeader", { fg = "#5d81ab" })
hi(0, "AlphaHeaderLabel", { fg = "#ff9b5e" })
hi(0, "AlphaShortcut", { fg = "#a8be81" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#ff9b5e" })
hi(0, "Character", { fg = "#9cd1bb" })
hi(0, "CmpItemAbbr", { fg = "#949cbb" })
hi(0, "CmpItemAbbrDefault", { fg = "#949cbb" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#737994", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#737994" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#fcfcfa" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#949cbb" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#fcfcfa" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#949cbb" })
hi(0, "CmpItemKind", { fg = "#5d81ab" })
hi(0, "CmpItemKindClass", { fg = "#eccc81" })
hi(0, "CmpItemKindClassDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindColor", { fg = "#ff657a" })
hi(0, "CmpItemKindColorDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindConstant", { fg = "#ff9b5e" })
hi(0, "CmpItemKindConstantDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindConstructor", { fg = "#5d81ab" })
hi(0, "CmpItemKindConstructorDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindCopilot", { fg = "#9cd1bb" })
hi(0, "CmpItemKindDefault", { fg = "#f4b8e4" })
hi(0, "CmpItemKindEnum", { fg = "#a8be81" })
hi(0, "CmpItemKindEnumDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindEnumMember", { fg = "#ff657a" })
hi(0, "CmpItemKindEnumMemberDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindEvent", { fg = "#5d81ab" })
hi(0, "CmpItemKindEventDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindField", { fg = "#a8be81" })
hi(0, "CmpItemKindFieldDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindFile", { fg = "#5d81ab" })
hi(0, "CmpItemKindFileDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindFolder", { fg = "#5d81ab" })
hi(0, "CmpItemKindFolderDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindFunction", { fg = "#5d81ab" })
hi(0, "CmpItemKindFunctionDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindInterface", { fg = "#eccc81" })
hi(0, "CmpItemKindInterfaceDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindKeyword", { fg = "#ff657a" })
hi(0, "CmpItemKindKeywordDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindMethod", { fg = "#5d81ab" })
hi(0, "CmpItemKindMethodDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindModule", { fg = "#5d81ab" })
hi(0, "CmpItemKindModuleDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindOperator", { fg = "#5d81ab" })
hi(0, "CmpItemKindOperatorDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindProperty", { fg = "#a8be81" })
hi(0, "CmpItemKindPropertyDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindReference", { fg = "#ff657a" })
hi(0, "CmpItemKindReferenceDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindSnippet", { fg = "#b18eab" })
hi(0, "CmpItemKindSnippetDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindStruct", { fg = "#5d81ab" })
hi(0, "CmpItemKindStructDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindText", { fg = "#9cd1bb" })
hi(0, "CmpItemKindTextDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindTypeParameter", { fg = "#5d81ab" })
hi(0, "CmpItemKindTypeParameterDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindUnit", { fg = "#a8be81" })
hi(0, "CmpItemKindUnitDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindValue", { fg = "#ff9b5e" })
hi(0, "CmpItemKindValueDefault", { fg = "#5d81ab" })
hi(0, "CmpItemKindVariable", { fg = "#eebebe" })
hi(0, "CmpItemKindVariableDefault", { fg = "#5d81ab" })
hi(0, "CmpItemMenu", { fg = "#fcfcfa" })
hi(0, "CmpItemMenuDefault", { fg = "#949cbb" })
hi(0, "ColorColumn", { bg = "#30303b" })
hi(0, "Comment", { fg = "#737994", italic = true })
hi(0, "Conceal", { fg = "#838ba7" })
hi(0, "Conditional", { fg = "#b18eab", italic = true })
hi(0, "Constant", { fg = "#ff9b5e" })
hi(0, "CurSearch", { bg = "#ff657a", fg = "#1c1d22" })
hi(0, "Cursor", { bg = "#fcfcfa", fg = "#202027" })
hi(0, "CursorColumn", { bg = "#1c1d22" })
hi(0, "CursorIM", { bg = "#fcfcfa", fg = "#202027" })
hi(0, "CursorLine", { bg = "#2a2a34" })
hi(0, "CursorLineNr", { fg = "#66729c" })
hi(0, "DapBreakpoint", { fg = "#ff657a" })
hi(0, "DapBreakpointCondition", { fg = "#eccc81" })
hi(0, "DapBreakpointRejected", { fg = "#b18eab" })
hi(0, "DapLogPoint", { fg = "#a6c9e5" })
hi(0, "DapStopped", { fg = "#f29ba7" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#a8be81" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#535763" })
hi(0, "DapUIBreakpointsInfo", { fg = "#a8be81" })
hi(0, "DapUIBreakpointsPath", { fg = "#a6c9e5" })
hi(0, "DapUIDecoration", { fg = "#a6c9e5" })
hi(0, "DapUIFloatBorder", { fg = "#a6c9e5" })
hi(0, "DapUILineNumber", { fg = "#a6c9e5" })
hi(0, "DapUIModifiedValue", { fg = "#ff9b5e" })
hi(0, "DapUIPlayPause", { fg = "#a8be81" })
hi(0, "DapUIRestart", { fg = "#a8be81" })
hi(0, "DapUIScope", { fg = "#a6c9e5" })
hi(0, "DapUISource", { fg = "#66729c" })
hi(0, "DapUIStepBack", { fg = "#5d81ab" })
hi(0, "DapUIStepInto", { fg = "#5d81ab" })
hi(0, "DapUIStepOut", { fg = "#5d81ab" })
hi(0, "DapUIStepOver", { fg = "#5d81ab" })
hi(0, "DapUIStop", { fg = "#ff657a" })
hi(0, "DapUIStoppedThread", { fg = "#a6c9e5" })
hi(0, "DapUIThread", { fg = "#a8be81" })
hi(0, "DapUIType", { fg = "#b18eab" })
hi(0, "DapUIUnavailable", { fg = "#3a3d4b" })
hi(0, "DapUIValue", { fg = "#a6c9e5" })
hi(0, "DapUIVariable", { fg = "#fcfcfa" })
hi(0, "DapUIWatchesEmpty", { fg = "#f29ba7" })
hi(0, "DapUIWatchesError", { fg = "#f29ba7" })
hi(0, "DapUIWatchesValue", { fg = "#a8be81" })
hi(0, "DapUIWinSelect", { fg = "#ff9b5e" })
hi(0, "DashboardCenter", { fg = "#a8be81" })
hi(0, "DashboardDesc", { fg = "#5d81ab" })
hi(0, "DashboardFiles", { fg = "#66729c" })
hi(0, "DashboardFooter", { fg = "#eccc81", italic = true })
hi(0, "DashboardHeader", { fg = "#5d81ab" })
hi(0, "DashboardIcon", { bold = true, fg = "#f4b8e4" })
hi(0, "DashboardKey", { fg = "#ff9b5e" })
hi(0, "DashboardMruTitle", { fg = "#a6c9e5" })
hi(0, "DashboardProjectTitle", { fg = "#a6c9e5" })
hi(0, "DashboardShortCut", { fg = "#f4b8e4" })
hi(0, "Delimiter", { fg = "#949cbb" })
hi(0, "DiagnosticError", { fg = "#ff657a", italic = true })
hi(0, "DiagnosticFloatingError", { fg = "#ff657a" })
hi(0, "DiagnosticFloatingHint", { fg = "#9cd1bb" })
hi(0, "DiagnosticFloatingInfo", { fg = "#a6c9e5" })
hi(0, "DiagnosticFloatingOk", { fg = "#a8be81" })
hi(0, "DiagnosticFloatingWarn", { fg = "#eccc81" })
hi(0, "DiagnosticHint", { fg = "#9cd1bb", italic = true })
hi(0, "DiagnosticInfo", { fg = "#a6c9e5", italic = true })
hi(0, "DiagnosticOk", { fg = "#a8be81", italic = true })
hi(0, "DiagnosticSignError", { fg = "#ff657a" })
hi(0, "DiagnosticSignHint", { fg = "#9cd1bb" })
hi(0, "DiagnosticSignInfo", { fg = "#a6c9e5" })
hi(0, "DiagnosticSignOk", { fg = "#a8be81" })
hi(0, "DiagnosticSignWarn", { fg = "#eccc81" })
hi(0, "DiagnosticUnderlineError", { sp = "#ff657a", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#9cd1bb", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#a6c9e5", underline = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#a8be81", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#eccc81", underline = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#35272f", fg = "#ff657a", italic = true })
hi(0, "DiagnosticVirtualTextHint", { bg = "#2c3135", fg = "#9cd1bb", italic = true })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#2d3039", fg = "#a6c9e5", italic = true })
hi(0, "DiagnosticVirtualTextOk", { bg = "#2c3135", fg = "#a8be81", italic = true })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#333030", fg = "#eccc81", italic = true })
hi(0, "DiagnosticWarn", { fg = "#eccc81", italic = true })
hi(0, "DiffAdd", { bg = "#383c37" })
hi(0, "DiffChange", { bg = "#242730" })
hi(0, "DiffDelete", { bg = "#482c36" })
hi(0, "DiffText", { bg = "#323d4f" })
hi(0, "Directory", { fg = "#5d81ab" })
hi(0, "DropBarIconUISeparator", { fg = "#838ba7" })
hi(0, "DropBarKindArray", { fg = "#fcfcfa" })
hi(0, "DropBarKindBoolean", { fg = "#fcfcfa" })
hi(0, "DropBarKindBreakStatement", { fg = "#fcfcfa" })
hi(0, "DropBarKindCall", { fg = "#fcfcfa" })
hi(0, "DropBarKindCaseStatement", { fg = "#fcfcfa" })
hi(0, "DropBarKindClass", { fg = "#fcfcfa" })
hi(0, "DropBarKindConstant", { fg = "#fcfcfa" })
hi(0, "DropBarKindConstructor", { fg = "#fcfcfa" })
hi(0, "DropBarKindContinueStatement", { fg = "#fcfcfa" })
hi(0, "DropBarKindDeclaration", { fg = "#fcfcfa" })
hi(0, "DropBarKindDelete", { fg = "#fcfcfa" })
hi(0, "DropBarKindDoStatement", { fg = "#fcfcfa" })
hi(0, "DropBarKindElseStatement", { fg = "#fcfcfa" })
hi(0, "DropBarKindEnum", { fg = "#fcfcfa" })
hi(0, "DropBarKindEnumMember", { fg = "#fcfcfa" })
hi(0, "DropBarKindEvent", { fg = "#fcfcfa" })
hi(0, "DropBarKindField", { fg = "#fcfcfa" })
hi(0, "DropBarKindFile", { fg = "#fcfcfa" })
hi(0, "DropBarKindFolder", { fg = "#fcfcfa" })
hi(0, "DropBarKindForStatement", { fg = "#fcfcfa" })
hi(0, "DropBarKindFunction", { fg = "#fcfcfa" })
hi(0, "DropBarKindIdentifier", { fg = "#fcfcfa" })
hi(0, "DropBarKindIfStatement", { fg = "#fcfcfa" })
hi(0, "DropBarKindInterface", { fg = "#fcfcfa" })
hi(0, "DropBarKindKeyword", { fg = "#fcfcfa" })
hi(0, "DropBarKindList", { fg = "#fcfcfa" })
hi(0, "DropBarKindMacro", { fg = "#fcfcfa" })
hi(0, "DropBarKindMarkdownH1", { fg = "#fcfcfa" })
hi(0, "DropBarKindMarkdownH2", { fg = "#fcfcfa" })
hi(0, "DropBarKindMarkdownH3", { fg = "#fcfcfa" })
hi(0, "DropBarKindMarkdownH4", { fg = "#fcfcfa" })
hi(0, "DropBarKindMarkdownH5", { fg = "#fcfcfa" })
hi(0, "DropBarKindMarkdownH6", { fg = "#fcfcfa" })
hi(0, "DropBarKindMethod", { fg = "#fcfcfa" })
hi(0, "DropBarKindModule", { fg = "#fcfcfa" })
hi(0, "DropBarKindNamespace", { fg = "#fcfcfa" })
hi(0, "DropBarKindNull", { fg = "#fcfcfa" })
hi(0, "DropBarKindNumber", { fg = "#fcfcfa" })
hi(0, "DropBarKindObject", { fg = "#fcfcfa" })
hi(0, "DropBarKindOperator", { fg = "#fcfcfa" })
hi(0, "DropBarKindPackage", { fg = "#fcfcfa" })
hi(0, "DropBarKindProperty", { fg = "#fcfcfa" })
hi(0, "DropBarKindReference", { fg = "#fcfcfa" })
hi(0, "DropBarKindRepeat", { fg = "#fcfcfa" })
hi(0, "DropBarKindScope", { fg = "#fcfcfa" })
hi(0, "DropBarKindSpecifier", { fg = "#fcfcfa" })
hi(0, "DropBarKindStatement", { fg = "#fcfcfa" })
hi(0, "DropBarKindString", { fg = "#fcfcfa" })
hi(0, "DropBarKindStruct", { fg = "#fcfcfa" })
hi(0, "DropBarKindSwitchStatement", { fg = "#fcfcfa" })
hi(0, "DropBarKindType", { fg = "#fcfcfa" })
hi(0, "DropBarKindTypeParameter", { fg = "#fcfcfa" })
hi(0, "DropBarKindUnit", { fg = "#fcfcfa" })
hi(0, "DropBarKindValue", { fg = "#fcfcfa" })
hi(0, "DropBarKindVariable", { fg = "#fcfcfa" })
hi(0, "DropBarKindWhileStatement", { fg = "#fcfcfa" })
hi(0, "DropBarMenuHoverEntry", { bg = "#3a3d4b", bold = true })
hi(0, "DropBarMenuHoverIcon", { reverse = true })
hi(0, "DropBarMenuHoverSymbol", { bold = true })
hi(0, "EndOfBuffer", { fg = "#202027" })
hi(0, "Error", { fg = "#ff657a" })
hi(0, "ErrorMsg", { bold = true, fg = "#ff657a", italic = true })
hi(0, "Exception", { fg = "#b18eab" })
hi(0, "FlashBackdrop", { fg = "#737994" })
hi(0, "FlashCurrent", { bg = "#202027", fg = "#ff9b5e" })
hi(0, "FlashLabel", { bg = "#202027", bold = true, fg = "#a8be81" })
hi(0, "FlashMatch", { bg = "#202027", fg = "#66729c" })
hi(0, "FlashPrompt", { bg = "#1c1d22", fg = "#fcfcfa" })
hi(0, "FloatBorder", { fg = "#5d81ab" })
hi(0, "FloatTitle", { fg = "#a5adce" })
hi(0, "FoldColumn", { fg = "#737994" })
hi(0, "Folded", { bg = "#3a3d4b", fg = "#5d81ab" })
hi(0, "Function", { fg = "#5d81ab" })
hi(0, "GitSignsAdd", { fg = "#a8be81" })
hi(0, "GitSignsAddPreview", { bg = "#383c37" })
hi(0, "GitSignsChange", { fg = "#eccc81" })
hi(0, "GitSignsCurrentLineBlame", { fg = "#3a3d4b" })
hi(0, "GitSignsDelete", { fg = "#ff657a" })
hi(0, "GitSignsDeletePreview", { bg = "#482c36" })
hi(0, "GlyphPalette1", { fg = "#ff657a" })
hi(0, "GlyphPalette2", { fg = "#9cd1bb" })
hi(0, "GlyphPalette3", { fg = "#eccc81" })
hi(0, "GlyphPalette4", { fg = "#5d81ab" })
hi(0, "GlyphPalette6", { fg = "#9cd1bb" })
hi(0, "GlyphPalette7", { fg = "#fcfcfa" })
hi(0, "GlyphPalette9", { fg = "#ff657a" })
hi(0, "IblIndent", { fg = "#30303b" })
hi(0, "IblScope", { fg = "#fcfcfa" })
hi(0, "Identifier", { fg = "#eebebe" })
hi(0, "IlluminatedWordRead", { bg = "#323440" })
hi(0, "IlluminatedWordText", { bg = "#323440" })
hi(0, "IlluminatedWordWrite", { bg = "#323440" })
hi(0, "IncSearch", { bg = "#99b8d2", fg = "#1c1d22" })
hi(0, "Include", { fg = "#b18eab" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#b18eab" })
hi(0, "Label", { fg = "#86aacc" })
hi(0, "LineNr", { fg = "#3a3d4b" })
hi(0, "LspCodeLens", { fg = "#737994" })
hi(0, "LspDiagnosticsDefaultError", { fg = "#ff657a" })
hi(0, "LspDiagnosticsDefaultHint", { fg = "#9cd1bb" })
hi(0, "LspDiagnosticsDefaultInformation", { fg = "#a6c9e5" })
hi(0, "LspDiagnosticsDefaultWarning", { fg = "#eccc81" })
hi(0, "LspDiagnosticsError", { fg = "#ff657a" })
hi(0, "LspDiagnosticsHint", { fg = "#9cd1bb" })
hi(0, "LspDiagnosticsInformation", { fg = "#a6c9e5" })
hi(0, "LspDiagnosticsUnderlineError", { sp = "#ff657a", underline = true })
hi(0, "LspDiagnosticsUnderlineHint", { sp = "#9cd1bb", underline = true })
hi(0, "LspDiagnosticsUnderlineInformation", { sp = "#a6c9e5", underline = true })
hi(0, "LspDiagnosticsUnderlineWarning", { sp = "#eccc81", underline = true })
hi(0, "LspDiagnosticsVirtualTextError", { fg = "#ff657a", italic = true })
hi(0, "LspDiagnosticsVirtualTextHint", { fg = "#9cd1bb", italic = true })
hi(0, "LspDiagnosticsVirtualTextInformation", { fg = "#a6c9e5", italic = true })
hi(0, "LspDiagnosticsVirtualTextWarning", { fg = "#eccc81", italic = true })
hi(0, "LspDiagnosticsWarning", { fg = "#eccc81" })
hi(0, "LspInfoBorder", { fg = "#5d81ab" })
hi(0, "LspInlayHint", { bg = "#2a2a34", fg = "#737994" })
hi(0, "LspReferenceRead", { bg = "#3a3d4b" })
hi(0, "LspReferenceText", { bg = "#3a3d4b" })
hi(0, "LspReferenceWrite", { bg = "#3a3d4b" })
hi(0, "LspSignatureActiveParameter", { fg = "#ff9b5e" })
hi(0, "Macro", { fg = "#b18eab" })
hi(0, "MatchParen", { bg = "#3a3d4b", bold = true, fg = "#ff9b5e" })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniIndentscopePrefix", { nocombine = true })
hi(0, "MiniIndentscopeSymbol", { fg = "#fcfcfa" })
hi(0, "MiniJump", { bg = "#f4b8e4", fg = "#949cbb" })
hi(0, "MiniJump2dSpot", { bg = "#202027", bold = true, fg = "#ff9b5e", underline = true })
hi(0, "MiniStarterFooter", { fg = "#eccc81", italic = true })
hi(0, "MiniStarterHeader", { fg = "#5d81ab" })
hi(0, "MiniStarterInactive", { fg = "#535763", italic = true })
hi(0, "MiniStarterItem", { fg = "#fcfcfa" })
hi(0, "MiniStarterItemBullet", { fg = "#5d81ab" })
hi(0, "MiniStarterItemPrefix", { fg = "#f4b8e4" })
hi(0, "MiniStarterQuery", { fg = "#a8be81" })
hi(0, "MiniStarterSection", { fg = "#eebebe" })
hi(0, "MiniStatuslineDevinfo", { bg = "#3a3d4b", fg = "#b5bfe2" })
hi(0, "MiniStatuslineFileinfo", { bg = "#3a3d4b", fg = "#b5bfe2" })
hi(0, "MiniStatuslineFilename", { bg = "#1c1d22", fg = "#fcfcfa" })
hi(0, "MiniStatuslineInactive", { bg = "#1c1d22", fg = "#5d81ab" })
hi(0, "MiniStatuslineModeCommand", { bg = "#ff9b5e", bold = true, fg = "#202027" })
hi(0, "MiniStatuslineModeInsert", { bg = "#a8be81", bold = true, fg = "#202027" })
hi(0, "MiniStatuslineModeNormal", { bg = "#5d81ab", bold = true, fg = "#1c1d22" })
hi(0, "MiniStatuslineModeOther", { bg = "#9cd1bb", bold = true, fg = "#202027" })
hi(0, "MiniStatuslineModeReplace", { bg = "#ff657a", bold = true, fg = "#202027" })
hi(0, "MiniStatuslineModeVisual", { bg = "#b18eab", bold = true, fg = "#202027" })
hi(0, "MiniSurround", { bg = "#f4b8e4", fg = "#3a3d4b" })
hi(0, "MiniTablineCurrent", { bg = "#202027", bold = true, fg = "#fcfcfa", italic = true, sp = "#ff657a", underline = true })
hi(0, "MiniTablineFill", { bg = "#202027" })
hi(0, "MiniTablineHidden", { bg = "#1c1d22", fg = "#fcfcfa" })
hi(0, "MiniTablineModifiedCurrent", { bold = true, fg = "#ff657a", italic = true })
hi(0, "MiniTablineModifiedHidden", { fg = "#ff657a" })
hi(0, "MiniTablineModifiedVisible", { fg = "#ff657a" })
hi(0, "MiniTablineTabpagesection", { bg = "#202027", fg = "#3a3d4b" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#ff657a" })
hi(0, "MiniTestPass", { bold = true, fg = "#a8be81" })
hi(0, "MiniTrailspace", { bg = "#ff657a" })
hi(0, "ModeMsg", { bold = true, fg = "#fcfcfa" })
hi(0, "MoreMsg", { fg = "#5d81ab" })
hi(0, "MsgSeparator", {})
hi(0, "NeoTreeDimText", { fg = "#838ba7" })
hi(0, "NeoTreeDirectoryIcon", { fg = "#5d81ab" })
hi(0, "NeoTreeDirectoryName", { fg = "#5d81ab" })
hi(0, "NeoTreeExpander", { fg = "#737994" })
hi(0, "NeoTreeFileNameOpened", { fg = "#f4b8e4" })
hi(0, "NeoTreeFilterTerm", { bold = true, fg = "#a8be81" })
hi(0, "NeoTreeFloatBorder", { fg = "#5d81ab" })
hi(0, "NeoTreeFloatTitle", { fg = "#a5adce" })
hi(0, "NeoTreeGitAdded", { fg = "#a8be81" })
hi(0, "NeoTreeGitConflict", { fg = "#ff657a" })
hi(0, "NeoTreeGitDeleted", { fg = "#ff657a" })
hi(0, "NeoTreeGitIgnored", { fg = "#737994" })
hi(0, "NeoTreeGitModified", { fg = "#eccc81" })
hi(0, "NeoTreeGitStaged", { fg = "#a8be81" })
hi(0, "NeoTreeGitUnstaged", { fg = "#ff657a" })
hi(0, "NeoTreeGitUntracked", { fg = "#b18eab" })
hi(0, "NeoTreeIndentMarker", { fg = "#737994" })
hi(0, "NeoTreeModified", { fg = "#ff9b5e" })
hi(0, "NeoTreeNormal", { bg = "#1c1d22", fg = "#fcfcfa" })
hi(0, "NeoTreeNormalNC", { bg = "#1c1d22", fg = "#fcfcfa" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#5d81ab" })
hi(0, "NeoTreeStatusLineNC", { bg = "#1c1d22", fg = "#1c1d22" })
hi(0, "NeoTreeSymbolicLinkTarget", { fg = "#f4b8e4" })
hi(0, "NeoTreeTabActive", { bg = "#1c1d22", bold = true, fg = "#66729c" })
hi(0, "NeoTreeTabInactive", { bg = "#202027", fg = "#737994" })
hi(0, "NeoTreeTabSeparatorActive", { bg = "#1c1d22", fg = "#1c1d22" })
hi(0, "NeoTreeTabSeparatorInactive", { bg = "#202027", fg = "#202027" })
hi(0, "NeoTreeTitleBar", { bg = "#5d81ab", fg = "#1c1d22" })
hi(0, "NeoTreeVertSplit", { bg = "#202027", fg = "#202027" })
hi(0, "NeoTreeWinSeparator", { bg = "#202027", fg = "#202027" })
hi(0, "NeogitBranch", { bold = true, fg = "#ff9b5e" })
hi(0, "NeogitChangeAdded", { bold = true, fg = "#a8be81" })
hi(0, "NeogitChangeBothModified", { bold = true, fg = "#eccc81" })
hi(0, "NeogitChangeCopied", { bold = true, fg = "#f4b8e4" })
hi(0, "NeogitChangeDeleted", { bold = true, fg = "#ff657a" })
hi(0, "NeogitChangeModified", { bold = true, fg = "#5d81ab" })
hi(0, "NeogitChangeNewFile", { bold = true, fg = "#a8be81" })
hi(0, "NeogitChangeRenamed", { bold = true, fg = "#b18eab" })
hi(0, "NeogitChangeUpdated", { bold = true, fg = "#ff9b5e" })
hi(0, "NeogitCommitViewHeader", { bg = "#323d4f", fg = "#7d9abb" })
hi(0, "NeogitDiffAdd", { bg = "#2d2f30", fg = "#8d9e6f" })
hi(0, "NeogitDiffAddHighlight", { bg = "#4f5746", fg = "#b5c793" })
hi(0, "NeogitDiffContext", { bg = "#202027" })
hi(0, "NeogitDiffContextHighlight", { bg = "#30303b" })
hi(0, "NeogitDiffDelete", { bg = "#35272f", fg = "#d25769" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#6d3844", fg = "#ff7c8d" })
hi(0, "NeogitDiffHeader", { bg = "#202027", bold = true, fg = "#5d81ab" })
hi(0, "NeogitDiffHeaderHighlight", { bg = "#202027", bold = true, fg = "#ff9b5e" })
hi(0, "NeogitFilePath", { fg = "#5d81ab", italic = true })
hi(0, "NeogitGraphBlue", { fg = "#5d81ab" })
hi(0, "NeogitGraphBoldBlue", { bold = true, fg = "#5d81ab" })
hi(0, "NeogitGraphBoldCyan", { bold = true, fg = "#5d81ab" })
hi(0, "NeogitGraphBoldGray", { bold = true, fg = "#b5bfe2" })
hi(0, "NeogitGraphBoldGreen", { bold = true, fg = "#a8be81" })
hi(0, "NeogitGraphBoldPurple", { bold = true, fg = "#66729c" })
hi(0, "NeogitGraphBoldRed", { bold = true, fg = "#ff657a" })
hi(0, "NeogitGraphBoldWhite", { bold = true })
hi(0, "NeogitGraphBoldYellow", { bold = true, fg = "#eccc81" })
hi(0, "NeogitGraphCyan", { fg = "#5d81ab" })
hi(0, "NeogitGraphGray", { fg = "#b5bfe2" })
hi(0, "NeogitGraphGreen", { fg = "#a8be81" })
hi(0, "NeogitGraphOrange", { fg = "#ff9b5e" })
hi(0, "NeogitGraphPurple", { fg = "#66729c" })
hi(0, "NeogitGraphRed", { fg = "#ff657a" })
hi(0, "NeogitGraphWhite", { fg = "#202027" })
hi(0, "NeogitGraphYellow", { fg = "#eccc81" })
hi(0, "NeogitHunkHeader", { bg = "#262934", fg = "#3f5169" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#2d3543", fg = "#5d81ab" })
hi(0, "NeogitNotificationError", { fg = "#ff657a" })
hi(0, "NeogitNotificationInfo", { fg = "#5d81ab" })
hi(0, "NeogitNotificationWarning", { fg = "#eccc81" })
hi(0, "NeogitObjectId", { fg = "#737994", italic = true })
hi(0, "NeogitPopupActionKey", { fg = "#66729c" })
hi(0, "NeogitPopupBold", { bold = true })
hi(0, "NeogitPopupConfigKey", { fg = "#66729c" })
hi(0, "NeogitPopupOptionKey", { fg = "#66729c" })
hi(0, "NeogitPopupSwitchKey", { fg = "#66729c" })
hi(0, "NeogitRebaseDone", { fg = "#737994", italic = true })
hi(0, "NeogitRebasing", { bold = true, fg = "#b18eab" })
hi(0, "NeogitRecentcommits", { bold = true, fg = "#b18eab" })
hi(0, "NeogitRemote", { bold = true, fg = "#a8be81" })
hi(0, "NeogitSectionHeader", { bold = true, fg = "#b18eab" })
hi(0, "NeogitStagedchanges", { bold = true, fg = "#b18eab" })
hi(0, "NeogitStash", { fg = "#737994", italic = true })
hi(0, "NeogitStashes", { bold = true, fg = "#b18eab" })
hi(0, "NeogitTagDistance", { fg = "#5d81ab" })
hi(0, "NeogitTagName", { fg = "#eccc81" })
hi(0, "NeogitUnmergedInto", { fg = "#5d81ab" })
hi(0, "NeogitUnmergedchanges", { bold = true, fg = "#b18eab" })
hi(0, "NeogitUnpulledFrom", { fg = "#5d81ab" })
hi(0, "NeogitUnpulledchanges", { bold = true, fg = "#b18eab" })
hi(0, "NeogitUnpushedTo", { bold = true, fg = "#66729c" })
hi(0, "NeogitUnstagedchanges", { bold = true, fg = "#b18eab" })
hi(0, "NeogitUntrackedfiles", { bold = true, fg = "#b18eab" })
hi(0, "NeogitWinSeparator", { fg = "#171719" })
hi(0, "NonText", { fg = "#737994" })
hi(0, "Normal", { bg = "#202027", fg = "#fcfcfa" })
hi(0, "NormalFloat", { bg = "#1c1d22", fg = "#fcfcfa" })
hi(0, "NormalNC", { bg = "#202027", fg = "#fcfcfa" })
hi(0, "NormalSB", { bg = "#171719", fg = "#fcfcfa" })
hi(0, "Number", { fg = "#ff9b5e" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#5d81ab" })
hi(0, "NvimTreeFolderIcon", { fg = "#5d81ab" })
hi(0, "NvimTreeFolderName", { fg = "#5d81ab" })
hi(0, "NvimTreeGitDeleted", { fg = "#ff657a" })
hi(0, "NvimTreeGitDirty", { fg = "#eccc81" })
hi(0, "NvimTreeGitNew", { fg = "#5d81ab" })
hi(0, "NvimTreeImageFile", { fg = "#fcfcfa" })
hi(0, "NvimTreeIndentMarker", { fg = "#737994" })
hi(0, "NvimTreeNormal", { bg = "#1c1d22", fg = "#fcfcfa" })
hi(0, "NvimTreeOpenedFile", { fg = "#f4b8e4" })
hi(0, "NvimTreeOpenedFolderName", { fg = "#5d81ab" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#66729c" })
hi(0, "NvimTreeSpecialFile", { fg = "#eebebe" })
hi(0, "NvimTreeStatuslineNc", { bg = "#1c1d22", fg = "#1c1d22" })
hi(0, "NvimTreeSymlink", { fg = "#f4b8e4" })
hi(0, "NvimTreeWinSeparator", { bg = "#202027", fg = "#202027" })
hi(0, "Operator", { fg = "#a6c9e5" })
hi(0, "Pmenu", { bg = "#2b2b34", fg = "#949cbb" })
hi(0, "PmenuSbar", { bg = "#3a3d4b" })
hi(0, "PmenuSel", { bg = "#3a3d4b", bold = true })
hi(0, "PmenuThumb", { bg = "#737994" })
hi(0, "PreProc", { fg = "#f4b8e4" })
hi(0, "Question", { fg = "#5d81ab" })
hi(0, "QuickFixLine", { bg = "#3a3d4b", bold = true })
hi(0, "RainbowDelimiterBlue", { fg = "#5d81ab" })
hi(0, "RainbowDelimiterCyan", { fg = "#9cd1bb" })
hi(0, "RainbowDelimiterGreen", { fg = "#a8be81" })
hi(0, "RainbowDelimiterOrange", { fg = "#ff9b5e" })
hi(0, "RainbowDelimiterRed", { fg = "#ff657a" })
hi(0, "RainbowDelimiterViolet", { fg = "#b18eab" })
hi(0, "RainbowDelimiterYellow", { fg = "#eccc81" })
hi(0, "Repeat", { fg = "#b18eab" })
hi(0, "Search", { bg = "#485360", fg = "#fcfcfa" })
hi(0, "SignColumn", { fg = "#3a3d4b" })
hi(0, "SignColumnSB", { bg = "#171719", fg = "#3a3d4b" })
hi(0, "Special", { fg = "#f4b8e4" })
hi(0, "SpecialKey", { fg = "#737994" })
hi(0, "SpellBad", { sp = "#ff657a", undercurl = true })
hi(0, "SpellCap", { sp = "#eccc81", undercurl = true })
hi(0, "SpellLocal", { sp = "#5d81ab", undercurl = true })
hi(0, "SpellRare", { sp = "#a8be81", undercurl = true })
hi(0, "Statement", { fg = "#b18eab" })
hi(0, "StatusLine", { bg = "#1c1d22", fg = "#fcfcfa" })
hi(0, "StatusLineNC", { bg = "#1c1d22", fg = "#3a3d4b" })
hi(0, "StorageClass", { fg = "#eccc81" })
hi(0, "String", { fg = "#a8be81" })
hi(0, "Structure", { fg = "#eccc81" })
hi(0, "Substitute", { bg = "#3a3d4b", fg = "#f4b8e4" })
hi(0, "TabLine", { bg = "#1c1d22", fg = "#3a3d4b" })
hi(0, "TabLineFill", {})
hi(0, "TabLineSel", { bg = "#3a3d4b", fg = "#a8be81" })
hi(0, "Tag", { bold = true, fg = "#66729c" })
hi(0, "TelescopeBorder", { fg = "#5d81ab" })
hi(0, "TelescopeMatching", { fg = "#5d81ab" })
hi(0, "TelescopePreviewBorder", { bg = "#171719", fg = "#171719" })
hi(0, "TelescopePreviewNormal", { bg = "#171719" })
hi(0, "TelescopePreviewTitle", { bg = "#171719", fg = "#171719" })
hi(0, "TelescopePromptBorder", { bg = "#30303b", fg = "#30303b" })
hi(0, "TelescopePromptCounter", { bold = true, fg = "#b18eab" })
hi(0, "TelescopePromptNormal", { bg = "#30303b" })
hi(0, "TelescopePromptPrefix", { bg = "#30303b" })
hi(0, "TelescopePromptTitle", { bg = "#30303b", fg = "#30303b" })
hi(0, "TelescopeResultsBorder", { bg = "#1c1d22", fg = "#1c1d22" })
hi(0, "TelescopeResultsNormal", { bg = "#1c1d22" })
hi(0, "TelescopeResultsTitle", { bg = "#1c1d22", fg = "#1c1d22" })
hi(0, "TelescopeSelection", { bg = "#30303b", bold = true, fg = "#fcfcfa" })
hi(0, "TelescopeSelectionCaret", { fg = "#eebebe" })
hi(0, "Title", { bold = true, fg = "#5d81ab" })
hi(0, "Todo", { bg = "#eebebe", bold = true, fg = "#202027" })
hi(0, "TreesitterContextBottom", { sp = "#30303b", underline = true })
hi(0, "TreesitterContextLineNumber", { bg = "#1c1d22", fg = "#3a3d4b" })
hi(0, "Type", { fg = "#eccc81" })
hi(0, "UfoFoldedEllipsis", { bg = "#5d81ab", fg = "#171719" })
hi(0, "UfoFoldedFg", { fg = "#66729c" })
hi(0, "VertSplit", { fg = "#171719" })
hi(0, "Visual", { bg = "#3a3d4b", bold = true })
hi(0, "VisualNOS", { bg = "#3a3d4b", bold = true })
hi(0, "WarningMsg", { fg = "#eccc81" })
hi(0, "Whitespace", { fg = "#3a3d4b" })
hi(0, "WildMenu", { bg = "#737994" })
hi(0, "WinBar", { fg = "#f2d5cf" })
hi(0, "WinBarNC", { fg = "#f2d5cf" })
hi(0, "WinSeparator", { fg = "#171719" })
hi(0, "csvCol0", { fg = "#ff657a" })
hi(0, "csvCol1", { fg = "#ff9b5e" })
hi(0, "csvCol2", { fg = "#eccc81" })
hi(0, "csvCol3", { fg = "#a8be81" })
hi(0, "csvCol4", { fg = "#a6c9e5" })
hi(0, "csvCol5", { fg = "#5d81ab" })
hi(0, "csvCol6", { fg = "#66729c" })
hi(0, "csvCol7", { fg = "#b18eab" })
hi(0, "csvCol8", { fg = "#f4b8e4" })
hi(0, "debugBreakpoint", { bg = "#202027", fg = "#737994" })
hi(0, "debugPC", { bg = "#171719" })
hi(0, "diffAdded", { fg = "#a8be81" })
hi(0, "diffChanged", { fg = "#5d81ab" })
hi(0, "diffFile", { fg = "#5d81ab" })
hi(0, "diffIndexLine", { fg = "#9cd1bb" })
hi(0, "diffLine", { fg = "#737994" })
hi(0, "diffNewFile", { fg = "#ff9b5e" })
hi(0, "diffOldFile", { fg = "#eccc81" })
hi(0, "diffRemoved", { fg = "#ff657a" })
hi(0, "gitcommitSummary", { fg = "#f2d5cf", italic = true })
hi(0, "healthError", { fg = "#ff657a" })
hi(0, "healthSuccess", { fg = "#9cd1bb" })
hi(0, "healthWarning", { fg = "#eccc81" })
hi(0, "htmlH1", { bold = true, fg = "#f4b8e4" })
hi(0, "htmlH2", { bold = true, fg = "#5d81ab" })
hi(0, "illuminatedCurWord", { bg = "#3a3d4b" })
hi(0, "illuminatedWord", { bg = "#3a3d4b" })
hi(0, "lCursor", { bg = "#fcfcfa", fg = "#202027" })
hi(0, "markdownCode", { fg = "#eebebe" })
hi(0, "markdownCodeBlock", { fg = "#eebebe" })
hi(0, "markdownH1", { fg = "#ff657a" })
hi(0, "markdownH2", { fg = "#ff9b5e" })
hi(0, "markdownH3", { fg = "#eccc81" })
hi(0, "markdownH4", { fg = "#a8be81" })
hi(0, "markdownH5", { fg = "#86aacc" })
hi(0, "markdownH6", { fg = "#66729c" })
hi(0, "markdownHeadingDelimiter", { bold = true, fg = "#ff9b5e" })
hi(0, "markdownLinkText", { fg = "#5d81ab", underline = true })
hi(0, "mkdCodeDelimiter", { bg = "#202027", fg = "#fcfcfa" })
hi(0, "mkdCodeEnd", { bold = true, fg = "#eebebe" })
hi(0, "mkdCodeStart", { bold = true, fg = "#eebebe" })
hi(0, "qfFileName", { fg = "#5d81ab" })
hi(0, "qfLineNr", { fg = "#eccc81" })
hi(0, "rainbow1", { fg = "#ff657a" })
hi(0, "rainbow2", { fg = "#ff9b5e" })
hi(0, "rainbow3", { fg = "#eccc81" })
hi(0, "rainbow4", { fg = "#a8be81" })
hi(0, "rainbow5", { fg = "#86aacc" })
hi(0, "rainbow6", { fg = "#66729c" })
hi(0, "stl_fill", { fg = "#fcfcfa" })
hi(0, "zshKSHFunction", { fg = "#5d81ab" })

-- No terminal colors defined
