-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "lavi"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@constructor", { ctermfg = 159, fg = "#ecbef1" })
hi(0, "@function", { ctermfg = 204, fg = "#9fa5ff" })
hi(0, "@function.call", { ctermfg = 159, fg = "#ecbef1" })
hi(0, "@keyword.operator", { ctermfg = 122, fg = "#f7dbfa" })
hi(0, "@markup", { link = "Title" })
hi(0, "@markup.emphasis", { italic = true })
hi(0, "@markup.link", { ctermfg = 141, fg = "#bfc5ff" })
hi(0, "@markup.link.uri", { ctermfg = 159, fg = "#ecbef1" })
hi(0, "@markup.list.checked", { ctermfg = 252, fg = "#888998" })
hi(0, "@markup.list.unchecked", { bold = true, ctermfg = 121, fg = "#f3c2f8" })
hi(0, "@markup.raw", { ctermfg = 122, fg = "#f7dbfa" })
hi(0, "@module", { ctermfg = 141, fg = "#bfc5ff" })
hi(0, "@punctuation.bracket", { ctermfg = 122, fg = "#f7dbfa" })
hi(0, "@string.escape", { ctermfg = 122, fg = "#f7dbfa" })
hi(0, "@string.special", { ctermfg = 135, fg = "#989dfb" })
hi(0, "@string.special.symbol", { ctermfg = 228, fg = "#ffdcdf" })
hi(0, "@symbol", { ctermfg = 228, fg = "#ffdcdf" })
hi(0, "@tag", { link = "Keyword" })
hi(0, "@tag.attribute", { link = "Constant" })
hi(0, "@tag.delimiter", { link = "Special" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.literal", { ctermfg = 122, fg = "#f7dbfa" })
hi(0, "@text.reference", { ctermfg = 141, fg = "#bfc5ff" })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.todo.checked", { ctermfg = 252, fg = "#888998" })
hi(0, "@text.todo.unchecked", { bold = true, ctermfg = 121, fg = "#f3c2f8" })
hi(0, "@text.uri", { ctermfg = 159, fg = "#ecbef1" })
hi(0, "@variable", { fg = "#e1e1e6" })
hi(0, "@variable.builtin", { ctermfg = 122, fg = "#f7dbfa" })
hi(0, "Added", { ctermfg = 10, fg = "#ffd3d6" })
hi(0, "Boolean", { ctermfg = 215, fg = "#ffa2ac" })
hi(0, "Changed", { ctermfg = 14, fg = "#f6d1fa" })
hi(0, "CmpItemAbbrDefault", { fg = "#e1dce1" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#888998" })
hi(0, "CmpItemAbbrMatch", { ctermfg = 141, fg = "#bfc5ff" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#e1dce1" })
hi(0, "CmpItemAbbrMatchFuzzy", { ctermfg = 228, fg = "#ffdcdf" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#e1dce1" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { fg = "#f7dbfa" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { link = "CmpItemKindDefault" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { link = "CmpItemKindFunction" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { link = "PreProc" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { link = "CmpItemKindDefault" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { link = "Constant" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { link = "CmpItemKindModule" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { link = "Comment" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { link = "Comment" })
hi(0, "CmpItemMenuDefault", { fg = "#e1dce1" })
hi(0, "ColorColumn", { bg = "#2e2e30", ctermbg = 233 })
hi(0, "Comment", { ctermfg = 252, fg = "#888998", italic = true })
hi(0, "Conceal", { ctermfg = 253, fg = "#e1dce1" })
hi(0, "Constant", { ctermfg = 141, fg = "#bfc5ff" })
hi(0, "CurSearch", { bg = "#f6e1a8", ctermbg = 11, ctermfg = 0, fg = "#07070c" })
hi(0, "Cursor", { bg = "#a0dbf6", ctermbg = 159, ctermfg = 236, fg = "#545665" })
hi(0, "CursorColumn", { bg = "#10101a", ctermbg = 232 })
hi(0, "CursorLine", { bg = "#10101a", ctermbg = 232 })
hi(0, "CursorLineNr", { bg = "#10101a", bold = true, ctermbg = 232, ctermfg = 159, fg = "#ecbef1" })
hi(0, "Delimiter", { fg = "#e1e1e6" })
hi(0, "DiagnosticError", { bg = "#10101a", ctermbg = 232, ctermfg = 204, fg = "#9fa5ff" })
hi(0, "DiagnosticFloatingError", { link = "DiagnosticSignError" })
hi(0, "DiagnosticFloatingHint", { link = "DiagnosticSignHint" })
hi(0, "DiagnosticFloatingInfo", { link = "DiagnosticSignInfo" })
hi(0, "DiagnosticFloatingWarn", { link = "DiagnosticSignWarn" })
hi(0, "DiagnosticHint", { bg = "#10101a", ctermbg = 232, ctermfg = 141, fg = "#bfc5ff" })
hi(0, "DiagnosticInfo", { bg = "#10101a", ctermbg = 232, ctermfg = 159, fg = "#ecbef1" })
hi(0, "DiagnosticOk", { ctermfg = 10, fg = "#ffd3d6" })
hi(0, "DiagnosticSignError", { ctermfg = 204, fg = "#9fa5ff" })
hi(0, "DiagnosticSignHint", { ctermfg = 141, fg = "#bfc5ff" })
hi(0, "DiagnosticSignInfo", { ctermfg = 159, fg = "#ecbef1" })
hi(0, "DiagnosticSignWarn", { ctermfg = 228, fg = "#ffdcdf" })
hi(0, "DiagnosticUnderlineError", { undercurl = true })
hi(0, "DiagnosticUnderlineHint", { undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { undercurl = true })
hi(0, "DiagnosticWarn", { bg = "#10101a", ctermbg = 232, ctermfg = 228, fg = "#ffdcdf" })
hi(0, "DiffAdd", { bg = "#1c3140", ctermbg = 119 })
hi(0, "DiffAdded", { ctermfg = 120, fg = "#ffc8cc" })
hi(0, "DiffChange", { bg = "#2e2e30", ctermbg = 233 })
hi(0, "DiffDelete", { bg = "#392432", ctermbg = 203, ctermfg = 236, fg = "#373677" })
hi(0, "DiffFile", { bold = true, ctermfg = 145, fg = "#e4e4e4" })
hi(0, "DiffIndexLine", { bold = true, ctermfg = 145, fg = "#e4e4e4" })
hi(0, "DiffRemoved", { ctermfg = 204, fg = "#9fa5ff" })
hi(0, "DiffText", { bg = "#25273c", ctermbg = 215 })
hi(0, "Directory", { ctermfg = 141, fg = "#bfc5ff" })
hi(0, "Error", { bg = "#10101a", bold = true, ctermbg = 232, ctermfg = 203, fg = "#7b7fd1" })
hi(0, "ErrorMsg", { ctermfg = 203, fg = "#7b7fd1" })
hi(0, "Float", { ctermfg = 215, fg = "#ffa2ac" })
hi(0, "FloatBorder", { link = "WinSeparator" })
hi(0, "FloatShadow", { bg = "#525252", blend = 80, ctermbg = 0 })
hi(0, "FloatShadowThrough", { bg = "#525252", blend = 100, ctermbg = 0 })
hi(0, "FoldColumn", { ctermfg = 75, fg = "#7977f4" })
hi(0, "Folded", { ctermfg = 75, fg = "#7977f4" })
hi(0, "Function", { ctermfg = 204, fg = "#9fa5ff" })
hi(0, "FzfLuaPreviewTitle", { bg = "#d2c2f4", ctermbg = 141, ctermfg = 232, fg = "#0e0e27" })
hi(0, "FzfLuaScrollFloatEmpty", { bg = "#575759", ctermbg = 236 })
hi(0, "FzfLuaScrollFloatFull", { bg = "#83a9ed", ctermbg = 135 })
hi(0, "FzfLuaTitle", { bg = "#bbe8d6", ctermbg = 120, ctermfg = 232, fg = "#0e0e27" })
hi(0, "GitSignsAdd", { ctermfg = 120, fg = "#ffc8cc" })
hi(0, "GitSignsAddInline", { bg = "#bbe8d6", ctermbg = 120, ctermfg = 232, fg = "#0e0e27" })
hi(0, "GitSignsAddLn", { ctermfg = 119, fg = "#ffb6bc" })
hi(0, "GitSignsAddLnInline", { bg = "#bbe8d6", ctermbg = 120, ctermfg = 232, fg = "#0e0e27" })
hi(0, "GitSignsAddPreview", { bg = "#2e2e30", ctermbg = 233, ctermfg = 120, fg = "#ffc8cc" })
hi(0, "GitSignsChange", { ctermfg = 228, fg = "#ffdcdf" })
hi(0, "GitSignsChangeDelete", { ctermfg = 215, fg = "#ffa2ac" })
hi(0, "GitSignsChangeInline", { bg = "#fae7bf", ctermbg = 228, ctermfg = 232, fg = "#0e0e27" })
hi(0, "GitSignsChangeLn", { ctermfg = 228, fg = "#ffdcdf" })
hi(0, "GitSignsChangeLnInline", { bg = "#fae7bf", ctermbg = 228, ctermfg = 232, fg = "#0e0e27" })
hi(0, "GitSignsChangeNr", { ctermfg = 215, fg = "#ffa2ac" })
hi(0, "GitSignsDelete", { ctermfg = 204, fg = "#9fa5ff" })
hi(0, "GitSignsDeleteInline", { bg = "#e49ab1", ctermbg = 204, ctermfg = 232, fg = "#0e0e27" })
hi(0, "GitSignsDeleteLnInline", { bg = "#e49ab1", ctermbg = 204, ctermfg = 232, fg = "#0e0e27" })
hi(0, "GitSignsDeletePreview", { bg = "#2e2e30", ctermbg = 233, ctermfg = 204, fg = "#9fa5ff" })
hi(0, "GitSignsDeleteVirtLn", { bg = "#2e2e30", ctermbg = 233, ctermfg = 204, fg = "#9fa5ff" })
hi(0, "GitSignsUntracked", { ctermfg = 159, fg = "#ecbef1" })
hi(0, "Identifier", { ctermfg = 141, fg = "#bfc5ff" })
hi(0, "Ignore", { ctermfg = 233, fg = "#1d1e25" })
hi(0, "IncSearch", { bg = "#fae7bf", ctermbg = 228, ctermfg = 233, fg = "#1d1e25" })
hi(0, "Keyword", { link = "@function" })
hi(0, "Label", { ctermfg = 135, fg = "#989dfb" })
hi(0, "LineNr", { ctermfg = 236, fg = "#545665" })
hi(0, "MatchParen", { bg = "#10101a", bold = true, ctermbg = 232, ctermfg = 141, fg = "#bfc5ff", underline = true })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniDiffSignAdd_stl", { fg = "#ffd3d6" })
hi(0, "MiniDiffSignChange_stl", { fg = "#f6d1fa" })
hi(0, "MiniDiffSignDelete", { link = "GitSignsDelete" })
hi(0, "MiniDiffSignDelete_stl", { fg = "#9fa5ff" })
hi(0, "MiniDiffSignsAdd", { link = "GitSignsAdd" })
hi(0, "MiniDiffSignsChange", { link = "GitSignsChange" })
hi(0, "MiniIndentscopeSymbol", { ctermfg = 145, fg = "#e4e4e4" })
hi(0, "ModeMsg", { bold = true, ctermfg = 252, fg = "#888998" })
hi(0, "MoreMsg", { link = "ModeMsg" })
hi(0, "NonText", { ctermfg = 236, fg = "#545665" })
hi(0, "Normal", { bg = "#1f1e25", ctermbg = 233, ctermfg = 253, fg = "#e1dce1" })
hi(0, "NormalFloat", { bg = "#080808" })
hi(0, "Number", { ctermfg = 215, fg = "#ffa2ac" })
hi(0, "NvimInternalError", { bg = "#eb4435", ctermbg = 9, ctermfg = 9, fg = "#7878ed" })
hi(0, "NvimTreeFolderIcon", { ctermfg = 141, fg = "#bfc5ff" })
hi(0, "NvimTreeFolderName", { ctermfg = 159, fg = "#ecbef1" })
hi(0, "NvimTreeRootFolder", { ctermfg = 120, fg = "#ffc8cc" })
hi(0, "Operator", { ctermfg = 121, fg = "#f3c2f8" })
hi(0, "Pmenu", { bg = "#2e2e30", ctermbg = 233, ctermfg = 253, fg = "#e1dce1" })
hi(0, "PmenuSbar", { bg = "#10101a", ctermbg = 232, ctermfg = 253, fg = "#e1dce1" })
hi(0, "PmenuSel", { bg = "#1f1e25", ctermbg = 233, ctermfg = 141, fg = "#bfc5ff" })
hi(0, "PmenuThumb", { bg = "#899dc3", ctermbg = 236, ctermfg = 253, fg = "#e1dce1" })
hi(0, "PreProc", { ctermfg = 120, fg = "#ffc8cc" })
hi(0, "Question", { ctermfg = 120, fg = "#ffc8cc" })
hi(0, "QuickFixLine", { ctermfg = 14, fg = "#f6d1fa" })
hi(0, "RedrawDebugClear", { bg = "#675420", ctermbg = 11, ctermfg = 0 })
hi(0, "RedrawDebugComposed", { bg = "#1c522b", ctermbg = 10, ctermfg = 0 })
hi(0, "RedrawDebugRecompose", { bg = "#511112", ctermbg = 9, ctermfg = 0 })
hi(0, "Removed", { ctermfg = 9, fg = "#c1c7ff" })
hi(0, "Search", { bg = "#e6b995", ctermbg = 215, ctermfg = 233, fg = "#1d1e25" })
hi(0, "SignColumn", { ctermfg = 120, fg = "#ffc8cc" })
hi(0, "Special", { ctermfg = 122, fg = "#f7dbfa" })
hi(0, "SpecialKey", { ctermfg = 159, fg = "#ecbef1" })
hi(0, "SpellBad", { ctermfg = 203, fg = "#7b7fd1", undercurl = true })
hi(0, "SpellCap", { ctermfg = 120, fg = "#ffc8cc", underline = true })
hi(0, "SpellLocal", { ctermfg = 119, fg = "#ffb6bc", underline = true })
hi(0, "SpellRare", { ctermfg = 204, fg = "#9fa5ff", underline = true })
hi(0, "Statement", { ctermfg = 120, fg = "#ffc8cc" })
hi(0, "StatusLine", { bg = "#899dc3", ctermbg = 236, ctermfg = 232, fg = "#0e0e27" })
hi(0, "StatusLineNC", { bg = "#10101a", ctermbg = 232, ctermfg = 252, fg = "#888998" })
hi(0, "String", { ctermfg = 228, fg = "#ffdcdf" })
hi(0, "TabLine", { bg = "#1f1e25", ctermbg = 233, ctermfg = 252, fg = "#888998" })
hi(0, "TabLineFill", { bg = "#1f1e25", ctermbg = 233, ctermfg = 252, fg = "#888998" })
hi(0, "TabLineSel", { bg = "#3f3d54", bold = true, ctermbg = 236, ctermfg = 253, fg = "#e1dce1" })
hi(0, "TelescopeBorder", { link = "LineNr" })
hi(0, "TelescopeMatching", { link = "String" })
hi(0, "TelescopeNormal", { ctermfg = 252, fg = "#888998" })
hi(0, "TelescopePreviewBorder", { bg = "#8b8b8b", ctermbg = 252, ctermfg = 252, fg = "#888998" })
hi(0, "TelescopePreviewNormal", { bg = "#8b8b8b", ctermbg = 252 })
hi(0, "TelescopePreviewTitle", { ctermfg = 252, fg = "#888998" })
hi(0, "TelescopePromptBorder", { bg = "#575759", ctermbg = 236, ctermfg = 236, fg = "#545665" })
hi(0, "TelescopePromptCounter", { bold = true, ctermfg = 120, fg = "#ffc8cc" })
hi(0, "TelescopePromptNormal", { bg = "#575759", ctermbg = 236 })
hi(0, "TelescopePromptPrefix", { bg = "#575759", ctermbg = 236 })
hi(0, "TelescopePromptTitle", { bg = "#575759", ctermbg = 236, ctermfg = 236, fg = "#545665" })
hi(0, "TelescopeResultsBorder", { bg = "#2e2e30", ctermbg = 233, ctermfg = 233, fg = "#2c2d37" })
hi(0, "TelescopeResultsDiffAdd", { ctermfg = 120, fg = "#ffc8cc" })
hi(0, "TelescopeResultsDiffChange", { ctermfg = 228, fg = "#ffdcdf" })
hi(0, "TelescopeResultsDiffDelete", { ctermfg = 204, fg = "#9fa5ff" })
hi(0, "TelescopeResultsDiffUntracked", { link = "Title" })
hi(0, "TelescopeResultsNormal", { bg = "#2e2e30", ctermbg = 233 })
hi(0, "TelescopeResultsTitle", { bg = "#2e2e30", ctermbg = 233, ctermfg = 233, fg = "#2c2d37" })
hi(0, "TelescopeSelection", { bg = "#575759", ctermbg = 236 })
hi(0, "Terminal", { bg = "#10101a", ctermbg = 232, ctermfg = 253, fg = "#e1dce1" })
hi(0, "Title", { ctermfg = 135, fg = "#989dfb" })
hi(0, "Todo", { bg = "#1f1e25", bold = true, ctermbg = 233, ctermfg = 215, fg = "#ffa2ac" })
hi(0, "Type", { ctermfg = 141, fg = "#bfc5ff" })
hi(0, "Underlined", { ctermfg = 121, fg = "#f3c2f8", underline = true })
hi(0, "Visual", { bg = "#3f3d54", ctermbg = 236 })
hi(0, "WarningMsg", { ctermfg = 228, fg = "#ffdcdf" })
hi(0, "WildMenu", { bg = "#c0f3f2", ctermbg = 122, ctermfg = 232, fg = "#0e0e27" })
hi(0, "WinBar", { bg = "#080808", bold = true, fg = "#9b9da9" })
hi(0, "WinBarNC", { bg = "#080808", fg = "#9b9da9" })
hi(0, "WinSeparator", { ctermfg = 236, fg = "#373677" })
hi(0, "diffFileId", { bold = true, ctermfg = 159, fg = "#ecbef1", reverse = true })
hi(0, "diffLine", { ctermfg = 141, fg = "#bfc5ff" })
hi(0, "diffNewFile", { bold = true, ctermfg = 145, fg = "#e4e4e4" })
hi(0, "diffNoEOL", { ctermfg = 141, fg = "#bfc5ff" })
hi(0, "diffOldFile", { bold = true, ctermfg = 145, fg = "#e4e4e4" })
hi(0, "diffSubname", { ctermfg = 145, fg = "#e4e4e4" })
hi(0, "elixirAtom", { ctermfg = 228, fg = "#ffdcdf" })
hi(0, "elixirVariable", { ctermfg = 141, fg = "#bfc5ff" })
hi(0, "gitcommitBranch", { ctermfg = 141, fg = "#bfc5ff" })
hi(0, "gitcommitComment", { ctermfg = 252, fg = "#888998" })
hi(0, "gitcommitDiscarded", { link = "gitcommitComment" })
hi(0, "gitcommitDiscardedArrow", { link = "gitcommitDiscardedFile" })
hi(0, "gitcommitDiscardedFile", { ctermfg = 204, fg = "#9fa5ff" })
hi(0, "gitcommitDiscardedType", { ctermfg = 204, fg = "#9fa5ff" })
hi(0, "gitcommitNoBranch", { link = "gitcommitBranch" })
hi(0, "gitcommitOverflow", { ctermfg = 204, fg = "#9fa5ff" })
hi(0, "gitcommitSelected", { link = "gitcommitComment" })
hi(0, "gitcommitSelectedArrow", { link = "gitcommitSelectedFile" })
hi(0, "gitcommitSelectedFile", { ctermfg = 120, fg = "#ffc8cc" })
hi(0, "gitcommitSelectedType", { ctermfg = 120, fg = "#ffc8cc" })
hi(0, "gitcommitSummary", { ctermfg = 145, fg = "#e4e4e4" })
hi(0, "gitcommitUnmerged", { ctermfg = 120, fg = "#ffc8cc" })
hi(0, "gitcommitUnmergedArrow", { link = "gitcommitUnmergedFile" })
hi(0, "gitcommitUnmergedFile", { ctermfg = 228, fg = "#ffdcdf" })
hi(0, "gitcommitUntracked", { link = "gitcommitComment" })
hi(0, "gitcommitUntrackedFile", { ctermfg = 122, fg = "#f7dbfa" })
hi(0, "htmlBold", { bold = true })
hi(0, "htmlBoldItalic", { bold = true, italic = true })
hi(0, "htmlEndTag", { link = "htmlTag" })
hi(0, "htmlH1", { bold = true, ctermfg = 135, fg = "#989dfb" })
hi(0, "htmlH2", { bold = true, ctermfg = 135, fg = "#989dfb" })
hi(0, "htmlH3", { ctermfg = 159, fg = "#ecbef1", italic = true })
hi(0, "htmlH4", { ctermfg = 159, fg = "#ecbef1", italic = true })
hi(0, "htmlH5", { ctermfg = 121, fg = "#f3c2f8" })
hi(0, "htmlH6", { ctermfg = 121, fg = "#f3c2f8" })
hi(0, "htmlItalic", { italic = true })
hi(0, "htmlLink", { ctermfg = 159, fg = "#ecbef1", underline = true })
hi(0, "htmlTag", { link = "Special" })
hi(0, "htmlTagN", { link = "Keyword" })
hi(0, "htmlTagName", { link = "Keyword" })
hi(0, "jsAsyncKeyword", { link = "PreProc" })
hi(0, "jsClassDefinition", { link = "Type" })
hi(0, "jsClassKeyword", { ctermfg = 141, fg = "#bfc5ff" })
hi(0, "jsConditional", { link = "PreProc" })
hi(0, "jsExtendsKeyword", { link = "PreProc" })
hi(0, "jsForAwait", { link = "PreProc" })
hi(0, "jsRepeat", { link = "PreProc" })
hi(0, "jsReturn", { link = "PreProc" })
hi(0, "jsxClosePunct", { link = "jsxOpenPunct" })
hi(0, "jsxOpenPunct", { ctermfg = 252, fg = "#888998" })
hi(0, "lCursor", { bg = "#d9dfe0", fg = "#1d1e25" })
hi(0, "markdownBlockquote", { ctermfg = 252, fg = "#888998" })
hi(0, "markdownBold", { bold = true, ctermfg = 253, fg = "#e1dce1" })
hi(0, "markdownBoldItalic", { bold = true, ctermfg = 253, fg = "#e1dce1", italic = true })
hi(0, "markdownCode", { ctermfg = 120, fg = "#ffc8cc" })
hi(0, "markdownCodeDelimiter", { ctermfg = 252, fg = "#888998" })
hi(0, "markdownEscape", { ctermfg = 253, fg = "#e1dce1" })
hi(0, "markdownH1", { bold = true, ctermfg = 135, fg = "#989dfb" })
hi(0, "markdownH2", { bold = true, ctermfg = 135, fg = "#989dfb" })
hi(0, "markdownH3", { bold = true, ctermfg = 135, fg = "#989dfb", italic = true })
hi(0, "markdownH4", { bold = true, ctermfg = 135, fg = "#989dfb", italic = true })
hi(0, "markdownH5", { ctermfg = 121, fg = "#f3c2f8" })
hi(0, "markdownH6", { ctermfg = 121, fg = "#f3c2f8" })
hi(0, "markdownHeadingDelimiter", { ctermfg = 253, fg = "#e1dce1" })
hi(0, "markdownHeadingRule", { ctermfg = 253, fg = "#e1dce1" })
hi(0, "markdownId", { ctermfg = 252, fg = "#888998" })
hi(0, "markdownIdDeclaration", { ctermfg = 252, fg = "#888998" })
hi(0, "markdownItalic", { ctermfg = 253, fg = "#e1dce1", italic = true })
hi(0, "markdownLinkDelimiter", { ctermfg = 252, fg = "#888998" })
hi(0, "markdownLinkText", { ctermfg = 253, fg = "#e1dce1" })
hi(0, "markdownLinkTextDelimiter", { ctermfg = 252, fg = "#888998" })
hi(0, "markdownListMarker", { ctermfg = 204, fg = "#9fa5ff" })
hi(0, "markdownOrderedListMarker", { ctermfg = 204, fg = "#9fa5ff" })
hi(0, "markdownRule", { ctermfg = 253, fg = "#e1dce1" })
hi(0, "markdownUrl", { ctermfg = 135, fg = "#989dfb", underline = true })
hi(0, "markdownUrlDelimiter", { ctermfg = 252, fg = "#888998" })
hi(0, "markdownUrlTitle", { ctermfg = 253, fg = "#e1dce1" })
hi(0, "markdownUrlTitleDelimiter", { ctermfg = 252, fg = "#888998" })
hi(0, "xmlEndTag", { link = "xmlTag" })
hi(0, "xmlTag", { link = "htmlTag" })
hi(0, "xmlTagName", { link = "htmlTagName" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#585273"
g.terminal_color_1 = "#f48fb1"
g.terminal_color_2 = "#a1efd3"
g.terminal_color_3 = "#ffe6b3"
g.terminal_color_4 = "#91ddff"
g.terminal_color_5 = "#d4bfff"
g.terminal_color_6 = "#abf8f7"
g.terminal_color_7 = "#1e1c31"
g.terminal_color_8 = "#585273"
g.terminal_color_9 = "#f02e6e"
g.terminal_color_10 = "#7fe9c3"
g.terminal_color_11 = "#f2b482"
g.terminal_color_12 = "#78a8ff"
g.terminal_color_13 = "#7676ff"
g.terminal_color_14 = "#63f2f1"
g.terminal_color_15 = "#8a889d"
