-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "sunset"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { fg = "#fd8996" })
hi(0, "@character.special", { fg = "#8b9aec" })
hi(0, "@comment", { fg = "#b368bc", italic = true })
hi(0, "@conditional", { fg = "#2fb79b" })
hi(0, "@constant.builtin", { fg = "#ff917f" })
hi(0, "@constant.builtin.lua", { fg = "#fd8996" })
hi(0, "@constant.macro", { fg = "#e16e5b" })
hi(0, "@constructor", { link = "@type" })
hi(0, "@constructor.lua", { fg = "#c8c8c8" })
hi(0, "@debug", { fg = "#2ca289" })
hi(0, "@define", { fg = "#e16e5b" })
hi(0, "@exception", { fg = "#2fb79b" })
hi(0, "@field", { fg = "#e16e5b" })
hi(0, "@field.lua", { fg = "#ffbdb0" })
hi(0, "@float", { fg = "#e7aeed" })
hi(0, "@function.builtin", { fg = "#eccaef" })
hi(0, "@function.call", { fg = "#eccaef" })
hi(0, "@function.macro", { fg = "#e16e5b" })
hi(0, "@include", { fg = "#2fb79b" })
hi(0, "@keyword.conditional", { fg = "#2fb79b" })
hi(0, "@keyword.coroutine", { fg = "#2fb79b" })
hi(0, "@keyword.function", { fg = "#e16e5b" })
hi(0, "@keyword.import.tsx", { fg = "#2fb79b" })
hi(0, "@keyword.operator", { fg = "#e16e5b" })
hi(0, "@keyword.repeat", { fg = "#2fb79b" })
hi(0, "@keyword.return", { fg = "#2fb79b" })
hi(0, "@lsp.mod.async.rust", { fg = "#2fb79b" })
hi(0, "@lsp.mod.global.lua", { fg = "#fd8996" })
hi(0, "@lsp.type.class.markdown", { fg = "#e16e5b" })
hi(0, "@lsp.type.comment", { fg = "#b368bc", italic = true })
hi(0, "@lsp.type.enum", { fg = "#fd8996" })
hi(0, "@lsp.type.formatSpecifier.rust", { fg = "#e16e5b" })
hi(0, "@lsp.type.interface", { fg = "#fd8996" })
hi(0, "@lsp.type.interface.typescriptreact", { fg = "#fd8996" })
hi(0, "@lsp.type.keyword", { fg = "#e16e5b" })
hi(0, "@lsp.type.namespace", { fg = "#fd8996" })
hi(0, "@lsp.type.namespace.typescriptreact", { fg = "#fd8996" })
hi(0, "@lsp.type.parameter", { fg = "#ffbdb0" })
hi(0, "@lsp.type.property", { fg = "#ffbdb0" })
hi(0, "@lsp.type.property.lua", { fg = "#ffbdb0" })
hi(0, "@lsp.type.variable", { fg = "#ffbdb0" })
hi(0, "@lsp.type.variable.lua", { fg = "#ffbdb0" })
hi(0, "@lsp.typemod.decorator.library.rust", { fg = "#eccaef" })
hi(0, "@lsp.typemod.function.async.rust", { fg = "#eccaef" })
hi(0, "@lsp.typemod.function.declaration.rust", { fg = "#eccaef" })
hi(0, "@lsp.typemod.function.defaultLibrary", { fg = "#eccaef" })
hi(0, "@lsp.typemod.function.global.lua", { fg = "#eccaef" })
hi(0, "@lsp.typemod.keyword.controlFlow.rust", { fg = "#2fb79b" })
hi(0, "@lsp.typemod.method.defaultLibrary", { fg = "#eccaef" })
hi(0, "@lsp.typemod.method.reference.rust", { fg = "#eccaef" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.variable.declaration.lua", { fg = "#ffbdb0" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { fg = "#ffbdb0" })
hi(0, "@lsp.typemod.variable.defaultLibrary.lua", { fg = "#fd8996" })
hi(0, "@lsp.typemod.variable.global.lua", { fg = "#fd8996" })
hi(0, "@lsp.typemod.variable.injected", { fg = "#ffbdb0" })
hi(0, "@lsp.typemod.variable.readonly.typescriptreact", { fg = "#ff917f" })
hi(0, "@markup.heading.1.html", { fg = "#c8c8c8" })
hi(0, "@markup.heading.2.html", { fg = "#c8c8c8" })
hi(0, "@markup.heading.3.html", { fg = "#c8c8c8" })
hi(0, "@markup.heading.4.html", { fg = "#c8c8c8" })
hi(0, "@markup.heading.5.html", { fg = "#c8c8c8" })
hi(0, "@markup.heading.6.html", { fg = "#c8c8c8" })
hi(0, "@markup.heading.html", { fg = "#c8c8c8" })
hi(0, "@markup.link.label.markdown_inline", { fg = "#8b9aec" })
hi(0, "@markup.link.markdown_inline", { fg = "#c8c8c8" })
hi(0, "@markup.link.url.markdown_inline", { fg = "#e16e5b", underline = true })
hi(0, "@markup.list.markdown", { fg = "#e16e5b" })
hi(0, "@markup.quote.markdown", { fg = "#c8c8c8" })
hi(0, "@markup.raw.markdown_inline", { fg = "#8b9aec" })
hi(0, "@method", { fg = "#eccaef" })
hi(0, "@method.call", { fg = "#eccaef" })
hi(0, "@namespace", { fg = "#fd8996" })
hi(0, "@parameter", { fg = "#ffbdb0" })
hi(0, "@preproc", { fg = "#fd8996" })
hi(0, "@property", { fg = "#ffbdb0" })
hi(0, "@punctuation.bracket", { fg = "#c8c8c8" })
hi(0, "@punctuation.delimeter", { fg = "#c8c8c8" })
hi(0, "@punctuation.special", { fg = "#e16e5b" })
hi(0, "@punctuation.special.markdown", { fg = "#b368bc" })
hi(0, "@repeat", { fg = "#e16e5b" })
hi(0, "@storageclass", { fg = "#fd8996" })
hi(0, "@string.escape", { fg = "#8b9aec" })
hi(0, "@string.regex", { fg = "#8b9aec" })
hi(0, "@string.special", { fg = "#8b9aec" })
hi(0, "@string.special.css", { fg = "#6fd3b9" })
hi(0, "@symbol", { fg = "#ffbdb0" })
hi(0, "@tag.attribute", { fg = "#ffbdb0", italic = true })
hi(0, "@tag.builtin.tsx", { fg = "#e16e5b" })
hi(0, "@tag.delimiter", { fg = "#956961" })
hi(0, "@tag.jsx", { fg = "#fd8996" })
hi(0, "@tag.tsx", { fg = "#fd8996" })
hi(0, "@text", { link = "None" })
hi(0, "@text.danger", { bg = "#1e1e1e", fg = "#8b9aec" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.environment", { fg = "#e16e5b" })
hi(0, "@text.environment.name", { fg = "#fd8996" })
hi(0, "@text.literal", { fg = "#8b9aec" })
hi(0, "@text.literal.markdown", { fg = "#8b9aec" })
hi(0, "@text.literal.markdown_inline", { fg = "#8b9aec" })
hi(0, "@text.math", { fg = "#8b9aec" })
hi(0, "@text.note", { fg = "#c8c8c8" })
hi(0, "@text.reference", { fg = "#ff917f" })
hi(0, "@text.reference.markdown", { fg = "#e16e5b" })
hi(0, "@text.reference.markdown_inline", { fg = "#8b9aec" })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true, fg = "#e16e5b" })
hi(0, "@text.title", { bold = true, fg = "#e16e5b" })
hi(0, "@text.title.markdown", { bold = true, fg = "#e16e5b" })
hi(0, "@text.todo", { bold = true, fg = "#6fd3b9" })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.uri", { link = "Underlined" })
hi(0, "@text.uri.markdown_inline", { fg = "#c8c8c8", underline = true })
hi(0, "@text.warning", { bold = true, fg = "#6fd3b9" })
hi(0, "@type.builtin", { fg = "#fd8996" })
hi(0, "@type.definition", { fg = "#fd8996" })
hi(0, "@type.definition.css", { fg = "#ffbdb0" })
hi(0, "@type.qualifier", { fg = "#fd8996" })
hi(0, "@type.qualifier.rust", { fg = "#e16e5b" })
hi(0, "@type.toml", { fg = "#e16e5b" })
hi(0, "@variable", { fg = "#ffbdb0" })
hi(0, "@variable.builtin", { fg = "#ffbdb0" })
hi(0, "@variable.lua", { fg = "#ffbdb0" })
hi(0, "Bold", { bold = true, fg = "#e16e5b" })
hi(0, "BookmarkAnnotationLine", { bg = "#00556d" })
hi(0, "BookmarkAnnotationSign", { fg = "#eccaef" })
hi(0, "BookmarkLine", { bg = "#00556d" })
hi(0, "BookmarkSign", { fg = "#ff907d" })
hi(0, "Boolean", { fg = "#e16e5b" })
hi(0, "BqfPreviewBorder", { bg = "#1e1e1e", fg = "#2d2d2d" })
hi(0, "BqfPreviewRange", { bg = "#00556d" })
hi(0, "BqfSign", { fg = "#eccaef" })
hi(0, "BufferCurrent", { bg = "#1e1e1e", fg = "#c8c8c8" })
hi(0, "BufferCurrentIndex", { bg = "#1e1e1e", fg = "#c8c8c8" })
hi(0, "BufferCurrentMod", { bg = "#1e1e1e", fg = "#eccaef" })
hi(0, "BufferCurrentSign", { bg = "#1e1e1e", fg = "#c8c8c8" })
hi(0, "BufferCurrentTarget", { bg = "#1e1e1e", bold = true, fg = "#2ca289" })
hi(0, "BufferInactive", { bg = "#181818", fg = "#956961" })
hi(0, "BufferInactiveIndex", { bg = "#181818", fg = "#956961" })
hi(0, "BufferInactiveMod", { bg = "#181818", fg = "#7784c7" })
hi(0, "BufferInactiveSign", { bg = "#181818", fg = "#76372d" })
hi(0, "BufferInactiveTarget", { bg = "#181818", bold = true, fg = "#2ca289" })
hi(0, "BufferLineIndicatorSelected", { fg = "#ff907d" })
hi(0, "BufferTabpage", { bg = "#181818", fg = "#76372d" })
hi(0, "BufferTabpages", { bg = "#181818" })
hi(0, "BufferVisible", { bg = "#181818", fg = "#c8c8c8" })
hi(0, "BufferVisibleIndex", { bg = "#181818", fg = "#c8c8c8" })
hi(0, "BufferVisibleMod", { bg = "#181818", fg = "#eccaef" })
hi(0, "BufferVisibleSign", { bg = "#181818", fg = "#c8c8c8" })
hi(0, "BufferVisibleTarget", { bg = "#181818", bold = true, fg = "#2ca289" })
hi(0, "Character", { fg = "#8b9aec" })
hi(0, "CmpDocumentation", { bg = "#181818", fg = "#c8c8c8" })
hi(0, "CmpItemAbbr", { fg = "#c8c8c8" })
hi(0, "CmpItemAbbrDefault", { fg = "#c8c8c8" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#999999", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#808080" })
hi(0, "CmpItemAbbrMatch", { fg = "#f57561" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#c8c8c8" })
hi(0, "CmpItemAbbrMatchFuzzy", { fg = "#f57561" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#c8c8c8" })
hi(0, "CmpItemKindClass", { fg = "#03c4a4" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { fg = "#c8c8c8" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { fg = "#ff917f" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { fg = "#03c4a4" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { fg = "#8b9aec" })
hi(0, "CmpItemKindEnum", { fg = "#03c4a4" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { fg = "#ff917f" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { fg = "#a7e3d2" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { fg = "#ffbdb0" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { fg = "#c8c8c8" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { fg = "#c8c8c8" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { fg = "#00a88c" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { fg = "#03c4a4" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { fg = "#c8c8c8" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { fg = "#00a88c" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { fg = "#c8c8c8" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { fg = "#c8c8c8" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { fg = "#ffbdb0" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { fg = "#d772e4" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { fg = "#c8c8c8" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { fg = "#03c4a4" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { fg = "#c8c8c8" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { fg = "#03c4a4" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { fg = "#c8c8c8" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { fg = "#c8c8c8" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { fg = "#ffbdb0" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenuDefault", { fg = "#c8c8c8" })
hi(0, "ColorColumn", { bg = "#181818" })
hi(0, "CommandMode", { fg = "#c2cdfe" })
hi(0, "Comment", { fg = "#808080", italic = true })
hi(0, "Conceal", { fg = "#808080" })
hi(0, "Conditional", { fg = "#2fb79b" })
hi(0, "Constant", { fg = "#ff917f" })
hi(0, "CopilotAnnotation", { fg = "#808080" })
hi(0, "CopilotSuggestion", { fg = "#808080" })
hi(0, "CurSearch", { bg = "#735752" })
hi(0, "CurosorLineFolded", { bg = "#00556d" })
hi(0, "Cursor", { bg = "#c8c8c8", fg = "#1e1e1e" })
hi(0, "CursorColumn", { bg = "#181818" })
hi(0, "CursorIM", { bg = "#c8c8c8", fg = "#1e1e1e" })
hi(0, "CursorLine", { bg = "#222222" })
hi(0, "CursorLineNr", { bold = true, fg = "#808080" })
hi(0, "Debug", { fg = "#2ca289" })
hi(0, "Define", { fg = "#e16e5b" })
hi(0, "Delimiter", { fg = "#c8c8c8" })
hi(0, "DiagnosticError", { fg = "#7a87d0" })
hi(0, "DiagnosticHint", { fg = "#ff907d" })
hi(0, "DiagnosticInfo", { fg = "#c6d1ff" })
hi(0, "DiagnosticOther", { fg = "#a95042" })
hi(0, "DiagnosticSignInformation", { fg = "#c6d1ff" })
hi(0, "DiagnosticSignOther", { fg = "#a95042" })
hi(0, "DiagnosticSignWarning", { fg = "#04c9a7" })
hi(0, "DiagnosticUnderlineError", { sp = "#f44937", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#30c5f5", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#ffbfb2", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#ff7a66", undercurl = true })
hi(0, "DiagnosticUnnecessary", { fg = "#808080" })
hi(0, "DiagnosticVirtualTextError", { bg = "#332224", fg = "#7a87d0" })
hi(0, "DiagnosticVirtualTextHint", { bg = "#222e33", fg = "#ff907d" })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#392c2a", fg = "#c6d1ff" })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#382623", fg = "#04c9a7" })
hi(0, "DiagnosticWarn", { fg = "#04c9a7" })
hi(0, "DiffAdd", { bg = "#392c2a" })
hi(0, "DiffAdded", { fg = "#934f9c" })
hi(0, "DiffChange", { bg = "#392c2a" })
hi(0, "DiffDelete", { bg = "#332224" })
hi(0, "DiffRemoved", { fg = "#145d4d" })
hi(0, "DiffText", { bg = "#392c2a" })
hi(0, "Directory", { fg = "#c8c8c8" })
hi(0, "EndOfBuffer", { fg = "#1e1e1e" })
hi(0, "Error", { bold = true, fg = "#7a87d0" })
hi(0, "ErrorMsg", { bg = "#1e1e1e", bold = true, fg = "#2ca289" })
hi(0, "Exception", { fg = "#2fb79b" })
hi(0, "EyelinerPrimary", { bold = true, fg = "#8897e9" })
hi(0, "EyelinerSecondary", { bold = true, fg = "#fecbce" })
hi(0, "Float", { fg = "#e7aeed" })
hi(0, "FloatBorder", { bg = "#1e1e1e", fg = "#2d2d2d" })
hi(0, "FoldColumn", { fg = "#3f3f3f" })
hi(0, "Folded", { bg = "#1e3037", fg = "#c8c8c8" })
hi(0, "Function", { fg = "#eccaef" })
hi(0, "GitSignsAdd", { fg = "#bb56c8" })
hi(0, "GitSignsChange", { fg = "#b35749" })
hi(0, "GitSignsDelete", { fg = "#2ba88e" })
hi(0, "IblIndent", { fg = "#3f3f3f" })
hi(0, "IblScope", { fg = "#636363" })
hi(0, "Identifier", { fg = "#ffbdb0" })
hi(0, "Ignore", { bold = true })
hi(0, "IlluminatedWordRead", { bg = "#323232" })
hi(0, "IlluminatedWordText", { bg = "#323232" })
hi(0, "IlluminatedWordWrite", { bg = "#323232" })
hi(0, "IncSearch", { bg = "#024a5f" })
hi(0, "Include", { fg = "#2fb79b" })
hi(0, "InsertMode", { fg = "#dd90e6" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#e16e5b" })
hi(0, "Label", { fg = "#ffbdb0" })
hi(0, "LazyButton", { bg = "#293337", fg = "#c8c8c8" })
hi(0, "LazyButtonActive", { bg = "#3a4347", fg = "#c8c8c8" })
hi(0, "LazyComment", { fg = "#808080", italic = true })
hi(0, "LazyCommit", { fg = "#8b9aec" })
hi(0, "LazyCommitIssue", { fg = "#e16e5b" })
hi(0, "LazyH1", { bg = "#181818", bold = true, fg = "#e16e5b" })
hi(0, "LazyReasonStart", { fg = "#fd8996" })
hi(0, "LazySpecial", { fg = "#e16e5b" })
hi(0, "LazyUrl", { fg = "#e16e5b" })
hi(0, "LazyValue", { fg = "#fd8996" })
hi(0, "LineNr", { fg = "#956961" })
hi(0, "LirDir", { fg = "#c8c8c8" })
hi(0, "LirEmptyDirText", { fg = "#808080", italic = true })
hi(0, "LirFloatNormal", { bg = "#181818", fg = "#c8c8c8" })
hi(0, "LirSymLink", { fg = "#fd8996" })
hi(0, "LspCodeLens", { fg = "#808080", italic = true })
hi(0, "LspCodeLensSeparator", { fg = "#808080", italic = true })
hi(0, "LspDiagnosticsDefaultError", { fg = "#7a87d0" })
hi(0, "LspDiagnosticsDefaultHint", { fg = "#ff907d" })
hi(0, "LspDiagnosticsDefaultInfo", { fg = "#c6d1ff" })
hi(0, "LspDiagnosticsDefaultInformation", { fg = "#c6d1ff" })
hi(0, "LspDiagnosticsDefaultWarning", { fg = "#04c9a7" })
hi(0, "LspDiagnosticsError", { fg = "#7a87d0" })
hi(0, "LspDiagnosticsFloatingError", { fg = "#7a87d0" })
hi(0, "LspDiagnosticsFloatingHint", { fg = "#ff907d" })
hi(0, "LspDiagnosticsFloatingInfo", { fg = "#c6d1ff" })
hi(0, "LspDiagnosticsFloatingInformation", { fg = "#c6d1ff" })
hi(0, "LspDiagnosticsFloatingWarning", { fg = "#04c9a7" })
hi(0, "LspDiagnosticsHint", { fg = "#ff907d" })
hi(0, "LspDiagnosticsInfo", { fg = "#c6d1ff" })
hi(0, "LspDiagnosticsInformation", { fg = "#c6d1ff" })
hi(0, "LspDiagnosticsSignError", { fg = "#7a87d0" })
hi(0, "LspDiagnosticsSignHint", { fg = "#ff907d" })
hi(0, "LspDiagnosticsSignInfo", { fg = "#c6d1ff" })
hi(0, "LspDiagnosticsSignInformation", { fg = "#c6d1ff" })
hi(0, "LspDiagnosticsSignWarning", { fg = "#04c9a7" })
hi(0, "LspDiagnosticsUnderlineError", { sp = "#f44937", undercurl = true })
hi(0, "LspDiagnosticsUnderlineHint", { sp = "#30c5f5", undercurl = true })
hi(0, "LspDiagnosticsUnderlineInfo", { sp = "#ffbfb2", undercurl = true })
hi(0, "LspDiagnosticsUnderlineInformation", { sp = "#ffbfb2", undercurl = true })
hi(0, "LspDiagnosticsUnderlineWarning", { sp = "#ff7a66", undercurl = true })
hi(0, "LspDiagnosticsVirtualTextError", { bg = "#332224", fg = "#7a87d0" })
hi(0, "LspDiagnosticsVirtualTextHint", { bg = "#222e33", fg = "#ff907d" })
hi(0, "LspDiagnosticsVirtualTextInfo", { bg = "#392c2a", fg = "#c6d1ff" })
hi(0, "LspDiagnosticsVirtualTextInformation", { bg = "#392c2a", fg = "#c6d1ff" })
hi(0, "LspDiagnosticsVirtualTextWarning", { bg = "#382623", fg = "#04c9a7" })
hi(0, "LspDiagnosticsWarning", { fg = "#04c9a7" })
hi(0, "LspInfoTip", { fg = "#808080" })
hi(0, "LspInlayHint", { fg = "#636363" })
hi(0, "Macro", { fg = "#e16e5b" })
hi(0, "Masondoc", { fg = "#808080" })
hi(0, "Masonpod", { fg = "#808080" })
hi(0, "MatchParen", { bg = "#00556d" })
hi(0, "MatchParenCur", { bg = "#00556d" })
hi(0, "MatchWord", { bg = "#323232" })
hi(0, "MatchWordCur", { bg = "#323232" })
hi(0, "MiniCursorword", { bg = "#323232" })
hi(0, "MiniCursorwordCurrent", { bg = "#323232" })
hi(0, "MiniDiffSignAdd_stl", { fg = "#f1d6f3" })
hi(0, "MiniDiffSignChange_stl", { fg = "#ffd0c7" })
hi(0, "ModeMsg", { bg = "#181818", fg = "#c8c8c8" })
hi(0, "MoreMsg", { fg = "#956961" })
hi(0, "MsgArea", { bg = "#1e1e1e", fg = "#c8c8c8" })
hi(0, "MsgSeparator", { bg = "#1e1e1e", fg = "#c8c8c8" })
hi(0, "NavicIconsArray", { fg = "#c8c8c8" })
hi(0, "NavicIconsBoolean", { fg = "#c8c8c8" })
hi(0, "NavicIconsClass", { fg = "#03c4a4" })
hi(0, "NavicIconsConstant", { fg = "#ff917f" })
hi(0, "NavicIconsConstructor", { fg = "#03c4a4" })
hi(0, "NavicIconsEnum", { fg = "#03c4a4" })
hi(0, "NavicIconsEnumMember", { fg = "#ff917f" })
hi(0, "NavicIconsEvent", { fg = "#a7e3d2" })
hi(0, "NavicIconsField", { fg = "#ffbdb0" })
hi(0, "NavicIconsFile", { fg = "#c8c8c8" })
hi(0, "NavicIconsFunction", { fg = "#00a88c" })
hi(0, "NavicIconsInterface", { fg = "#03c4a4" })
hi(0, "NavicIconsKey", { fg = "#c8c8c8" })
hi(0, "NavicIconsKeyword", { fg = "#c8c8c8" })
hi(0, "NavicIconsMethod", { fg = "#00a88c" })
hi(0, "NavicIconsModule", { fg = "#c8c8c8" })
hi(0, "NavicIconsNamespace", { fg = "#03c4a4" })
hi(0, "NavicIconsNull", { fg = "#c8c8c8" })
hi(0, "NavicIconsNumber", { fg = "#c8c8c8" })
hi(0, "NavicIconsObject", { fg = "#c8c8c8" })
hi(0, "NavicIconsOperator", { fg = "#c8c8c8" })
hi(0, "NavicIconsPackage", { fg = "#c8c8c8" })
hi(0, "NavicIconsProperty", { fg = "#ffbdb0" })
hi(0, "NavicIconsStruct", { fg = "#03c4a4" })
hi(0, "NavicIconsTypeParameter", { fg = "#03c4a4" })
hi(0, "NavicIconsVariable", { fg = "#ffbdb0" })
hi(0, "NavicSeparator", { fg = "#a9a9a9" })
hi(0, "NavicText", { fg = "#a9a9a9" })
hi(0, "NeogitBranch", { fg = "#8b9aec" })
hi(0, "NeogitDiffAdd", { bg = "#392c2a" })
hi(0, "NeogitDiffAddHighlight", { bg = "#392c2a" })
hi(0, "NeogitDiffDelete", { bg = "#332224" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#332224" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#50c0e8", fg = "#1e1e1e" })
hi(0, "NeogitNotificationInfo", { fg = "#e16e5b" })
hi(0, "NeogitRecentcommits", { fg = "#e16e5b" })
hi(0, "NeogitRemote", { fg = "#8b9aec" })
hi(0, "NeogitStagedchanges", { fg = "#e16e5b" })
hi(0, "NeogitUnstagedchanges", { fg = "#e16e5b" })
hi(0, "NeogitUntrackedfiles", { fg = "#e16e5b" })
hi(0, "NoiceCmdlineIcon", { link = "DiagnosticSignInfo" })
hi(0, "NoiceCmdlineIconSearch", { link = "DiagnosticSignHint" })
hi(0, "NoiceCmdlinePopupBorder", { link = "DiagnosticSignHint" })
hi(0, "NoiceCmdlinePopupTitle", { link = "DiagnosticSignHint" })
hi(0, "NoiceCmdlinePrompt", { fg = "#c8c8c8" })
hi(0, "NoiceFormatProgressDone", { bg = "#003d4f", fg = "#c8c8c8" })
hi(0, "NonText", { fg = "#636363" })
hi(0, "Normal", { bg = "#1e1e1e", fg = "#c8c8c8" })
hi(0, "NormalFloat", { bg = "#1e1e1e", fg = "#c8c8c8" })
hi(0, "NormalMode", { fg = "#d26a5a" })
hi(0, "NormalNC", { bg = "#1e1e1e", fg = "#c8c8c8" })
hi(0, "Number", { fg = "#e7aeed" })
hi(0, "NvimTreeCursorLine", { bg = "#003d4f" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#808080", italic = true })
hi(0, "NvimTreeEndOfBuffer", { fg = "#181818" })
hi(0, "NvimTreeExecFile", { fg = "#d772e4" })
hi(0, "NvimTreeFolderIcon", { fg = "#c8c8c8" })
hi(0, "NvimTreeFolderName", { fg = "#c8c8c8" })
hi(0, "NvimTreeGitDeleted", { fg = "#b7c4ff" })
hi(0, "NvimTreeGitDirty", { fg = "#b7c4ff" })
hi(0, "NvimTreeGitIgnored", { fg = "#808080", italic = true })
hi(0, "NvimTreeGitMerge", { fg = "#b7c4ff" })
hi(0, "NvimTreeGitNew", { fg = "#d487dd" })
hi(0, "NvimTreeGitRenamed", { fg = "#d487dd" })
hi(0, "NvimTreeGitStaged", { fg = "#bb56c8" })
hi(0, "NvimTreeImageFile", { fg = "#00a88c" })
hi(0, "NvimTreeIndentMarker", { fg = "#c8c8c8" })
hi(0, "NvimTreeLspDiagnosticsError", { fg = "#7a87d0" })
hi(0, "NvimTreeLspDiagnosticsHint", { fg = "#ff907d" })
hi(0, "NvimTreeLspDiagnosticsInfo", { fg = "#c6d1ff" })
hi(0, "NvimTreeLspDiagnosticsInformation", { fg = "#c6d1ff" })
hi(0, "NvimTreeLspDiagnosticsWarning", { fg = "#04c9a7" })
hi(0, "NvimTreeNormal", { bg = "#181818", fg = "#c8c8c8" })
hi(0, "NvimTreeOpenedFolderName", { bold = true, fg = "#c8c8c8", italic = true })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#c8c8c8" })
hi(0, "NvimTreeSpecialFile", { fg = "#03c4a4" })
hi(0, "NvimTreeSymlink", { fg = "#fd8996" })
hi(0, "NvimTreeWinSeparator", { bg = "#181818", fg = "#181818" })
hi(0, "Operator", { fg = "#c8c8c8" })
hi(0, "PackageInfoOutdatedVersion", { bg = "#382623", fg = "#04c9a7" })
hi(0, "PackageInfoUpToDateVersion", { bg = "#392c2a", fg = "#c6d1ff" })
hi(0, "Pmenu", { bg = "#1e1e1e", fg = "#c8c8c8" })
hi(0, "PmenuSbar", { bg = "#181818" })
hi(0, "PmenuSel", { bg = "#003d4f" })
hi(0, "PmenuThumb", { bg = "#808080" })
hi(0, "PreCondit", { fg = "#6fd3b9" })
hi(0, "PreProc", { fg = "#fd8996" })
hi(0, "Question", { fg = "#956961" })
hi(0, "QuickFixLine", { bg = "#003d4f" })
hi(0, "Repeat", { fg = "#e16e5b" })
hi(0, "ReplaceMode", { fg = "#7d8bd6" })
hi(0, "Search", { bg = "#653129" })
hi(0, "SelectMode", { fg = "#7b89db" })
hi(0, "SignColumn", { bg = "#1e1e1e" })
hi(0, "Special", { fg = "#8b9aec" })
hi(0, "SpecialChar", { fg = "#8b9aec" })
hi(0, "SpecialComment", { fg = "#c8c8c8" })
hi(0, "SpecialKey", { bold = true, fg = "#ff917f" })
hi(0, "SpellBad", { sp = "#d16b5c", undercurl = true })
hi(0, "SpellCap", { sp = "#ffc9bf", undercurl = true })
hi(0, "SpellLocal", { underline = true })
hi(0, "SpellRare", { sp = "#b98ace", underline = true })
hi(0, "Statement", { fg = "#c8c8c8" })
hi(0, "StatusLine", { bg = "#181818", fg = "#c8c8c8" })
hi(0, "StatusLineNC", { bg = "#1e1e1e", fg = "#1e1e1e" })
hi(0, "StorageClass", { fg = "#fd8996" })
hi(0, "String", { fg = "#8b9aec" })
hi(0, "Structure", { fg = "#fd8996" })
hi(0, "Substitute", { bg = "#00556d" })
hi(0, "TSRainbowBlue", { fg = "#e8715d" })
hi(0, "TSRainbowCoral", { fg = "#7e8cd8" })
hi(0, "TSRainbowGreen", { fg = "#dd90e6" })
hi(0, "TSRainbowOrange", { fg = "#7b89db" })
hi(0, "TSRainbowPink", { fg = "#33c0a3" })
hi(0, "TSRainbowRed", { fg = "#7d8bd6" })
hi(0, "TSRainbowViolet", { fg = "#8998ea" })
hi(0, "TSRainbowYellow", { fg = "#ecccef" })
hi(0, "TabLine", { bg = "#181818", fg = "#808080" })
hi(0, "TabLineFill", { bg = "#181818", fg = "#c8c8c8" })
hi(0, "TabLineSel", { bg = "#1e1e1e", fg = "#c8c8c8" })
hi(0, "Tag", { fg = "#e16e5b" })
hi(0, "TelescopeBorder", { bg = "#1e1e1e", fg = "#956961" })
hi(0, "TelescopeMatching", { bold = true, fg = "#f57561", italic = true })
hi(0, "TelescopeNormal", { bg = "#1e1e1e", fg = "#c8c8c8" })
hi(0, "TelescopePreviewHyphen", { fg = "#ffffff" })
hi(0, "TelescopePreviewTitle", { fg = "#ffffff" })
hi(0, "TelescopePromptCounter", { fg = "#ffffff" })
hi(0, "TelescopePromptPrefix", { fg = "#03c4a4" })
hi(0, "TelescopePromptTitle", { fg = "#ffffff" })
hi(0, "TelescopeResultsTitle", { fg = "#ffffff" })
hi(0, "TelescopeSelection", { bg = "#003d4f" })
hi(0, "TelescopeSelectionCaret", { bg = "#003d4f", fg = "#b45849" })
hi(0, "TermCursor", { bg = "#c8c8c8", fg = "#1e1e1e" })
hi(0, "TermCursorNC", { bg = "#c8c8c8", fg = "#1e1e1e" })
hi(0, "Title", { bold = true, fg = "#e16e5b" })
hi(0, "Todo", { bold = true, fg = "#6fd3b9" })
hi(0, "Type", { fg = "#fd8996" })
hi(0, "Typedef", { fg = "#fd8996" })
hi(0, "Variable", { fg = "#ffbdb0" })
hi(0, "VertSplit", { bg = "#1e1e1e", fg = "#808080" })
hi(0, "Visual", { bg = "#00556d" })
hi(0, "VisualMode", { fg = "#de6754" })
hi(0, "VisualNOS", { bg = "#181818" })
hi(0, "WarningMsg", { bg = "#1e1e1e", fg = "#8b9aec" })
hi(0, "WhichKey", { fg = "#00a88c" })
hi(0, "WhichKeyBorder", { bg = "#1e1e1e", fg = "#2d2d2d" })
hi(0, "WhichKeyDesc", { fg = "#c8c8c8" })
hi(0, "WhichKeyFloat", { bg = "#181818" })
hi(0, "WhichKeyGroup", { fg = "#ff917f" })
hi(0, "WhichKeySeperator", { fg = "#808080", italic = true })
hi(0, "WhichKeyValue", { fg = "#c8c8c8" })
hi(0, "Whitespace", { fg = "#956961" })
hi(0, "WildMenu", { bg = "#00b2e0", fg = "#c8c8c8" })
hi(0, "WinBar", { bg = "#1e1e1e", fg = "#a9a9a9" })
hi(0, "WinBarInactive", { bg = "#1e1e1e", fg = "#a9a9a9" })
hi(0, "WinBarNC", { bg = "#1e1e1e", fg = "#1e1e1e" })
hi(0, "WinSeparator", { fg = "#808080" })
hi(0, "diffNewFile", { fg = "#b368bc" })
hi(0, "diffOldFile", { fg = "#2ca289" })
hi(0, "gitcommitBranch", { fg = "#8b9aec" })
hi(0, "gitcommitHeader", { fg = "#e16e5b" })
hi(0, "gitcommitSummary", { fg = "#c8c8c8" })
hi(0, "lCursor", { bg = "#c8c8c8", fg = "#1e1e1e" })
hi(0, "ngxBlock", { fg = "#e16e5b" })
hi(0, "ngxComment", { fg = "#b368bc" })
hi(0, "ngxDirective", { fg = "#ffbdb0" })
hi(0, "ngxDirectiveBlock", { fg = "#e16e5b" })
hi(0, "ngxDirectiveImportant", { fg = "#2fb79b" })
hi(0, "ngxDirectiveThirdParty", { fg = "#ffbdb0" })
hi(0, "qfError", { bold = true, fg = "#7a87d0" })
hi(0, "qfFilename", { fg = "#fd8996" })
hi(0, "qfLineNr", { fg = "#8b9aec" })
hi(0, "qfSeparator", { fg = "#c8c8c8" })
hi(0, "rustEnumVariant", { fg = "#fd8996" })
hi(0, "rustEscape", { fg = "#8b9aec" })
hi(0, "rustSigil", { fg = "#c8c8c8" })
hi(0, "typescriptArrowFuncArg", { fg = "#c8c8c8" })
hi(0, "typescriptBraces", { fg = "#c8c8c8" })
hi(0, "typescriptCall", { fg = "#c8c8c8" })
hi(0, "typescriptTemplateSB", { fg = "#2fb79b" })
hi(0, "zshCommands", { fg = "#eccaef" })
hi(0, "zshDeref", { fg = "#c8c8c8" })
hi(0, "zshKSHFunction", { fg = "#eccaef" })
hi(0, "zshShortDeref", { fg = "#c8c8c8" })
hi(0, "zshSubst", { fg = "#c8c8c8" })
hi(0, "zshSubstDelim", { fg = "#e16e5b" })
hi(0, "zshVariableDef", { fg = "#c8c8c8" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#634e6c"
g.terminal_color_1 = "#f88f9d"
g.terminal_color_2 = "#a8e7ff"
g.terminal_color_3 = "#ffded7"
g.terminal_color_4 = "#8fdefd"
g.terminal_color_5 = "#e2baf5"
g.terminal_color_6 = "#c7efff"
g.terminal_color_7 = "#27192d"
g.terminal_color_8 = "#634e6c"
g.terminal_color_9 = "#f22e64"
g.terminal_color_10 = "#88deff"
g.terminal_color_11 = "#fcab9d"
g.terminal_color_12 = "#12bae9"
g.terminal_color_13 = "#b75ddc"
g.terminal_color_14 = "#9fe4ff"
g.terminal_color_15 = "#928698"
